### ISSUE TITLE
Foolproof: add more warnings if plugins are put in a wrong order

### ISSUE THREAD

**Issue by wookayin** [marlonrichert/zsh-autocomplete#1]
This plugin requires that `fzf` (and accompanied `~/.fzf.zsh`) must precede `zsh-autocomplete`.

Though it was mentioned in README, I don't think [it was not](https://github.com/marlonrichert/zsh-autocomplete#installation) emphasized enough. It would be great to have a fool-proof feature such that if an user have wrong ordering in their zshrc, a warning message would be printed (or disable the plugin).

Otherwise it would mess up everything: [for example](https://www.reddit.com/r/zsh/comments/gdaxsx/zshautocomplete_intellisenselike_findasyoutype/fpihq8s/), any keypress of `<TAB>` will ALWAYS invoke fzf, make the shell almost unusable.

**Comment by marlonrichert** [comment]
@wookayin I updated the code. Can you test if it resolves the issue for you?

**Comment by wookayin** [comment]
The commit is a squashed of many changes so it's hard to keep track of what has changed.

Having fzf source *after* zsh-autocomplete, pressing `<tab>` accepts autocompletion rather than invoking fzf. But I do see the following error messages:

```
$HOME/.zgen/marlonrichert/zsh-autocomplete-master/zsh-autocomplete.plugin.zsh:zle:215: invalid widget `menu-select'  
_zsh_autocomplete_init:bindkey:27: no such keymap `menuselect'  
```

Why would be that?

**Comment by marlonrichert** [comment]
Originally, `zsh-autocomplete` loaded `zsh/complist` itself, but I found out this should be done _before_ loading `compinit`. Please see the installation instructions: https://github.com/marlonrichert/zsh-autocomplete/blob/master/README.md#installation

**Comment by marlonrichert** [comment]
@wookayin I pushed in a new fix. Please git pull and let me know if that makes it work for you. 🙂

**Comment by marlonrichert** [comment]
`zsh-autocomplete` should be fairly robust by now with regards to the order in which it and other plugins are sourced. Closing this issue now. If you find another specific case that does not work, please open a new issue for it.
