### ISSUE TITLE
Want to switch to default Tab behaviour while using cd. 

### ISSUE THREAD

**Issue by TanishBansal** [marlonrichert/zsh-autocomplete#10]
How do I switch to default Tab behaviour while using cd i.e. togge between the options rather than insert all the options

**Comment by marlonrichert** [comment]
Can you please describe, step by step, what you are doing and what you expect? I don't understand what you mean.

**Comment by wookayin** [comment]
Just like the default behavior.

``
$ f|
fa/ fb/ fc/
```

- Pressing tab for the first time: select `fa/`
- Second time: `fb/`
- Third time: `fc/`

**Comment by marlonrichert** [comment]
Thanks, I understand it now. I don’t have an answer to that yet. I’ll look into it.

**Comment by marlonrichert** [comment]
@TanishBansal @wookayin 

First, please `git pull`, so you're updated to the latest version.

Then, to get back the old skool complete behavior, add the following to your `.zshrc` file, right _after_ you source `zsh-autocomplete`:
```shell
zle -N complete-word
complete-word() {
  zle .complete-word
}
```

**Comment by wookayin** [comment]
@marlonrichert You should introduce an environment variable to configure behaviors.

Also, the tab completion still doesn't work as I described. Did you ever test it? Even after the "roll back" overriding of `complete-word`, it is inserting completions just twice.

**Comment by marlonrichert** [comment]
@wookayin Yes, I tested it and it worked for me exactly as you described.

What do you mean with “ it is inserting completions just twice“? Can you give me an exact test case for this where this happens?

Do you have a concrete proposal for what kind of environment variables you think should be introduced and how they shoul work? If you can write a pull request for it, even better. 🙂

**Comment by marlonrichert** [comment]
> it is inserting completions just twice.

After using my suggested solution above, I can tab around infinitely, not just twice. I'm going to close this issue now. If you can provide me with a test case that let's me reproduce it, then I will reopen the issue.

**Comment by marlonrichert** [comment]
@TanishBansal @wookayin
I just wanted to let you know that 7256aebc89d2180be74bb242f80c1bd20e89d63a adds a new way to configure tab completion. Please see the Readme.

**Comment by NICHOLAS85** [comment]
hey @marlonrichert, I see you added support for [`zsh-autosuggestions`](https://github.com/zsh-users/zsh-autosuggestions) and it looks like everything is working correctly. However, I can't change the tab behavior as it suggests in the readme. I'd like to cycle through options using tab but it seems it always accepts the autosuggestion. Is there a way to work around this?

**Comment by marlonrichert** [comment]
Sorry, I somehow managed to commit the new code commented out. 🤦🏽‍♂️

I now pushed it in again, but not commented out this time. Please try again.

**Comment by TanishBansal** [comment]
Thanks @marlonrichert, I have made quite a lot of changes from[19bc2c ](https://github.com/marlonrichert/zsh-autocomplete/commit/19bc2cd937312d3b18d2213b3de55d737d8d4ae0)which fulfills my current need plenty.

Thanks for your awesome work.!
