### ISSUE TITLE
The "zstyle ':autocomplete:tab:*' completion select" no longer works

### ISSUE THREAD

**Issue by maarekj** [marlonrichert/zsh-autocomplete#100]
### Describe the bug
The option `zstyle ':autocomplete:tab:*' completion select` no longer works in last commit.

### To Reproduce

```shell
$ cd $(mktemp -d) 
$ ZDOTDIR=$PWD HOME=$PWD zsh -df
$ source path/to/zsh-autocomplete.plugin.zsh
$ zstyle ':autocomplete:tab:*' completion select
$ cd /
# tap ⇥ to enter in completion menu, but it selects the first item of menu.
```

### Expected behavior
tap ⇥ must enter in completion menu, not select the first item. (If `completion select` is set for `:autocomplete:tab:*`)

### Actual behavior
tap ⇥ selects the first item of menu.

### Desktop
 - OS + distribution: macOS
 - Zsh version: 5.7.1
 - Plugin version: 8993d533ac42468d301e4c9059e2b6fdc314d5d7

**Comment by dmknght** [comment]
On dev branch, latest commits, you can use
```
zstyle ':autocomplete:tab:*' accept-autosuggestions no
zstyle ':autocomplete:tab:*' widget-style menu-select
``` (For anybody want to save time to add new settings)

**Comment by marlonrichert** [comment]
Closing this as I will redo the features that I prototyped on the `dev` branch.
