### ISSUE TITLE
Recent directory and file completion stopped working?

### ISSUE THREAD

**Issue by weilbith** [marlonrichert/zsh-autocomplete#102]
Hey,
I'm back with an issue. Unfortunately a possible bug. I'm pretty sure that I haven't changed my zsh environment for a long while. Just updating the plugins from time to time. But over the time recognized more and more that I'm missing the recent * completion group. I think sometimes super rarely they still do appear. But most of the time no more. This is a pretty important feature for me, especially since I removed the manual key-binding for getting the suggestions by the tool itself (I mean calling `fasd` in my case).
I know that you did some major refactoring of this plugin and added a lot of new stuff. Did there maybe something slipped through? On the other hand I'm apparently the only one experiencing this issue.
I barely can provide much insight to the issue, since I simple have no. I tried it on a fresh setup machine with a pretty minimal setup as well ans also there it is not working or just once or twice in a while.
Sorry for this awkward report. But it has really become a major issue for me.

**Comment by weilbith** [comment]
I switched to the `dev` branch. There it kinda works or at least fails different. The suggestions look like this:

```sh
~/projects/brainbot-projects/repositories/raiden/hub.raiden.network$'\n'/home/thore/projects/brainbot-projects/repositories/raiden/light-client/raiden-dapp$'\n'/home/thore/projects/brainbot-projects/repositories/raiden/light-client/raiden-ts$'\n'/home/thore/projects/brainbot-projects/repositories/raiden/ansible-role-raiden-hub$'\n'/home/thore/projects/brainbot-projects/repositories/raiden$'\n'/home/thore/projects/brainbot-projects/repositories/raiden/light-client-prs/raiden-dapp$'\n'/home/thore/projects/brainbot-projects/repositories/raiden/light-client-prs/raiden-cli$'\n'/home/thore/projects/brainbot-projects/repositories/raiden/light-client-prs/raiden-ts$'\n'/home/thore/projects/brainbot-projects/repositories/raiden/light-client/raiden-cli$'\n'/home/thore/projects/brainbot-projects/repositories/raiden/light-client/raiden-ts/raiden-contracts$'\n'/home/thore/projects/brainbot-projects/repositories/raiden/raiden-hub$'\n'/home/thore/projects/brainbot-projects/repositories/raiden/light-client-prs/raiden-ts/raiden-contracts$'\n'/home/thore/projects/brainbot-projects/repositories/raiden/raiden$'\n'/home/thore/projects/brainbot-projects/repositories/raiden/light-client-test/raiden-cli$'\n'/home/thore/projects/brainbot-projects/repositories/raiden/light-client-prs/raiden-ts/raiden-contracts/raiden_contracts
recent file:
~/projects/brainbot-projects/repositories/raiden/light-client/raiden-ts/src/raiden.ts$'\n'/home/thore/projects/brainbot-projects/repositories/raiden/light-client/raiden-dapp/src/services/raiden-service.ts$'\n'/home/thore/projects/brainbot-projects/repositories/raiden/light-client/raiden-dapp/tests/unit/raiden-service.spec.ts$'\n'/home/thore/projects/brainbot-projects/repositories/raiden/light-client-prs/raiden-dapp/src/services/raiden-service.ts$'\n'/home/thore/projects/brainbot-projects/repositories/raiden/light-client/raiden-ts/tests/e2e/raiden.spec.ts$'\n'/home/thore/projects/brainbot-projects/repositories/raiden/light-client-prs/raiden-ts/src/raiden.ts
```

**Comment by marlonrichert** [comment]
@weilbith Sorry, the `dev` branch is a bit of a mess at the moment. I'm going to spend some time first to port all the bug fixes to `master` and then I will start cleaning it up.

**Comment by weilbith** [comment]
Sounds good. I adopted for the moment my configuration to use the `dev` branch because it also fixes some other issues I had like the autosuggestion highlighting etc.

**Comment by marlonrichert** [comment]
@weilbith Those fixes should now be available on the `master` branch. Please let me know if there's anything missing.

The features I prototyped on the `dev` branch will take a bit longer to come to the `master` branch, I'm afraid.
