### ISSUE TITLE
Incompatible color with zsh-autosuggestions

### ISSUE THREAD

**Issue by dmknght** [marlonrichert/zsh-autocomplete#103]
### Describe the bug
In previous version, of zsh-autocomplete, 2 plugins work fine together
![Screenshot at 2020-09-27 16-55-37](https://user-images.githubusercontent.com/29118926/94361979-aacc8280-00a7-11eb-8962-25342de1d557.png)
In this version, somehow it make zsh-autosuggestion doesn't show gray color anymore
![Screenshot at 2020-09-27 16-56-33](https://user-images.githubusercontent.com/29118926/94362003-cafc4180-00a7-11eb-82ca-fe21ef0e42e7.png)

### To Reproduce
1. I install zsh-autocomplete as debian package (i packaged my own)
2. Open shell in new version.
3. Disable zsh-autocomplete, the zsh-autosuggestion works fine.

### My .zshrc
```
# Prompt
PROMPT="%F{red}┌[%f%F{cyan}%m%f%F{red}]─[%f%F{yellow}%D{%H:%M-%d/%m}%f%F{red}]─[%f%F{magenta}%d%f%F{red}]%f"$'\n'"%F{red}└╼%f%F{green}$USER%f%F{yellow}$%f"
# Export PATH$
export PATH=~/.local/bin:/snap/bin:/usr/sandbox/:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/usr/share/games:/usr/local/sbin:/usr/sbin:/sbin:$PATH

# alias
alias ls='ls -lh --color=auto'
alias dir='dir --color=auto'
alias vdir='vdir --color=auto'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
#####################################################
# Auto completion / suggestion
# Mixing zsh-autocomplete and zsh-autosuggestions
# Requires: zsh-autocomplete (custom packaging by Parrot Team)
# Jobs: suggest files / foldername / histsory bellow the prompt
# Requires: zsh-autosuggestions (packaging by Debian Team)
# Jobs: Fish-like suggestion for command history
source /usr/share/zsh-autosuggestions/zsh-autosuggestions.zsh
source /usr/share/zsh-autocomplete/zsh-autocomplete.plugin.zsh
# Select all suggestion instead of top on result only
zstyle ':autocomplete:tab:*' completion select
zstyle ':autocomplete:list-choices:*' max-lines 100%
zstyle ':autocomplete:list-choices:*' min-input 2
zstyle ':autocomplete:*' recent-dirs off

##################################################
# Fish like syntax highlighting
# Requires "zsh-syntax-highlighting" from apt
source /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# Save type history for completion and easier life
HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
setopt appendhistory
```

### Expected behavior
The color showed by zsh-autosuggestions is not changed

### Actual behavior
The color showed by zsh-autosuggestions was changed to input color

### Desktop
 - OS + distribution: Parrot OS 4.10
 - Zsh version: 5.8
 - Plugin version: Well i don't know how to check hash commit history. the version was cloned 27th Sep 2020, branch master

P/s: The plugin makes zsh starts slower. Hope you can fix it too

**Comment by dmknght** [comment]
I've installed version from dev branch. The problem was solved.

**Comment by marlonrichert** [comment]
Fixed now on `master`.
