### ISSUE TITLE
exit takes too long time

### ISSUE THREAD

**Issue by dmknght** [marlonrichert/zsh-autocomplete#104]
### Describe the bug
With latest commit of zsh-autocomplete (ce4e5e7c9125a720529ba65ca855ea4084aa0b48), exit zsh takes 1 second or so to exit the terminal
### To Reproduce
1. Open terminal (zsh default)
2. type `exit` and `enter`

### Expected behavior
No delay for exit (like pervious versions)

### Actual behavior
1. Start zsh has delay time (i think it is faster than commits last month but it is till slow)
2. Exit zsh has delay time (like 1 second)
### Desktop
 - OS + distribution: Parrot OS 4.10
 - Zsh version: 5.8
 - Plugin version: ce4e5e7c9125a720529ba65ca855ea4084aa0b48

**Comment by marlonrichert** [comment]
@dmknght Can you try the latest commit on the `dev` branch and tell me if it's still a problem there? I'm not able to reproduce it.

**Comment by dmknght** [comment]
> @dmknght Can you try the latest commit on the `dev` branch and tell me if it's still a problem there? I'm not able to reproduce it.

Oh the problem is fixed on latest commit. Thank you @marlonrichert your plugin is awesome.
