### ISSUE TITLE
Unknown file attribute error

### ISSUE THREAD

**Issue by mushi-nova** [marlonrichert/zsh-autocomplete#105]
# Environment
- Zsh version: 5.8
- `zsh-autocomplete` version: **???**

Please report if the bug occurs without config files:
```zsh
$ cd $(mktemp -d)  # Create a temp dir and enter it.
$ ZDOTDIR=$PWD HOME=$PWD zsh -f  # Start a subshell without config files.
% source path/to/zsh-autocomplete.plugin.zsh  # Source the plugin.
% # Try to reproduce your bug...
```
Does the bug occur without config files?
* [ ] Yes
* [ ] No

If not, which combination of config causes the bug to appear?

**???**

# Steps to reproduce

1. **???**
2. ...

## Actual behavior
```
$ ls 
_autocomplete.recent-paths:10: unknown file attribute: 6
_autocomplete.recent-paths:10: unknown file attribute: 6
_autocomplete.recent-paths:10: unknown file attribute: 6
_autocomplete.recent-paths:10: unknown file attribute: 6
_autocomplete.recent-paths:10: unknown file attribute: 6
_autocomplete.recent-paths:10: unknown file attribute: 6
_autocomplete.recent-paths:10: unknown file attribute: 6
_autocomplete.recent-paths:10: unknown file attribute: 6
```

**Comment by marlonrichert** [comment]
@mushi-nova Can you give me a reproducible test case, please? If I cannot reproduce the bug, then I can neither test it nor fix it.

**Comment by mushi-nova** [comment]
Sorry but I don't know how you can specifically reproduce this. I have sourced autocomplete in my .zshrc but such error appears every time I try to type any command. But the appearance of such an error is erratic that means it happens sometimes for every keypress and other times it happens after typing the whole command.

I failed to understand the meaning of the error or the bug.

**Comment by marlonrichert** [comment]
@mushi-nova `_autocomplete.recent-paths` is the function that fetches your recent dirs from whatever dir jumping tool you are using: `zsh-z`, `zoxide`, `z.lua`, `rupa/z.sh`, `autojump` or `fasd`.

Which one of these do you use?

If you haven't installed any of these, then `zsh-autocomplete` defaults to `cdr`. http://zsh.sourceforge.net/Doc/Release/User-Contributions.html#Recent-Directories

**Comment by marlonrichert** [comment]
Closing this as I have no way of reproducing this and I haven't heard back from @mushi-nova.
