### ISSUE TITLE
Disable history_words completion

### ISSUE THREAD

**Issue by yutakatay** [marlonrichert/zsh-autocomplete#107]
### Is your feature request related to a problem? Please describe.

I don't want you to use history for completion. So I would like the option to disable it.

### Describe the solution you'd like

I'd like the option to disable `history_words`

### Describe alternatives you've considered

I haven't tried it, but I think I can disable it if I configure it myself using `zstyle ':autocomplete:*' config off`.
Or I could disable it by deleting the `_autocomplete.history_words` file.

**Comment by marlonrichert** [comment]
@yutakatay It is now possible to individually disable any and all extra completions that `zsh-autocomplete` adds: https://github.com/marlonrichert/zsh-autocomplete/blob/master/README.md#disable-particular-completions

**Comment by yutakatay** [comment]
Great work!! Thank you very much :joy:

**Comment by GeorgeGedox** [comment]
This is currently broken and all `zstyle ':completion:*:'` options are ignored

**Comment by marlonrichert** [comment]
@GeorgeGedox Can you give me a reproducible test case, so I can see this for myself and fix it?
