### ISSUE TITLE
How can i set a "bash-like" history for upper arrow?

### ISSUE THREAD

**Issue by dmknght** [marlonrichert/zsh-autocomplete#110]
I prefer the style of bash when use up arrow: select last history. By default, zsh-autocomplete shows full list of history which causes me delay and not very friendly. So is there any option that i can disable this or swich the style?

**Comment by marlonrichert** [comment]
Not yet. 🙂 I will implement this as part of #98 and #108.

**Comment by marlonrichert** [comment]
It is now possible to override the Arrow Up/Down key binding. Please see the [relevant section in the Readme](https://github.com/marlonrichert/zsh-autocomplete/blob/master/README.md#change-other-key-bindings).
