### ISSUE TITLE
Candidate completions for file paths containing a ~(tilde) are not colored

### ISSUE THREAD

**Issue by yutakatay** [marlonrichert/zsh-autocomplete#111]
# Environment
* Zsh version: zsh 5.8.0.2-dev (x86_64-pc-linux-gnu)
* `zsh-autocomplete` version: 0da3bdc1dd7c97a6afba53e922483a8be70acb4d

Does the bug occur without config files?
* [x] Yes
* [ ] No

# Steps to reproduce

```zsh
$ cd $(mktemp -d)  # Create a temp dir and enter it.
$ ZDOTDIR=$PWD HOME=$PWD zsh -f  # Start a subshell in it without config files.
% source path/to/zsh-autocomplete.plugin.zsh  # Source the plugin.
% zstyle ':completion:*' list-colors "${(@s.:.)LS_COLORS}"
% mkdir ~/.aaa
% touch ~/.bbb.sh
% ls -l ~/.
# There's no color on auto candidate completion
% ls -l $HOME/.
# This is OK
% ls -l /
# This is also OK
```

## Expected behavior
Candidate completions are colored even if the path starts with a `~` (home directory).

## Actual behavior
Paths with tilde's don't get colored.

**Comment by marlonrichert** [comment]
Should be fixed now.

**Comment by yutakatay** [comment]
I was able to check this fix. Thank you very much.
