### ISSUE TITLE
undefined-key information when start zsh

### ISSUE THREAD

**Issue by xcetos** [marlonrichert/zsh-autocomplete#114]
# Environment
* Zsh version: **5.8**
* `zsh-autocomplete` version: ** edf6f867fa75032ae55403891dde014bb33ca1f4**

Please report if the bug occurs without config files:
```zsh
$ cd $(mktemp -d)  # Create a temp dir and enter it.
$ ZDOTDIR=$PWD HOME=$PWD zsh -f  # Start a subshell in it without config files.
% source path/to/zsh-autocomplete.plugin.zsh  # Source the plugin.
% # Try to reproduce your bug...
```
Does the bug occur without config files?
* [x] Yes
* [ ] No

# Steps to reproduce

1. Start a subshell in it without config files.
2. source zsh-autocomplete.plugin.zsh

## Expected behavior
**No output**

## Actual behavior

```zsh
"up-line-or-search" undefined-key
"down-line-or-select" undefined-key
"history-search" undefined-key
"menu-select" undefined-key
"list-expand" undefined-key
"accept-and-hold" undefined-key
"^I" complete-word
"^J" accept-line
"^M" accept-line
"^[OA" up-line-or-history
"^[OB" down-line-or-history
"^[OC" forward-char
"^[OD" backward-char
"^[[A" up-line-or-history
"^[[B" down-line-or-history
"^[[C" forward-char
"^[[D" backward-char
"vi-backward-blank-word" undefined-key
"vi-forward-blank-word" undefined-key
"backward-word" undefined-key
"forward-word" undefined-key
"beginning-of-history" undefined-key
"end-of-history" undefined-key
```

**Comment by marlonrichert** [comment]
@xcetos I'm not able to reproduce this with the latest commit on the `master` branch. Can you please `git pull` and try again?

**Comment by xcetos** [comment]
Ops! The problem was solved after I did `git pull`, though I still don't know why. Anyway, thank you!
