### ISSUE TITLE
zsh-autosuggestion not responding to → press, instead just navigates through suggested characters

### ISSUE THREAD

**Issue by paw-lu** [marlonrichert/zsh-autocomplete#116]
# Environment
* Zsh version: **5.8**
* `zsh-autocomplete` version: **4aa819f98e05776**

Does the bug occur without config files?
* [x] Yes
* [ ] No

# Steps to reproduce

```zsh
$ cd $(mktemp -d)  # Create a temp dir and enter it.
$ ZDOTDIR=$PWD HOME=$PWD zsh -f  # Start a subshell in it without config files.
% source /Users/pawlu/.oh-my-zsh/custom/plugins/zsh-autosuggestions/zsh-autosuggestions.plugin.zsh
% source /Users/pawlu/.oh-my-zsh/custom/plugins/zsh-autocomplete/zsh-autocomplete.plugin.zsh
% s
```

Pressing <kbd>→</kbd> will now toggle though suggested characters one at a time instead of completing suggestion.

![Kapture 2020-10-23 at 10 53 54](https://user-images.githubusercontent.com/30049606/97037551-470a6d80-151e-11eb-98f0-71c8a63029e6.gif)

## Expected behavior
Pressing <kbd>→</kbd> will accept the entire suggestion.

## Actual behavior
Pressing <kbd>→</kbd> moves one character at a time through the suggestion.

---

As always, thanks for the project. It evolves by _so much_ each time I check in on it.

**Comment by marlonrichert** [comment]
@paw-lu This is actually intended behavior. I like to be able to accept single characters. 🙂 If you want to accept the entire suggestion, you can press <kbd>End</kbd>.

But I noticed that the autosuggest highlighting is now broken under these circumstances. I will have to fix that.

**Comment by paw-lu** [comment]
Got it, thank you so much for the help!

I didn't find this documented anywhere, so I suggested #117 to prevent others from getting stumped.

**Comment by marlonrichert** [comment]
I added a comment to your PR. I might remove this feature, since I'm starting to feel it doesn't really belong in `zsh-autocomplete`.

**Comment by marlonrichert** [comment]
I removed the feature. `zsh-autosuggestions` keys should be back to default. If you want to keep that behavior, you can add the following to your `~/.zshrc` file:
```zsh
source path/to/zsh-autosuggestions.plugin.zsh
ZSH_AUTOSUGGEST_ACCEPT_WIDGETS=( "${ZSH_AUTOSUGGEST_ACCEPT_WIDGETS[@]:#*forward-char}" )
ZSH_AUTOSUGGEST_PARTIAL_ACCEPT_WIDGETS+=( forward-char vi-forward-char )
```

**Comment by paw-lu** [comment]
Got it! I agree that this is out of scope for this project!

As always, thanks @marlonrichert !
