### ISSUE TITLE
zle-line-finish

### ISSUE THREAD

**Issue by sejgit** [marlonrichert/zsh-autocomplete#12]
when running a command like which fzf (might be with any command), no shell function 'zle-line-finish' exists flashes up then is erased and a blank prompt comes up.  I have turned off my whole init file then back on, the behavior persists.

**Comment by sejgit** [comment]
think I found the issue ; line #117 got truncated, should read:
zle -N zle-line-finish _zsh_autocomplete_finish

**Comment by marlonrichert** [comment]
Thanks! Weird that this didn’t happen when I tested it. I will fix it.

**Comment by marlonrichert** [comment]
Fixed. Thanks again!
