### ISSUE TITLE
Invalid warning about deprecated zstyle settings.

### ISSUE THREAD

**Issue by nisegami** [marlonrichert/zsh-autocomplete#121]
## Environment:
- ZSH version: zsh 5.4.2 (x86_64-ubuntu-linux-gnu)
- zsh-autocomplete: up to date with master branch
- Framework: none
- Plugin manager: zinit
- .zshrc: https://gist.github.com/nisegami/4e384729fbf6dc704fca6e848cbfa0ba 

Note: that's a minimal .zshrc with nothing but zinit and zsh-autocomplete loaded. 

## Steps to reproduce
Start a shell

### Expected behavior
No warnings as I am not using any zstyle commands.

### Actual behavior
Following warning printed:
```
Warning: `zstyle :autocomplete:list-choices:*` settings are no longer supported.
Please use `zstyle :autocomplete:*` for these settings instead.
```
![Image of error](https://user-images.githubusercontent.com/2251723/98451438-d9fcf780-211b-11eb-836a-4cfbd6737418.png)

## Fix?
I believe this is the problematic line: https://github.com/marlonrichert/zsh-autocomplete/blob/95af8f02dd8fd1c8dea3d6348d70096e8b3b3593/module/.autocomplete.config#L9

Changing the 0 to a 1 resolves the issue. Changing it to 1 also still prints the warning if I intentionally add an old zstyle command to my .zshrc.

**Comment by marlonrichert** [comment]
@nisegami I am not able to reproduce this with just `zinit` and `zsh-autocomplete`. Here's what I did:
 1. Create a temp dir and `cd` into it:
    ```zsh
    cd "$(mktemp -d)"
    ```
 1. In that temp dir, create a file `.zshrc` and put the following two lines in it:
    ```zsh
    source /Users/marlon/.zsh/zinit/zinit.zsh
    zinit light-mode for marlonrichert/zsh-autocomplete
    ```
 1. Start a subshell in that temp dir, which will use that `.zshrc`, but no global config files:
    ```zsh
    ZDOTDIR=$PWD HOME=$PWD zsh -d
    ````

Result: Everything works fine and no error message is shown.

Ergo, it must be a problem in one of those "annexes" or whatever else you have in the `.zshrc` file you linked to.

Try to narrow down what is causing it by removing more things from your `.zshrc` file, until the bug disappears. Then file a bug in the appropriate repo in https://github.com/zinit-zsh
