### ISSUE TITLE
Error printed if I press 'up' in a fresh session.

### ISSUE THREAD

**Issue by nisegami** [marlonrichert/zsh-autocomplete#122]
## Environment:
- ZSH version: zsh 5.4.2 (x86_64-ubuntu-linux-gnu)
- zsh-autocomplete: up to date with master branch
- Framework: none
- Plugin manager: zinit
- .zshrc: https://gist.github.com/nisegami/4e384729fbf6dc704fca6e848cbfa0ba 

Note: that's a minimal .zshrc with nothing but zinit and zsh-autocomplete loaded. 

## Steps to reproduce
- Start a shell
- Press up

### Expected behavior
Nothing?

### Actual behavior
Following error printed:
```
_autocomplete.history_lines:55: displays: assignment to invalid subscript range
```
![Image of error](https://user-images.githubusercontent.com/2251723/98451549-09f8ca80-211d-11eb-8766-39752c167d2a.png)

**Comment by marlonrichert** [comment]
@nisegami Thanks for reporting. I am able to reproduce this. I'll investigate.

**Comment by marlonrichert** [comment]
Should be fixed now.
