### ISSUE TITLE
How to make the ENTER directly execute the command

### ISSUE THREAD

**Issue by zigitn** [marlonrichert/zsh-autocomplete#123]
## What do you want?
when I use completion or history and choose one, I want to execute command directly when I type enter, not just exit the prompt.

## Why do you want this?
Every time I need to press ENTER twice, it makes me feel tired.

## Other
I don’t know if there are related issues, but I have checked the issues as much as possible, and have not found the same issues.  
thanks for you work, it's awesome plugin.

**Comment by marlonrichert** [comment]
Good idea. It's there now.

**Comment by maarekj** [comment]
I prefered the old behavior.
Currently I can navigate in directory with `tab, tab, enter, tab, tab, enter`

Example:
I am in `~/`
I want execute the script (with some options) `~/myproject/bin/console -vvv --option`

Previously I press `my, tab, enter, bi, enter, con, enter, -vvv --option, enter`
Currently I if press `my, tab, enter`, it executes `myproject` (equivalent to `cd myproject`)

**Comment by marlonrichert** [comment]
@maarekj I can see how that's a problem for you. I'll add a setting to enable the old behavior.

**Comment by marlonrichert** [comment]
@maarekj It's now possible to revert back to the old behavior of Enter in the menu. Please see [this section of the Readme](https://github.com/marlonrichert/zsh-autocomplete/blob/master/README.md#change-other-key-bindings).

**Comment by maarekj** [comment]
Thank you !
