### ISSUE TITLE
yay stops with this plugin

### ISSUE THREAD

**Issue by Fijxu** [marlonrichert/zsh-autocomplete#124]
## Environment
* `zsh-autocomplete` version: 50c8a92 
* Zsh version: 5.8
* Framework: Oh My Zsh 
* `~/.zshrc` file: https://pastebin.com/Y28gKwAL 

Please test if the bug occurs without config files:
```zsh
$ cd $(mktemp -d)  # Create a temp dir and enter it.
$ ZDOTDIR=$PWD HOME=$PWD zsh -f  # Start a subshell in it without config files.
% source path/to/zsh-autocomplete.plugin.zsh  # Source the plugin.
% # Try to reproduce your bug...
```
Does the bug occur without config files?
* No 

If not, gradually add lines from your config file to the subshell until the bug appears.

Which combination of config causes the bug to appear?
* Add zsh-autcomplete to the active plugins 

## Steps to reproduce

1. Enable zsh-autocomplete plugin in the ~/.zshrc config
2. Write `yay ` in the console 

### Expected behavior

yay should works fine

### Actual behavior

yay stops and coredump start running

**Comment by Fijxu** [comment]
Before this did not happen, before I used the edition of manjaro KDE Minimal but now I used manjaro Architect to test and things like that, and when I installed the plugin and wrote "yay" was stuck only, and that with the minimal version kde did not happen to me

![Peek 2020-11-13 16-16](https://user-images.githubusercontent.com/61166695/99126503-0a91d500-25e5-11eb-87ba-864d66235925.gif)

**Comment by marlonrichert** [comment]
Sorry, but I'm not able to reproduce this. Here's what I did: 
```zsh
$ cd "$(mktemp -d)"; ZDOTDIR=$PWD HOME=$PWD zsh -f
% fpath+=( path/to/yays/_pacman_comp )
% source path/to/zsh-autocomplete.plugin.zsh
```
Works fine for me, without any lag. If you can provide me with a reproducible test case, then I'll investigate further.
