### ISSUE TITLE
compadd:22: command not found: _autocomplete.compadd_opts_le after pulling 668b78fe8e2316ef0df4908ea832bc5b4ebeeee6

### ISSUE THREAD

**Issue by naefl** [marlonrichert/zsh-autocomplete#125]
## Environment
* `zsh-autocomplete` version: 668b78fe8e2316ef0df4908ea832bc5b4ebeeee6  
* Zsh version: 5.8  
* Framework: omz 
* `~/.zshrc` file: none  

Does the bug occur without config files?
* Yes  

If not, gradually add lines from your config file to the subshell until the bug appears.

Which combination of config causes the bug to appear?
* None 

## Steps to reproduce

1. 668b78fe8e2316ef0df4908ea832bc5b4ebeeee6 causes `compadd:22: command not found: _autocomplete.compadd_opts_le` to show up ~20-30x whenever I enter a letter (tested on Kitty, iTerm2, Alacritty). MacOS BigSur. Everything up to 314db984e864ca5a7088e84e780f1a6aead87089 works fine (i.e. reverting to `314...` fixes it.

### Expected behavior

Autocomplete without output

### Actual behavior

`compadd:22: command not found: _autocomplete.compadd_opts_le`

**Comment by marlonrichert** [comment]
Sorry, but I cannot reproduce this. Here's what I did:
```zsh
$ cd "$(mktemp -d)"; ZDOTDIR=$PWD HOME=$PWD zsh -f
% sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
% source path/to/zsh-autocomplete.plugin.zsh
```
Works fine for me.

Have you tried deleting OMZ's compdump file?
```zsh
 rm -i $ZSH_COMPDUMP
```

**Comment by naefl** [comment]
That didn't help - however the patch to the timeout logic you just pushed fixed it so fine either way.

While we're at it: thanks a ton for the awesome project & spending your free time on this!
