### ISSUE TITLE
Is it possible to filter continuous and repeated history records？

### ISSUE THREAD

**Issue by zigitn** [marlonrichert/zsh-autocomplete#129]
## What do you want?
could you add an option to filter out continuous and repeated history records?

## Why do you want this?
Sometimes I will use a lot of the same commands repeatedly, which makes it difficult to find the history records I want. 

## Who else would benefit from this?
Other people who use repeated commands a lot, I think.

**Comment by marlonrichert** [comment]
[Zsh itself has various options for that](http://zsh.sourceforge.net/Doc/Release/Options.html#History):

> * `HIST_FIND_NO_DUPS:` When searching for history entries in the line editor, do not display duplicates of a line previously found, even if the duplicates are not contiguous.
> * `HIST_IGNORE_ALL_DUPS`: If a new command line being added to the history list duplicates an older one, the older command is removed from the list (even if it is not the previous event).

**Comment by thekip** [comment]
@marlonrichert could you elaborate a bit how using this options hide this duplicates? 

![image](https://user-images.githubusercontent.com/1586852/109292130-33ec0f00-782a-11eb-8bad-7738ab0a39db.png)

I tried to add `setopt HIST_FIND_NO_DUPS` to my `.zhrc` and then  `source ~/.zshrc` but still see a lot of duplicates in search. Sorry if it's a stupid question, I'm a complete newbie in all these things

**Comment by marlonrichert** [comment]
You're right, the option doesn't seem to work here. I'll see if I can change the code to respect it.

**Comment by thekip** [comment]
Moreover now it shows one command in the list, but pick up different command when you navigate to it. 

![screencast 2021-03-02 08-41-30](https://user-images.githubusercontent.com/1586852/109615091-c266d600-7b33-11eb-8ad9-74ef6c43caea.gif)

**Comment by GabrielDeml** [comment]
Could you point me in the direction of where this bug would be? I have been having the same problem and would like to fix it. Starting next Thursday I will have a couple days off from school so at least I could take a shot at fixing it.

**Comment by marlonrichert** [comment]
@GabrielDeml Sure thing. You can find the code in question here: https://github.com/marlonrichert/zsh-autocomplete/blob/main/completion/_autocomplete.history_lines

**Comment by marlonrichert** [comment]
All right, it's there.

**Comment by marlonrichert** [comment]
@GabrielDeml Sorry, this turned out not to be a "good first issue" at all. My bad. 😅
