### ISSUE TITLE
Closing termnial window when pressing arrow up

### ISSUE THREAD

**Issue by DanDobrick** [marlonrichert/zsh-autocomplete#13]
This must have changed at some point today since I updated the plugin this evening, but when pressing the up arrow to attempt to cycle through my history, the terminal window closes instead.

On OSX using both iTerm and the terminal bundled with rubymine.

**Comment by DanDobrick** [comment]
Stepping through the commits and trying them all out it looks to have happened in this commit: 9d0e92e7733d1f3f3cd9aa438aae722bd20cd2a4

**Comment by marlonrichert** [comment]
Thanks, I’ll have to see if I can reproduce that.

**Comment by marlonrichert** [comment]
This seems to happen when you don't have Fzf installed, which causes `zsh-autocomplete` to fall back to the `history-search-backward` widget. And for some reason, this crashes Zsh. Not sure why or how to work around it. I'll have to investigate some more.

**Comment by andreypopp** [comment]
Have fzf installed and in PATH but it happens for me as well, if I comment a line which binds an up arrow in this plugin then it works ok.

**Comment by marlonrichert** [comment]
@andreypopp Are you sourcing [Fzf's keybindings](https://github.com/junegunn/fzf/blob/master/shell/key-bindings.zsh)? Without them, the code falls back to using `history-search-backward`. Simply having Fzf in your path is not enough.

**Comment by andreypopp** [comment]
@marlonrichert no, I'm not. Still a bit confusing why it closes the shell on "Up" in that case.

**Comment by marlonrichert** [comment]
OK, you **_should_** source Fzf's keybindings if you want `zsh-autocomplete` to use Fzf for history search. 🙂 

As to why calling any of Zsh's history widgets inside another widget closes the shell, I have no idea. It only works if you call them right away, but if you do anything before that, the shell crashes.

**Comment by marlonrichert** [comment]
@DanDobrick @andreypopp I pushed in a fix. Please `git pull` and let me know if it works for you. 🙂

**Comment by DanDobrick** [comment]
@marlonrichert Works perfectly, thanks!
