### ISSUE TITLE
Magic-enter messes up the displayed command that was executed

### ISSUE THREAD

**Issue by foxale** [marlonrichert/zsh-autocomplete#131]
## Environment
* `zsh-autocomplete` version:  latest (22.11.2020)
* Zsh version: zsh-5.8-0-g77d203f
* Framework: Oh My Zsh
* Plugin manager: none
* `~/.zshrc` file: https://github.com/foxale/dotfiles/tree/master/zsh 

Please test if the bug occurs without config files:
```zsh
$ cd $(mktemp -d)  # Create a temp dir and enter it.
$ ZDOTDIR=$PWD HOME=$PWD zsh -f  # Start a subshell in it without config files.
% source path/to/zsh-autocomplete.plugin.zsh  # Source the plugin.
% ls -la
% ls  # "-la" is suggested at this point, but I decide to go with bare ls and hit return
```
Here the same with "ls /Applications" as this is the autocompletion's proposition for "ls" in my case: 
![image](https://user-images.githubusercontent.com/14327763/99906271-6ee42100-2cd6-11eb-893c-0928a27ed0a9.png)
After I hit return:
![image](https://user-images.githubusercontent.com/14327763/99906280-799eb600-2cd6-11eb-9d81-a9b804d549c5.png)
The command suggests that I entered "ls /Applications", but in fact a bare "ls" command was executed

Does the bug occur without config files?
No

![image](https://user-images.githubusercontent.com/14327763/99906166-d8affb00-2cd5-11eb-93bf-bd83d58c3347.png)
![image](https://user-images.githubusercontent.com/14327763/99906172-e5345380-2cd5-11eb-960f-5facc7c21514.png)

If not, gradually add lines from your config file to the subshell until the bug appears.

Which combination of config causes the bug to appear?
magic-enter plugin
https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/magic-enter

## Steps to reproduce

1. Add magic-enter to plugins, before zsh-autocomplete
2. Play around

**Comment by marlonrichert** [comment]
I'm able to reproduce this, but it's not a bug in `zsh-autocomplete`. Rather, it's bad interaction between `magic-enter` and `zsh-autosuggestions`. You can see for yourself as follows:
 1. First, do the following:
    ```zsh
    $ cd "$(mktemp -d)"
    $ ZDOTDIR=$PWD HOME=$PWD zsh -f
    % source path/to/ohmyzsh/plugins/magic-enter/magic-enter.plugin.zsh; source path/to/zsh-autosuggestions/zsh-autosuggestions.plugin.zsh
    % touch foo
    % ls foo
    foo
    % ls 
    ```
 1. Make sure you press Space after the last `ls`, so you get the suggestion `foo`.
 1. Press Enter.

Expected Result: The suggestion should be cleared, as it is without `magic-enter`.

Actual Result: The suggestion remains.

Please file a bug with Oh My Zsh and tag `@dufferzafar` (the plugin's maintainer).
