### ISSUE TITLE
Match case-insensitive beginning letters of files first

### ISSUE THREAD

**Issue by PatrickJosh** [marlonrichert/zsh-autocomplete#132]
## What do you want?
I'd like the plugin to match the beginning letters of a file or directory first, although the file's or directory's name is not entered the same case as the name is. For example, if you have to directories, one named `Documents`, the other named `University` and you type `cd u`, then the suggestions are `Documents` and `University` in this order. I'd like `University` or any other file/directory whose name begins with `u` or `U` to come up first.
Maybe, there could be an option to select this? 

## Why do you want this?
I think it is more natural to show the files and directories that begin with the same letters as typed first, no matter if the case is matched. Moreover, while changing directories, I'm lazy and type lowercase only and don't want to mind the case of the directory's name.

## Who else would benefit from this?
I guess everyone that's lazy as I am in this case, and the people coming from default zsh with case-insensitive completion (as I came from) who are used to this behaviour (although I don't know if it is the zsh default for case-insensitive completion or just an `oh-my-zsh` specific thing).

## Explain in detail how you would expect this to work
Given the following situation above:
The files and directories whose names are matched from the beginning should be shown first, regardless of case. So in the situation above, `University` should come up first and then `Documents`. Alternatively, `Documents` could be omitted completely as it is with the default case-insensitive completion of zsh.

If there is an option (of zsh or this plugin) to select this behaviour already, I'm sorry for opening this issue, but I haven't found one yet.

**Comment by marlonrichert** [comment]
Thanks for the suggestions. It's there now.
