### ISSUE TITLE
History suggestion by up arrow appears but fails to execute

### ISSUE THREAD

**Issue by ShrirajHegde** [marlonrichert/zsh-autocomplete#133]
## Environment
* `zsh-autocomplete` version: 6020398e918f4859e542bf4ebca838188593cc66
 
* Zsh version: zsh-5.8-0-g77d203f
* Framework:none 
* Plugin manager: none 
* `~/.zshrc` file:  https://pastebin.com/3WYHT8rN

Please test if the bug occurs without config files:
```zsh
$ cd $(mktemp -d)  # Create a temp dir and enter it.
$ ZDOTDIR=$PWD HOME=$PWD zsh -f  # Start a subshell in it without config files.
% source path/to/zsh-autocomplete.plugin.zsh  # Source the plugin.
% # Insert here the steps you take to reproduce your bug.
```
Does the bug occur without config files?
* YES 

## Steps to reproduce

1. use any command , say `clear`

2. use top arrow to get suggestions and select right one and press enter
![image](https://user-images.githubusercontent.com/66936172/100196019-3d5d9680-2f1e-11eb-864a-e4dc4a21d2d2.png)

### Actual behavior
The suggestion is correct,but command doesn't get executed (just blank and goes to next commant) 

### Expected behavior
Execute the highlighted command from suggestions

**Comment by marlonrichert** [comment]
Sorry, I cannot reproduce this at all. Here's what I did:
```zsh
$ cd "$(mktemp -d)"; ZDOTDIR=$PWD HOME=$PWD zsh -f
% source /Users/marlon/.zsh/zsh-autocomplete/zsh-autocomplete.plugin.zsh
% touch foo bar baz
% ls
```
I then pressed ⬆️ and then ↩️. Result: `ls` gets executed again. Works fine.

If you can give me a working test case, then I'll reopen the issue.
