### ISSUE TITLE
Interferes with fast-syntax-highlighting

### ISSUE THREAD

**Issue by wu-qing-157** [marlonrichert/zsh-autocomplete#134]
If using together with `fast-syntax-highlighting`, the highlighting appears on every key strokes, but then disappears when the completion list is displayed.

# Environment
* `zsh-autocomplete` version: eff7388
* Zsh version: 5.8
* Framework: Oh My Zsh

Please test if the bug occurs without config files:
```zsh
$ cd $(mktemp -d)  # Create a temp dir and enter it.
$ ZDOTDIR=$PWD HOME=$PWD zsh -f  # Start a subshell in it without config files.
% source path/to/fast-syntax-highlighting.plugin.zsh
% source path/to/zsh-autocomplete.plugin.zsh  # Source the plugin.
```
Does the bug occur without config files?
Yes

## Steps to reproduce
Just use the above test without config files

### Expected behavior
`fast-syntax-highlighting` works properly

### Actual behavior
After a key is pressed, `fast-syntax-highlighting` works properly. Shortly after, when `zsh-autocomplete` display the completion suggestion list, the typed command becomes un-highlighted (plain white).

## Others

I have binary search the commit list on branch `master` using the above test without config test.
4c0ef48 works properly, but the issue appears on 6020398.

**Comment by marlonrichert** [comment]
Fixed.

**Comment by wu-qing-157** [comment]
Hi! The problem seems to take place again after [1bc63f7](https://github.com/marlonrichert/zsh-autocomplete/commit/1bc62f7859262d02cc3aa3f1472869194a3baa71).

**Comment by marlonrichert** [comment]
@wu-qing-157 Fixed.
