### ISSUE TITLE
Completion for Zoxide not working - how can I debug?

### ISSUE THREAD

**Issue by weilbith** [marlonrichert/zsh-autocomplete#135]
## Environment
* `zsh-autocomplete` version: acfd9db0b0f0ac8191f96706ecd86a7c91a27750
* Zsh version: `zsh-5.8-0-g77d203f`
* Framework: none
* Plugin manager: Zinit
* `~/.zshrc` file: complicated... the relevant combi should look like this:

```zsh
eval "$(zoxide init zsh)"

# Can't use `wait` mode, else hooks get not registered for the first prompt.
zinit lucid light-mode \
  atinit"zstyle ':completion:*' extra-verbose yes" \
  atinit"zstyle ':autocomplete:*' groups 'always'" \
  atinit"zstyle ':autocomplete:tab:*' widget-style menu-select" \
  atinit"zstyle ':autocomplete:tab:*' fzf-completion yes" \
  for marlonrichert/zsh-autocomplete
```

## Steps to reproduce
1. Make sure that `zoxide` is working, e.g. `zoxide quert some-dir` provides results
2. Type `cd some-dir` and check if there are recent directory suggestions provided

### Actual behavior
The recent directory group is never shown

### Expected behavior
I get recent directory suggestions

**Comment by marlonrichert** [comment]
It appears that `zoxide` has renamed its `chpwd` hook from `_zoxide_hook` to `__zoxide_hook`. Thanks for reporting this. I'll update the code.

**Comment by marlonrichert** [comment]
Oh, and as for your question "how can I debug?"; this is the steps I took to discover this:
```zsh
% # Check which recent dirs tool is being called:
% type -f _autocomplete.recent_dirs 
_autocomplete.recent_dirs () {
	reply=(${(M@)_autocomplete__recent_dirs[@]:#*/[^/]#$word[-1][^/]#}) 
	(( $#reply > 0 ))
}
% # Looks like it's `zsh-autocomplete`'s own default and not `zoxide`.
% # Let's see which part of
% # `[[ -v commands[zoxide] && -v functions[__zoxide_hook] ]] &&
% #  zstyle -T ':autocomplete:' recent-dirs 'zoxide'` fails, one piece at a time.
% [[ -v commands[zoxide] ]]; print $?
0
% [[ -v functions[__zoxide_hook] ]]; print $?
1
% # Bingo! Now let's look what `zoxide`'s init code looks like these days:
% zoxide init zsh       
[...]
# =============================================================================
#
# Hook configuration for zoxide.
#

# Hook to add new entries to the database.
function __zoxide_hook() {
    zoxide add "$(__zoxide_pwd)"
}

# Initialize hook.
chpwd_functions=(${chpwd_functions[@]} "__zoxide_hook")
[...]
```
And Bob's your uncle.

**Comment by marlonrichert** [comment]
Fixed.

**Comment by weilbith** [comment]
Cool, thank you very much! :pray:

**Comment by weilbith** [comment]
@marlonrichert I'm sorry, but I updated this morning the plugin and now I get basically no completion anymore, or only every century. What happened?

**Comment by marlonrichert** [comment]
@weilbith It works for me. Have you tried deleting `~/.zcompdump`?

**Comment by marlonrichert** [comment]
`zsh-autocomplete` actually tries to auto-delete your comp dump file, but it seems to fail for some end users. I have no idea why.

**Comment by weilbith** [comment]
Hmm. I deleted it once manually. Then it worked for the first couple of seconds.
I think my setup with `zinit` is off. Their documentation confuses me. The dump file and the cache get now also stored next to my `.zshrc` which is a no go (there is "cache" in the name not "config"). Recently changed that.
When or where do you call `compinit`?

**Comment by marlonrichert** [comment]
> I think my setup with `zinit` is off. Their documentation confuses me.

One of the reasons I wrote [Znap](https://github.com/marlonrichert/zsh-snap). 😉

> When or where do you call `compinit`?

Here: https://github.com/marlonrichert/zsh-autocomplete/blob/05cc0e37737a11a99161ba77e3248ebf180d6dc6/utility/.autocomplete.compinit#L9

**Comment by weilbith** [comment]
Sorry to annoy you. So I ran `zsh -fd` source your plugin and auto-completion works.
So my current buggy behavior is that I sometimes get completion for the first character and then always just when I hit `Tab`. Who can I find out why this automatic stuff does not happen anymore? Is that a hook to establish that gets not established?

**Comment by marlonrichert** [comment]
Could be. What output do you get from `add-zle-hook-widget -L`?

**Comment by weilbith** [comment]
Output:
```zsh
zstyle zle-line-init widgets 1:.autocomplete.key.line-init
zstyle zle-line-finish widgets 1:.autocomplete.key.line-finish
zstyle zle-line-pre-redraw widgets 1:.autocomplete.async.line-pre-redraw
```

I mean 2 days ago everything was fine and your plugin was fantastic as always (I mean except the zoxide issue :stuck_out_tongue: ). Then the update and it only works "manually" anymore. Which is bad for a plugin with "auto" in its name. :joy:

**Comment by marlonrichert** [comment]
I still cannot reproduce this. What happens if you manually `source path/to/zsh-autocomplete.plugin.zsh`, without `zinit`?

**Comment by marlonrichert** [comment]
I just tried it with `zinit` and it works fine for me. Here's what I did:
```zsh
$ cd "$(mktemp -d)"; ZDOTDIR=$PWD HOME=$PWD PS1='%~:%?> ' PS4='+%e %N:%I %?> %_ ' zsh -f
% sh -c "$(curl -fsSL https://raw.githubusercontent.com/zdharma/zinit/master/doc/install.sh)"
% source .zshrc
% zinit light-mode for marlonrichert/zsh-autocomplete
```
Works fine.

**Comment by weilbith** [comment]
> What happens if you manually source path/to/zsh-autocomplete.plugin.zsh, without zinit?

I tried already, but it doesn't help (doing it after my normal setup with zinit).

Yeah I mean it was working fine since a couple of days ago. No clue what changed. Okay, so I have no chance but going step for step from an "empty" setup to my current and see when it stops working. :expressionless:

**Comment by marlonrichert** [comment]
Good luck!

**Comment by weilbith** [comment]
@marlonrichert I found the issue. I have the following in my `.zshrc`:

```zsh
# Always be in normal/vicmd mode on new prompt.
zle-line-init() { zle -K vicmd; }
zle -N zle-line-init
```

If I comment/uncomment this, it either works or does not work. But this part of my configuration exists for years already. Did you changed something with the recent commits that breaks it? :thinking:

**Comment by marlonrichert** [comment]
Should be fixed now.

**Comment by weilbith** [comment]
Great! It works. Thank you very much! 🙏
