### ISSUE TITLE
.autocomplete.key:X: command not found: add-zle-hook-widget

### ISSUE THREAD

**Issue by dukman83** [marlonrichert/zsh-autocomplete#137]
## Environment
* `zsh-autocomplete` version: ???  Shown in most recent version.
* Zsh version: ???  5.7.1
* Framework: ???  Oh My Zsh
* Plugin manager: ???  none
* `~/.zshrc` file: ???  N/A

Please test if the bug occurs without config files:
```zsh
$ cd $(mktemp -d)  # Create a temp dir and enter it.
$ ZDOTDIR=$PWD HOME=$PWD zsh -f  # Start a subshell in it without config files.
% source path/to/zsh-autocomplete.plugin.zsh  # Source the plugin.
% # Insert here the steps you take to reproduce your bug.
```
Does the bug occur without config files?
* ??? 

If not, gradually add lines from your config file to the subshell until the bug appears.

Which combination of config causes the bug to appear?
* ??? 
Shown every time the user signs in to Raspberry Pi.

## Steps to reproduce

1. ssh into Raspberry Pi user whose default shell is zsh with autocomplete installed
2. ...

### Actual behavior
??? 
Two errors: 
.autocomplete.key:59: command not found: add-zle-hook-widget
.autocomplete.key.66: command not found: add-zle-hook-widget

### Expected behavior
??? 
No errors when signing into shell.

**Comment by marlonrichert** [comment]
Fixed.

**Comment by dukman83** [comment]
You are amazing! 😄

Regards,

Alex Alduk

________________________________
