### ISSUE TITLE
.autocomplete.add-zsh-hook:1: maximum nested function level reached; increase FUNCNEST?

### ISSUE THREAD

**Issue by dukman83** [marlonrichert/zsh-autocomplete#138]
## Environment
* `zsh-autocomplete` version: ???  Most recent
 Zsh version: ???  5.7.1-1
* Framework: ???  Oh My ZSH
* Plugin manager: ???  none
* `~/.zshrc` file: ???  N/A

Please test if the bug occurs without config files:
```zsh
$ cd $(mktemp -d)  # Create a temp dir and enter it.
$ ZDOTDIR=$PWD HOME=$PWD zsh -f  # Start a subshell in it without config files.
% source path/to/zsh-autocomplete.plugin.zsh  # Source the plugin.
% # Insert here the steps you take to reproduce your bug.
```
Does the bug occur without config files?
* ??? 

If not, gradually add lines from your config file to the subshell until the bug appears.

Which combination of config causes the bug to appear?
* ??? 

## Steps to reproduce

1. ???
2. ...

### Actual behavior
??? 
As soon as logging into Raspberry Pi the error ".autocomplete.add-zsh-hook:1: maximum nested function level reached; increase FUNCNEST?" appears 5 times.
### Expected behavior
??? 
No errors upon logging in.

**Comment by marlonrichert** [comment]
Can you add `setopt verbose xtrace` to the bottom of your `.zshrc` and tell me what output you get?

**Comment by marlonrichert** [comment]
Also, can you please fill out all the `???`s in the bug template? They’re not there for nothing. In particular, did you test without any config?

**Comment by dukman83** [comment]
My apologies, I checked my .zshrc file and it had exactly 5 additional source lines.
...scripting and automation error on my behalf!
Not an issue with the plugin.
Thanks again!

**Comment by dukman83** [comment]
> Also, can you please fill out all the `???`s in the bug template? They’re not there for nothing. In particular, did you test without any config?

I left that out because I wasn't entirely sure what you meant by that. Thanks for the help.
