### ISSUE TITLE
Errors on every autocompletion

### ISSUE THREAD

**Issue by Iron-E** [marlonrichert/zsh-autocomplete#139]
## Environment
* `zsh-autocomplete` version: a3f9709579639887ffef162d6476df6af33f8d30
* Zsh version: zsh-5.8-0-g77d203f
* Framework: Oh My Zsh
* Plugin manager: none
* `~/.zshrc` file: [here](https://gitlab.com/Iron_E/dotfiles/-/tree/master/.zshrc)

Please test if the bug occurs without config files:
```zsh
cd $(mktemp -d)  # Create a temp dir and enter it.
ZDOTDIR=$PWD HOME=$PWD zsh -f  # Start a subshell in it without config files.
source /home/iron-e/.oh-my-zsh/oh-my-zsh.sh
source /home/iron-e/Repos/zsh-autocomplete/zsh-autocomplete.plugin.zsh
```
Does the bug occur without config files?

* Yes

## Steps to reproduce

1. `cd $(mktemp -d)`
2. `ZDOTDIR=$PWD HOME=$PWD zsh -f`
3. `source /home/<username>/.oh-my-zsh/oh-my-zsh.sh`
4. `source /home/<username>/<path to>/zsh-autocomplete/zsh-autocomplete.plugin.zsh`

### Actual behavior

Whenever trying to autcomplete anything, a sizeable list of errors appears. For example, this is what I get when hitting `<Tab>` after typing `git`:

```log
.autocomplete._main_complete:135: command not found: _autocomplete.oldlist
.autocomplete._main_complete:135: command not found: _autocomplete.oldlist
_expand:1: command not found: _autocomplete.is_globintroduced a bug
.autocomplete._expand:71: command not found: _autocomplete.is_glob
_expand:1: command not found: _autocomplete.is_globing tree
_expand:1: command not found: _autocomplete.is_globy
.autocomplete._main_complete:322: command not found: _autocomplete.extras
```

This is what happens when hitting `<Tab>` after typing `cd`:

```log
.autocomplete._main_complete:135: command not found: _autocomplete.oldlist
.autocomplete._main_complete:135: command not found: _autocomplete.oldlist
.autocomplete._main_complete:135: command not found: _autocomplete.oldlist
_expand:1: command not found: _autocomplete.is_glob
.autocomplete._expand:71: command not found: _autocomplete.is_glob
_expand:1: command not found: _autocomplete.is_glob
_expand:1: command not found: _autocomplete.is_glob
_path_files:2: command not found: _autocomplete.recent_paths
.autocomplete._main_complete:322: command not found: _autocomplete.extras
```

### Expected behavior

I expected completion to occur without error.

**Comment by Iron-E** [comment]
Temporary workaround: checkout a0111e9f647bbe9b756c576684b22c70c8cc52db on this plugin.

**Comment by marlonrichert** [comment]
Should be fixed now.

**Comment by Iron-E** [comment]
Confirmed. Thanks!
