### ISSUE TITLE
Hidden files ignored by auto-suggest / leading dot ignored

### ISSUE THREAD

**Issue by Dwight-D** [marlonrichert/zsh-autocomplete#14]
Hidden files are ignored or downprioritized by auto-suggest. Typing the name of a dotfile will match that part against substrings in other filenames, but not exact matches of dotfiles.

Steps to reproduce:

    ➜ touch .test file.test
    ➜ rm .tes
    file.test
    ➜ \t
    ➜ rm file.test

Expected:

    ➜ touch .test file.test
    ➜ rm .tes
    .test file.test
    ➜ \t
    ➜ rm .test

**Comment by marlonrichert** [comment]
@Dwight-D I pushed in a fix. Please git pull and let me know if it works for you. 🙂

**Comment by marlonrichert** [comment]
Closing this issue now as the test case you provided completes successfully for me. Let me know if it doesn't for you, then I will reopen the issue.
