### ISSUE TITLE
Warning about zstyle :autocomplete:list-choices:*

### ISSUE THREAD

**Issue by aulialuthfi99** [marlonrichert/zsh-autocomplete#140]
## Environment
* `zsh-autocomplete` version: 9bf93684a4a954e9175cd268428d9c7e68b89218
* Zsh version: zsh-5.5.1-0-gfd4056f
* Framework: Oh My Zsh
* Plugin manager: none
* `~/.zshrc` file: Haven't uploaded it yet, cause it happens even without it

Please test if the bug occurs without config files:
```zsh
$ cd $(mktemp -d)  # Create a temp dir and enter it.
$ ZDOTDIR=$PWD HOME=$PWD zsh -f  # Start a subshell in it without config files.
% source path/to/zsh-autocomplete.plugin.zsh  # Source the plugin.
% # Insert here the steps you take to reproduce your bug.
```
Does the bug occur without config files?
* yes

### Actual behavior
[Can't upload to GitHub for some reason, sorry](https://i.imgur.com/Ddca1fw.png)

### Expected behavior
[Also this, sorry](https://i.imgur.com/N9haSv9.png)

**Comment by marlonrichert** [comment]
Yeah, so, do you have any `zstyle :autocomplete:list-choices:*` statements in your `~/.zshrc`? Then please remove it.
