### ISSUE TITLE
Option to not add semicolon when using space in select

### ISSUE THREAD

**Issue by muuvmuuv** [marlonrichert/zsh-autocomplete#141]
## What do you want?

So when typing a word, going into history with <kbd>Arrow Up</kbd> and the select something with <kbd>Space</kbd>, it adds a `;` at the end which prevents me from adding flags or anything like that.

## Why do you want this?

Because it prevents me from expending a history command fast.

## Who else would benefit from this?

Everyone which e.g. works with `npm` and wants to add `--help` or something at the end of a script command.

## Explain in detail how you would expect this to work
Given the following situation:

```
zstyle ':autocomplete:tab:*' add-ending no
```

When I perform the following steps:

1. 
1. ... 

Then I expect the following to happen:
* ???

![Bildschirmvideo aufnehmen 2020-12-07 um 07 49 04](https://user-images.githubusercontent.com/11534760/101318573-d9fa2f80-3860-11eb-95e6-70fcf2748a68.gif)

**Comment by marlonrichert** [comment]
No need for a setting. The `;` is now automatically removed for all input except <kbd>Ctrl</kbd><kbd>Space</kbd> and <kbd>Alt</kbd><kbd>Space</kbd>.
