### ISSUE TITLE
Tab completion for some use cases displays extra forward slashes

### ISSUE THREAD

**Issue by thepreacher** [marlonrichert/zsh-autocomplete#144]
## Environment
* `zsh-autocomplete` version: commit bac65644ab1b82c48189b5f25bf2b1379b5d1797 
* Zsh version: 5.8
* Framework: None
* Plugin manager: Znap
* `~/.zshrc` file: [zshrc](https://github.com/thepreacher/dotfiles/blob/master/znap/zshrc)

### Actual behavior
From the prompt say I try to access a `dot folder or file` in this case use *sublime text* to open a file located in `.config` so `$ subl ~/.con`

At this point I hit TAB once and then I get `$ subl ~//.con`. I hit TAB again and it now shows `$ subl ~///.con`. I've attached screen shots for further explanation.

The second pic is when I've pressed TAB first time, the next is second TAB press in that sequence.

<img width="444" alt="Screenshot 2020-12-10 at 03 30 36" src="https://user-images.githubusercontent.com/219075/101721719-883fe800-3aa0-11eb-836d-4728afbb671b.png">
<img width="444" alt="Screenshot 2020-12-10 at 03 31 06" src="https://user-images.githubusercontent.com/219075/101721721-88d87e80-3aa0-11eb-932a-c067dd3d7863.png">
<img width="444" alt="Screenshot 2020-12-10 at 03 31 15" src="https://user-images.githubusercontent.com/219075/101721723-89711500-3aa0-11eb-9360-e0d87269b4a0.png">
<img width="444" alt="Screenshot 2020-12-10 at 03 31 34" src="https://user-images.githubusercontent.com/219075/101721725-8a09ab80-3aa0-11eb-8767-dabd2af77a87.png">

**Comment by marlonrichert** [comment]
Thanks for reporting this. Fixed.
