### ISSUE TITLE
Newline is inserted during completion when oh-my-zsh is sourced

### ISSUE THREAD

**Issue by paw-lu** [marlonrichert/zsh-autocomplete#146]
## Environment
* `zsh-autocomplete` version: 395d47cd6f455 
* Zsh version: 5.7.1
* Framework: Oh My Zsh 
* Plugin manager: none 
* `~/.zshrc` file:  

```sh
# Minimal .zshrc
export ZSH="/home/me/.oh-my-zsh
plugins = (
    zsh-autocomplete
)
source $ZSH/oh-my-zsh.sh
```

Please test if the bug occurs without config files (it doesn't):
```zsh
$ cd $(mktemp -d)  # Create a temp dir and enter it.
$ ZDOTDIR=$PWD HOME=$PWD zsh -f  # Start a subshell in it without config files.
% source path/to/zsh-autocomplete.plugin.zsh  # Source the plugin.
% source $ZSH/oh-my-zsh.sh
# Bug does not occur
```
Does the bug occur without config files?
* No! 

If not, gradually add lines from your config file to the subshell until the bug appears.

Which combination of config causes the bug to appear?

```sh
# Minimal .zshrc
export ZSH="/home/me/.oh-my-zsh
plugins = (
    zsh-autocomplete
)
source $ZSH/oh-my-zsh.sh
```

## Steps to reproduce

1. Use `.zshrc` provided, clone Oh My Zsh, and start new shell
2. Start typing, the first time you type in <kbd>␣</kbd> a newline should be created

### Actual behavior

![newline](https://user-images.githubusercontent.com/30049606/102562172-5a076d00-408b-11eb-92c5-d2a7e4962708.gif)

New lines continue to be created.

### Expected behavior
No new line created.

**Comment by marlonrichert** [comment]
I cannot reproduce this. Also, 
```zsh
plugins = (
    zsh-autocomplete
)
```
is not valid syntax for declaring an array. It should be 
```zsh
plugins=(
    zsh-autocomplete
)
```

**Comment by paw-lu** [comment]
The plugins was a typo on my part! It is correct on the true `.zshrc` file. I have corrected it in the original post.

One thing I have just noticed is that once I navigate to another directory, the issue no longer occurs. So there is something about my home directory that is causing this.

**Comment by marlonrichert** [comment]
When your command line jumps like that, it means that an error message is getting printed. Unfortunately, it appears the completion menu then gets printed on top of the error message.

**Comment by marlonrichert** [comment]
Next time, can you please use [`asciinema`](https://asciinema.org) to record your screen? Gifs are annoying in that one cannot stop or rewind them in most browsers.

**Comment by paw-lu** [comment]
Revisited this to investigate, and at least on 4e5fc7736737f0d8b6a5a2aa3fbee8727b89d943 (latest as of the time of this post) this issue seems to be no longer exist.

Anyways that works for me!
Thanks (again) for the great project!
