### ISSUE TITLE
Configure delay of displaying completions

### ISSUE THREAD

**Issue by Mellbourn** [marlonrichert/zsh-autocomplete#147]
## What do you want?
I would like to be able to set a delay for showing completions. E.g. if I pause typing for at least half a second, _then_ the completions show, not immediately.

## Why do you want this?
I really like the idea of zsh-autocomplete, but in practice I find it very distracting to have completions flickering by all the time. I need them mainly when I hesitate - thinking "what is the next parameter?", that is the time I would like the completions to show up.

**Comment by marlonrichert** [comment]
Sure, that is doable. I have considered it before.

**Comment by marlonrichert** [comment]
All right, it's there. Documentation here: https://github.com/marlonrichert/zsh-autocomplete/blob/master/README.md#wait-for-a-minimum-amount-of-time
