### ISSUE TITLE
sleep: invalid option -- '0'

### ISSUE THREAD

**Issue by Mellbourn** [marlonrichert/zsh-autocomplete#148]
## Environment
* `zsh-autocomplete` version: 4e649be63 
* Zsh version: 5.3.1 
* Framework: none 
* Plugin manager: zinit 
* `~/.zshrc` file: https://github.com/Mellbourn/dotfiles/blob/master/.zshrc 

So, I guess this is related to my request of delay configuration https://github.com/marlonrichert/zsh-autocomplete/issues/147
The latest version works fine on my Macbook and Mac mini. But the above error shows up when I use the zsh-autocomplete on a Raspberry pi.

The problem does not occur if `:autocomplete:*' min-delay` is set to an integer value (e.g. `1`), it does occur if the setting is missing or is set to a decimal (e.g. `0.2` or `.2`).

About this system
```zsh
> uname -a
Linux alternative-pi-hole 4.19.66-v7+ #1253 SMP Thu Aug 15 11:49:46 BST 2019 armv7l GNU/Linux
> zsh --version
zsh 5.3.1 (arm-unknown-linux-gnueabihf)
```

Please test if the bug occurs without config files:
```zsh
$ cd $(mktemp -d)  # Create a temp dir and enter it.
$ ZDOTDIR=$PWD HOME=$PWD zsh -f  # Start a subshell in it without config files.
% source path/to/zsh-autocomplete.plugin.zsh  # Source the plugin.
% # Insert here the steps you take to reproduce your bug.
```
Does the bug occur without config files?
* yes 

## Steps to reproduce

1. just start typing at the prompt

### Actual behavior
As I start to type, an error message is printed
`sleep: invalid option -- '0'`
The completion output is also printed.
The error message is repeated for every letter I type.

### Expected behavior
Just listing the completions

**Comment by thepreacher** [comment]
I have the same issue but reported it on the wrong zsh-snap instead. See [invalid option](https://github.com/marlonrichert/zsh-snap/issues/10).

I'm a Macbook Pro 2019.

**Comment by euglevi** [comment]
I had the same issue on Ubuntu 20.04 without any plugin framework. I also confirm that only by using integer numbers I can overcome this. I tried looking if the sleep utils accept only integer, but no it does not look like it.

**Comment by marlonrichert** [comment]
Hi, all! Thanks for reporting this and apologies for the inconvenience. I know how to fix it. You can expect a patch from me soon.

**Comment by marlonrichert** [comment]
Should be fixed now.

**Comment by Mellbourn** [comment]
Confirmed, it is fixed for me in the latest version
