### ISSUE TITLE
Autocomplete keybindings overwrite custom user keybinds

### ISSUE THREAD

**Issue by Dwight-D** [marlonrichert/zsh-autocomplete#15]
Any keybindings user places in their own .zshrc (or elsewhere) will be overwritten by `_zsh_autocomplete_init`. 

This makes it difficult to unbind undesired widgets, like `magic-space` for instance.

**Comment by marlonrichert** [comment]
I added `_zsh_autocomplete_init` so that end users don’t have to worry whether they source it or `fzf` first.

I will have think how I can make it easier for you to use only the parts that you really want.

**Comment by marlonrichert** [comment]
@Dwight-D Please `git pull` to update. You should be able to more easily change the keybindings now. 🙂

**Comment by marlonrichert** [comment]
I also added [additional instructions to the Readme](https://github.com/marlonrichert/zsh-autocomplete/blob/master/README.md#configuration). Closing this issue now. If you have additional customization options, please let know.
