### ISSUE TITLE
Completion error with oh-my-zip kubectl plugin when typing inexistance file name

### ISSUE THREAD

**Issue by skonmeme** [marlonrichert/zsh-autocomplete#150]
## Steps to reproduce
1. install oh-my-zip
2. plugins=(kubectl) in .zshrc
3. try to complete inexistent file file like 'cd noWhere'

'''
cd noWhere.autocomplete._approximate:48: command not found: _bash_comp
.autocomplete._approximate:48: command not found: _bash_comp
~/cd noWhere
'''

### Actual behavior
lots of error messages

### Expected behavior
nothing change: no error message

**Comment by marlonrichert** [comment]
Sorry, but I cannot reproduce this. Here's what I did:
```zsh
$ cd $(mktemp -d); HOME=$PWD ZDOTDIR=$PWD zsh -d
% source /Users/marlon/.zsh/zsh-autocomplete/zsh-autocomplete.plugin.zsh 
% source /Users/marlon/.zsh/ohmyzsh/plugins/kubectl/kubectl.plugin.zsh 
% cd noWhere
```
No error messages.

**Comment by skonmeme** [comment]
It shows same error by below commands.
---
cd $(mktemp -d); HOME=$PWD ZDOTDIR=$PWD zsh -d
# just to avoid error "complete:13: command not found: compdef"
# autoload -Uz compinit
# compinit
OLDHOME=/Users/skon
source $OLDHOME/.oh-my-zsh/plugins/helm/helm.plugin.zsh
source $OLDHOME/.oh-my-zsh/custom/plugins/zsh-autocomplete/zsh-autocomplete.plugin.zsh
---
cd no<tab>.autocomplete._approximate:48: command not found: _bash_comp 
---

**Comment by marlonrichert** [comment]
Sorry, I cannot reproduce it with those steps either.

Also, this appears to be either a bug in Kubectl or perhaps you incorrectly configured Kubectl completion:
* https://github.com/kubernetes/kubectl/issues/125
* https://github.com/kubernetes/website/issues/19844
