### ISSUE TITLE
Modify autocomplete behaviour to work closer to the default

### ISSUE THREAD

**Issue by kheaactua** [marlonrichert/zsh-autocomplete#151]
This is more of a question,.. I like most of the features of this, except how the autocomplete works right now. 

For instance, I have two items in my directory, the executable `doupdate.sh` and the directory `dotfiles`.  When I type `ls dot<tab>` it autocompletes to `ls doupdate.sh` (it ignores the `t` and chooses the first executable, rather than the best match.  Sort of how powershell autocompletion works.)

I've played with the zstyle settings in the readme to no avail.  How do I get it to not discard what I've entered (the `t` in this example) and instead complete to the best match?

I've had to shut this plugin off because of this :(

Thanks

## Who else would benefit from this?
Everyone I imagine..

**Comment by ChocolateOverflow** [comment]
Additionally, it I have 2 directories `git` and `.cargo` and I type `g<TAB>`, it should give me `git` *before* `.cargo`. Having used bash completion with this alphabetic listing, it's annoying to get `.cargo` when I'm trying to type out & finish `git` by starting with a `g`.

**Comment by skonmeme** [comment]
In history menu, it shows unacceptable ordered list.
For example, it suppose I typed 'ls a', 'ls c', and then 'ls b'. In bash, when I pressed up arrow button, it shows 'ls b' first.
But, In history menu of autocomplete, a selection row is located in 'ls a' firstly. 
It is quite confusing me.

**Comment by marlonrichert** [comment]
Sorry, it appears there were some bugs in the matching logic. They should be fixed now. Please try again.

**Comment by Mallchad** [comment]
I believe this actually solves a little niggle I've dealt with for months.
This latest update works amazingly : D

**Comment by marlonrichert** [comment]
@kheaactua @ChocolateOverflow @skonmeme @nisegami Does it work for you, too?

**Comment by kheaactua** [comment]
It works!  Thanks!
