### ISSUE TITLE
The order of the file suggestions is weird

### ISSUE THREAD

**Issue by maarekj** [marlonrichert/zsh-autocomplete#152]
## Environment
* `zsh-autocomplete` version: d23lic618df15b26bc0a783a2b754de5ab66d700974
* Zsh version: ubuntu/5.8-3ubuntu1
* Framework: none
* Plugin manager: none
* `~/.zshrc` file: none

Does the bug occur without config files?
* Yes

## Steps to reproduce
```zsh
$ cd $(mktemp -d)  # Create a temp dir and enter it.
$ ZDOTDIR=$PWD HOME=$PWD zsh -f  # Start a subshell in it without config files.
% source path/to/zsh-autocomplete.plugin.zsh  # Source the plugin.
% cd /home/maarek/Documents/projects/myproject
% cd pub
local directory
psalm-stubs/  public/ 
```
1. I move to a directory  that contains 2 directories named `public` and `psalm-stubs`.
2. I type `pub` and I wait suggestions.

### Actual behavior
The suggestions for suggested local directories are (in order) `psalm-stubs/` and `public/`.

### Expected behavior
The suggestions should be in order `public/` and `psalm-stubs/`.

![Capture d’écran de 2020-12-23 10-15-54](https://user-images.githubusercontent.com/1654977/102981459-433c9c80-4509-11eb-9004-3ab4b6902f85.png)

**Comment by marlonrichert** [comment]
Sorry, it appears there were some bugs in the matching logic. They should be fixed now. Please try again.

**Comment by maarekj** [comment]
Magnifique !!
Thank you very much.

It is work perfectly.
