### ISSUE TITLE
Smart case completion suggestion

### ISSUE THREAD

**Issue by ChocolateOverflow** [marlonrichert/zsh-autocomplete#153]
## What do you want?

I'd like "smart case" completion similar to vim's "smart case" search.

## Why do you want this?

I sometimes *explicitly* type a character in UPPERCASE because the file/directory I want has the uppercase letter in the name. However,  the autocompletion currently ignores the uppercase-ness and the thing I'm looking for comes up way further down the completion queue.

## Who else would benefit from this?

Anyone who works with file names with uppercase letters.

## Explain in detail how you would expect this to work

Given the following situation:

I have many files `m1`, `m2`, `m3`, `Makefile`, `meme.png`, and I want to run `nvim Makefile`.

When I perform the following steps:

1. type `nvim M`
2. <TAB>

Then I expect the following to happen:

`Makefile` comes **first** in the suggestion queue since it matches best with the provided `M`.

Additionally, as this is "smart case" and not "case sensitive", typing a lowercase `m` should have no difference from the current behaviour. This additional feature is expected to prioritize file names with the uppercase letter only when the user has typed an uppercase character.

**Comment by marlonrichert** [comment]
All right, it's there.
