### ISSUE TITLE
autocomplete.async.timeout.fd-widget:5: 23: bad file descriptor

### ISSUE THREAD

**Issue by euglevi** [marlonrichert/zsh-autocomplete#156]
## Environment
* `zsh-autocomplete` last version and it did not happen until the update of a few days ago
* Zsh version: 5.8
* Framework: none
* Plugin manager: none

Which combination of config causes the bug to appear?
Adding zsh-autosuggestions

## Steps to reproduce
1. Typing cd and then a folder
2. Erasing what has just been typed

### Actual behavior
I get the following error message: `.autocomplete.async.timeout.fd-widget:5: 23: descrittore di file errato` ("descrittore di file errato" means "bad file descriptor"). Moreover, the terminal moves to another line every two words erased.

**Comment by marlonrichert** [comment]
I cannot reproduce this. Here's what I did:
```zsh
> cd $(mktemp -d); HOME=$PWD ZDOTDIR=$PWD zsh
% source /Users/marlon/.zsh/zsh-autocomplete/zsh-autocomplete.plugin.zsh; source /Users/marlon/.zsh/zsh-autosuggestions/zsh-autosuggestions.plugin.zsh
% mkdir foo
% cd foo
% cd ..
% cd f
```
Works fine for me.

**Comment by skonmeme** [comment]
I have same error messages without different number like 23, 28, or 25.
And after I exclude "helm" and "kubectl" plugins, these error messages do not show again.

**Comment by marlonrichert** [comment]
@skonmeme [As I pointed out on #150](https://github.com/marlonrichert/zsh-autocomplete/issues/150#issuecomment-752261004), your case appears to be either a bug in Kubectl or you have not set up Kubectl completion correctly.
