### ISSUE TITLE
Partial completion as first choice

### ISSUE THREAD

**Issue by ChocolateOverflow** [marlonrichert/zsh-autocomplete#160]
When in bash, if I have 2 choices with similar starting sub-strings, a partial completion up to the difference is given by default. For example, in my directory I have `file123` and `file456`, and I type `f<TAB>`, bash would give me `file` and I can clarify the file I want by further typing out the names/options with the different strings, e.g. `f<TAB>1<TAB>` would give me `file` and then `file123`.

It's nice that zsh offers me to scroll through options till I get my intended string, but I prefer doing partial completions like with bash. Scrolling  through the options is a pain in cases where I have a lot of files with similar like `file001`, `file002`, ..., `file999`, sometimes with gaps in between (no `file234`), making scrolling through the options a pain (and I prefer not having to use the arrow keys).

In a directory with 3 files `file123`, `file456`, `file123456`, I'd like the following behavior:

```
$cmd f<TAB> -> file
# Since all files start with `file`, the `f` would be unnecessary as a <TAB> with nothing typed should offer `file` anyway.

$cmd file<TAB>
file   file123   file456   file789
# `file` is highlighted as the first choice

$cmd file1<TAB> -> file123
file123   file123456
# Insert up to the difference
```

The whole action of getting to `file123456` would be `cmd f<TAB>1<TAB>4<TAB>` which is much easier than scrolling through the options, especially if I already have a good  idea of what is in my directory (as I usually do).

**Comment by jedahan** [comment]
Thank you for articulating exactly why I disabled zsh-autocomplete for now, I had a hard time putting it to words.

**Comment by marlonrichert** [comment]
@ChocolateOverflow @jedahan That's already built in. As mentioned [in the Readme, under "Change <kbd>Tab</kbd> behavior](https://github.com/marlonrichert/zsh-autocomplete#change-tab-behavior), you can enable it with
```zsh
zstyle ':autocomplete:tab:*' insert-unambiguous yes
```

Note, though, that since commit 2a838cb6ef05c9912569cf9f899087f02ecf0c87, _without_ the above setting enabled, you can simply type `cmd f14`<kbd>Tab</kbd> for the case you describe.

**Comment by ChocolateOverflow** [comment]
If anyone still doesn't get the partial completion after adding `zstyle ':autocomplete:tab:*' insert-unambiguous yes`, it might be due to `zstyle ':autocomplete:tab:*' fzf-completion yes` which you'd need to remove for partial completion to work. I happened to add `fzf-completion` because I like fzf without really knowing what it does exactly, which might also be the case for others.

**Comment by marlonrichert** [comment]
@ChocolateOverflow I just tested with both `insert-unambiguous` and `fzf-completion` enabled at the same time and it works fine for me. Here's what I did:
```zsh
> cd "$(mktemp -d)"  # Go to a new temp dir
> ZDOTDIR=$PWD HOME=$PWD zsh -f  # Start a sub shell without dotfiles.
% /usr/local/opt/fzf/install  # Install Fzf's shell extensions.
Downloading bin/fzf ...
  - Already exists
  - Checking fzf executable ... 0.24.3
Do you want to enable fuzzy auto-completion? ([y]/n) y
[...]
% source ~/.fzf.zsh  # Source the file that it generates.
% zstyle ':autocomplete:tab:*' insert-unambiguous yes
% zstyle ':autocomplete:tab:*' fzf-completion yes
% source /Users/marlon/.zsh/zsh-autocomplete/zsh-autocomplete.plugin.zsh
```
Perhaps you have not installed/sourced Fzf's completion code?

**Comment by marlonrichert** [comment]
@ChocolateOverflow Wherever you have installed Fzf, there should be an [`install` script](https://github.com/junegunn/fzf/blob/master/install).

**Comment by ChocolateOverflow** [comment]
It works after sourcing [completion.zsh](https://github.com/junegunn/fzf/blob/master/shell/completion.zsh)
