### ISSUE TITLE
Feature Request: Searching an Enviornment Variable shows its value

### ISSUE THREAD

**Issue by ksparakis** [marlonrichert/zsh-autocomplete#161]
## What do you want?
I think a really cool time-saving feature would be that as you type the name of an environment variable it lists it, with its value slightly grayed out next to it. 

## Why do you want this?
I work in an environment where we heavily rely on environment variables, and it can be annoying to have to use printenv and having to pipe into that and search or even using echo. I think having a quick autocomplete which shows me an environment variables value and choosing to autocomplete the value vs just the name of the variable, would save me time and add to my efficiency.

## Who else would benefit from this?
Any user that uses environment variables often and sometimes needs to double-check or need to modify could use this functionality to help improve their efficiency.

## Explain in detail how you would expect this to work

* User has the option to turn this feature on/off in the zshrc

* As I type something that matches an environment variable, it shows me the environment variable via auto-complete with its value slightly grayed out next to it. 
<img width="889" alt="Screen Shot 2021-01-05 at 11 07 09 AM" src="https://user-images.githubusercontent.com/4424951/103671457-edc0b080-4f48-11eb-8c24-57b2e83a2c0b.png">

* If I click the down arrow to navigate onto the variable and then click shift+enter (or some shortcut) it auto-fills in the command I'm writing with the value of the environment variable instead of its name.

* If I type env, the autocomplete displays all env variables in a way where I can quickly scroll through the expanded list with space+ctrl each one displaying its value next to it.

* Some environment variables have values that are really long, wrapping that text might not be the best option? maybe as you hover above an env variable the value starts to scroll to the left showing hidden characters as an led text display would?

**Comment by marlonrichert** [comment]
Most of this is already supported:
* Type `$` followed by a parameter's full name to see its value.
* Press <kbd>Tab</kbd> on any parameter to insert its value.

So, for your example:
 1. Type `$GOSU`.
    * Autocomplete displays `GOSUMDB`.
 1. Press <kbd>Tab</kbd>.
    * `$GOSU` gets completed to `$GOSUMDB`.
    * Autocomplete displays `/User/Path/.go/`.
 1. Press <kbd>Tab</kbd> again.
    * `$GOSUMDB` get expanded to `/User/Path/.go/`.

Please try this out for a while and then let me know whether you still badly need the other features. 🙂

**Comment by marlonrichert** [comment]
Oh, and if you add
```zsh
setopt autocd cdablevars
```
to your `.zshrc`, then this enables the following:

 1. Type `GOSU`.
    * Autocomplete displays GOSUMDB.
 1. Press <kbd>Tab</kbd>.
    * `GOSU` gets completed to `GOSUMDB`.
 1. Press <kbd>Enter</kbd>.
    * You auto-`cd` to `/User/Path/.go/`.

**Comment by ksparakis** [comment]
@marlonrichert  Thank you for the detailed response! Loving the autocomplete honestly absolute gamechanger. Already have a lot of my colleagues at work using it as well :) Thank you for all the hard work!

I still do think having the values listed next to the parameter could be very useful as well as perhaps an env variable search like that of the history, where it lists everything out and you can see values.

I went ahead and added that to my zshrc, I however get expansions off, is there any way to enable them? 
![Screen Shot 2021-01-07 at 4 51 13 PM](https://user-images.githubusercontent.com/4424951/103949068-c31d5600-5108-11eb-8905-87e78ad8833d.png)

**Comment by marlonrichert** [comment]
`zsh-autocomplete` does nothing to disable them. Can you please try the following?
```zsh
> cd "$(mktemp -d)"  # Go to a new temp dir
> # Start a subshell without config files.
> ZDOTDIR=$PWD HOME=$PWD PS1='%~:%?> ' PS4='+%e %N:%I %?> %_ ' zsh -f 
% source /Users/marlon/.zsh/zsh-autocomplete/zsh-autocomplete.plugin.zsh
% $PWD
```
If you get the expansions this way, without any dotfiles, then that means there's something in your dotfiles that's turning off expansions.

**Comment by marlonrichert** [comment]
@ksparakis All right, it's there now. Please try it out.
