### ISSUE TITLE
Option to start in "Live History Search" mode by default.

### ISSUE THREAD

**Issue by tekhnee** [marlonrichert/zsh-autocomplete#162]
## What do you want?

Please consider adding an option for defaulting to "Live History Search", rather than the "Completions Menu," at the command prompt.

## Why do you want this?

Typically relying on the command history for autocompletion; having to press `Cmd-S` or `Cmd-R` almost every time to switch from Completions to Live History is counterproductive.

## Who else would benefit from this?

Administrators, code builders, and generally users with a narrow repertoire of highly repetitive commands.

## Explain in detail how you would expect this to work

1. User is at prompt with ZSH ready to accept a command line.
2. User begins to type. `zsh-autocomplete` presents suggestions based on most recent (or least recent) history.
3. (In the rare case that the the completions menu is needed, pressing `Cmd-R` or `Cmd-S` would still reveal it, in accordance with the current behavior of the plugin.)

**Comment by marlonrichert** [comment]
@tekhnee @up-to-you It's there now. Please see [this section of the Readme](https://github.com/marlonrichert/zsh-autocomplete/blob/master/README.md#start-autocompletion-in-history-search-mode).

**Comment by tekhnee** [comment]
@marlonrichert thank you for kindly taking this up — and for one of the most extraordinary zsh plugins around.

Unfortunately I cannot get this to work, even though the relevant line `zstyle ':autocomplete:*' default-context history-incremental-search-backward` is ran from `.zshrc`, as I understand it should.

**Comment by up-to-you** [comment]
It's awesome ! And works, but with some glitches. For example: if i type `cd` and then choosing common command like `cd the_most_frequently_used_dir` it ends with `cd cd the_most_frequently_used_dir`

**Comment by marlonrichert** [comment]
@up-to-you No, it’s not supposed to work that way. That’s definitely a bug. I’ll look into it.

@tekhnee It should be possible to do even outside your `.zshrc`.

**Comment by marlonrichert** [comment]
@tekhnee Can you please try the following?
```zsh
$ cd $(mktemp -d)  # Create a temp dir and enter it.
$ ZDOTDIR=$PWD HOME=$PWD zsh -f  # Start a subshell in it without config files.
% source path/to/zsh-autocomplete.plugin.zsh  # Source the plugin.
% zstyle ':autocomplete:*' default-context history-incremental-search-backward
```
Does it work then for you?

**Comment by tekhnee** [comment]
@marlonrichert thank you for looking into this.

I ran these four commands with no errors, but unfortunately they didn't help. The plugin still displays the Completions Menu by default.

**Comment by tekhnee** [comment]
@marlonrichert UPDATE: It seems to be working now (and as far as I can tell, there was no update to the plugin meanwhile).

Puzzling… I wonder if some sort of caching is at work due to zplug(?)

Marking this closed for now. Sorry for the (probably) false alarm.

**Comment by marlonrichert** [comment]
@tekhnee Zplug hasn't really seen [any updates in the past two years](https://github.com/zplug/zplug/graphs/code-frequency). If you're interested in trying a different plugin manager, that's actively maintained and won't change the behavior of any plugins, give [Znap](https://github.com/marlonrichert/zsh-snap) a try. 🙂

**Comment by tekhnee** [comment]
Done :)
