### ISSUE TITLE
Prioritizing name not working after first directory

### ISSUE THREAD

**Issue by ChocolateOverflow** [marlonrichert/zsh-autocomplete#164]
## Environment
* `zsh-autocomplete` version: 1f59fc6ec81a589dd744800fc5d92d371da5fc09
* Zsh version: zsh-5.8-0-g77d203f
* Framework: none
* Plugin manager: none
* `~/.zshrc` file: https://github.com/ChocolateOverflow/dotfiles_arch/blob/main/home/.zshrc

Does the bug occur without config files?
* Yes

```tree
.
└── sync
    ├── music
    └── stuff
```

In the current directory, after typing `cd sync/s<TAB>`, I expect `stuff` to come up *before* `music` since `stuff` starts with `s` which is the letter I've typed out, and should therefore be prioritized in the suggestion queue. However, in this case, `music` comes before `stuff` in the suggestion queue.

This problem does *not* happen when I'm in `sync` and type `s<TAB>`, and only happens when the names to be completed are not in the current directory. Basically, anything after the 1st `/` fails to prioritize the file name with the provided first character.

**Comment by marlonrichert** [comment]
Should be fixed now.
