### ISSUE TITLE
Tab key inserts top result of completion menu even when the history menu is visible.

### ISSUE THREAD

**Issue by tekhnee** [marlonrichert/zsh-autocomplete#167]
Pressing <kbd>tab</kbd> in *history* mode, and with `fzf` autocompletion enabled, inserts the first result of the *completions* menu when the insertion is a filename or directory.

The issue is not manifest when the insertion is a command option.

## Environment

* `zsh-autocomplete` version: `d728cf566bd0aba01b0a3937c781bbcb055b1bd0`

* Zsh version: `zsh-5.8-0-g77d203f`

* Framework: None

* Plugin manager: `znap` 

* `~/.zshrc` file: [Available here](https://cl1p.net/zshrcdebug) 

Please test if the bug occurs without config files:
```zsh
$ cd $(mktemp -d)  # Create a temp dir and enter it.
$ ZDOTDIR=$PWD HOME=$PWD zsh -f  # Start a subshell in it without config files.
% source path/to/zsh-autocomplete.plugin.zsh  # Source the plugin.
% # Insert here the steps you take to reproduce your bug.
```
Does the bug occur without config files?
* Unable to tell because the <kbd>Ctrl</kbd>-<kbd>R</kbd> and <kbd>Ctrl</kbd>-<kbd>R</kbd> bindings are unavailable in this temporary shell.

* The issue goes away if `completion.zsh` is not sourced by the `.fzf.zsh` loader.
* (It is unaffected by the bollean value of `zstyle ':autocomplete:tab:*' fzf-completion`.)

Which combination of config causes the bug to appear?
* Enabling fuzzy autocompletion during `fzf` setup.

## Steps to reproduce

1. Enable fuzzy autocompletion by selecting the appropriate option when `fzf` is set up (`./opt/fzf/install`).
2. Enable the fuzzy finder (`source ~/.frf.zsh`).
3. Enter a command that accepts a file or directory as argument (e.g. `ls`) and matches one or more lines of the history.
4. Press <key>Ctrl</key>-<key>R</key> to activate the history menu.
5. Press <key>tab</key>.

### Actual behavior

Although the history menu is active, pressing <key>tab</key> inserts the first result of the completions menu.

### Expected behavior

I would expect the top result of the history menu to be inserted instead.

**Comment by marlonrichert** [comment]
Should be fixed now.
