### ISSUE TITLE
Bad file descriptor when plugin is used with zsh-autosuggestions

### ISSUE THREAD

**Issue by tekhnee** [marlonrichert/zsh-autocomplete#170]
* `zsh-autocomplete` version: 
* 4e5fc7736737f0d8b6a5a2aa3fbee8727b89d943
* Zsh version: 
* zsh-5.8-0-g77d203f
* Framework: 
* none
* Plugin manager: 
* Znap

#### Reproducing

```zsh
$ cd $(mktemp -d)  # Create a temp dir and enter it.
$ ZDOTDIR=$PWD HOME=$PWD zsh -f  # Start a subshell in it without config files.

Create a `.zshrc` file with the following three lines alone:

source /Absolute/path/to/zsh-autocomplete.plugin.zsh
source /Absolute/path/to/zsh-users/zsh-autosuggestions/zsh-autosuggestions.plugin.zsh
ZSH_AUTOSUGGEST_STRATEGY=(history completion)
```
then
```
$ exit
$ zsh -f
$ source .zshrc
$ <make some command history>
```
ERROR:

`.autocomplete.async.timeout.fd-widget:4: 14: bad file descriptor`

I believe the `completion` option in the `ZSH_AUTOSUGGEST_STRATEGY` array makes `zsh-autocomplete` susceptible to this error.

**Comment by marlonrichert** [comment]
@tekhnee Should be fixed now.
