### ISSUE TITLE
ITerm and Terminal not usable anymore after commit 0dc77fa4109799f9d0e768e7c878eefdbef7c179

### ISSUE THREAD

**Issue by thepreacher** [marlonrichert/zsh-autocomplete#174]
Both terminals iTerm and Terminal app have become unusable since commit 0dc77fa4109799f9d0e768e7c878eefdbef7c179

For iTerm any command I type even `znap pull` closes the app/window. And for the Terminal app, the command does nothing and then when I press `Enter` again, it displays the message `[Process competed]`.

As it stands I'm not even able to downgrade since every command crashes the terminals.

Like I said every command crashes the terminal so I can't provide any debug info.

I posted this earlier on the wrong repo [here](https://github.com/marlonrichert/zsh-snap/issues/24)

**Comment by marlonrichert** [comment]
@thepreacher I'm using Terminal.app myself and it works fine. Can you please try the following  a couple of times and paste here the lines where it crashes?
```zsh
PS4='%? %e %N %x %I %_ ' exec zsh -vx
```

**Comment by thepreacher** [comment]
I'm very sorry to have to do this to you man, but the output was like 6800 lines and I've got no clue what I'm supposed to be looking for so I'm linking to the file [here](https://gist.github.com/thepreacher/f6cf0d575b30c8668ab0566a68b3e895)

**Comment by marlonrichert** [comment]
@thepreacher No problem! 🙂 I need only the last couple of lines from the output. Can you repeat this a couple of times and paste the last couple of lines from each crash? And with "crash", I mean the point where `[Process competed]` appears.

**Comment by thepreacher** [comment]
Alright so I now think it may actually be `powerlevel10k` causing the issue. So with the code you provided at the end of my `.zshrc` plus with `znap source zsh-autocomplete` uncommented, I get a whole bunch of text on the screen, then when I type a command like `cd projects`, I get some more text scroll up the terminal screen. I copied all the text to an editor and tried to find `[Process completed]` but I couldn't.

In my previous attempt at tracking down the cause, I deleted all the plugins then installed `zsh-snap`, followed by `powerlevel10k`. Then I tested with some commands and everything was fine.  I after installed `zsh-autocomplete` and tested again, then the issue came up so I concluded it was `zsh-autocomplete`.

But you just said you use Terminal and don't have any issues so I commented out `znap source powerlevel10k` and `[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh` and the issue is gone. But with `powerlevel10k` sourced I get this:

<img width="819" alt="Screenshot 2021-01-25 at 11 08 00" src="https://user-images.githubusercontent.com/219075/105699783-cf265780-5eff-11eb-9520-31fb4351dc71.png">


I therefore think it's a `powerlevel10k` issue. It's a shame since I quite like the prompt it allows me to have 😞

**Comment by thepreacher** [comment]
While on the issue what is the best way to setup the `pure` prompt with znap? I ask because I have checked out your `.zshrc` and you appear to use `pure` like this `znap prompt pure`. 

However in your `znap-repos` list you only have `git@github.com:sindresorhus/pure.git`. What about `git@github.com:mafredri/zsh-async.git` which appears to be a requirement according to the docs for `pure`?

**Comment by marlonrichert** [comment]
`zsh-async` is included in `pure`. So, just `znap prompt sindresorhus/pure` will suffice.

**Comment by marlonrichert** [comment]
@thepreacher Can you try adding this to the end of your `.zshrc`:
```zsh
.autocomplete.async.clear() {
  zle -M ''
  .autocomplete.async.stop
  .autocomplete.async.reset-context
  return 0
}
```
Does that fix the problem?

**Comment by thepreacher** [comment]
> @thepreacher Can you try adding this to the end of your `.zshrc`:
> 
> ```shell
> .autocomplete.async.clear() {
>   zle -M ''
>   .autocomplete.async.stop
>   .autocomplete.async.reset-context
>   return 0
> }
> ```
> 
> Does that fix the problem?

No it doesn't make any difference.

I just commented out all `powerlevel10` codes and replaced it with `znap prompt sindresorhus/pure` which is working fine except when I start the terminal the first time I get this extra tilde. I'll have to look into why.

<img width="630" alt="Screenshot 2021-01-25 at 14 08 08" src="https://user-images.githubusercontent.com/219075/105717184-bc1f8180-5f17-11eb-980d-bfacaa520950.png">

**Comment by marlonrichert** [comment]
That probably means there's an error message, but the prompt gets printed on top of it. I should try to add a better way of dealing with error message in `znap prompt`.

**Comment by marlonrichert** [comment]
@thepreacher Can you still try this, though, a couple of times and show me the last couple of lines that get printed? I would like to know what exactly is the problem.
```zsh
PS4='%? %e %N %x %I %_ '
setopt verbose xtrace
```

**Comment by thepreacher** [comment]
@marlonrichert Ok so when I start Terminalm this the top few lines of code I see. This is the first time the prompt shows up:

<img width="1076" alt="Screenshot 2021-01-26 at 07 32 13" src="https://user-images.githubusercontent.com/219075/105814871-f2a5dc80-5fa9-11eb-9bdf-3e2c61f457c5.png">


Then after *69000* odd lines of code I see the prompt again like this:

<img width="1087" alt="Screenshot 2021-01-26 at 07 39 02" src="https://user-images.githubusercontent.com/219075/105815196-79f35000-5faa-11eb-81c0-34516774f2fe.png">

After that it's just a repeat of the following set of code about over 20 odd times
<img width="1087" alt="Screenshot 2021-01-26 at 07 39 29" src="https://user-images.githubusercontent.com/219075/105815408-c2ab0900-5faa-11eb-8aec-bb4006f2ed5a.png">

Thanks.

**Comment by thepreacher** [comment]
Also I noticed that you committed to `zsh-autocomplete` and `zsh-snap` few hours ago so I pulled the changes in and tried my original `powerlevel10k` prompt again. This time `Terminal` and `iTerm` don't crash however after the first time that the prompt shows up you don't see it again. Below should help explain:

Just after starting terminal:

<img width="692" alt="Screenshot 2021-01-26 at 08 00 22" src="https://user-images.githubusercontent.com/219075/105816863-bc1d9100-5fac-11eb-9cc3-85f30c8c2398.png">


Now typing a command `ls` autocomplete kicks in as expected:

<img width="692" alt="Screenshot 2021-01-26 at 08 00 47" src="https://user-images.githubusercontent.com/219075/105816927-d5264200-5fac-11eb-8681-d75d5dc1792a.png">


After hitting `Enter` I have this, you'll notice that the prompt is missing:

<img width="692" alt="Screenshot 2021-01-26 at 08 01 00" src="https://user-images.githubusercontent.com/219075/105817035-fc7d0f00-5fac-11eb-904f-cfaaa53a831e.png">

Trying to type `ls` again and still no prompt but autocomplete works fine:

<img width="692" alt="Screenshot 2021-01-26 at 08 01 21" src="https://user-images.githubusercontent.com/219075/105817134-1e769180-5fad-11eb-8b5a-614481710619.png">

**Comment by marlonrichert** [comment]
@thepreacher I need _the **last lines** just before you get a crash or_ `[Process complete]`. Also, I need you to do this several times, to make sure that the problem happens at the same point each time.

**Comment by thepreacher** [comment]
After `znap pull` this morning `commit 431f3e3220562f1a261278e4af62fac47ae55e21` for `zsh-autocomplete`, I don't get the '[Process completed]` anymore. Terminal isn't crashing anymore. It works fine except the issue now is as described in my [comment](https://github.com/marlonrichert/zsh-autocomplete/issues/174#issuecomment-767373640)

**Comment by marlonrichert** [comment]
That should be fixed by 431f3e3. Please update again.

**Comment by marlonrichert** [comment]
@thepreacher Is this the same problem as issue #175?

**Comment by thepreacher** [comment]
@marlonrichert after submitting my last comment I noticed that you undid the commit that fixed the crashing of Terminal for me. With some trepidation, I decided to `znap pull` which I was expecting will undo the crashing fix bringing me to square one but to my supprise, the latest commit has fixed all the issues I have been having. 

I'm now using `powerlevel10k` and no more crashing and no more disappering prompt. As far as I'm concerned all my issues are fixed. Please whatever you do don't touch the code ever gain 😄

**Comment by thepreacher** [comment]
If it's okay with you I'll close this issue.

**Comment by marlonrichert** [comment]
@thepreacher I think you might have some caching issues somewhere. Next time, before you file an issue, try removing `${XDG_CACHE_HOME:-$HOME/.cache}/zcompdump` and run `znap clean` inside both plugins.

**Comment by thepreacher** [comment]
@marlonrichert got you. Will do thanks.
