### ISSUE TITLE
The prompt disappear 

### ISSUE THREAD

**Issue by euglevi** [marlonrichert/zsh-autocomplete#175]
* `zsh-autocomplete` version:  431f3e3220562f1a261278e4af62fac47ae55e21
* Zsh version:  ubuntu/5.8-3ubuntu1
* Framework:  none
* Plugin manager:  Zinit

```
$ cd $(mktemp -d)  # Create a temp dir and enter it.
$ ZDOTDIR=$PWD HOME=$PWD zsh -f  # Start a subshell in it without config files.
% source path/to/zsh-autocomplete.plugin.zsh  # Source the plugin.
% source path/to/powerlevel10k.zsh-theme
```

After the last update, even in the minimal test case whenever I source the powerlevel10k theme after sourcing zsh-autocomplete I get an empty left side of the prompt. The problem persists even as I press "enter" to go to a new line. Moreover, even by reverting the order of the sourcing, the problem stays: as soon as I source zsh-autocomplete, the prompt disappears.

The problem does not seem to be specific to powelevel10k: it happens also with Starship.

**Comment by marlonrichert** [comment]
I reverted the last commit. This fixes the here, but again leaves #173 unresolved.
