### ISSUE TITLE
Fzf's ALT-C leaves unknown sequence of characters after selection

### ISSUE THREAD

**Issue by sakakibara** [marlonrichert/zsh-autocomplete#180]
* `zsh-autocomplete` version: e561e0c651956ea37bb66c1a9cb276872ae5fd2a
* Zsh version: zsh-5.8-0-g77d203f
* Framework: none
* Plugin manager: Zinit

```zsh
$ cd $(mktemp -d)  # Create a temp dir and enter it.
$ ZDOTDIR=$PWD HOME=$PWD zsh -f # Start a subshell in it without config files.
% git clone https://github.com/marlonrichert/zsh-autocomplete.git # Clone this plugin to $HOME
% git clone https://github.com/junegunn/fzf.git # Clone fzf repository to $HOME
% $HOME/fzf/install # Answer yes to all installation prompts
% bindkey -e # Set emacs keymap
% source $HOME/zsh-autocomplete/zsh-autocomplete.plugin.zsh # Source this plugin
% source $HOME/.zshrc # Source .zshrc created by fzf/install
press ALT-C to invoke fzf's fuzzy directory selection for cd
press Enter on any directory
```

Following the steps above results in a prompt with unknown sequence of characters like below.
```zsh
% 5;1R
```

Although cd did happen as running `pwd` showed the path selected within fzf directory selection.

This does not happen if I don't use `bindkey -e`.

Above reproduction steps were tested on macOS, but I had the same problem with WSL Debian with my own zsh config which also has the combination of `bindkey -e`, zsh-autocomplete and fzf.

**Comment by marlonrichert** [comment]
@sakakibara This is a bug in Fzf's code. I submitted a patch: https://github.com/junegunn/fzf/pull/2340

**Comment by sakakibara** [comment]
@marlonrichert 
Sorry I thought the culprit was in zsh-autocomplete since I could only reproduce the issue with this plugin.

Thanks for the swift fix on this!
I have updated fzf and it's key bindings script and confirmed the patch fixes the issue.
