### ISSUE TITLE
Command not found when use tab while using cd command

### ISSUE THREAD

**Issue by dmknght** [marlonrichert/zsh-autocomplete#181]
* `zsh-autocomplete` version: 2021-02-03
* Zsh version: debian/5.8-5+b1
* Framework: No framework or plugin manager

zshrc
```
# Prompt
PROMPT="%F{red}┌[%f%F{cyan}%m%f%F{red}]─[%f%F{yellow}%D{%H:%M-%d/%m}%f%F{red}]─[%f%F{magenta}%d%f%F{red}]%f"$'\n'"%F{red}└╼%f%F{green}$USER%f%F{yellow}$%f"
# Export PATH$
export PATH=~/.local/bin:/snap/bin:/usr/sandbox/:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/usr/share/games:/usr/local/sbin:/usr/sbin:/sbin:$PATH

# alias
alias ls='ls -lh --color=auto'
alias dir='dir --color=auto'
alias vdir='vdir --color=auto'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias python='python3'
#####################################################
# Auto completion / suggestion
# Mixing zsh-autocomplete and zsh-autosuggestions
# Requires: zsh-autocomplete (custom packaging by Parrot Team)
# Jobs: suggest files / foldername / histsory bellow the prompt
# Requires: zsh-autosuggestions (packaging by Debian Team)
# Jobs: Fish-like suggestion for command history
source /usr/share/zsh-autosuggestions/zsh-autosuggestions.zsh
source /usr/share/zsh-autocomplete/zsh-autocomplete.plugin.zsh
# Select all suggestion instead of top on result only
zstyle ':autocomplete:tab:*' insert-unambiguous yes
zstyle ':autocomplete:tab:*' widget-style menu-select
#zstyle ':autocomplete:*' max-lines 100%
#zstyle ':completion:*' list-rows-first yes
#zstyle ':completion:*' group-name ''
zstyle ':autocomplete:*' min-input 2
# Set a bash-like history
bindkey $key[Up] up-line-or-history
bindkey $key[Down] down-line-or-history

##################################################
# Fish like syntax highlighting
# Requires "zsh-syntax-highlighting" from apt
source /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# Save type history for completion and easier life
HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
setopt appendhistory
```
Steps:
1. Clone a project from git (mkdir should be the same)
2. Use tab for completion name
3. Error appears
```
cd fara_path_files:6: command not found: _autocomplete.ancestor_dirs
adayday_plcd faraday_path_files:6: command not found: _autocomplete.ancestor_dirsocal directory
```

![image](https://user-images.githubusercontent.com/29118926/106859229-a26dff00-66ba-11eb-8662-92428060df51.png)

Likely zsh confused the new folder name which contains `-` vs different folder name which has `_`

**Comment by marlonrichert** [comment]
@dmknght Unrelated to your bug, but I recommend you **_remove_** the following two lines from your `.zshrc` file:
```zsh
bindkey $key[Up] up-line-or-history
bindkey $key[Down] down-line-or-history
```
Then ⬆️ will open `zsh-autocomplete`’s history menu and ⬇️ will start menu selection.

**Comment by marlonrichert** [comment]
> Likely zsh confused the new folder name

@dmknght What new folder name do you mean?

**Comment by marlonrichert** [comment]
I used your `.zshrc` file, but I cannot reproduce the bug with it. Do you have any other config files on your system that Zsh reads?

Alternatively, the problem might be that you have some faulty completion functions installed. See issues #156, #150, and #73.

**Comment by dmknght** [comment]
> I am unable to reproduce the bug with the .zshrc file you provided. Do you have any other config files on your system that Zsh reads?

No i don't.

> Alternatively, the problem might be that you have some faulty completion functions installed. See issues #156, #150, and #73.

It looks really similar. For now, after reboot, i don't see any error shows up. Let me use a while to see. I can reopen the issue if i see

> Then arrow_up will open zsh-autocomplete’s history menu and arrow_down will start menu selection.

Thank you. That setting was for older version. Let me try without it

**Comment by dmknght** [comment]
Alright the bug is still there.
I'm having different folders
- faraday
- faraday-cli
- faraday-client
- faraday-plugins

Type `cd fara` on terminal then use `Tab` shows the error.

**Comment by marlonrichert** [comment]
I used your `.zshrc` and created those dirs, then typed `cd fara` and pressed <kbd>Tab</kbd>. No problem.

**Comment by marlonrichert** [comment]
Can you try the following?
1. Type `cd fara` (but don't yet press <kbd>Tab</kbd> or <kbd>Enter</kbd>).
2. Press <kbd>Alt</kbd><kbd>Q</kbd>.
3. Type `setopt verbose xtrace` and press <kbd>Enter</kbd>.
4. Press <kbd>Tab</kbd>.
5. Copy the output.
6. Paste it here.

**Comment by dmknght** [comment]
I tried as you said and i got very long long output, includes my recent dirs and so on
And i realize i didn't remove cache files, which is needed for totally new version.
For now i don't see any error like that. It is data config of old and new version for sure.
Thank you for your help ^^
