### ISSUE TITLE
"Unknown sort specifier" on cd.

### ISSUE THREAD

**Issue by yrammos** [marlonrichert/zsh-autocomplete#182]
With zsh-autocomplete enabled, every `cd` action returns the message:

`.autocomplete.recent_dirs.chpwd:2: unknown sort specifier`

followed by the command output.

Loading the plugin in a pristine shell (per the usual procedure) actually resolves the issue. Likewise, commenting-out the plugin from `.zshrc` also resolves the issue.

So this must be caused by the interaction zsh-autcomplete with another plugin and/or other `.zshrc` parameters. Before attempting an exhaustive "bisect" on my long `~/.zshrc` to track down the error, might @marlonrichert have an idea about where to look? 

For the history (no pun intended), I also use the zsh-hist plugin with the following shell options:

```zsh
setopt histfcntllock histignorealldups histsavenodups sharehistory hist_verify hist_reduce_blanks
```

Many thanks for any ideas.

**Comment by marlonrichert** [comment]
Do `chpwd_recent_filehandler; print -l $reply[@]` and investigate the output. Do you have any paths that end in `(…)`?

**Comment by yrammos** [comment]
Much appreciated, @marlonrichert. No, I don't have any such paths.

**Comment by marlonrichert** [comment]
What does `type -f .autocomplete.recent_dirs.chpwd` output?

**Comment by yrammos** [comment]
Here it goes:

```
.autocomplete.recent_dirs.chpwd () {
	chpwd_recent_filehandler
	typeset -gHa _autocomplete__recent_dirs=($~reply[@])
}
```

**Comment by dmknght** [comment]
Did you upgrade from previous version or you have fresh install?
Make sure you deleted all cache file that was generated by zsh and zsh-autocomplete. I have similar issue before and it solved by remove all old cache data

**Comment by yrammos** [comment]
@dmknght thank you for the suggestion. Deleting `zcompdump` did not help. What cache files might you have in mind?

**Comment by marlonrichert** [comment]
@yrammos If you paste this into the command line, does it solve the problem?
```zsh
.autocomplete.recent_dirs.chpwd () {
	chpwd_recent_filehandler
	typeset -gHa _autocomplete__recent_dirs=("$reply[@]")
}
```

**Comment by yrammos** [comment]
Thank you, @marlonrichert — yes it does!

**Comment by marlonrichert** [comment]
Fixed (albeit in a different way than above).
