### ISSUE TITLE
Add instalation instructions for Oh My Zsh

### ISSUE THREAD

**Issue by ricardogaspar2** [marlonrichert/zsh-autocomplete#183]
## What do you want?
OhMyZsh plugins can be installed in an easy way: https://github.com/ohmyzsh/ohmyzsh/wiki/Customization#overriding-and-adding-plugins

## Why do you want this?
It's easier to set up for those who use OhMyZsh.

## Who else would benefit from this?
Users who use OhMyZsh.

## Explain in detail how you would expect this to work
I've installed your plugin like a regular OhMyZsh plugin (following their instructions) and it worked.
I've followed these instructions from another plugin: https://github.com/zdharma/history-search-multi-word#oh-my-zsh

**Comment by marlonrichert** [comment]
@ricardogaspar2 Why should I add installation instructions for OMZ, if OMZ has installation instructions? I even included [a note about this in the Readme](https://github.com/marlonrichert/zsh-autocomplete#as-a-plugin):

> `zsh-autocomplete` should work as a plugin with most frameworks & plugin managers. Please refer to your framework's/plugin manager's documentation for instructions.

Is there some part of this that you think is unclear?

**Comment by ricardogaspar2** [comment]
Hey! Thank you for your reply.

I read that sentence. Yes, I think it's somewhat vague. What do you think about adding a list of those you know the plugin works with?

**Comment by marlonrichert** [comment]
I’ll have to think about it. At present, I don’t actively test it with any plugin managers or frameworks.

**Comment by RoyalTS** [comment]
The instructions could be really simple:

1. Clone the repo:
```sh
git clone https://github.com/marlonrichert/zsh-autocomplete ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autocomplete
```

2. Add to the list of plugins in `.zshrc`:

```sh
plugins=(
  ...
  zsh-autocomplete
)
```

**Comment by marlonrichert** [comment]
Closing this as `wontfix` for the following reasons:
1. I don't see any clear benefit to installing `zsh-autocomplete` as an Oh My Zsh plugin. In fact, your shell will probably start up faster if you `source /path/to/zsh-autocomplete.plugin.zsh` at the top of your `.zshrc` file instead.
2. I don't want to maintain installation instructions for 3rd party software. Those are better maintained there.
3. I don't want to encourage people to use Oh My Zsh. That "framework" has given me enough as it is already.
4. If I would add instructions specific to OMZ, then it wouldn't be fair if I don't add instructions for Prezto, Zimfw, etc., too. I don't want to go there.

If you want the plugin installation instruction for OMZ to be easier to find, then please [file an issue about that with OMZ](https://github.com/ohmyzsh/ohmyzsh/issues/new/choose).

**Comment by tejasc0** [comment]
> Closing this as `wontfix` for the following reasons:
> 
> * I don't see any clear benefit to installing `zsh-autocomplete` as an Oh My Zsh plugin. In fact, your shell will probably start up faster if you `source /path/to/zsh-autocomplete.plugin.zsh` at the top of your `.zshrc` file instead.
> * I don't want to maintain installation instructions for 3rd party software. Those are better maintained there.
> * If I would add instructions specific to OMZ, then it wouldn't be fair if I don't also add instructions for Prezto, Zimfw, etc. and I don't want to go there.
> * I don't want to encourage people to use Oh My Zsh. That "framework" has already given me enough headaches as it is.
> 
> If you want OMZ's plugin installation instruction to be easier to find, then please [file an issue about that with OMZ](https://github.com/ohmyzsh/ohmyzsh/issues/new/c we dont need to add each plugin in plugins section

right, we dont need to add each plugin in plugins section of zshrc
