### ISSUE TITLE
"command not found" errors on _autocomplete

### ISSUE THREAD

**Issue by GitUser0080** [marlonrichert/zsh-autocomplete#184]
* `zsh-autocomplete` version:  2021-02-05 (February 5 commit)
* Zsh version:  5.8
* Framework:  none
* Plugin manager:  none

```zsh
$ cd $(mktemp -d)  # Create a temp dir and enter it.
$ ZDOTDIR=$PWD HOME=$PWD zsh -f  # Start a subshell in it without config files.
% source path/to/zsh-autocomplete.plugin.zsh  # Source the plugin.
% # any selection causes errors
```
This issue occurs to me even without any config files. Every time I want to select an item from the list it returns a "command not found" errors. Also pressing KeyUp and KeyDown to look through the history returns the same errors.
Screenshot:

![2021-02-09_11-38](https://user-images.githubusercontent.com/66826956/107352057-527ca700-6ac3-11eb-9465-c7a035418ce4.png)

Here's my actual .zshrc just in case: <a href="https://pastebin.com/GiGg2FYs">Link</a>

**Comment by marlonrichert** [comment]
I cannot reproduce this and since it occurs for you without config files, too, I suspect it's something else in your environment. The problem might be that you have some faulty completion functions installed. Please check issues #156, #150, and #73.

**Comment by GitUser0080** [comment]
It's most likely not the case here since I don't have kubectl installed at all. Is there any possibility that plugins installed with Vim and Tmux could affect the environment autocompletion and therefore break this plugin?

**Comment by GitUser0080** [comment]
After playing around for a while the solution appeared to be much simpler than I thought. Sourcing the `zsh-autocomplete.plugin.zsh` file couldn't actually initialize the plugin properly. For some reason it didn't load the whole script, so I had to manually do `zsh zsh-autocomplete.plugin.zsh` for this to work.  
I still don't know what caused this issue though.

**Comment by marlonrichert** [comment]
> Sourcing the `zsh-autocomplete.plugin.zsh` file couldn't actually initialize the plugin properly. For some reason it didn't load the whole script, so I had to manually do `zsh zsh-autocomplete.plugin.zsh` for this to work.  

That is quite weird. 🤔
