### ISSUE TITLE
Add some recommended settings with demo on git?

### ISSUE THREAD

**Issue by dmknght** [marlonrichert/zsh-autocomplete#185]
Some users might not have time to test all features. So maybe it is easier to regular users by adding some .zsh config as examples, allow users to create pull request and add some screenshot / short video for the demo -> regular users can choose it

**Comment by marlonrichert** [comment]
The defaults are the recommended settings. No config required. 🙂

**Comment by dmknght** [comment]
Well IMO some preconfigs for some useful cases are better to normal users. Conky could be a good example of users create custom configs and share. Ofc the comparison is not very fair because default config of conky is very basic (or likely not useful as i remember).

**Comment by marlonrichert** [comment]
Sure, I can rewrite the Readme a bit.

**Comment by marlonrichert** [comment]
What do you need demos/videos for, though?

**Comment by dmknght** [comment]
> For what do you need screenshots and videos, though?

Well i meant something like a screenshot or the gif that is showing in readme so users can understand the features of customization :D

**Comment by dmknght** [comment]
Well i don't see any problem for now. Maybe i'll check it more carefully later + try on my config and see

**Comment by marlonrichert** [comment]
If you do, please open a new, more specific issue.
