### ISSUE TITLE
Option to expand wildcard list

### ISSUE THREAD

**Issue by wu-qing-157** [marlonrichert/zsh-autocomplete#188]
## What do you want?
The default oh-my-zsh enables us to use `tab` on a wildcard to expand the matched file list.
For example, if I have three zip files in current directory, when I type `ls *.zip` and press `tab`, the command line will become `ls a.zip b.zip c.zip`.
However, in current version of `zsh-autocomplete`, it will only show an autocomplete list consisting of the three zip files.

## Why do you want this?
The feature is useful in several cases. If I want to check the wildcard exactly matches my idea, I can expand it to check all the matched files. If I want to exclude several files matched by the wildcard, I can first expand it, and then remove some of the matched files in the command line.

## Who else would benefit from this?
I believe many users get used to such feature in oh-my-zsh.

## Explain in detail how you would expect this to work
Given the following situation:
I type a wildcard expression in command line

When I perform the following steps:
1. I press `tab` or some other key

Then I expect the following to happen:
All matched files appear in the command line instead of the wildcard expression

I think it better to enable this feature with an option or use another key than `tab` as the current behavior of `zsh-autocomplete` also have some advantages.

**Comment by marlonrichert** [comment]
Available now on the `main` branch.
