### ISSUE TITLE
Option to disable C-R history search

### ISSUE THREAD

**Issue by modk** [marlonrichert/zsh-autocomplete#189]
Because the default history-search via '^R' requires at least one key press less (I can press <Enter> as soon as I have a match), I would like to disable this particular autocompletion but keep all the others.

For now I just commented out the respective lines in `.autocomplete.async` that override the default behavior, e.g.:
```
  #zle -N history-incremental-search-backward .autocomplete.async.history-incremental-search
```

but a dedicated option or flag would be nicer. Is this somehow possible or planned?

When I disable this feature as above, the default `bck-i-search` is only shown for some milliseconds. It would be nice to keep it as well but this is less of a hassle.

Thanks for your work btw, I have been a user of auto-fu for years but its age shows.

**Comment by marlonrichert** [comment]
This is now implemented. See here for instructions: https://github.com/marlonrichert/zsh-autocomplete/blob/main/README.md#disable-live-history-search

**Comment by modk** [comment]
Just wanted to report back that it works nicely. Thank you.
