### ISSUE TITLE
pull up the prompt to middle of the screen

### ISSUE THREAD

**Issue by cibinmathew** [marlonrichert/zsh-autocomplete#191]
## What do you want?
If the prompt is in the bottom, pull up the prompt to top(ideally middle, so that I still could see the last command output while typing).
I tried  [almostontop](https://github.com/Valiev/almostontop). But
* it erases the output of last command(my last command output is erased in a fraction of second)
* It always stays on first line(After every command I have to scroll up to see what is printed in last output)

## Why do you want this?
When the prompt reaches the bottom, there is little space left in the bottom to see the available suggestions

## Explain in detail how you would expect this to work
Given the following situation:
* 

When I perform the following steps:
1. 
1. 

Then I expect the following to happen:
*

**Comment by marlonrichert** [comment]
This should be better now on the `main` branch. Please try it out.

**Comment by cibinmathew** [comment]
Here is what I get when it is almost near the bottom

On typing `git c`, I could see some options. Now if I backspace and remove `<space>c` and key in `<space>` again, I could see few more suggestions which were not visible earlier. This keeps on increasing with above steps repeated(I have to repeat around 4 5 times to see all suggestions come up in the visible pane)

![image](https://user-images.githubusercontent.com/10793628/110683684-50148680-8202-11eb-9481-e722d621e5e3.png)
![image](https://user-images.githubusercontent.com/10793628/110683847-8225e880-8202-11eb-97f0-097fa10fff38.png)
![image](https://user-images.githubusercontent.com/10793628/110683979-9d90f380-8202-11eb-8b8d-cae1c6663d39.png)
![image](https://user-images.githubusercontent.com/10793628/110684062-b26d8700-8202-11eb-9610-4779d78c5521.png)

**Comment by marlonrichert** [comment]
@cibinmathew As it states below your prompt, if you want to see the whole list, press ⬇️.

**Comment by cibinmathew** [comment]
It could be more useful with few more options visible(2 or 3 seems too less) without the need for an extra key in (but for further and extended options, this explicit input makes sense). 

Here is mix of code that I managed to use as a workaround. Not sure if this helps
```sh

# prompt-at-the-vertical-middle

# https://itectec.com/superuser/can-i-have-the-terminal-prompt-at-the-vertical-middle-of-a-window/

zmodload zsh/terminfo  # load terminfo modules to make the associative array $terminfo available

# save current prompt to parameter PS1o
PS1o="$PS1"

# calculate how many lines for offset
halfpage=${$((LINES/2.5))%.*}  # rounds to integer eg: ${12.5%.*}

# construct parameter to go down/up $halfpage lines via termcap
halfpage_down=""
for i in {1..$halfpage}; do
  halfpage_down="$halfpage_down$terminfo[cud1]"
done

halfpage_up=""
for i in {1..$halfpage}; do
  halfpage_up="$halfpage_up$terminfo[cuu1]"
done

# define functions
function prompt_middle() {
  # print $halfpage_down
  PS1="%{${halfpage_down}${halfpage_up}%}$PS1o"
}

function prompt_restore() {
  PS1="$PS1o"
}
function pre_cmd() {
  print ${halfpage_down}${halfpage_up}$terminfo[cuu1]
}

autoload -Uz add-zsh-hook
add-zsh-hook precmd pre_cmd
```

**Comment by marlonrichert** [comment]
@cibinmathew This is now implemented on the `main` branch. Please see the `list-lines` setting in the Readme: https://github.com/marlonrichert/zsh-autocomplete/blob/main/README.md#settings
