### ISSUE TITLE
Conflited with Oh my zsh's vi-mode

### ISSUE THREAD

**Issue by yueyejinghun** [marlonrichert/zsh-autocomplete#199]
* `zsh-autocomplete` version: 817af7c
* Zsh version: 5.8 on Fedora (plus Ubuntu 20.04 and Arch)
* Framework: Oh My Zsh
* Plugin manager: antigen
* Content of .zshrc:
```zsh
source ~/antigen.zsh

antigen use oh-my-zsh
antigen bundle vi-mode

antigen bundle marlonrichert/zsh-autocomplete

antigen apply
```

steps to reproduce

Clone master branch manually (This is not related with this issue, only to get zsh-autocomplete to work)
Install Oh My Zsh with antigen and only enable vi-mode
Down arrow key does not work at all, it cannot go to the menu
Ctrl-Space is also not working
I think it has something to do with #192 because this issue appeared only recently
[debug_vi_mode.log](https://github.com/marlonrichert/zsh-autocomplete/files/6073397/debug_vi_mode.log)

**Comment by marlonrichert** [comment]
> I think it has something to do with #192 because this issue appeared only recently

That’s not possible, because I did not yet merge that to `main`.

**Comment by marlonrichert** [comment]
Duplicate of #192.
