### ISSUE TITLE
zsh: do you wish to see all ___ possibilities ?

### ISSUE THREAD

**Issue by thepreacher** [marlonrichert/zsh-autocomplete#200]
Since upgrading to release `2021-03-04` my terminal is acting weird. First off all the very first key I press is misinterpreted. For example, when I press any letter of the alphabet on a new command prompt, it's interpreted as `n` or `^?`.  I then have to delete the character(s) and type again.

Every time I start  a new terminal and without typing anything, I get the following error:

`zsh: do you wish to see all 175 possibilities (52 lines)?` 

I have no Idea how to diagnose the error. This also happens after every command. I don't get any of the above issues with `zsh-autocomplete` disabled.

Thanks

**Comment by yueyejinghun** [comment]
I have encountered this problem today too. It possibly wants to list all enabled plugin commands and aliases from .zshrc. Disable the ones you don't need currently as many as possible until the prompt is gone and wait for the update

**Comment by MarcPartensky** [comment]
I too have encountered this problem. My fix for now: git checkout d90b83d

**Comment by marlonrichert** [comment]
Sorry about that. Fix is now available on `main`.
