### ISSUE TITLE
Shift-Tab keep selecting forward instead of backward with widget-style menu-select

### ISSUE THREAD

**Issue by lkhphuc** [marlonrichert/zsh-autocomplete#209]
* `zsh-autocomplete` version: 6284119
* Zsh version: zsh-5.8-0-g77d203f
* Framework: none
* Plugin manager: Znap

I'm adjusting my behavior to keep typing ahead and use the default mode, instead of performing the Tab dance. 
However, for the sake of reporting bug, with `zstyle ':autocomplete:tab:*' widget-style menu-select`, Shift-Tab behaviors is identical to Tab, i.e it keep select forward instead of backward.
It works fine for `zstyle ':autocomplete:tab:*' widget-style menu-complete`

```zsh
# Go to your clone of the `zsh-autocomplete` repo.
$ cd /path/to/zsh-autocomplete

 # Make sure you always test with the `main` branch.
$ git checkout main

# Update to the latest commit.
$ git pull

# Create a temp dir and enter it.
$ cd $(mktemp -d)

# Restart Zsh without config files in this dir.
$ ZDOTDIR=$PWD HOME=$PWD exec zsh -f

# Source the plugin.
% source /path/to/zsh-autocomplete/zsh-autocomplete.plugin.zsh

# Test and document the steps that reproduce the problem.
Sorry don't know how to get the `zstyle ':autocomplete:tab:*' widget-style complete-word` to run in this environment.
 Just run it on the command line or source it in a file doesn't seem to have any effect.
```

**Comment by marlonrichert** [comment]
Fixed on the `main` branch.
