### ISSUE TITLE
Tab in select widget conflicts with zsh-autosuggestions

### ISSUE THREAD

**Issue by dmknght** [marlonrichert/zsh-autocomplete#211]
* `zsh-autocomplete` version: 2021-03-07
* Zsh version: debian/5.8-6
No framework or plugin manager

My .zshrc
```
# Greeting
echo "Welcome to Parrot OS"

# Prompt
PROMPT="%F{red}┌[%f%F{cyan}%m%f%F{red}]─[%f%F{yellow}%D{%H:%M-%d/%m}%f%F{red}]─[%f%F{magenta}%d%f%F{red}]%f"$'\n'"%F{red}└╼%f%F{green}$USER%f%F{yellow}$%f"
# Export PATH$
export PATH=~/.local/bin:/snap/bin:/usr/sandbox/:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/usr/share/games:/usr/local/sbin:/usr/sbin:/sbin:$PATH

# alias
alias ls='ls -lh --color=auto'
alias dir='dir --color=auto'
alias vdir='vdir --color=auto'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias python='python3'
#####################################################
# Auto completion / suggestion
# Mixing zsh-autocomplete and zsh-autosuggestions
# Requires: zsh-autocomplete (custom packaging by Parrot Team)
# Jobs: suggest files / foldername / histsory bellow the prompt
# Requires: zsh-autosuggestions (packaging by Debian Team)
# Jobs: Fish-like suggestion for command history
source /usr/share/zsh-autosuggestions/zsh-autosuggestions.zsh
source /usr/share/zsh-autocomplete/zsh-autocomplete.plugin.zsh
# Select all suggestion instead of top on result only
zstyle ':autocomplete:tab:*' insert-unambiguous yes
zstyle ':autocomplete:tab:*' widget-style menu-select
zstyle $key[Up] up-line-or-history
zstyle $key[Down] down-line-or-history
#zstyle ':autocomplete:*' max-lines 100%
#zstyle ':completion:*' list-rows-first yes
#zstyle ':completion:*' group-name ''
zstyle ':autocomplete:*' min-input 2
bindkey $key[Up] up-line-or-history
bindkey $key[Down] down-line-or-history


##################################################
# Fish like syntax highlighting
# Requires "zsh-syntax-highlighting" from apt
source /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# Save type history for completion and easier life
HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
setopt appendhistory

alias time="/usr/bin/time -f '\t%E real,\t%U user,\t%S sys,\t%K amem,\t%M mmem'"
DEBFULLNAME="Nong Hoang Tu"
DEBEMAIL="dmknght@parrotsec.org"
export DEBFULLNAME DEBEMAIL
```
Please note that we have this problem in `2021-03-07` and i didn't saw this problem before.
# Step
1. Type any command to have history -> `zsh-autosuggestions` works
2. We use command with suggestion of history (zsh-autosuggestions) 
![image](https://user-images.githubusercontent.com/29118926/110941939-f9f23100-8330-11eb-9eac-944630544e84.png)
3. Type keywords of directory to use completion of zsh-autocomplete (in this case the folder is `ParrotProjects`.
![image](https://user-images.githubusercontent.com/29118926/110942039-20b06780-8331-11eb-9491-2f32743cdf2f.png)
4. Press tab to complete the suggested text. See the problem: The suggested text of `zsh-autosuggestions` become `rrotProjects/parrot-menu/bin` and it should be `/parrot-menu/bin`
![image](https://user-images.githubusercontent.com/29118926/110941999-11c9b500-8331-11eb-840e-4080aecd66b1.png)
5. Optional: `press right arrow` to trigger the `zsh-autosuggestions`. The whole text is wrong 
![image](https://user-images.githubusercontent.com/29118926/110942183-5bb29b00-8331-11eb-9618-a837992a4586.png)
-> Possibly the overwrite is doing something wrong

**Comment by marlonrichert** [comment]
I would like to highlight a part of the bug report template that you deleted:
```
# Make sure you always test with the `main` branch.
$ git checkout main
```
Did you? Because I cannot reproduce this on the `main` branch.

Also, as it says in the bug report template:
```
<!-- Please use the following template to put together a minimal test case with which I can
reproduce the bug. If I cannot reproduce the bug, then I cannot fix it! -->
```
Don't paste in your `.zshrc` file. Instead, give me minimum reproducible test case, please.

**Comment by dmknght** [comment]
> Did you? Because I cannot reproduce this on the main branch.
Sorry i was using the version from release so i meant report the bug for that version and i thought it wasn't fixed

> Don't paste in your .zshrc file. Instead, give me minimum reproducible test case, please. slightly_smiling_face

Sorry again. I thought the .zshrc could do something wrong. Next time i'll follow your all steps i promise.
So i've just checked the latest version that you made release. The problem is fixed but it brings other small problem: when i press tab to complete the folder name, the "tail" of text, which is given by `zsh-autosuggestions` is removed. (see screenshot2). It didn't happen before.
![image](https://user-images.githubusercontent.com/29118926/111003227-a60e3900-837e-11eb-8853-398761bbea1f.png)
![image](https://user-images.githubusercontent.com/29118926/111003246-ac041a00-837e-11eb-8b2f-a5d9105baea6.png)
When i delete a character from folder name that press tab gives, it shows suggested text from `zsh-autosuggestions`
![image](https://user-images.githubusercontent.com/29118926/111003348-deae1280-837e-11eb-81de-95d715b0deab.png)
P/s: likely the `zstyle ':autocomplete:*' min-input 2` created the problem because when i press `P` for name suggestion, press Tab still creates this error
![image](https://user-images.githubusercontent.com/29118926/111003461-1ae17300-837f-11eb-9602-ea05c609bd20.png)
![image](https://user-images.githubusercontent.com/29118926/111003486-2339ae00-837f-11eb-8541-9ec02b75d4b6.png)
Let me check the template again follow your all steps to spot the bug

**Comment by dmknght** [comment]
I did commands
```
# Create a temp dir and enter it.
$ cd $(mktemp -d)

# Restart Zsh without config files in this dir.
$ ZDOTDIR=$PWD HOME=$PWD exec zsh -f
```
Then i exported source of `zsh-autocomlete` and `zsh-autosuggestions`
```
ParrotPC% source /usr/share/zsh-autocomplete/zsh-autocomplete.plugin.zsh 
ParrotPC% source /usr/share/zsh-autosuggestions/zsh-autosuggestions.zsh
```
Because in zshrc, i use `tab` for the dir completion, so i added 2 settings
```
zstyle ':autocomplete:tab:*' insert-unambiguous yes
zstyle ':autocomplete:tab:*' widget-style menu-select
```
I created same folder structure to test
`ParrotProjects/zsh-autocomplete`
Everything seems normal
I added `zstyle ':autocomplete:*' min-input 2` because .zshrc has it as well -> no bug after some cd

On my terminal which is having bug, the text shows wrong (the case with `~/P`) but press `Enter` still have correct path. Meanwhile the `alias` is still having the `\` at start

**Comment by dmknght** [comment]
On second test, i was able to reprocedure the problem.
![image](https://user-images.githubusercontent.com/29118926/111006634-0dc78280-8385-11eb-9457-5344c7097daf.png)
Steps:
1. Init the test folder
```
cd $(mktemp -d)
ZDOTDIR=$PWD HOME=$PWD exec zsh -f
```
2. Use everything that is not comment from `.zshrc`
3. Make dir like this `ParrotProjects/parrot-menu/bin/`. Bug happened
=> So i guess the problem is something wrong with my `.zshrc`. I'm redo it to check anything could be wrong.
2. ```

**Comment by dmknght** [comment]
@marlonrichert i can able reprocedure the problem using the steps from template. (Previous tests above was my mistake and something was wrong so i couldn't reprocedure.)
Commands i used
```
cd $(mktemp -d)
ZDOTDIR=$PWD HOME=$PWD exec zsh -f
source /usr/share/zsh-autosuggestions/zsh-autosuggestions.zsh
source /usr/share/zsh-autocomplete/zsh-autocomplete.plugin.zsh
mkdir -p ParrotProjects/parrot-menu/bin/
cd ParrotProjects/parrot-menu/bin
cd ../../..
```
Then press `cd P` then `Tab`
![image](https://user-images.githubusercontent.com/29118926/111007549-00ab9300-8387-11eb-88fc-293a3818fe3a.png)

**Comment by marlonrichert** [comment]
Yes, I can reproduce it like this:
```zsh
> cd $(mktemp -d)
> ZDOTDIR=$PWD HOME=$PWD exec zsh -f
% source /Users/marlon/Git/zsh-autosuggestions/zsh-autosuggestions.plugin.zsh
% source /Users/marlon/Git/zsh-autocomplete/zsh-autocomplete.plugin.zsh
% mkdir -p ParrotProjects/parrot-menu/bin/
% cd ParrotProjects/parrot-menu/bin
% cd ../../..
```
**but** that's **not** a real-word use case. When you source these two plugins on separate command lines, all kinds of events will happen in between that don't happen when you source them in your `.zshrc` file.

If I instead put them on the same line, then everything works fine: 
```zsh
> cd $(mktemp -d)
> ZDOTDIR=$PWD HOME=$PWD exec zsh -f
% source /Users/marlon/Git/zsh-autosuggestions/zsh-autosuggestions.plugin.zsh; source /Users/marlon/Git/zsh-autocomplete/zsh-autocomplete.plugin.zsh
% mkdir -p ParrotProjects/parrot-menu/bin/
% cd ParrotProjects/parrot-menu/bin
% cd ../../..
```

**Comment by dmknght** [comment]
> **but** that's **not** a real-word use case. When you source these two plugins on separate command lines, all kinds of events will happen in between that don't happen when you source them in your `.zshrc` file.

The problem is version 21.03.07 didn't have this problem and i didn't see it in previous versions

**Comment by marlonrichert** [comment]
But do you have the problem, too, when both plugins are sourced in your `.zshrc` instead of in separate statements on the command line? Becasuse I cannot reproduce it with them in a `.zshrc` file and sourcing them separately on the command line is simply not supported.

**Comment by dmknght** [comment]
> But do you have the problem, too, when both plugins are sourced in your .zshrc instead of in separate statements on the command line? Becasuse I cannot reproduce it with them in a .zshrc file and sourcing them separately on the command line is simply not supported.
In previous test, as i remember, it happened no matter `.zshrc` has source at same line nor different line.
And i can't see the problem in version 21.03.12. Press `Tab` now removes all string instead
