### ISSUE TITLE
Up arrow key not displaying previously run command

### ISSUE THREAD

**Issue by parthv21** [marlonrichert/zsh-autocomplete#213]
* `zsh-autocomplete` version: `6284119`
* Zsh version: `zsh-5.8-0-g77d203f`
* Framework: Oh My Zsh
* Plugin manager: "none"

```
 ~/.oh-my-zsh/custom/plugins/zsh-autocomplete  main  > cd $(mktemp -d)                                                                                           
 /var/folders/9t/0pvv38nd4kxff89szytt53mm0000gr/T/tmp.ACv97Ehd > ZDOTDIR=$PWD HOME=$PWD exec zsh -f                                                                  
3c22fb686d64% pwd
/var/folders/9t/0pvv38nd4kxff89szytt53mm0000gr/T/tmp.ACv97Ehd
3c22fb686d64% source /Users/XYZ/.oh-my-zsh/custom/plugins/zsh-autocomplete
3c22fb686d64% source /Users/XYZ/.oh-my-zsh/custom/plugins/zsh-autocomplete/zsh-autocomplete.plugin.zsh
3c22fb686d64%
No suffix alias found.
```

Pressing the up arrow key after using auto complete to run a command returns the following error instead of typing out the previously run command. But this issue does not occur if I use only zsh-autocomplete.

```zsh
.autocomplete._main_complete:135: command not found: _autocomplete.history_lines _autocomplete._main_complete.post:11: command not found: _autocomplete.unambiguous
```

**Comment by marlonrichert** [comment]
@parthv21 Can you please fill out the rest of the bug report template, instead of deleting it? If I cannot reproduce your issue, then I cannot fix it.

**Comment by parthv21** [comment]
I am not exactly sure what to fill in those spaces is there some guide?

**Comment by marlonrichert** [comment]
A guide? What part of this don't you understand?

```zsh
# Go to your clone of the `zsh-autocomplete` repo.
$ cd /path/to/zsh-autocomplete

 # Make sure you always test with the `main` branch.
$ git checkout main

# Update to the latest commit.
$ git pull

# Create a temp dir and enter it.
$ cd $(mktemp -d)

# Restart Zsh without config files in this dir.
$ ZDOTDIR=$PWD HOME=$PWD exec zsh -f

# Source the plugin.
% source /path/to/zsh-autocomplete/zsh-autocomplete.plugin.zsh

# Test and document the steps that reproduce the problem.
% <steps to reproduce>
```

**Comment by parthv21** [comment]
NVM, I have updated my main issue. The issue does not occur when only using zsh-complete. But also, somehow when I ran `git pull`, I was not on the latest commit. Which is strange since I had just pulled this morning.

**Comment by parthv21** [comment]
I think the git pull fixed this issue. Not getting this issue with all plugins running anymore.

**Comment by marlonrichert** [comment]
It's probably a caching issue. Next time you run into problem like this, try
```
% rm $_comp_dumpfile
```
then restart your terminal. 🙂

> Which is strange since I had just pulled this morning.

It's not that strange if you consider I had pushed in new commits just seconds before your filed your issue. 😉

**Comment by parthv21** [comment]
Lol didn't see that! What was causing the error though? Googling it did not help...  What were those commands? `_autocomplete.history_lines`

**Comment by marlonrichert** [comment]
Those are private methods/internal functions used by `zsh-autocomplete`. When you see error messages like that, it means they failed to load.

**Comment by parthv21** [comment]
Got it! This is such an amazing plugin. I am recommending it to everyone! :D

**Comment by parthv21** [comment]
This issue happened again. It disappeared after I ran these steps. 

```
$ git -C ~zsh-autocomplete switch main  # Was already on main branch
$ git -C ~zsh-autocomplete pull         # Was not on latest commit, but had tried running `git pull` when this issue first reappeared 3-4 days back
$ cd $(mktemp -d)                       # Went to this directory but I don't think it affects fixing stuff
$ unset _comp_dumpfile ZDOTDIR XDG_CACHE_HOME XDG_CONFIG_HOME XDG_DATA_HOME # I think this command returned a warning that some folder was not found
$ HOME=$PWD exec zsh -f       # Ran this but I don't think it has any effect on fixing things
```

After this in another tab I was trying to find the path to `.zsh` and noticed that things were working properly again with arrows keys showing history. I am not sure why this issue keeps coming up periodically.  But could you add a command to run these things together like `fix-autocomplete = git -C ~zsh-autocomplete switch main && git -C ~zsh-autocomplete pull && unset _comp_dumpfile ZDOTDIR XDG_CACHE_HOME XDG_CONFIG_HOME XDG_DATA_HOME`?

**Comment by marlonrichert** [comment]
> ```zsh
> $ unset _comp_dumpfile ZDOTDIR XDG_CACHE_HOME XDG_CONFIG_HOME XDG_DATA_HOME
> # I think this command returned a warning that some folder was not found
> ```

Well, yeah, those variables (except the first one) all point to folders. So, unsetting them will of course lead to problems. We're doing this, however, to prepare for the next step:

> ```zsh
> $ HOME=$PWD exec zsh -f
> ```

This restarts your shell _without sourcing **any** config files._

If the steps above fix the problem for you, then that means the problem is somewhere in your config files. Here's the [full list of all files sourced by Zsh on startup](http://zsh.sourceforge.net/Doc/Release/Files.html#Startup_002fShutdown-Files): 
```zsh
/etc/zshenv
${ZDOTDIR:-$HOME}/.zshenv
/etc/zprofile
${ZDOTDIR:-$HOME}/.zprofile
/etc/zshrc
${ZDOTDIR:-$HOME}/.zshrc
/etc/zlogin
${ZDOTDIR:-$HOME}/.zlogin
```
This happens in the order given above. You will have to go through each of those to try to figure out where the problem lies.

> But could you add a command to run these things together like `fix-autocomplete = git -C ~zsh-autocomplete switch main && git -C ~zsh-autocomplete pull && unset _comp_dumpfile ZDOTDIR XDG_CACHE_HOME XDG_CONFIG_HOME XDG_DATA_HOME`?

No, because that wouldn't fix anything, as I explained above.

**Comment by parthv21** [comment]
I don't understand how the steps I ran fix issues with my config files? Only `git pull` or `unset _comp_dumpfile ZDOTDIR XDG_CACHE_HOME XDG_CONFIG_HOME XDG_DATA_HOME` could have had any substantial effect. I feel it was the later, since I don't think that code breakage was introduced suddenly. 

But you say 'So, unsetting them will of course lead to problems', but in my case it looks like unsetting actually solved the problem. So what's going on here?

**Comment by marlonrichert** [comment]
What output do you get from `ls $_comp_dumpfile $ZDOTDIR $XDG_CACHE_HOME $XDG_CONFIG_HOME $XDG_DATA_HOME`?

**Comment by StefanLobbenmeier** [comment]
> @StefanLobbenmeier Is #213 the same problem as yours? If so, let’s continue the discussion over there.

_Originally posted by @marlonrichert in https://github.com/marlonrichert/zsh-autocomplete/issues/215#issuecomment-808708437_

Yes, I thinnk my issue is the same. When I open a new terminal (without compinit in my .zshrc) and press the up arrow I get this output:
```
~ ❯❯❯ .autocomplete._main_complete:135: command not found: _autocomplete.history_linesrectory --
_autocomplete._main_complete.post:12: command not found: _autocomplete.unambiguouseam/      Templates/  Videos/                                   
~ ❯❯❯ 
 -- directory --
Desktop/    Documents/  Downloads/  Music/      Pictures/   Public/     Steam/      Templates/  Videos/ 

```

However, also this issue is solved by adding
`autoload -U compinit; compinit`
to my .zshrc.

@parthv21 could you also try adding `autoload -U compinit; compinit` as the last line of your .zshrc?

**Comment by StefanLobbenmeier** [comment]
Just one more thing: I also tried using prezto instead of oh my zsh, with the same behaviour, autoload -U compinit; compinit is needed as the last line when using zsh-autocomplete

**Comment by parthv21** [comment]
> What output do you get from `ls $_comp_dumpfile $ZDOTDIR $XDG_CACHE_HOME $XDG_CONFIG_HOME $XDG_DATA_HOME`? 

Unfortunately I don't remember the output. If I face the same issue again and the issue recreation steps solve it I will make a note. But wasn't the command `$ unset _comp_dumpfile ZDOTDIR XDG_CACHE_HOME XDG_CONFIG_HOME XDG_DATA_HOME `? Why are you asking the output for `ls $_comp_dumpfile $ZDOTDIR $XDG_CACHE_HOME $XDG_CONFIG_HOME $XDG_DATA_HOME`?

**Comment by parthv21** [comment]
> @parthv21 could you also try adding autoload -U compinit; compinit as the last line of your .zshrc?

@StefanLobbenmeier Right now the issue seems fixed. I will try adding it if it appears again

**Comment by marlonrichert** [comment]
@StefanLobbenmeier I pushed in a potential fix. Please remove `compinit` from your `.zshrc` file and try again.

**Comment by StefanLobbenmeier** [comment]
> I pushed in a potential fix. Please remove compinit from your .zshrc file and try again.

I removed the `autoload -U compinit; compinit` and opened a new terminal, looks good so far. I was both able to fetch the last command without an error and tab for completion also works.

**Comment by parthv21** [comment]
This issue again appeared. 

Running issue reproduction steps:
```
git -C ~zsh-autocomplete switch main                                                                                                                                                  
Already on 'main'
Your branch is up to date with 'origin/main'.
```

```
git -C ~zsh-autocomplete pull                                                                                                                                                             
hint: Pulling without specifying how to reconcile divergent branches is
hint: discouraged. You can squelch this message by running one of the following
hint: commands sometime before your next pull:
hint:
hint:   git config pull.rebase false  # merge (the default strategy)
hint:   git config pull.rebase true   # rebase
hint:   git config pull.ff only       # fast-forward only
hint:
hint: You can replace "git config" with "git config --global" to set a default
hint: preference for all repositories. You can also pass --rebase, --no-rebase,
hint: or --ff-only on the command line to override the configured default per
hint: invocation.
remote: Enumerating objects: 26, done.
remote: Counting objects: 100% (26/26), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 14 (delta 10), reused 12 (delta 8), pack-reused 0
Unpacking objects: 100% (14/14), 1.98 KiB | 168.00 KiB/s, done.
From https://github.com/marlonrichert/zsh-autocomplete
   0a027ac..fdc21c0  main       -> origin/main
Updating 0a027ac..fdc21c0
Fast-forward
 README.md                             | 45 ++++++++++++++++++++++-----------------------
 completion/_autocomplete.recent_paths | 14 ++++++++++----
 module/.autocomplete.compinit         |  8 ++++----
 3 files changed, 36 insertions(+), 31 deletions(-)
```
After this, iterm crashed when I hit up arrow key, and now seeing this weird broken history menu when I press up.


<img width="646" alt="image" src="https://user-images.githubusercontent.com/17941287/113431370-44e7ed00-93a1-11eb-9214-ca3e10bf60d7.png">

<img width="646" alt="image" src="https://user-images.githubusercontent.com/17941287/113431404-5630f980-93a1-11eb-87c6-775468c34be1.png">

**Comment by marlonrichert** [comment]
@parthv21 Can you please make me a reproducible test case with the _entire_ template below? What you've posted now does not help me reproduce the problem at all. Also, you _don't_ need to share the ouput of `git` commands with me. That is not at all helpful and is just wasting screen space.
```zsh
$ git -C ~zsh-autocomplete switch main  # Make sure you test with the `main` branch.
$ git -C ~zsh-autocomplete pull         # Update to the latest commit.
$ cd $(mktemp -d)                       # Create a temp dir and enter it.
$ unset _comp_dumpfile ZDOTDIR XDG_CACHE_HOME XDG_CONFIG_HOME XDG_DATA_HOME
$ HOME=$PWD exec zsh -f       # Restart Zsh without config files in this dir.
% source /path/to/zsh-autocomplete/zsh-autocomplete.plugin.zsh
% 👉YOUR STEPS TO REPRODUCE👈  # Test and document the steps to reproduce the problem.
```

**Comment by marlonrichert** [comment]
Closing this, as I haven't heard back from @parthv21.
