### ISSUE TITLE
Error with logging

### ISSUE THREAD

**Issue by ChocolateOverflow** [marlonrichert/zsh-autocomplete#214]
* `zsh-autocomplete` version: Commit 70417848c6cd0715955ce4cbaf4b9ed779c7402c or later
* Zsh version: zsh-5.8-0-g77d203f
* Framework: none
* Plugin manager: none

The bug is introduced by commit 704178 and persists up to the current 3a20f6. It happens even when my `.zshrc` contains nothing but `source ~/tools/zsh-autocomplete/zsh-autocomplete.plugin.zsh` and commenting out that line removes the issue.

Upon launching zsh, I  get the error `.autocomplete.__init__.precmd:31: can't clobber parameter _autocomplete__log_fd containing file descriptor 0` and zsh-autocomplete fails to load.

**Comment by marlonrichert** [comment]
Should be fixed now.
