### ISSUE TITLE
History expansions are mostly unusable due to premature auto-expansion

### ISSUE THREAD

**Issue by nisavid** [marlonrichert/zsh-autocomplete#22]
This plugin's immediate auto-expansion of history expansions causes the latter to be mostly unusable.  Some examples are detailed below.  The overarching theme is that history expansions should only be auto-expanded if they are unambiguous, where "ambiguous" is meant in the sense that the already typed history expansion could possibly be altered by further characters that have yet to be typed.

Such yet-to-be-typed characters could add a word designator (e.g. `:1` after `!!`), alter a word designator (e.g. `-2` after `!:1`), or add modifiers (e.g. `:a` after `!$`).  Generally speaking, it is unknown whether a history expansion has been fully typed unless it uses the `!{…}` form or until a character is typed that does not further alter the expansion.

Perhaps a more usable approach would be to nix the current behavior and instead perform history auto-expansion as part of `magic-space` and/or a separate expand-under-the-cursor key-binding.

# Example: `!-2`

If I want to expand the second-to-last command (or any part of it, using additional word designators), I would normally type `!-2`.  However, history auto-expansion is invoked immediately after typing `!-`, which obviously fails, thereby causing the `!` to be deleted, leaving the command line as if one had only typed `-`.

Of course, this problem applies likewise to any other intended event designator of the form `!-n`.

# Example: `!:1-2`

If I want to insert the first two arguments of the last command, I would normally type `!:1-2` or, equivalently, `!!:1-2` or `!-1:1-2`.  However, history auto-expansion is invoked immediately after typing `!:1` or `!!` or `!-`, in all cases preventing the possibility of typing what was intended.

Numerous other examples can be found that follow this pattern, whereby one intends to use other word designators and/or history expansion modifiers.  In all cases, the intended expansion is made impossible by premature auto-expansion.

# Example: `!#:1`

If I want to reference the first argument of the currently-being-typed command, I would normally type `!#:1`.  However, history auto-expansion is invoked after typing `!#`, thus expanding to the entire already-typed command (up to the previous word, inclusive).

**Comment by marlonrichert** [comment]
Thanks for the detailed report! I haven’t tested history expansion, because I always just use the Up key instead. I find that it’s faster and more accurate.

I will have a look at what is the best way to fix and let you know when I’ve pushed in a fix.

**Comment by marlonrichert** [comment]
@nisavid The problem here is not `magic-space`. It seems that `zsh-autocomplete`'s automatic use of `list-choices` somehow causes history expansion for some cases. I'll have to investigate more to see how I can fix this.

**Comment by marlonrichert** [comment]
@nisavid I pushed in a fix that works for me when trying the cases above and also the cases listed in http://zsh.sourceforge.net/Doc/Release/Expansion.html#History-Expansion

Please update and try it out. 🙂

**Comment by marlonrichert** [comment]
Closing this issue now. Let me know if you experience any new problems with this.
