### ISSUE TITLE
Recalculate screen size on window resize

### ISSUE THREAD

**Issue by MenkeTechnologies** [marlonrichert/zsh-autocomplete#230]
* `zsh-autocomplete` version: 7662f28a3bca1165efeee853e2571d12837e855d
* Zsh version: 5.8
* Framework: omz
* Plugin manager: zinit

```zsh
 # Make sure you always test with the `main` branch.
$ git -C /path/to/zsh-autocomplete switch main

# Update to the latest commit.
$ git -C /path/to/zsh-autocomplete pull

# Create a temp dir and enter it.
$ cd $(mktemp -d)

# Restart Zsh without config files in this dir.
$ ZDOTDIR=$PWD HOME=$PWD exec zsh -f

# Source the plugin.
% source /path/to/zsh-autocomplete/zsh-autocomplete.plugin.zsh

# Test and document the steps that reproduce the problem.
% <insert your steps to reproduce here>
```
.autocomplete.screen-space only runs on precmd.  Therefore _autocomplete__max_lines  is incorrect  when terminal was resized, prompt was moved up down without command running.  In other words  _autocomplete__screen_space is incorrect in these scenarios until precmd.  Because of this, you can get stuck in loop where every letter typed results in listscroll mode.

```
.autocomplete.async.list-choices.complete() {
   # .autocomplete.screen-space
  local -i _autocomplete__max_lines=$(( _autocomplete__max_lines() ))

```

```
_autocomplete__max_lines() {
  local -i lines; zstyle -s ":autocomplete:${curcontext}:" list-lines lines ||
    lines=16
  return $(( max( lines, _autocomplete__screen_space - BUFFERLINES ) ))
}
```

```
.autocomplete.screen-space() {
  emulate -L zsh; setopt $_autocomplete__options

  local -a reply=()
  print -nr $'\e[6n'
  IFS=$'\e[;' read -Asd R
  local -i y=$reply[-2]
  local -i pslines=${#${(%%)PS1}//[^$'\n']}
  _autocomplete__screen_space=$(( LINES - y - pslines - 2 ))
}
```
Fix would be to recalculate _autocomplete__screen_space before each list-choices

**Comment by marlonrichert** [comment]
> Fix would be to recalculate _autocomplete__screen_space before each list-choices

Be my guest. Patches welcome. 🙂

**Comment by MenkeTechnologies** [comment]
https://github.com/MenkeTechnologies/zsh-autocomplete/commit/500fd8592b1935500510beeb955685c0531965a9

i am not sure how to calculate the y value as this breaks my prompt
```
  local -a reply=()
  print -nr $'\e[6n'
  IFS=$'\e[;' read -Asd R
  local -i y=$reply[-2]
  local -i pslines=${#${(%%)PS1}//[^$'\n']}
```

I tried to use BUFFERLINES but not sure.

**Comment by marlonrichert** [comment]
The problem is that normal `read` operations don't work while the Zsh Line Editor is active. You are limited to using only `read -q` or `read -k [<num>]`.

You need to be able to determine the vertical position of the cursor somehow. Using `$BUFFERLINES` would work only when the command line starts at the top of the screen.

**Comment by marlonrichert** [comment]
Actually, I just realized, even though we can no longer query the terminal for the cursor after `precmd`, we _can_ update the calculated screen to account for the new value of `$COLUMNS` on `line-pre-redraw`.

**Comment by marlonrichert** [comment]
Done.

**Comment by marlonrichert** [comment]
@MenkeTechnologies I found a better solution. Patch coming soon.™

**Comment by marlonrichert** [comment]
Nah, never mind; it didn't really work. The best solution is simply to press ⬇️. That will expand the menu as far as possible. 🙂
