### ISSUE TITLE
[Process completed] on any interaction with shell

### ISSUE THREAD

**Issue by japanese-goblinn** [marlonrichert/zsh-autocomplete#233]
* OS: macOS 11.2.1
* `zsh-autocomplete` version: last
* Zsh version: 5.8
* Framework: none
* Plugin manager: none

```zsh
$ git -C ~zsh-autocomplete switch main  # Make sure you test with the `main` branch.
$ git -C ~zsh-autocomplete pull         # Update to the latest commit.
$ cd $(mktemp -d)                       # Create a temp dir and enter it.
$ ZDOTDIR=$PWD HOME=$PWD exec zsh -f    # Restart Zsh without config files in this dir.
% source /path/to/zsh-autocomplete/zsh-autocomplete.plugin.zsh
% cd enythins/
zsh: .autocomplete.screen-space: function definition file not found
```

Added this plugin like this:
```bash
# .zshrc
source "$DOTFILES_DEPENDECIES_PATH/zsh-autocomplete/zsh-autocomplete.plugin.zsh"
```

Tried to manipulate with `fpath` but nothing worded :c

Also I saw #174 but clearing `.cache` not helped.

<img width="682" alt="Screenshot 2021-03-22 at 00 05 16" src="https://user-images.githubusercontent.com/33631005/111920836-49a7c980-8aa2-11eb-86d0-a09b7a5964af.png">

**Comment by marlonrichert** [comment]
> ```zsh
> $ git -C ~zsh-autocomplete switch main  # Make sure you test with the `main` branch.
> $ git -C ~zsh-autocomplete pull         # Update to the latest commit.
> $ cd $(mktemp -d)                       # Create a temp dir and enter it.
> $ ZDOTDIR=$PWD HOME=$PWD exec zsh -f    # Restart Zsh without config files in this dir.
> % source /path/to/zsh-autocomplete/zsh-autocomplete.plugin.zsh
> % cd enythins/
> zsh: .autocomplete.screen-space: function definition file not found
> ```
> 
Did you actually, literally do _all_ of the steps above? Because I am unable to reproduce it that way.

**Comment by japanese-goblinn** [comment]
@marlonrichert well, I've repeated this steps one more time and now I'm not getting any errors. May be you can provide any suggestions how to fix this in my environment? (I'm not using any frameworks or pluging managers, just sourcing stuff from .zshrc 😁)

**Comment by marlonrichert** [comment]
You can try commenting out lines from your `.zshrc` file until the problem disappears.
