### ISSUE TITLE
Don't tab-complete with 0 input

### ISSUE THREAD

**Issue by ChocolateOverflow** [marlonrichert/zsh-autocomplete#249]
## What do you want?

With blank input (nothing but white spaces) on a line, `<TAB>` should do nothing.

## Why do you want this?

I don't like how accidentally pressing `<TAB>` with nothing typed suggests *everything*, even with `zstyle ':autocomplete:*' min-input 1` set.

## Who else would benefit from this?

People who often accidentally press `<TAB>`.

## Explain in detail how you would expect this to work

I haven't type anything (besides maybe a space accidentally) and accidentally press `<TAB>`, don't give me suggestions.

**Comment by marlonrichert** [comment]
> pressing `<TAB>` with nothing typed suggests *everything*, even with `zstyle ':autocomplete:*' min-input 1` set.

I cannot reproduce that. Here's what I did:
```zsh
$ cd $(mktemp -d)
$ unset _comp_dumpfile ZDOTDIR XDG_CACHE_HOME XDG_CONFIG_HOME XDG_DATA_HOME
$ PS1='%# ' HOME=$PWD exec zsh -f 
% source /Users/marlon/Git/zsh-autocomplete/zsh-autocomplete.plugin.zsh
% mkdir foo bar 
% zstyle ':autocomplete:*' min-input 1
%
```
Then I pressed <kbd>Tab</kbd>. It inserts a tab. 

You probably have something else in your config that causes this behavior.

**Comment by ChocolateOverflow** [comment]
I've checked and found that the following setting seems to cause the 0-input tab-completion problem

```zsh
zstyle ':completion:*:complete:*:' tag-order '! ancestor-directories recent-directories recent-files' -
```

Removing the individual items in the `'! ...'` string doesn't seem to  solve the problem so I suspect it's the whole `tag-order` thing causing the issue.

**Comment by marlonrichert** [comment]
Try instead:
```zsh
zstyle ':completion:*:' tag-order '! ancestor-directories recent-directories recent-files' -
```

**Comment by ChocolateOverflow** [comment]
> `zstyle ':completion:*:' tag-order '! ancestor-directories recent-directories recent-files' -`

Still tab-completes with 0 input

**Comment by marlonrichert** [comment]
Sorry, but I cannot reproduce it. Here's what I did:

```zsh
$ cd $(mktemp -d)
$ unset _comp_dumpfile ZDOTDIR XDG_CACHE_HOME XDG_CONFIG_HOME XDG_DATA_HOME
$ PS1='%# ' HOME=$PWD exec zsh -f 
% source /Users/marlon/Git/zsh-autocomplete/zsh-autocomplete.plugin.zsh
% mkdir foo bar 
% zstyle ':completion:*:' tag-order '! ancestor-directories recent-directories recent-files' -
% zstyle ':autocomplete:*' min-input 1
%
```
Then I pressed <kbd>Tab</kbd>. It inserts a tab.

If you can use the above to make me a reproducible test case, then I'll reopen the issue.
