### ISSUE TITLE
Enabling autodescriptions by default

### ISSUE THREAD

**Issue by CadaverLab** [marlonrichert/zsh-autocomplete#25]
This isn't so much a bug report as it is a feature request: would it be possible to have groups and autodescriptions enabled by default as opposed to having to press shift+tab each time?
An option to have it always turned on would work too

**Comment by marlonrichert** [comment]
I don't want to enable it by default, but you can enable for yourself by adding the following to your `.zshrc` file _after_ sourcing `zsh-autocomplete`:
```shell
zstyle ':completion:*' format '%F{yellow}%d%f'
zstyle ':completion:*' group-name ''
```

I'll add this to the Customization section of the Readme, too. 🙂

**Comment by marlonrichert** [comment]
It's now in the Readme. Closing this issue.

**Comment by marlonrichert** [comment]
@CadaverLab 
I just wanted to let you know that 7256aeb adds a new way to make `zsh-autocomplete` show groups. Please see the Readme.
