### ISSUE TITLE
accidental raw key insertion when navigating command parameters

### ISSUE THREAD

**Issue by Aetherall** [marlonrichert/zsh-autocomplete#251]
* `zsh-autocomplete` version:  76ff7df91c9ec436d8f1c5b519d91fc426eae801
* Zsh version:  zsh 5.8 (x86_64-ubuntu-linux-gnu)
* Framework:  none
* Plugin manager:  none

```zsh
git -C ~zsh-autocomplete switch main  # Make sure you test with the `main` branch.
git -C ~zsh-autocomplete pull         # Update to the latest commit.
cd $(mktemp -d)                       # Create a temp dir and enter it.
unset _comp_dumpfile ZDOTDIR XDG_CACHE_HOME XDG_CONFIG_HOME XDG_DATA_HOME
HOME=$PWD exec zsh -f       # Restart Zsh without config files in this dir.
source /path/to/zsh-autocomplete/zsh-autocomplete.plugin.zsh
```

From there you can see two strange behaviours
For them to show up, type this command manually
`ls -H -H`
The unwanted behaviour is the not-found prompt, which make navigating difficult ( curl command edition etc)

**Comment by Aetherall** [comment]
Bisection revealed the faulty commit:
[2a838cb6ef05c9912569cf9f899087f02ecf0c87] Reintroduce fully fuzzy matching as a fallback

**Comment by Aetherall** [comment]
Sorry I've not been really precise

I noticed a strange behavior when moving my cursor backward when correcting a curl command.

The behavior was the insertion of `^D` characters when navigating across a header argument (-H)

I was able to reproduce it when typing `ls - H - H` in my terminal, and I noticed that when typing the second `-H`, zsh tried to look for possible matches within $PATH, and a key press on the arrow key inserted the key char into the prompt input

I tried on a clean Ubuntu docker image, with only zsh, git, and zsh-autocomplete, no zsh config

I will post a gif this weekend demonstrating the issue

**Comment by marlonrichert** [comment]
Closing this. If you can give me a working test case, I will reopen it.
