### ISSUE TITLE
Show autocompletion for command being aliased

### ISSUE THREAD

**Issue by J-E-Mc** [marlonrichert/zsh-autocomplete#252]
## What do you want?
make it so that aliased commands show autocompletion

## Why do you want this?
i have `ls`, `ll` and `la` aliased to `exa`, `exa -l` and `exa -a` respectively and i want this to show the autocompletion as if i typed those commands in

## Who else would benefit from this?
anyone who uses aliases

## Explain in detail how you would expect this to work
Given the following situation:

When I perform the following steps:
1. If I have `alias ls=exa` in my .zshrc
1. I type in `ls -` into the prompt

Then I expect the following to happen:
It should display the same autocompletion suggestions as if i typed `exa -` instead

**Comment by marlonrichert** [comment]
Done.
