### ISSUE TITLE
Insert unambiguous on blank arguament

### ISSUE THREAD

**Issue by J-E-Mc** [marlonrichert/zsh-autocomplete#253]
## What do you want?
Insert unambiguous with blank arguament

## Who else would benefit from this?
People who use insert unambiguous in directories with files that all begin with the same substring (e.g. log directories)

## Explain in detail how you would expect this to work
Given the following situation:
A directory contains many log files all beginning with `2021-`

When I perform the following steps:
typing `vim ` (including the space) and then pressing tab

Then I expect the following to happen:
the prompt completes to `vim 2021-`

**Comment by marlonrichert** [comment]
That's already implemented. [See the example in the included `.zshrc` file.](https://github.com/marlonrichert/zsh-autocomplete/blob/966312b149fb82a9d01144454de886b6a626ce69/.zshrc#L34)

**Comment by J-E-Mc** [comment]
I already looked through that and couldn't find anything that made it work with a blank arguament (I already have insert-unambiguous enabled)

**Comment by marlonrichert** [comment]
Works for me:
```zsh
% cd $(mktemp -d) 
% mkdir 2021-{1..999}
% zstyle ':autocomplete:*' insert-unambiguous yes
% vim <TAB>
% vim 2021-
```

**Comment by J-E-Mc** [comment]
found the issue, I was also using fzf-completion at the same time, it seems that the flags are incompatible

**Comment by marlonrichert** [comment]
The problem is that Fzf's "completion" feature does not use Zsh's completion system at all. So, it's not possible to use `zstyle` to change how that works. You'll have to tweak Fzf's settings instead.
