### ISSUE TITLE
Make `zstyle ':autocomplete:*' list-lines <num>` apply to history search

### ISSUE THREAD

**Issue by maarekj** [marlonrichert/zsh-autocomplete#255]
* `zsh-autocomplete` version: 966312b149fb82a9d01144454de886b6a626ce69
* Zsh version: ubuntu/5.8-3ubuntu1
* Framework: none
* Plugin manager: none
* 
```zsh
$ git -C ~zsh-autocomplete switch main  # Make sure you test with the `main` branch.
$ git -C ~zsh-autocomplete pull         # Update to the latest commit.
$ cd $(mktemp -d)                       # Create a temp dir and enter it.
$ unset _comp_dumpfile ZDOTDIR XDG_CACHE_HOME XDG_CONFIG_HOME XDG_DATA_HOME
$ HOME=$PWD exec zsh -f       # Restart Zsh without config files in this dir.
% source /path/to/zsh-autocomplete/zsh-autocomplete.plugin.zsh
% zstyle ':autocomplete:*' list-lines 32
% echo 1
% echo 1
% # many times
% echo 1
% # press up key
```

![Capture d’écran de 2021-05-14 14-40-46](https://user-images.githubusercontent.com/1654977/118272179-82708780-b4c2-11eb-9c69-09d255f80379.png)

As you can see on the screenshot, there are only 16 lines displayed in history instead of 32

**Comment by marlonrichert** [comment]
Not a bug: History search is intentionally hard-capped at 16. But I can implement this as an enhancement. 🙂

**Comment by cathex-matt** [comment]
I noticed the same just today and was about to engage a discussion.

**Comment by crazy-matt** [comment]
I noticed the same just today and was about to engage a discussion.

**Comment by marlonrichert** [comment]
Done.

**Comment by maarekj** [comment]
Thank you @marlonrichert 
Good stuff.
