### ISSUE TITLE
Freezing and gobbling CPU when tab-complete on directory with space in name

### ISSUE THREAD

**Issue by ChocolateOverflow** [marlonrichert/zsh-autocomplete#256]
* zsh-autocomplete version: 966312b149fb82a9d01144454de886b6a626ce69
* Zsh version: zsh-5.8-0-g77d203f
* Framework: none
* Plugin manager: none

1. Have `zstyle ':autocomplete:tab:*' widget-style menu-select` set in `.zshrc`
2. Have a directory whose  name includes a space: `mkdir 'a b'`
3. Try to tab-complete after the directory name: `ls a\ b/<TAB>`
4. The process freezes and somehow eats up 12.5% of my CPU
5. Try to kill it with `ctrl+C` but only get the message `Killed by signal in compadd after 1s` and the terminal is still frozen
(With just an empty directory `a b`, the freeze stops after 1-2 seconds, but lasts much longer with more spaces in the name and/or more content to suggest)

```zsh
$ mkdir 'a b'
$ ls a<TAB><TAB>
# 1st <TAB> gives: a\ b/
# 2nd <TAB> freezes
```

**Comment by marlonrichert** [comment]
Sorry, but I cannot reproduce this. Here's what I did:
```zsh
$ git -C ~zsh-autocomplete switch main  # Make sure you test with the `main` branch.
$ git -C ~zsh-autocomplete pull         # Update to the latest commit.
$ cd $(mktemp -d)                       # Create a temp dir and enter it.
$ unset _comp_dumpfile ZDOTDIR XDG_CACHE_HOME XDG_CONFIG_HOME XDG_DATA_HOME
$ HOME=$PWD exec zsh -f       # Restart Zsh without config files in this dir.
% source /path/to/zsh-autocomplete/zsh-autocomplete.plugin.zsh
% mkdir 'a b'
% ls a<TAB><TAB>
```
No problem.

Also, did you see this message in the bug report template?

> ⚠️ DO NOT DELETE the template below. Instead, use it to put together a minimal test case with
which I can reproduce the bug. If I cannot reproduce the bug, then I cannot fix it!

It's there for a reason.
