### ISSUE TITLE
Odd key behavior

### ISSUE THREAD

**Issue by Ahira-hub** [marlonrichert/zsh-autocomplete#26]
Hello,
Upon first installation, this plugin runs like a dream. Rebooting my terminal (I'm using Kitty), there is very erratic behavior. It's almost like the it's stuck in a hotkey mode. For example:
I want to type "sudo". 
S: Just fine
u: is ignored (letter is not typed)
d: "do you want to display all 348 results?
o: same as above 
spacebar: same as above. 

I'm guess it's mistaking each key press for tab? Sorry if this doesn't make sense...I don't know a better way to explain it. 

Running Kubuntu 20.04.

**Comment by marlonrichert** [comment]
@Ahira-hub Can you paste me a copy of your `.zshrc` file? Then I can try to reproduce the problem.

**Comment by Ahira-hub** [comment]
Sure thing. It's pretty simple at this point as I just started

# Load Antigen
source /usr/share/zsh-antigen/antigen.zsh

# Load the oh-my-zsh's library.
antigen use oh-my-zsh

# Path to your oh-my-zsh installation.
export ZSH="/home/ibrahiemk/.oh-my-zsh"

source $ZSH/oh-my-zsh.sh

#Antigen Themes
antigen theme  https://github.com/denysdovhan/spaceship-zsh-theme spaceship


#Antigen Bundles
#antigen bundle marlonrichert/zsh-autocomplete

# Tell Antigen that you're done.
antigen apply

**Comment by marlonrichert** [comment]
Thanks! It looks like this is a bug in Antigen: https://github.com/zsh-users/antigen/issues/703

Please ask them to fix it. 🙂 

In the meantime, you can work around it by installing `zsh-autocomplete` manually. See instructions over here: https://github.com/marlonrichert/zsh-autocomplete/blob/master/README.md#manually

**Comment by marlonrichert** [comment]
Or, if you want a plugin manager that actually works and is also faster than Antigen, try https://github.com/zdharma/zinit

**Comment by Ahira-hub** [comment]
See...this is funny. I was literally nuking antigen just before seeing this and installing zinit. I'm still  new-ish to this zsh stuff :). Thanks for the assist and great project!

**Comment by marlonrichert** [comment]
@Ahira-hub If you want some tips to get started, check out [my `.zshrc` file](https://github.com/marlonrichert/.config/blob/master/zsh/.zshrc).

**Comment by marlonrichert** [comment]
In particular, I recommend you ditch `ohmyzsh` and just use this instead:
```shell
zstyle ':prezto:*:*' color 'yes'
zinit light-mode for \
  https://github.com/sorin-ionescu/prezto/blob/master/modules/environment/init.zsh \
  https://github.com/sorin-ionescu/prezto/blob/master/modules/history/init.zsh \
  https://github.com/sorin-ionescu/prezto/blob/master/modules/directory/init.zsh
```

**Comment by Ahira-hub** [comment]
Thank you for the info and .zshrc file! I'm still trying to extract the SSH functionality from Z4H. I really like that script, but prefer to have more control over the rest. Your plugin doesn't work well with Z4H (same issue as antigen). So I'm trying to piece things together :)

**Comment by marlonrichert** [comment]
@Ahira-hub Can you please file a bug report with Z4H? I would love to know why this happens. Hopefully, it can be fixed.
