### ISSUE TITLE
Sometimes `^[[52;1R` gets printed inbetween prompts seemingly randomly

### ISSUE THREAD

**Issue by h0adp0re** [marlonrichert/zsh-autocomplete#261]
* `zsh-autocomplete` version: 405c29211047968516c9dbd9f41146976725462e
* Zsh version: `zsh-5.8-0-g77d203f`
* Framework: none
* Plugin manager: none

```zsh
$ git -C ~zsh-autocomplete switch main  # Make sure you test with the `main` branch.
$ git -C ~zsh-autocomplete pull         # Update to the latest commit.
$ cd $(mktemp -d)                       # Create a temp dir and enter it.
$ unset _comp_dumpfile ZDOTDIR XDG_CACHE_HOME XDG_CONFIG_HOME XDG_DATA_HOME
$ HOME=$PWD exec zsh -f       # Restart Zsh without config files in this dir.
% # hold return, you should get an uninterrupted stream of new prompts
% source /path/to/zsh-autocomplete/zsh-autocomplete.plugin.zsh
% # hold return, the prompts are no longer uninterrupted and sometimes `^[[52;1R` appears
```
I recorded it to maybe give a better idea of what's going on.

https://user-images.githubusercontent.com/11251772/118860441-11770880-b8e4-11eb-8389-7f17e9039fff.mov

**Comment by marlonrichert** [comment]
Which terminal do you use? What is the value of `$TERM`?

**Comment by h0adp0re** [comment]
If you're asking about a terminal emulator, then I use Alacritty. My `$TERM` is set to `screen-256color`.

**Comment by marlonrichert** [comment]
And are you actually using `screen`? If not, that explains it.

**Comment by marlonrichert** [comment]
OK, that's interesting. I didn't know `tmux` works like that. So, what happens if you don't use `tmux`? Does the problem go away?

**Comment by marlonrichert** [comment]
No, don't do that. What I meant is, can you try running `zsh-autocomplete` in Alacritty _without_ starting `tmux`? Does it then work?

**Comment by marlonrichert** [comment]
OK, I will close this then. I have tried to reproduce it with `tmux` on Alacritty, but it works fine for me.
