### ISSUE TITLE
Error printed on first autocompletion menu: "couldn't create cache-dir /zsh/compcache"

### ISSUE THREAD

**Issue by tomKPZ** [marlonrichert/zsh-autocomplete#262]
This bug only repros when I set:
zstyle ':completion:*' extra-verbose true

The issue is that .autocomplete.config sets cache-path to "$XDG_CACHE_HOME/zsh/compcache", but my XDG_CACHE_HOME is not set.  According to the XDG spec [1], "If $XDG_CACHE_HOME is either not set or empty, a default equal to $HOME/.cache should be used."

[1] https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by marlonrichert** [comment]
> my XDG_CACHE_HOME is not set.

Are you sure? Because it gets set here: https://github.com/marlonrichert/zsh-autocomplete/blob/405c29211047968516c9dbd9f41146976725462e/module/.autocomplete.__init__#L43

**Comment by tomKPZ** [comment]
I'm sure.  I can see it's empty if I "echo $XDG_CACHE_HOME" at the end of my .zshrc.  I think the issue is that .autocomplete.__init__.precmd runs after .zshrc.

Also zsh-autocomplete should not be exporting XDG_CACHE_HOME/XDG_DATA_HOME.  It should just use "${XDG_CACHE_HOME:-$HOME/.cache}" where appropriate, or use "local" instead of "export".

**Comment by marlonrichert** [comment]
> I think the issue is that .autocomplete.init.precmd runs after .zshrc.

Yes, that is intentional.

> Also zsh-autocomplete should not be exporting XDG_CACHE_HOME/XDG_DATA_HOME. It should just use "${XDG_CACHE_HOME:-$HOME/.cache}" where appropriate, or use "local" instead of "export".

Sure, I can change that.

Anyway, I cannot reproduce this. Can you please use the [bug report template](https://github.com/marlonrichert/zsh-autocomplete/issues/new?assignees=&labels=bug&template=bug-report.md&title=) that you deleted when you created this issue to make a reproducible test case? It doesn't have this warning for nothing:
> ⚠️ DO NOT DELETE the template below. Instead, use it to put together a minimal test case with
which I can reproduce the bug. If I cannot reproduce the bug, then I cannot fix it!

**Comment by tomKPZ** [comment]
The repro steps are:
```zsh
$ git -C ~zsh-autocomplete switch main  # Make sure you test with the `main` branch.
$ git -C ~zsh-autocomplete pull         # Update to the latest commit.
$ cd $(mktemp -d)                       # Create a temp dir and enter it.
$ unset _comp_dumpfile ZDOTDIR XDG_CACHE_HOME XDG_CONFIG_HOME XDG_DATA_HOME
$ HOME=$PWD exec zsh -f       # Restart Zsh without config files in this dir.
% source /path/to/zsh-autocomplete/zsh-autocomplete.plugin.zsh
% zstyle ':completion:*' extra-verbose true
% l
```

Upon typing "l", I get "couldn't create cache-dir /zsh/compcache".  The error is not shown again.

The key to getting this to reproduce for me is ```zstyle ':completion:*' extra-verbose true```.

> > I think the issue is that .autocomplete.init.precmd runs after .zshrc.
> 
> Yes, that is intentional.

That explains why the issue is occurring.  At the time ```.autocomplete.config``` runs, ```XDG_CACHE_HOME``` is unset, which means [1]:
```zstyle ':completion:*' cache-path "$XDG_CACHE_HOME/zsh/compcache"```
will expand to:
```zstyle ':completion:*' cache-path "/zsh/compcache"```

[1] https://github.com/marlonrichert/zsh-autocomplete/blob/main/module/.autocomplete.config#L15

**Comment by marlonrichert** [comment]
> That explains why the issue is occurring.  At the time ```.autocomplete.config``` runs, ```XDG_CACHE_HOME``` is unset, which means [1]:
```zstyle ':completion:*' cache-path "$XDG_CACHE_HOME/zsh/compcache"```
will expand to:
```zstyle ':completion:*' cache-path "/zsh/compcache"```

Thanks. I can confirm that is indeed the case. Will fix.

**Comment by marlonrichert** [comment]
Fixed.

**Comment by tomKPZ** [comment]
Woo! Thank you very much for the fix!
