### ISSUE TITLE
Random numbers suggested for recent directories when using z

### ISSUE THREAD

**Issue by tomKPZ** [marlonrichert/zsh-autocomplete#263]
Here's an example of a suggestion when typing "cd":
$ cd
directory
dev/         docs/        mnt/         net/         pics/        tmp/         vids/
ancestor directory
home/
recent directory
1040                    ~/dev/forks/wlroots/    1274                    /usr/share/zsh/plugins/

I don't have any directories called "1040" or "1274".  I've attached my $HOME/.z for you to use to reproduce the issue:
https://pastebin.com/QBLuRrAw

**Comment by marlonrichert** [comment]
Which implementation of `z` do you use? The numbers come from its output. If that output has changed format, then I need to update my parsing code.

**Comment by tomKPZ** [comment]
I'm using oh-my-zsh ToT with plugins=(z ...).  If I just run "z", then I see the first 2 lines in the output:
```
997        /home/redacted/dev/forks/wlroots
1211       /usr/share/zsh/plugins
```
Which is suspiciously close to the recent directory suggestion:
```
recent directory
997                     ~/dev/forks/wlroots/    1211                    /usr/share/zsh/plugins/
```

**Comment by marlonrichert** [comment]
That's not suspicious at all. It's fairly obvious that the parsing fails somehow. However, I'm unable to reproduce it.

Again, can you please use the [bug report template](https://github.com/marlonrichert/zsh-autocomplete/issues/new?assignees=&labels=bug&template=bug-report.md&title=) that you deleted when you created this issue to make a reproducible test case? It doesn't have this warning for nothing, you know:
> ⚠️ DO NOT DELETE the template below. Instead, use it to put together a minimal test case with
which I can reproduce the bug. If I cannot reproduce the bug, then I cannot fix it!

**Comment by tomKPZ** [comment]
The repro steps are:

```zsh
$ git -C ~zsh-autocomplete switch main  # Make sure you test with the `main` branch.
$ git -C ~zsh-autocomplete pull         # Update to the latest commit.
$ cd $(mktemp -d)                       # Create a temp dir and enter it.
$ unset _comp_dumpfile ZDOTDIR XDG_CACHE_HOME XDG_CONFIG_HOME XDG_DATA_HOME
$ HOME=$PWD exec zsh -f       # Restart Zsh without config files in this dir.
% curl https://pastebin.com/raw/QBLuRrAw > .z
% source /usr/share/oh-my-zsh/plugins/z/z.plugin.zsh
% source /path/to/zsh-autocomplete/zsh-autocomplete.plugin.zsh
% 👉YOUR STEPS TO REPRODUCE👈 # Test and document the steps to reproduce the problem.
```

Replace ```/usr/share/oh-my-zsh/plugins/z/z.plugin.zsh``` with your real path.

**Comment by marlonrichert** [comment]
Thanks for the test data. I can reproduce it now and will fix it.

**Comment by marlonrichert** [comment]
Fixed.

**Comment by tomKPZ** [comment]
Thanks for fixing :)
