### ISSUE TITLE
Delays of 10s on mc (Midnight Commander) startup and broken shell

### ISSUE THREAD

**Issue by balta2ar** [marlonrichert/zsh-autocomplete#269]
* `zsh-autocomplete` version:  405c29211047968516c9dbd9f41146976725462e

* Zsh version:  zsh-5.8-0-g77d203f
* Framework:  none
* Plugin manager:  none
```
GNU Midnight Commander 4.8.26
Built with GLib 2.68.0
Built with S-Lang 2.3.2 with terminfo database
With builtin Editor
With subshell support as default
With support for background operations
With mouse support on xterm and Linux console
With support for X11 events
With internationalization support
With multiple codepages support
With ext2fs attributes support
Virtual File Systems:
 cpiofs, tarfs, sfs, extfs, ftpfs, sftpfs, fish, smbfs
Data types:
 char: 8; int: 32; long: 64; void *: 64; size_t: 64; off_t: 64
```

The problem is that when zsh-autocomplete is sourced in `~/.zshrc`, **mc takes 10s to startup (probably some timeout), and then internal shell doesn't work** (Ctrl-o is used to switch to internal shell and type commands).

I'm sorry but I'm having a hard time producing a minimal example. I commented out everything but zsh-autocomplete in `~/.zshenv`, other typical configuration files are empty or missing:
```bash
boltmsi% ls -l ~/.zshrc ~/.zshenv ~/.zlogin ~/.zprofile                                                         
ls: cannot access '/home/bz/.zlogin': No such file or directory                                                 
ls: cannot access '/home/bz/.zprofile': No such file or directory                                               
lrwxrwxrwx 1 bz bz 27 Sep 22  2019 /home/bz/.zshenv -> /home/bz/rc.arch/bz/.zshenv
lrwxrwxrwx 1 bz bz 26 Sep 22  2019 /home/bz/.zshrc -> /home/bz/rc.arch/bz/.zshrc

boltmsi% ls -l ~/rc.arch/bz/.zshrc ~/rc.arch/bz/.zshenv
-rw-r--r-- 1 bz bz  0 May 21 21:36 /home/bz/rc.arch/bz/.zshenv
-rw-r--r-- 1 bz bz 80 May 21 21:36 /home/bz/rc.arch/bz/.zshrc

boltmsi% cat /home/bz/rc.arch/bz/.zshrc
source $HOME/rc.arch/bz/thirdparty/zsh-autocomplete/zsh-autocomplete.plugin.zsh
```
It works fine when I do just this:
```zsh
$ cd $(mktemp -d)
$ HOME=$PWD exec zsh
$ mc
```
which probably means some other configuration files are read and affect zsh-autocomplete, but I'm not sure how to bisect them further. I'd appreciate if you could try it locally and maybe you could give me some tips on what I can do further to help you track it down.

If it helps, I have a piece of strace log of mc startup (`strace -o trace.log -f -t mc`). I removed most of it, and only left the block around the timeout: https://pastebin.com/raw/4gTS5rc1
If it's mc, perhaps it's something about precmd, but this is all I know...

**Comment by balta2ar** [comment]
By the way, it worked fine a very long time ago and I haven't updated for a while. I did git bisec, I started with some commit 7 months ago (127e44c) and finished here: c85f98fb75d7c8d0320f1dfc351448adbb335f64 is the first bad commit

**Comment by marlonrichert** [comment]
Thanks for the detailed info. I can reproduce it, but I don't yet have any idea what causes it. This will require some more investigation.

**Comment by marlonrichert** [comment]
Fixed.

Tip: You can speed up Midnight Commander's startup even more by adding this to your `.zshrc` file
```
[[ -v MC_SID ]] && return
```
and then put after it all things that you don't need inside `mc`.

**Comment by marlonrichert** [comment]
@balta2ar Actually, I just realized this is, in fact, a bug in Midnight Commander. Just try the following:
```zsh
$ cd $(mktemp -d)
exec env -i HOME=$PWD TERM=$TERM zsh -f 
% print -r "typeset -F SECONDS
print -nr \$'\e[6n'
IFS=\$'\e[;' read -Asd R -- reply
print \$SECONDS
" > .zshrc
% exec zsh
0.0557880000
% SECONDS=0; mc; print $SECONDS

11.5728380000
%
```

**Comment by marlonrichert** [comment]
@balta2ar I filed a bug report with Midnight Commander: https://midnight-commander.org/ticket/4253

**Comment by balta2ar** [comment]
Thank you for the investigation! Since it's a bug in mc and should be fixed on their side, should https://github.com/marlonrichert/zsh-autocomplete/commit/114c857d56e916ea942923cb2df4c7508a4926f7 be reverted? Because I'd like to have completions in mc subshell, I have mc running in most of my terminals, but until mc fixed it, I can do the same in my zshrc (conditionally loading zsh-autocomplete when not in mc).

**Comment by marlonrichert** [comment]
I pushed in a more subtle workaround. You should have a fast `mc` startup again. The only feature I disabled when `mc` is running is to query the terminal for the cursor position. Hence, under `mc`, the max autocompletion list length is always the full screen.
