### ISSUE TITLE
Simplify Customization Options

### ISSUE THREAD

**Issue by PSalant726** [marlonrichert/zsh-autocomplete#27]
I'm really enjoying this plugin; thanks for your hard work and continued attention!

As a suggestion, it would be nice to simplify the customization options using `ENV` variables set in a user's `.zshrc` file (likely before sourcing `zsh-autocomplete`). Some recommended variable names:
- Always show group names:
```sh
export ZSH_AUTOCOMPLETE_ALWAYS_SHOW_GROUP_NAMES=true
```
- Turn off automatic spelling correction:
```sh
export ZSH_AUTOCOMPLETE_AUTO_CORRECT_SPELLING=true
```
- Use tab to cycle matches:
```sh
export ZSH_AUTOCOMPLETE_CYCLE_WITH_TAB=true
```
- Use tab and shift-tab to navigate the menu:
```sh
export ZSH_AUTOCOMPLETE_NAVIGATE_WITH_TAB=true
```

I could see the last two conflicting with one another, but that could be called out in the `README.md`.

**Comment by marlonrichert** [comment]
Thank you for your kind praise! 🙇🏽‍♂️

About the feature request itself: I will have to think about it. 🙂

**Comment by weilbith** [comment]
I would love to have the tabbing. I must admit that I fail to adjust my keybinds to your widgets to achieve that... 🙈

**Comment by marlonrichert** [comment]
@PSalant726 @weilbith @Mallchad @romzie 
Starting with 7256aeb, you can configure `zsh-autocomplete` through Zsh's `zstyle` mechanism. Please see the Readme for the details.

**Comment by romzie** [comment]
Great job!

**Comment by romzie** [comment]
Does not seem to work for me

**Comment by marlonrichert** [comment]
Sorry, I somehow managed to commit the new code commented out. 🤦🏽‍♂️

I now pushed it in again, but not commented out this time. Please try again.

**Comment by weilbith** [comment]
Awesome. I love it. Thank you so much. :pray:

**Comment by romzie** [comment]
Works like a charm now, great job, thank you!

**Comment by cenk1cenk2** [comment]
Amazing this was also what I was looking for. Thanks for this great piece of work.
