### ISSUE TITLE
Feature Request: Verbose aliases

### ISSUE THREAD

**Issue by tomKPZ** [marlonrichert/zsh-autocomplete#272]
## What do you want?
Similar to https://github.com/marlonrichert/zsh-autocomplete/issues/161 for parameters, aliases should show their expansions when ```zstyle -T ":completion:${curcontext}:aliases" verbose```.

## Why do you want this?
OMZ plugins often add lots of aliases, like the popular ```git``` plugin.  The issue is it's sometimes difficult to tell which alias does what.   Does```gcl``` expand to ```git clone``` or ```git clean```?

## Who else would benefit from this?
Anyone using plugins that add aliases, especially the ```git``` plugin.  When using dotcommon [1] to analyze ```zshrc```s on github, the ```git``` plugin is by far the most popular OMZ plugin [2].

[1] https://github.com/Kharacternyk/dotcommon
[2] https://pastebin.com/Hmsc5eQn

## Explain in detail how you would expect this to work

When I perform the following steps:
1. Type ```gcl```

Then I expect the following to happen:
* The aliases are suggested as such:
```
gcl     -- git clone --recurse-submodules
gclean  -- git clean -id
```

**Comment by marlonrichert** [comment]
This is already implemented, although in a slightly different way: The expanded alias shows up as a separate command.
```zsh
% ls
alias
ls                                          \ls --group-directories-first -AFX        
```
Does this not work for you?

**Comment by tomKPZ** [comment]
It doesn't seem to work for me on Arch Linux.  The repro steps are:

```zsh
$ git -C ~zsh-autocomplete switch main  # Make sure you test with the `main` branch.
$ git -C ~zsh-autocomplete pull         # Update to the latest commit.
$ cd $(mktemp -d)                       # Create a temp dir and enter it.
$ unset _comp_dumpfile ZDOTDIR XDG_CACHE_HOME XDG_CONFIG_HOME XDG_DATA_HOME
$ HOME=$PWD exec zsh -f       # Restart Zsh without config files in this dir.
% source /path/to/zsh-autocomplete/zsh-autocomplete.plugin.zsh
% zstyle ':completion:*' verbose true # not sure which of these are necessary
% zstyle ':completion:*' extra-verbose true
% alias ls='ls --color=auto'
% ls
alias
ls
```

**Comment by tomKPZ** [comment]
I tested on macOS and now I'm getting the same results as you in https://github.com/marlonrichert/zsh-autocomplete/issues/272#issuecomment-846892332.  I'm using zsh 5.8 on both systems.

However, it still seems a bit buggy.  The alias only expands if you type the full thing.  I'm not sure if that's intentional, but it would be cool to have all of them expanded like with parameters.

There's some inconsistency in the way alias expansions are displayed/formatted:
```
% alias ls='ls --color=auto'
% alias lsa='ls -a'
% ls
alias
ls                  \ls --color=auto    lsa
% lsa
alias
ls -a  lsa
```

**Comment by marlonrichert** [comment]
@tomKPZ I submitted two patches to Zsh for this feature: 
* [Make `_expand_alias` more usable as a completer ](https://www.zsh.org/mla/workers/2021/msg01172.html)
* [Let 'extra-verbose' completion show alias values ](https://www.zsh.org/mla/workers/2021/msg01173.html)

**Comment by tomKPZ** [comment]
Wow, that's awesome!  I'll apply those patches to my zsh so I can try it out 🎉🎉

**Comment by tomKPZ** [comment]
This issue is resolved for me, so I'm closing it out.  Thanks again for the patches!
