### ISSUE TITLE
Unable to queue up slow commands

### ISSUE THREAD

**Issue by tomKPZ** [marlonrichert/zsh-autocomplete#279]
* `zsh-autocomplete` version: 7f44a6d94761b7404955ce360e9c76b906130ca0
* Zsh version: zsh-5.8-436-g0c14732
* Framework: Oh My Zsh

```zsh
$ cd ~zsh-autocomplete
$ git switch main       # Make sure you test with the `main` branch.
$ git pull              # Update to the latest commit.
$ cd $(mktemp -d)       # Create a temp dir and enter it.
$ # Restart Zsh without config files or environment variables in this dir:
$ exec env -i HOME=$PWD PS1='%# ' TERM=$TERM zsh -f
% source /path/to/zsh-autocomplete/zsh-autocomplete.plugin.zsh
% # Type the following rapidly: "sleep 1<Enter>ls<Enter>"
```

The ```ls``` command gets lost if it is typed while ```sleep 1``` is running.  Queueing up slow commands is useful when working with large repositories and it seems to work in all major shells (bash, zsh, fish).  The issue only reproduces when zsh-autocomplete is enabled.

**Comment by marlonrichert** [comment]
Fixed.

**Comment by tomKPZ** [comment]
Thanks for the fix!  However there seems to be a lingering issue.  With the patch, if I type ```sleep 1<Enter>ls<Enter>```  then I see ```ls<Newline>```, but I still have to press Enter to run the command.  The command should be run without additional input.

**Comment by marlonrichert** [comment]
Hm, I didn't realize it behaved like that. I'll look into it.

**Comment by marlonrichert** [comment]
Well, that was quite easy.

**Comment by tomKPZ** [comment]
Wow that was fast!  I can confirm it's working properly now, thanks again!
