### ISSUE TITLE
Errors after clean install with zimfw

### ISSUE THREAD

**Issue by hanschen** [marlonrichert/zsh-autocomplete#288]
* `zsh-autocomplete` version: e40c1318a30fd722f18ffa0ed99e20819ff60568
* Zsh version: zsh-5.8-0-g77d203f
* Framework: Zimfw
* Plugin manager: none

I'm trying out Zimfw and was interested in using this plugin. Reading other issues, it seems like the two should work well out-of-the-box (e.g. #37). However, after I installed and enabled this plugin, I get the following error after each line:

```
_zsh_highlight_call_widget: maximum nested function level reached; increase FUNCNEST?
```

If I disable `zsh-users/zsh-syntax-highlighting`, I instead get:

```
_zsh_highlight_widget_zle-line-init: job table full or recursion limit exceeded
```

Finally, if I disable `zsh-users/zsh-history-substring-search`, the error messages disappear.

Any fix for this? This may also be related to #283.

Here are my configs (clean install except for the addition of this plugin):

- .zlogin: https://github.com/zimfw/install/blob/9f1979eb3fb5e907a014d6c264b292044dcbb145/src/templates/zlogin
- .zshenv: https://github.com/zimfw/install/blob/9f1979eb3fb5e907a014d6c264b292044dcbb145/src/templates/zshenv
- .zshrc: https://github.com/zimfw/install/blob/9f1979eb3fb5e907a014d6c264b292044dcbb145/src/templates/zshrc

.zimrc:
```zsh
# Start configuration added by Zim install {{{
# -------
# Modules
# -------

# Sets sane Zsh built-in environment options.
zmodule environment
# Provides handy git aliases and functions.
zmodule git
# Applies correct bindkeys for input events.
zmodule input
# Sets a custom terminal title.
zmodule termtitle
# Utility aliases and functions. Adds colour to ls, grep and less.
zmodule utility

#
# Prompt
#
# Exposes to prompts how long the last command took to execute, used by asciiship.
zmodule duration-info
# Exposes git repository status information to prompts, used by asciiship.
zmodule git-info
# A heavily reduced, ASCII-only version of the Spaceship and Starship prompts.
zmodule asciiship

# Additional completion definitions for Zsh.
zmodule zsh-users/zsh-completions
# Enables and configures smart and extensive tab completion.
# completion must be sourced after zsh-users/zsh-completions
zmodule completion
# Fish-like autosuggestions for Zsh.
zmodule zsh-users/zsh-autosuggestions
# Fish-like syntax highlighting for Zsh.
# zsh-users/zsh-syntax-highlighting must be sourced after completion
zmodule zsh-users/zsh-syntax-highlighting
# Fish-like history search (up arrow) for Zsh.
# zsh-users/zsh-history-substring-search must be sourced after zsh-users/zsh-syntax-highlighting
zmodule zsh-users/zsh-history-substring-search
# }}} End configuration added by Zim install

zmodule marlonrichert/zsh-autocomplete
```

It doesn't seem to matter where I put `zmodule marlonrichert/zsh-autocomplete`.

**Comment by marlonrichert** [comment]
This is actually [a bug in `zsh-syntax-highlighting`](https://github.com/zsh-users/zsh-syntax-highlighting/issues/816) (or `add-zle-hook-widget`, depending on how you look at it). However, I will implement a workaround to prevent this from happening.

**Comment by marlonrichert** [comment]
Workaround implemented.

**Comment by hanschen** [comment]
Many thanks for the fix and for opening a bug against `zsh-syntax-highlighting`. I just noticed that [`fast-syntax-highlighting`](https://github.com/zdharma/fast-syntax-highlighting) seems to have the same bug - would it be possible to apply the same workaround for this plugin?

**Comment by marlonrichert** [comment]
Thanks for informing me. I filed a [bug with `fast-syntax-highlighting`](https://github.com/zdharma/fast-syntax-highlighting/issues/224). 

I just tested it and yes, I can easily apply the same workaround there.

**Comment by marlonrichert** [comment]
Workaround added.

**Comment by marlonrichert** [comment]
If you use my software on a regular basis, please consider [sponsoring me](https://github.com/sponsors/marlonrichert). 🙂
