### ISSUE TITLE
Feature Request: Show live man preview like in mbhynes/fzf-gcloud

### ISSUE THREAD

**Issue by naefl** [marlonrichert/zsh-autocomplete#290]
## What do you want?

Basically this  https://github.com/mbhynes/fzf-gcloud but everywhere :) the fuzzy search aspect is less important  (would be cool to enable though), less than the man preview. Would be awesome to have man completion on the right pane for everything 

## Why do you want this?
Will making learning new commands way easier. also seems very much in the spirit of this app and you already have some infos for the flags 

## Who else would benefit from this?
Rookies like me (:

**Comment by marlonrichert** [comment]
Won't fix. Showing man pages is not completion and thus out of scope for this plugin.

If you want an easy way to show help (man page or otherwise) for the command you are currently typing, add this to your `.zshrc` file:
```zsh
# Alt-H: Open `man` page (or other help) for current command.
unalias run-help
autoload +X -Uz run-help
zmodload -F zsh/parameter p:functions_source
autoload -Uz $functions_source[run-help]-*~*.zwc
```
