### ISSUE TITLE
Certain command and option combinations cause "do you wish to see all XX possibilites" instead of the nice menu

### ISSUE THREAD

**Issue by mike2point71** [marlonrichert/zsh-autocomplete#291]
* `zsh-autocomplete` version: a1ee18e7d640dbf0ca2ae48001d7d35e9e7080cc
* Zsh version: zsh-5.8-0-g77d203f
* Framework: oh-my-zsh
* Plugin manager: none
* Operating system: darwin20.0

 1. Paste the following into your terminal and <kbd>Enter</kbd>:
    ```zsh
    cd $(mktemp -d)
    git clone --depth 1 -- https://github.com/marlonrichert/zsh-autocomplete.git
    print '
    PS1="%# " PS2="  " RPS2="< %^"; setopt transientrprompt
    source zsh-autocomplete/zsh-autocomplete.plugin.zsh
    ' > .zshrc
    exec env -i HOME=$PWD TERM=$TERM SHELL=$SHELL $SHELL -d
    ```
 1. In the shell session created above, try to reproduce your problem and
    record all of it here:
    ```zsh
    Last login: Sun Jun 13 00:13:29 on ttys009
    ❯ cd $(mktemp -d)
    _zlua_precmd:1: exec format error: /Users/username/github/czmod/czmod
    ❯ git clone --depth 1 -- https://github.com/marlonrichert/zsh-autocomplete.git
    Cloning into 'zsh-autocomplete'...
    remote: Enumerating objects: 59, done.
    remote: Counting objects: 100% (59/59), done.
    remote: Compressing objects: 100% (54/54), done.
    remote: Total 59 (delta 0), reused 29 (delta 0), pack-reused 0
    Receiving objects: 100% (59/59), 1.60 MiB | 336.00 KiB/s, done.
    ❯ print '
    PS1="%# " PS2="  " RPS2="< %^"; setopt transientrprompt
    source zsh-autocomplete/zsh-autocomplete.plugin.zsh
    ' > .zshrc
    ❯ exec env -i HOME=$PWD TERM=$TERM SHELL=$SHELL $SHELL -d
    % rg -C
    zsh: do you wish to see all 36 possibilities (38 lines)? 
    ```

**Comment by marlonrichert** [comment]
It's a bug in Zsh: https://www.zsh.org/mla/workers/2021/msg00304.html

**Comment by mike2point71** [comment]
You're the man.  Love your plugin, and I can't believe you were able to respond with the exact thing so fast.

**Comment by hoteit** [comment]
hi. getting stuck with the same error when i mainly type "cd".  once I type "c" I get the do you wish to see all X possibilities. Is there any way to force certain keywords like "cd" to not attempt a menu popup?

**Comment by marlonrichert** [comment]
@hoteit I would like to reproduce that. Can you post a minimal test case?

**Comment by marlonrichert** [comment]
If anyone wants to submit a patch to Zsh for this, that would be great.

**Comment by shtolfensie** [comment]
I get the "do you wish to see all ..." prompt on any larger list of possible suggestions - e.g., after typing sudo, git, man. It started happening in commit 2c22ed0.
It happens on a fresh install, manual sourcing, clean shell (as described in the bug report template). On the previous commit it works as I would expect (shows an incomplete list with (MORE) at the bottom.

**Comment by marlonrichert** [comment]
@shtolfensie OK, I'm able to reproduce it now. I'll look into it.

**Comment by marlonrichert** [comment]
Fixed.

**Comment by marlonrichert** [comment]
Just to be clear, I fixed the problem pointed out by shtolfensie [in their comment](https://github.com/marlonrichert/zsh-autocomplete/issues/291#issuecomment-884141162), not the whole issue.

**Comment by marlonrichert** [comment]
This has now been fixed in Zsh with https://github.com/zsh-users/zsh/commit/b4dff9a8e85802afcd52e7798176ebeb5e662da9. No idea when that will be released.
