### ISSUE TITLE
Menu selection by number

### ISSUE THREAD

**Issue by Timoses** [marlonrichert/zsh-autocomplete#293]
## What do you want?

Display menu options prepended with a selection number which can be used by user to select option by typing the number.

## Why do you want this?

I am using voice programming and numbers are a great visual aid in selecting options.

## Who else would benefit from this?

Anyone who wants to type less.

## Explain in detail how you would expect this to work
Given the following situation:
* The autocompletion menu lists some options
* The options should be prepended by a uniquely identifiable number each (for the current menu display)
* If the user types further and the menu changes, the options' numbers are reassigned to the newly displayed options.
* Numbers should be displayed in a sorted manner.

When I perform the following steps:
1. 
1. Either:
    * when I type a number which matches an option (prepended by that number) and press 'tab' it completes with that selection
2. or
    * before typing a number and pressing 'tab' the user could be required to enter the "number selection mode" by pressing some key shortcut. 

Then I expect the following to happen:
* 
The option selected by the number and confirmed via 'tab' is autocompleted.

**Comment by marlonrichert** [comment]
Thanks for the suggestion, but that's better implemented in Zsh's completion system and thus out of scope for this project. You should make your suggestion on the [`zsh-workers` mailing list](https://zsh.sourceforge.io/Arc/mlist.html).
