### ISSUE TITLE
.autocomplete.async.timeout.fd-widget

### ISSUE THREAD

**Issue by YodaEmbedding** [marlonrichert/zsh-autocomplete#294]
* `zsh-autocomplete` version: ff84e8d2c987614083903723f933c921f0f16056
* Zsh version: /bin/zsh zsh-5.8-0-g77d203f
* Framework: Oh-my-zsh
* Plugin manager: zinit
* Operating system: linux-gnu

**Steps to reproduce:**

Create .zshrc:

```zsh
if [[ ! -f $HOME/.zinit/bin/zinit.zsh ]]; then
    mkdir -p "$HOME/.zinit" && chmod g-rwX "$HOME/.zinit"
    git clone https://github.com/zdharma/zinit "$HOME/.zinit/bin"
fi

source "$HOME/.zinit/bin/zinit.zsh"
zinit snippet OMZP::vi-mode
zinit light marlonrichert/zsh-autocomplete
```

Run a new shell and type:

```zsh
% read -r
wait a few seconds then hit enter

.autocomplete.async.timeout.fd-widget:zle:3: No handler installed for fd 15
.autocomplete.async.timeout.fd-widget:12: failed to close file descriptor 15: bad file descriptor

%
```

Appears to happen due to the vi-mode OMZ plugin.

**Comment by marlonrichert** [comment]
@YodaEmbedding Can you please add a reproducible test case _without_ `zinit`? It complicates things needlessly.

**Comment by YodaEmbedding** [comment]
Reproduce without zinit:

```zsh
% git clone --depth=1 https://github.com/ohmyzsh/ohmyzsh
% source ohmyzsh/plugins/vi-mode/vi-mode.plugin.zsh
% read -r
wait a few seconds then hit enter
%
.autocomplete.async.timeout.fd-widget:zle:3: No handler installed for fd 14
.autocomplete.async.timeout.fd-widget:12: failed to close file descriptor 14: bad file descriptor
%                   
```

**Comment by marlonrichert** [comment]
@YodaEmbedding It's a bug in `vi-mode.plugin.zsh` or `add-zle-hook-widget` (depending on how you look at it).

* [On line 20 in `vi-mode-plugin.zsh`](https://github.com/ohmyzsh/ohmyzsh/blob/e32d4b1e195f4c7777844beea97af42bd93434eb/plugins/vi-mode/vi-mode.plugin.zsh#L20), `_vi-mode-set-cursor-shape-for-keymap` always returns non-zero when `$VI_MODE_SET_CURSOR` is not equal to `true`.
* This causes [`zle-line-finish` on line 65](https://github.com/ohmyzsh/ohmyzsh/blob/e32d4b1e195f4c7777844beea97af42bd93434eb/plugins/vi-mode/vi-mode.plugin.zsh#L65) to always return non-zero.
* This in turn causes `add-zle-hook-widget` to [abort all other calls to `line-init` hooks after this one](https://github.com/zsh-users/zsh/blob/2912139261960da1229e49cd33f7ed90e8f37e99/Functions/Misc/add-zle-hook-widget#L53).

**Comment by marlonrichert** [comment]
I sent a question about it to the Zsh mailing list: https://www.zsh.org/mla/workers/2021/msg01330.html

**Comment by marlonrichert** [comment]
By the way, this could be fixed easily in `vi-mode.plugin.zsh`, as follows:
* Use `add-zle-hook-widget` instead of defining zle-xxx widgets directly.
* Make sure your hook widget functions always return zero, _unless you actually, intentionally want that all hooks that follow get canceled._

Please file a bug report with OhMyZsh about this. This problem not limited to just the `vi-mode` plugin. There are several other places in OhMyZsh where [previous hook widget are blindly overwritten](https://github.com/ohmyzsh/ohmyzsh/search?q=%22zle+-N+zle%22).
