### ISSUE TITLE
Semicolon not removed from hist completion (regression)

### ISSUE THREAD

**Issue by pcjmfranken** [marlonrichert/zsh-autocomplete#297]
* `zsh-autocomplete` version: Confirmed in `d11612a` and `b164ae7` (current `main`)
* Zsh version: 5.8
* Framework: none
* Plugin manager: none

Shell output:
```zsh
% git config --get remote.origin.url
https://github.com/marlonrichert/zsh-autocomplete.git
% git config --get remote.origin.url;
```

Reproduction steps:
1. Populate history by executing a command
2. Type the first word of the command again
3. Press <kbd>&uparrow;</kbd> to have it autocompleted from the history menu
4. Press <kbd>Space</kbd> and you will see that the semicolon is not removed

Possible regression because of:
> No need for a setting. The `;` is now automatically removed for all input except <kbd>Ctrl</kbd><kbd>Space</kbd> and <kbd>Alt</kbd><kbd>Space</kbd>.

_Originally posted by @marlonrichert in https://github.com/marlonrichert/zsh-autocomplete/issues/141#issuecomment-740064674_

Let me know if you require more info!

**Comment by marlonrichert** [comment]
Fixed.

**Comment by marlonrichert** [comment]
PS: If you enjoy using this software, please consider [becoming a sponsor](https://github.com/sponsors/marlonrichert). 🙂
