### ISSUE TITLE
No completion in /etc, magic space issue with sudo

### ISSUE THREAD

**Issue by romzie** [marlonrichert/zsh-autocomplete#30]
Just doing `cd /etc/` does not prompt me with any suggestions, even when pressing tab.
Works fine when disabling the plugin.

2nd problem (did not want to open another issue for that only):
Just type `cp x y` then use the arrows to go back to the beginning of the line.
Then add `sudo` and press space to add a real space : the `cp` disappears.

Precision: I have `cp` aliased to `cp -i`

**Comment by marlonrichert** [comment]
Wow, thanks. Those are really surprising issues (in the sense of, how can I not have noticed those myself?), but I can in fact reproduce them. Thanks for reporting them!

**Comment by marlonrichert** [comment]
@romzie It should be fixed now. Thanks again for reporting!

**Comment by romzie** [comment]
Yep, all fine now ! Thank you for the quick support !

**Comment by romzie** [comment]
I found another behavior I did not expect

When the window cannot contain all completion suggestions, none of them are displayed. Just tested with `cd /usr/share/` on fullscreen (all appears) and on half-screen (none appears but if I press tab I get a partial list).

I dont know if it is expected behavior

**Comment by marlonrichert** [comment]
Yes, this is expected behavior. Do you think it would make sense to show some kind of message instead?

**Comment by romzie** [comment]
One could think a directory is empty when it happens so personnally I would suggest having a message like zsh gives when there is too much items to display.
Something non interactive like "Too much (<count>) items to display.".

But what I think would be neat is to have a customizable maximum terminal height to display suggestions, and being able to display a partial list if not enough space, with a message on bottom line saying something like "X more items".
But maybe I should open another issue for this improvement suggestion and maybe it is not feasible, I dont know.

**Comment by marlonrichert** [comment]
Yes, please open another issue for this. This needs more thought. 🙂
