### ISSUE TITLE
max-lines has no effect

### ISSUE THREAD

**Issue by YodaEmbedding** [marlonrichert/zsh-autocomplete#300]
* `zsh-autocomplete` version: b164ae7bc70978131c2515bca4cb3bcaf3f95dbc
* Zsh version: /bin/zsh zsh-5.8-0-g77d203f
* Framework: none
* Plugin manager: none
* Operating system: Arch Linux

**Steps to reproduce:**

```zsh
cd $(mktemp -d)
git clone --depth 1 -- https://github.com/marlonrichert/zsh-autocomplete.git
print 'PS1="%# " PS2="  " RPS2="< %^"; setopt transientrprompt
zstyle ":autocomplete:*" max-lines 50%
zstyle ":autocomplete:list-choices:*" max-lines 50%
source ~/zsh-autocomplete/zsh-autocomplete.plugin.zsh
zstyle ":autocomplete:*" max-lines 50%
zstyle ":autocomplete:list-choices:*" max-lines 50%
' > .zshrc
SHELL==zsh
exec -c zsh -fc "HOME=$PWD SHELL=$SHELL TERM=$TERM exec $SHELL -d"
```

**Results**:

For a terminal window of size height=8 and width=32,

```zsh
% l
builtin command
let     limit   local   log
logout
external command
latexmk   libevdev-tweak-device
linguist  llvm-link
(MORE)
```

**Expected:**

```zsh
%
%
%
%
% l
builtin command
let     limit   local   log
(MORE)
```

**Comment by marlonrichert** [comment]
That’s because I removed the `max-lines` setting some time ago. Please use the [`list-lines` setting](https://github.com/marlonrichert/zsh-autocomplete/blob/b164ae7bc70978131c2515bca4cb3bcaf3f95dbc/.zshrc#L23) instead.

**Comment by vitaly** [comment]
Actually, `list-lines` still doesn't work:

* `zsh-autocomplete` version: b164ae7bc70978131c2515bca4cb3bcaf3f95dbc
* Zsh version: /usr/local/bin/zsh zsh-5.8-0-g77d203f
* Framework: zim
* Plugin manager: none
* Operating system: darwin19.6.0

~~~zsh
cd $(mktemp -d -t autest)
git clone --depth 1 -- https://github.com/marlonrichert/zsh-autocomplete.git
print "
PS1='%# ' PS2='  ' RPS2='< %^'; setopt transientrprompt
zstyle ':autocomplete:*' list-lines 2
source ~/zsh-autocomplete/zsh-autocomplete.plugin.zsh
" > .zshrc
exec env -i HOME=$PWD TERM=$TERM SHELL=$SHELL $SHELL -d     
~~~
% x
external command
x265             xar              xargs            xattr
xattr-2.7        xcode-select     xcodebuild       xcrun
xcscontrol       xcsdiagnose      xed              xgettext
xgettext.pl      xgettext5.18.pl  xgettext5.28.pl  xip
xjc              xminicom         xml2-config      xml2man
xmlcatalog       xmlif            xmllint          xmlto
xpath            xpath5.18        xpath5.28        xslt-config
xsltproc         xsubpp           xsubpp5.18       xsubpp5.28
xxd              xz               xzcat            xzcmp
xzdec            xzdiff           xzegrep          xzfgrep
xzgrep           xzless           xzmore
~~~

I have `list-lines` set to 8, but it frequently fills my whole screen with suggestions.

**Comment by vitaly** [comment]
I opened a new #302

**Comment by YodaEmbedding** [comment]
Is there a way to ensure that completions use only a maximum number/percentage of lines, and without shifting the completion to the top of the terminal window?

**Use case:** I often want to look at the previous command's output when crafting my new command.

```
% cat fruits.txt
apples
bananas
oranges
% l
builtin command
let     limit   local   log
(MORE)
```

In the above example, `max-terminal-lines-used=50%`, so I can comfortably view the contents of fruits.txt while writing my command, `ln -s apples oranges`.

**Comment by marlonrichert** [comment]
> I have `list-lines` set to 8, but it frequently fills my whole screen with suggestions.

Because your prompt is not at the bottom of the screen. If the space is already available, it will be filled.

**Comment by marlonrichert** [comment]
> Is there a way to ensure that completions use only a maximum number/percentage of lines, and without shifting the completion to the top of the terminal window?

Yes, the `list-lines` setting. [See here](https://github.com/marlonrichert/zsh-autocomplete/blob/a7f69c9ed25b33952d98b21c5196d92c16b65af0/.zshrc#L21) for examples.

**Comment by vitaly** [comment]
@marlonrichert Actually it frequently takes my prompt from the bottom of the screen to the top, completely wiping out the information above the command line.

**Comment by marlonrichert** [comment]
@vitaly How tall is your terminal? If it’s 16 lines or less, then that’s expect behavior. You can use `list-lines` to reduce this. If your terminal is more than 16 lines tall, then that’s a bug. If so, are you able to provide me with a reproducible test case?

**Comment by vitaly** [comment]
As I mentioned I have `list-lines` set to 8. I figured out what the problem is, or at least a direction to look. in short: `tmux`. Seems like terminal size detection fails inside tmux: https://www.loom.com/share/317c1da30aa54d7cb4b04bb156759aa8

**Comment by vitaly** [comment]
looks like `_autocomplete__buffer_start_line` is always `1` in side TMUX

**Comment by vitaly** [comment]
looks like there's no `terminfo[u6]` and `terminfo[u7] ]]` inside TMUX

**Comment by marlonrichert** [comment]
Thanks! I will have to think of some kind of workaround for it. In the meantime, can you please open a new issue for this? 🙂

**Comment by vitaly** [comment]
https://github.com/marlonrichert/zsh-autocomplete/issues/309
