### ISSUE TITLE
should complete exact prefix before fuzzy matches

### ISSUE THREAD

**Issue by vitaly** [marlonrichert/zsh-autocomplete#301]
* `zsh-autocomplete` version: b164ae7bc70978131c2515bca4cb3bcaf3f95dbc
* Zsh version: /usr/local/bin/zsh zsh-5.8-0-g77d203f
* Framework: zim
* Plugin manager: none
* Operating system: darwin19.6.0

| BTW, the above, imho, should be generated by a command

### the problem:

I'm very fast at the keyboard, and used to type ahead, not waiting for shell to catch up.

Since switching to `zsh-autocomplete`  shell frequently does something very unexpected.

Where it comes to autocompletion, there is a lot of 'muscle memory' and default expectation as to how such a system supposed to work. For example, if I type something that is an **exact prefix** of some completion, then I expect it to be used when I press tab. 

Here is an example:

I have 2 aliases `git-merged` which shows branches merged into current, and `git-clean-merged` which deletes those branches. I usually run `git-merged` first ;).
To my surprise, when I typed `git-mer<tab><enter>` it got `git-clean-merged` executed. 

Another frequent problem is when I need to change into a directory, and I type couple of first letters, knowing there are no other directories with the same prefix, then `<tab><enter>`, and then taken to some random unexpected place, because it got completed from history or something.

### test script: 
```zsh
cd $(mktemp -d -t autest)
git clone --depth 1 -- https://github.com/marlonrichert/zsh-autocomplete.git
print '
PS1="%# " PS2="  " RPS2="< %^"; setopt transientrprompt
alias git-merged=true
alias git-clean-merged=false
source ~/zsh-autocomplete/zsh-autocomplete.plugin.zsh
' > .zshrc
exec env -i HOME=$PWD TERM=$TERM SHELL=$SHELL $SHELL -d
```

### result
```zsh
% git-me
alias
git-clean-merged  git-merged
```
At this point (or even before the completion appears) if I press `tab` it will complete `git-clean-merged`, which I think is wrong, when an `exact prefix` completion exists.

**Comment by marlonrichert** [comment]
> BTW, the above, imho, should be generated by a command

Can you give examples of GitHub repos where this is done that way? I would like to see if there's any standard or conventions for this, instead of just making up my own.

**Comment by marlonrichert** [comment]
Implemented.

**Comment by marlonrichert** [comment]
PS: If you enjoy using this software, please consider [becoming a sponsor](https://github.com/sponsors/marlonrichert). 🙂

**Comment by vitaly** [comment]
> PS: If you enjoy using this software, please consider [becoming a sponsor](https://github.com/sponsors/marlonrichert). 🙂

done ;)

**Comment by vitaly** [comment]
> > BTW, the above, imho, should be generated by a command
> 
> Can you give examples of GitHub repos where this is done that way? I would like to see if there's any standard or conventions for this, instead of just making up my own.

No. I just think that instead of copy pasting commands to and from terminal, running something like `zsh-autocomplete-bug-report` would be more convenient ;)

**Comment by marlonrichert** [comment]
Sure, I can add some kind of command for that.
