### ISSUE TITLE
`list-lines` has no effect.

### ISSUE THREAD

**Issue by vitaly** [marlonrichert/zsh-autocomplete#302]
`list-lines` has no effect. I Initially commented on #300 but it's closed as `wontfix`, so I thought a new issue is better ;).

* `zsh-autocomplete` version: b164ae7bc70978131c2515bca4cb3bcaf3f95dbc
* Zsh version: /usr/local/bin/zsh zsh-5.8-0-g77d203f
* Framework: zim
* Plugin manager: none
* Operating system: darwin19.6.0

~~~zsh
cd $(mktemp -d -t autest)
git clone --depth 1 -- https://github.com/marlonrichert/zsh-autocomplete.git
print "
PS1='%# ' PS2='  ' RPS2='< %^'; setopt transientrprompt
zstyle ':autocomplete:*' list-lines 2
source ~/zsh-autocomplete/zsh-autocomplete.plugin.zsh
" > .zshrc
exec env -i HOME=$PWD TERM=$TERM SHELL=$SHELL $SHELL -d     
~~~

~~~zsh
% x
external command
x265             xar              xargs            xattr
xattr-2.7        xcode-select     xcodebuild       xcrun
xcscontrol       xcsdiagnose      xed              xgettext
xgettext.pl      xgettext5.18.pl  xgettext5.28.pl  xip
xjc              xminicom         xml2-config      xml2man
xmlcatalog       xmlif            xmllint          xmlto
xpath            xpath5.18        xpath5.28        xslt-config
xsltproc         xsubpp           xsubpp5.18       xsubpp5.28
xxd              xz               xzcat            xzcmp
xzdec            xzdiff           xzegrep          xzfgrep
xzgrep           xzless           xzmore
~~~

I have `list-lines` set to 8, but it frequently fills my whole screen with suggestions.

**Comment by marlonrichert** [comment]
You're misunderstanding what `list-lines` does. I've updated the [documentation](https://github.com/marlonrichert/zsh-autocomplete/blob/810deb896da7df1e6eb3cb2a8f227d3521f8bf89/.zshrc#L21) to make it more clear.

**Comment by vitaly** [comment]
is there a way to limit the maximum number of lines? often I have some information on the screen I intend to use in a command line, but autocomplete produces so much options that the command line goest to the top, so nothing is seen except command line and completions. this is quite inconvenient. besides, having full screen of completion options is useless anyway... too much.  especially on big screens.

**Comment by marlonrichert** [comment]
How many lines do you have in your terminal? By default, the prompt will be pushed up to the 16th line from the bottom at most. If it gets pushed up more than that, then that’s a bug.

You can use `list-lines` to override this behavior.
