### ISSUE TITLE
`insert-unambiguous` doesn't affect alias expansion

### ISSUE THREAD

**Issue by vitaly** [marlonrichert/zsh-autocomplete#304]
* `zsh-autocomplete` version: b164ae7bc70978131c2515bca4cb3bcaf3f95dbc
* Zsh version: /usr/local/bin/zsh zsh-5.8-0-g77d203f
* Framework: zim
* Plugin manager: none
* Operating system: darwin19.6.0

~~~zsh
% zstyle ':autocomplete:*' insert-unambiguous yes
% alias foobar-a=a
% alias foobar-b=b
% alias foobar-c=c
# type `foob<tab>`
% foobar-a
directory
zsh-autocomplete/
~~~

**Comment by marlonrichert** [comment]
Works for me. Here's what I did:
```zsh
% cd $(mktemp -d)
% print 'PS1="%# "; source /Users/marlon/Git/zsh-autocomplete/zsh-autocomplete.plugin.zsh' > .zshrc
% SHELL==zsh
% exec -c eval "HOME=$PWD SHELL=$SHELL TERM=$TERM exec $SHELL -d" 
% zstyle ':autocomplete:*' insert-unambiguous yes
% alias foobar-a=a
% alias foobar-b=b
% alias foobar-c=c
% foob<tab>
% foobar-
alias
foobar-a  foobar-b  foobar-c
```
Can you reproduce it with the steps above?

PS: Please don't ignore the bug report template (which I replicated above). It's there for a reason. Kindly follow the steps as instructed.

**Comment by vitaly** [comment]
it works in the last version.
