### ISSUE TITLE
Shell quits when attempting autocompletion of non-existing path before min-delay expires 

### ISSUE THREAD

**Issue by Timoses** [marlonrichert/zsh-autocomplete#306]
* `zsh-autocomplete` version: a7f69c9ed25b33952d98b21c5196d92c16b65af0
* Zsh version: zsh-5.8-0-g77d203f
* Framework: none
* Plugin manager: antibody
* Operating system: MacOS

Shell closes when `zstyle ':autocomplete:*' min-delay 0.5` is set and one quickly presses `<TAB>` when typing e.g. `ls col` where `col` is not part of the current directory.

This only happens within the **0.5s** before autocomplete shows the autocomplete menu. If I wait after typing `ls col` until the autocomplete menu appears and then press `<TAB>` the error does not occur.

If I take out the option `min-delay` it does not happen regardless of how quickly I type `ls col<TAB>`.

This previously triggered #298

**Comment by marlonrichert** [comment]
I cannot reproduce this. Here's what I did:
```zsh
% cd $(mktemp -d)    
% git clone --depth 1 -- https://github.com/marlonrichert/zsh-autocomplete.git    
% print 'PS1="%# "; setopt transientrprompt; ~/zsh-autocomplete/zsh-autocomplete.plugin.zsh' > .zshrc
% SHELL==zsh    
% exec -c zsh -fc "HOME=$PWD SHELL=$SHELL TERM=$TERM exec $SHELL -d"    
% zstyle ':autocomplete:*' min-delay 0.5
% mkdir foo
% cd foo
% ls asdf<tab>
```
No crash.

PS: Next time, please don't delete the bug report's steps-to-reproduce template (which I used above). It's there for a reason.
