### ISSUE TITLE
How to stop zsh-autocomplete when I using `z`?

### ISSUE THREAD

**Issue by gauravnumber** [marlonrichert/zsh-autocomplete#312]
* `zsh-autocomplete` version: 3abe9dba037b681ab54131a1219a733f4abb9761
* Zsh version: /usr/bin/zsh ubuntu/5.8-3ubuntu1
* Framework: Oh My Zsh
* Plugin manager:  none
* Operating system: linux-gnu

 1. Paste the following into your terminal:
     ```zsh
     z <press SPACE>
     ```
 2. Then output looks like this:
![image](https://user-images.githubusercontent.com/75254747/127277890-82c4c8c1-b17c-4380-b257-1e152ace6da7.png)

How do I stop `zsh-autocomplete` when I using `z` command?

**Comment by marlonrichert** [comment]
I'm unable to reproduce this with the steps you've given.
