### ISSUE TITLE
Hide zsh-autosuggestions results when entering menu

### ISSUE THREAD

**Issue by tshu-w** [marlonrichert/zsh-autocomplete#317]
As metioned in https://github.com/marlonrichert/zsh-autocomplete/discussions/316

* `zsh-autocomplete` version: 20b332c172066daabf1476567daad983bb51fe56
* Zsh version: zsh-5.8-0-g77d203f
* Framework: none
* Plugin manager: Znap
* Operating system: darwin20.0

 1. Paste the following into your terminal and press <kbd>Enter</kbd>(**modified**):
    ```zsh
    cd $(mktemp -d)
    git clone --depth 1 -- https://github.com/marlonrichert/zsh-snap.git
    print 'PS1="%# " PS2="  " RPS2="< %^"; setopt transientrprompt
    source ~/zsh-snap/znap.zsh
    znap source zsh-users/zsh-autosuggestions
    znap source marlonrichert/zsh-autocomplete
    ' > .zshrc
    SHELL==zsh
    exec -c zsh -fc "HOME=$PWD SHELL=$SHELL TERM=$TERM exec $SHELL -d"
    ```
 1. Once you're able to reproduce your problem in the shell session created
    above, copy-paste the contents of your terminal here:
    ```zsh
    % brew update
    Already up-to-date.
    % brew # press down
    ```
<img width="1183" alt="Screen Shot 2021-08-02 at 14 05 19" src="https://user-images.githubusercontent.com/13161779/127811999-8ae8d5a0-e779-4dc8-a368-a4e08cc71f09.png">
<img width="822" alt="Screen Shot 2021-08-02 at 14 05 31" src="https://user-images.githubusercontent.com/13161779/127812062-87af1187-84f5-4f19-938e-1eefad141d9d.png">

**Comment by marlonrichert** [comment]
Thanks, I'm able to reproduce that.

**Comment by marlonrichert** [comment]
This appears to happen only when `zsh-autocomplete` is sourced _after_ `zsh-autosuggestions`.

**Comment by tshu-w** [comment]
Yes, maybe we should mention it somewhere.

**Comment by marlonrichert** [comment]
No, I can fix it. I'll upload a patch later today.

**Comment by tshu-w** [comment]
You are really so productive!

**Comment by marlonrichert** [comment]
Fixed.

---

PS: If you enjoy using my software, please consider [sponsoring me](https://github.com/sponsors/marlonrichert). 🙂

**Comment by tshu-w** [comment]
Done. Not a lot, a little regard ❤️

**Comment by tshu-w** [comment]
> PS: If you enjoy using my software, please consider [sponsoring me](https://github.com/sponsors/marlonrichert). 🙂

Done. Not a lot, a little regard ❤️
