### ISSUE TITLE
some command is executed without pressing enter when zsh-autocomplete enable

### ISSUE THREAD

**Issue by tshu-w** [marlonrichert/zsh-autocomplete#318]
* `zsh-autocomplete` version: 
* Zsh version: zsh-5.8-0-g77d203f
* Framework: none
* Plugin manager: Znap
* Operating system: darwin20.0

 1. Paste the following into your terminal and press <kbd>Enter</kbd>:
    ```zsh
    cd $(mktemp -d)
    git clone --depth 1 -- https://github.com/marlonrichert/zsh-autocomplete.git
    print 'PS1="%# " PS2="  " RPS2="< %^"; setopt transientrprompt
    source ~/zsh-autocomplete/zsh-autocomplete.plugin.zsh
    export PATH=/Users/wangtianshu/.local/bin:$PATH # add path for ec
    ' > .zshrc
    SHELL==zsh
    exec -c zsh -fc "HOME=$PWD SHELL=$SHELL TERM=$TERM exec $SHELL -d"
    ```
 1. Once you're able to reproduce your problem in the shell session created
    above, copy-paste the contents of your terminal here:
    ```zsh
    ec # type ec and space, focus on Emacs
    ```
Here is the content of my [ec](https://github.com/tshu-w/dotfiles/blob/main/local/bin/ec).
And here is a gif, you can see when I type `ec` and space, I switch focus to Emacs. This usually happens the first time I enter when I start a new zsh session.
![Kapture 2021-08-07 at 12 06 45](https://user-images.githubusercontent.com/13161779/128587405-a344e5e2-0d4b-4e5e-85dc-6d61e197b009.gif)

**Comment by K4LCIFER** [comment]
I have encountered the same issue with KiCAD. I'm guessing zsh is running `kicad --help` in the background to get the options list, but KiCAD doesn't have a help option, so running `kicad --help` ends up opening a file called `--help` in KiCAD.

**Comment by tshu-w** [comment]
Thanks for the tip, it seems to be the case, I'll try to add special handling to `--help`.

**Comment by tshu-w** [comment]
Thx @K4LCIFER, adding special judgments solves this issue. Any 
```
# Don't change focus with --help
if [ "$1" = "--help" ]; then
    emacsclient --help
    exit 0
fi
```
Other tips are welcome.

**Comment by marlonrichert** [comment]
> I'm guessing zsh is running `kicad --help` in the background to get the options list

@K4LCIFER Yes, that is exactly the case. I will have to remove that code and think if there’s a better way to handle that.

**Comment by marlonrichert** [comment]
@K4LCIFER @tshu-w Would perhaps some kind of blacklist feature be sufficient?

**Comment by marlonrichert** [comment]
Another idea would be to allow you to override per command how we should fetch help.

**Comment by tshu-w** [comment]
I think these two can be combined into one, if the override is left blank that is disabled.
