### ISSUE TITLE
"Unknown sort identifier".

### ISSUE THREAD

**Issue by yrammos** [marlonrichert/zsh-autocomplete#319]
* `zsh-autocomplete` version: `ca35064`
* Zsh version: `zsh-5.8-0-g77d203f`
* Framework: none
* Plugin manager: none
* Operating system: macOS 11.5.1

Unfortunately I'm not able to reproduce my issue with the "blank slate" of the template provided. This is driving me insane, though, so I'm taking the liberty to describe it and appeal for help.

My minimal `~/.zshrc` contains a single line:

```bash
source ~/zsh_plugins/zsh-autocomplete/zsh-autocomplete.plugin.zsh
```

I get a number of errors attempting to autocomplete. For instance, typing:

`$ cd /Appl` <kbd>tab</kbd>

I get:

```
_autocomplete.recent_dirs:9: unknown sort specifier
```

I find this quite bizarre and unfortunately am unable to pinpoint the commit that may have generated it. Would be grateful for any help.

**Comment by marlonrichert** [comment]
Which app are you using for “recent dirs”? The built-in default or something else?

**Comment by marlonrichert** [comment]
And is the problem with recent dirs only, or do you get the same problem otherwise, too? If so, can you post some more examples?

**Comment by yrammos** [comment]
@marlonrichert thank you for your lightning-fast response.

Before I attempt to answer your questions: I just noticed that, using the "blank slate" environment of your GitHub issue template, a new command line is generated on each keypress. For example, pressing <kbd>s</kbd> multiple consecutive times at the prompt, I get:

```
% s
...
% ss
…
% sss
...
% ssss
...
% sssss
...
% sssssss
```

**Comment by yrammos** [comment]
(Oh gosh, this second symptom might be a different issue, however, because it only occurs with the `xterm-kitty` terminal, not iTerm…)

**Comment by yrammos** [comment]
> And is the problem with recent dirs only, or do you get the same problem otherwise, too? If so, can you post some more examples?

It does not seem limited to recent dirs only. I just tried with a dir that I'm confident to have never cd'd do:

`$ cd ~/Pict` <kbd>tab</kbd> (attempting to enter `~/Pictures`)

In another similar case I got a different error:

`$ cd /Library/Op` <kbd>tab</kbd> (attempting to enter `/Library/OpenDirectory`)

`_autocomplete.recent_dirs:9: number expected`

**Comment by yrammos** [comment]
> Which app are you using for “recent dirs”? The built-in default or something else?

The built-in default.

**Comment by marlonrichert** [comment]
> > And is the problem with recent dirs only, or do you get the same problem otherwise, too? If so, can you post some more examples?
> 
> It does not seem limited to recent dirs only. I just tried with a dir that I'm confident to have never cd'd do:
> 
> `$ cd ~/Pict` <kbd>tab</kbd> (attempting to enter `~/Pictures`)
> 
> In another similar case I got a different error:
> 
> `$ cd /Library/Op` <kbd>tab</kbd> (attempting to enter `/Library/OpenDirectory`)
> 
> `_autocomplete.recent_dirs:9: number expected`

That is still the same error message, which shows a failure in trying to check for recent dirs that match your command line.

So, it's always the same error message, right?

Can you share your `.zshrc` file?

**Comment by yrammos** [comment]
My `.zshrc` is a single-liner:

```
source ~/zsh_plugins/zsh-autocomplete/zsh-autocomplete.plugin.zsh
```

**Comment by marlonrichert** [comment]
Can you try the following?
1. Run `functions -t _autocomplete.recent_dirs`.
2. Generate the error.
3. Go to `$XDG_DATA_HOME/zsh-autocomplete/log`.
4. Post the contents of the newest log file.

**Comment by yrammos** [comment]
Here is the resulting log.

I redacted various long lists of directories with the string `[space-delimited-list-of-directories]`.

[log.log](https://github.com/marlonrichert/zsh-autocomplete/files/6951541/log.log)

**Comment by marlonrichert** [comment]
It looks like you've filed this bug before: #182.

Can you run `git bisect` to find out which commit regressed it for you?

**Comment by marlonrichert** [comment]
Never mind: I already figured out what is the problem.

**Comment by marlonrichert** [comment]
Fixed.

---

PS: If you enjoy using my software, please consider [sponsoring me](https://github.com/sponsors/marlonrichert). 🙂

**Comment by yrammos** [comment]
Thank you, @marlonrichert. Fixed indeed!
