### ISSUE TITLE
Slow apt completion

### ISSUE THREAD

**Issue by romzie** [marlonrichert/zsh-autocomplete#32]
Awesome work you are doing, not a real issue but an improvement suggestion which would benefit the plugin I guess.

I noticed that when I type `sudo apt install`, and then the first 2 to 5 first letters of a package, the completion is really slow (which is normal, lots of packages exists).

The issue is that the input is lagging and therefore I cannot see what I type in real time, I have to wait a bit to check what I wrote.

This might be related to #17  and #24 , for the async part.

(btw I tried disabling completion for apt but did not succeed)
* I did not find a `/usr/share/zsh/functions/Completion/Unix/_apt` 
* I tried adding 
`zstyle ':completion:(correct-word|list-choices):*:(pacman|trizen):argument-rest:*' tag-order "! argument-rest" "-"`
to my zshrc but did not change anything

Would be neat to enable async list-choices for a few commands though :) for those heavy completion cases.

**Comment by marlonrichert** [comment]
@romzie When it hangs and you press Ctrl-C, what does it say?

**Comment by marlonrichert** [comment]
@romzie Also, can you do the following? Type until it hangs, then wait until you can move the cursor again, then press Ctrl-X and then H. What output do you get?

**Comment by romzie** [comment]
When it hangs and I ctrl-c it says `Killed by signal in _main_complete after ls`.
Ii does not hang for long so I did it another time and got `Killed by signal in _autocomplete.handle_long_list after ls`
Another time I got `Killed by signal in _deb_packages after 2s`

Doing this ctrl-c sometimes makes my zsh crash btw ^^

Well I get no output from doing ctrl-x then h. It justs removes the suggestions.
Maybe its different keybindings idk

**Comment by marlonrichert** [comment]
> Another time it hanged for longer and I got Killed by signal in _deb_packages after 2s

Bingo! That's the one we're looking for.

> Well I get no output from doing ctrl-x then h. It justs removes the suggestions.
Maybe its different keybindings idk

Try disabling `zsh-autocomplete` first and then, on the spot where it would normally get stuck, press Ctrl-X and then H.

**Comment by marlonrichert** [comment]
I just checked the source code of `_deb_packages` and it's supposed to do caching. Is it always slow or only at first?

For example, I use [Homebrew](https://brew.sh) as my package manager and it's usually slow at first, too, when I haven't accessed it for a while or try to access a function I haven't used before, but the second time it's faster.

It could be an idea to try to get it to build the cache in the background.

**Comment by romzie** [comment]
It does not feel like it is cached but it might be another thing causing the slowdown. Even when I delete characters it is slow. When I disable the plugin there is no slowdown.

from ctrl-x then h I get following output:
```
tags in context :completion::complete:apt::
    packages  (_apt-cmd_sm_sm _apt-cmd_sm _apt-cmd _apt)
    packages (_deb_packages _apt-cmd_sm_sm _apt-cmd_sm _apt-cmd _apt)
tags in context :completion::complete:sudo::
    argument-rest  (_arguments _sudo)
```

**Comment by marlonrichert** [comment]
Thanks. I'm first going to finish implementing #28, though. It might be that after that, this one becomes a non-issue. 🙂

**Comment by marlonrichert** [comment]
@romzie Is this an issue anymore, now that we have asynchronous completion?

**Comment by romzie** [comment]
Completion results are still slow to arrive but I doubt you can do anything so I am closing this.
