### ISSUE TITLE
args completion on nvim seems throwing errors

### ISSUE THREAD

**Issue by i3d** [marlonrichert/zsh-autocomplete#322]
* `zsh-autocomplete` version: 53ef40140a4bb210588e46532c588ad965542435
* Zsh version: /Users/jimxu/homebrew/bin/zsh zsh-5.8-0-g77d203f
* Framework: Oh My Zsh, Prezto
* Plugin manager: Zinit, zplug
* Operating system: darwin20.0

> Paste the following into your terminal and press <kbd>Enter</kbd>:
    ```zsh
    cd $(mktemp -d)
    git clone --depth 1 -- https://github.com/marlonrichert/zsh-autocomplete.git
    print 'PS1="%# " PS2="  " RPS2="< %^"; setopt transientrprompt
    source ~/zsh-autocomplete/zsh-autocomplete.plugin.zsh
    ' > .zshrc
    SHELL==zsh
    exec -c zsh -fc "HOME=$PWD SHELL=$SHELL TERM=$TERM exec $SHELL -d"
    ```
The above command kills my terminal session. I think it is due to exec -c.

without that, I could go into a new zsh session, which the local .zshrc.

> Once you're able to reproduce your problem in the shell session created above, copy-paste the contents of your terminal here:
```zsh
% # v .zsh<tab>                                                                                                                      
_arguments:comparguments:325: invalid option definition: -V[N]file[Verbose (level)(file)]
_arguments:comparguments:325: invalid option definition: -V[N]file[Verbose (level)(file)]
_arguments:comparguments:325: invalid option definition: -V[N]file[Verbose (level)(file)]
_arguments:comparguments:325: invalid option definition: -V[N]file[Verbose (level)(file)]
_arguments:comparguments:325: invalid option definition: -V[N]file[Verbose (level)(file)]
```

Here, 'v' is a custom command from a local script I created:

```zsh
#!/bin/zsh
exec nvim -u $HOME/.vimrc -XO "$@"
```

I put this little script under $HOME/bin and in my $PATH.

However, if I just call plain 'nvim .zsh<tab>' then tab doesn't trigger any error. On both cases, they will eventually still do command completion correctly.

**Comment by i3d** [comment]
actually, when the error is throw, the autocompletion no longer able to complete on command options but only seems history...

e.g. if I want to edit a file 'foo', which hasn't been in history before, then

v f<tab> will never give me the local file 'foo' (it just completes on history) .... but nvim f<tab> will.

**Comment by i3d** [comment]
ok, I have another linux box that also installed ZAC, and I tried on that it didn't manifest the issue, but then I did a git pull, which these changes

Updating 3abe9db..53ef401
Fast-forward
 module/.autocomplete.__init__    |  4 ++++
 module/.autocomplete.async       | 91 ++++++++++++++++++++++++++++++++++++++++++++++++-------------------------------------------
 module/.autocomplete.compinit    |  5 +++--
 module/.autocomplete.config      |  3 +++
 module/.autocomplete.recent-dirs | 29 ++++++++++++++++-------------
 utility/.autocomplete.patch      |  2 +-
 6 files changed, 75 insertions(+), 59 deletions(-)

and then tried again, and the issue manifested. So it's pretty clear the bug was introduced among these files.

**Comment by marlonrichert** [comment]
I am unable to reproduce your issue. Are you able to create a minimal test case for me in the following environment?
```zsh
cd $(mktemp -d)
git clone --depth 1 -- https://github.com/marlonrichert/zsh-autocomplete.git
print 'PS1="%# "; source ~/zsh-autocomplete/zsh-autocomplete.plugin.zsh' > .zshrc
HOME=$PWD ZDOTDIR=$PWD zsh -d
```

**Comment by marlonrichert** [comment]
> So it's pretty clear the bug was introduced among these files.

Can you run a `git bisect` to find out what was the exact commit that broke this for you?

**Comment by marlonrichert** [comment]
Can you update to 1be32b0 and see if that fixes the issue for you?

**Comment by marlonrichert** [comment]
Glad to hear that!

---

PS: If you enjoy using my software, please consider [sponsoring me](https://github.com/sponsors/marlonrichert). 🙂
