### ISSUE TITLE
disable "do you wish to see all N possibilities"

### ISSUE THREAD

**Issue by rwmitchell** [marlonrichert/zsh-autocomplete#329]
I have a short terminal window. Entering commands get interrupted with "do you wish to all all N possibilities".

To Reproduce

Create a short (6 rows) terminal window

type: ```alias[SPACE]```
zsh prompts with:
```zsh: do you wish to see all 194 possibilities (23 lines)?```

Expected behavior

Ideally I'd like to never see that prompt. If the screen size allows the information to be displayed, just display it. If it doesn't, indicate there are more options that can be displayed, but do not eat any input characters as that ruins the flow of what is b being typed.

An ideal solution would then allow a special keystroke to display all possibilities.

**Comment by marlonrichert** [comment]
> If the screen size allows the information to be displayed, just display it. If it doesn't, indicate there are more options that can be displayed, but do not eat any input characters as that ruins the flow of what is b being typed.

Yes, that’s exactly what `zsh-autocomplete` is trying to do. Do you think I’m trying to eat your keystrokes on purpose? 🙂

**Comment by marlonrichert** [comment]
> Create a short (6 rows) terminal window

How wide?

**Comment by rwmitchell** [comment]
>120, but the width is really very important, neither is the height.

I think the real issue is, the possible completions should only be shown when there is a slight pause in typing.

Regardless of terminal size, some completions are going to expand to enough options to generate the "do you wish to see" prompt.  When rapidly typing a command where the user isn't actually looking at the completions, the random prompt, which then eats a character, throws off getting the command correct.

A slight pause (user definable) is an indication the user is now thinking about what to type next and is appropriate to show possible completions.  Is there already an option to set such a timer?

**Comment by marlonrichert** [comment]
Yes, there is:
https://github.com/marlonrichert/zsh-autocomplete/blob/f59c44d981478632dd31dea1c5244e4a74244934/.zshrc#L11

**Comment by rwmitchell** [comment]
What is the unit? seconds, milliseconds, nanoseconds?

**Comment by marlonrichert** [comment]
It is all [documented in the file I linked to](https://github.com/marlonrichert/zsh-autocomplete/blob/main/.zshrc).
