### ISSUE TITLE
_async_zle_watcher:6: 2: parameter not set

### ISSUE THREAD

**Issue by euglevi** [marlonrichert/zsh-autocomplete#342]
* `zsh-autocomplete` version: last one
* Zsh version: 5.8
* Plugin manager: Znap
* Operating system: Ubuntu 20.10

I could not make bug template to work but I could easily reproduce my issue with this minimal zshrc configuration: 

```
source ~/.zsh/zsh-snap/znap.zsh

znap prompt sindresorhus/pure

znap source marlonrichert/zsh-autocomplete 

```
The error message I get as soon as I open the terminal is: 

`_async_zle_watcher:6: 2: parameter not set`

If I comment out one of the two plugins, the problem does not emerge. Is it a hint that it is an incompatibility issue? Is anyone else experiencing the same issue?

Thank you and great plugin!

**Comment by marlonrichert** [comment]
Fixed. 🙂

---

PS: If you enjoy using my software, please consider [sponsoring me](https://github.com/sponsors/marlonrichert). 💝
