### ISSUE TITLE
Simplification

### ISSUE THREAD

**Issue by drewauff** [marlonrichert/zsh-autocomplete#346]
I love what you have done, but it can be very overwhelming at times, so much so I had to disable it.

It literally shows everything, all the time. I doubt anyone would need it "all" all the time. To much to process.

I suggest the following:

- More options with regard to customisation (colours etc.)
- add the ability to set dir list depth, listing the whole system is just to much
- allow setting what it can show
- add setting so that only top ten recent dirs/files are listed, next to the names have an assigned number (1-0) the most 
frequently used at number 1 and least at 0 etc.

Thats it for now, I will edit this post if I come up with any more.

**Comment by marlonrichert** [comment]
> - More options with regard to customisation (colours etc.)

If you want to customize the colors, I recommend you use my [Z Colors](https://github.com/marlonrichert/zcolors) plugin.

> - add the ability to set dir list depth, listing the whole system is just to much

What do you mean with “listing the whole system”? Can you give an example of when it does that?

> - allow setting what it can show

No idea what you mean with that. Can you be more specific?

> - add setting so that only top ten recent dirs/files are listed, next to the names have an assigned number (1-0) the most frequently used at number 1 and least at 0 etc.

That’s an interesting an idea. I’ll give it some thought.

**Comment by drewauff** [comment]
on that last point, I use fasd and with that there is an interactive "mode" which does exactly what I suggested you but there are no theming options available nor will there ever be. Also i cant be piped through fzf. The fact that all you have to do is tap a number and thats it makes it appealing.

I will have a look at zcolors tonight. thank you for the suggestion.

As soon as you start typing you get programs, directories, flag completions etc. What I meant was a setting whereby you can choose to see only file or directories etc.

All people really need is the most recently used and the most frequently used programs/commands/dirs/flags, don't need to see the all at the same time so if I can configure to show, for example  (my case needs) :

- 25 Most recent directories
- 25 Most recent files
- 10 "Bookmarked" commands/programs
- command/program flags

I hope this is more clear for you.

keep up the awesome work

-
Andy

**Comment by marlonrichert** [comment]
I think most of this should be better by now. If there are specific things you still would like improved, please open a new issue for each point individually. It's easier to keep track of them that way, rather than having one big list in a single issue.

**Comment by marlonrichert** [comment]
> It literally shows everything, all the time. I doubt anyone would need it "all" all the time. To much to process.

Try adding this to your `.zshrc` file:
```zsh
zstyle ':autocomplete:*' min-delay 1.0  # seconds
```
Documented [here](https://github.com/marlonrichert/zsh-autocomplete/blob/b41b5635c3a6b11cc14c46e80f32c4c292c63539/.zshrc#L11).
