### ISSUE TITLE
Autocomplete selection doesn't work if command wraps over like

### ISSUE THREAD

**Issue by J-E-Mc** [marlonrichert/zsh-autocomplete#347]
If I type a command on one line that is long enough to have to wrap over to another line then I can't enter the completion menu

### Environment

```zsh
f208d04 (HEAD -> main, origin/main, origin/HEAD) Catch some more potentially unset parameters

/home/mcard/dotfiles/base/zsh/znap/zsh-snap/functions/.znap.source:23
/home/mcard/dotfiles/base/zsh/znap/zsh-snap/functions/.znap.source:26
/home/mcard/dotfiles/base/zsh/znap/zsh-snap/functions/znap:42
/home/mcard/.zsh/.zshrc:12

pc linux-gnu /usr/bin/zsh zsh zsh-5.8-0-g77d203f
```

### Steps to reproduce

```zsh
touch very_long_filename
# if very_long_filename wraps over to a different line then
# pressing any of the keys bound to down-line-or-select or menu-select
# will cause nothing to happen (except some terminal flickering)
rm very_long_filename
```

**Comment by marlonrichert** [comment]
Can you update your steps to reproduce with a concrete example with which I can actually reproduce it? Include any key presses that I need to make. 

Also, what terminal do you use?

**Comment by marlonrichert** [comment]
Never mind. I was able to reproduce it.

**Comment by marlonrichert** [comment]
@J-E-Mc It's fixed now. PS: If you enjoy using my software, please consider [sponsoring me](https://github.com/sponsors/marlonrichert). 🙂
