### ISSUE TITLE
Issue with the widget-style menu-select/menu-complete options

### ISSUE THREAD

**Issue by euglevi** [marlonrichert/zsh-autocomplete#358]
I did not succeed in using the bug template. However, I think you can reproduce this quite easily because the bug happens even with this minimal zshrc configuration:

```
source ~/.zsh/zsh-snap/znap.zsh
zstyle ':autocomplete:*' widget-style menu-select
znap source marlonrichert/zsh-autocomplete  

```

The issue is that when I try to enter the menu after "cd" - so to choose a directory - the following error message appears twice:
`.autocomplete.complete-word.post:12: array parameter mbegin set in enclosing scope in function .autocomplete.complete-word.post`
Then, I can still cycle in the menu to select my folder.

If I remove the widget-style option, the issue disappears.

Thank you so much for this nice plugin.

**Comment by marlonrichert** [comment]
Sorry, but I cannot reproduce it. Have you updated to the latest version?
