### ISSUE TITLE
Navigate menu selection items with `Alt-hjkl` key style 

### ISSUE THREAD

**Issue by volodymyrprokopyuk** [marlonrichert/zsh-autocomplete#359]
## What do you want?

Navigate items in the selection menu using `Alt-h`, `Alt-j`, `Alt-k` and `Alt-l` key combination in the same way the `right`, `down`, `up` and `left` cursor keys work. As I understand this is a matter of `bindkey -M menuselect 'Alt-h' menu-selection-command`, but I do not know 1) how to define `Alt-key` combination for the above keys and 2) what the exact menu selection command should I use (possibly `down-line-or-select` and `up-line-or-search`)

## Why do you want this?

By using the proposed key combinations (along with the existing cursor keys) the left hand does not have to be moved to the cursor keys and so is much faster, comfortable and convenient. A menu selection item can be chosen without moving the left hand from the main position on the keyboard

## Who else would benefit from this?

All the users that use vim and vi-style keybindings in other applications will want and benefit from the proposed enhancement

## Example scenario

Given the following situation:

* After entering the `cd` + `space` command a selection menu of possible directories is presented

When I perform the following steps:

1. When the `Alt+j` key combination is entered

Then I expect the following to happen:

*  The next item in the selection menu is chosen and highlighted (corresponding actions are taken for the rest of the `Alt+hjkl` key combinations`)

**Comment by marlonrichert** [comment]
Menu selection itself is not a feature `zsh-autocomplete`, but rather of `zsh`. `zsh-autocomplete` merely enables it and adds some sensible defaults. For information on how to customize it, please see [this section of the `zsh` manual](https://zsh.sourceforge.io/Doc/Release/Zsh-Modules.html#Menu-selection).
