### ISSUE TITLE
Async update causes flood of errors.

### ISSUE THREAD

**Issue by Mallchad** [marlonrichert/zsh-autocomplete#36]
As mentioned in #28 by @weilbith,
In the latest update has problem where 
`_autocomplete.async-list-choices:30: command not found: zpty                                         ─╯
_autocomplete.async-list-choices:31: command not found: zpty`
floods the console
I, also I should note that it doesn't actually prevent you from typing commands so you can just enter another shell and resolve the issue temporarily by rolling back the update. 
Failing that you can always switch to another user and change the shell/sudo.

**Comment by marlonrichert** [comment]
Whoops! 😅  This commit should fix it. Please update. @Mallchad @weilbith
