### ISSUE TITLE
Auto-remove dangling `;` behind last history line

### ISSUE THREAD

**Issue by adinklotz** [marlonrichert/zsh-autocomplete#361]
The pesky semicolons, as seen in #141 and #297, seem to be back. They are correctly removed on other characters, but not when pressing space

### Environment

```zsh
git -C ~zsh-autocomplete log --oneline -n1
print -l $_autocomplete__funcfiletrace
print $VENDOR $OSTYPE $SHELL $ZSH_ARGZERO $ZSH_PATCHLEVEL
```
e2ff14e (grafted, HEAD -> main, origin/main, origin/HEAD) Suppress a warning
/home/adin/.zsh/.zshrc:68
ubuntu linux-gnu /usr/bin/zsh -zsh ubuntu/5.8-3ubuntu1

### Steps to reproduce

```
% ls
zsh-autocomplete
% ls # press ↑
zsh-autocomplete
% ls -a # press ↑-a (semicolon is removed)
.  ..  .cache  .local  .zshrc  zsh-autocomplete
% ls; -a # press ↑↑ -a (note space after up, and semicolon is not removed)
zsh-autocomplete
zsh: command not found: -a
%
```
It's a little hard to see in text since it has to do with text changing as you type, so here's a clip

https://user-images.githubusercontent.com/16441122/138140681-32bd2e1c-b763-478a-9c62-a84cbe1cefb5.mp4

**Comment by adinklotz** [comment]
Is there, or could there be, a way to disable multiselection entirely then? I never use it, and would rather have sane semicolon behavior.

**Comment by marlonrichert** [comment]
Yes, I could add that.

**Comment by marlonrichert** [comment]
Actually, I just recalled that I can, in fact, auto-remove the `;`. It just has some visual bugs in the current version of `zsh`, but those should be fixed in the release.

**Comment by marlonrichert** [comment]
Done.

PS: If you enjoy using my software, please consider [sponsoring me](https://github.com/sponsors/marlonrichert). 🙂

**Comment by amomchilov** [comment]
Hey Marlon, pardon me if this is a silly question, but here goes:

Is there a config setting that fully removes the semi-colons, even prior to pressing space? I can't imagine when I'd need to repeat a command from history while also tacking on another command with `;`.

**Comment by marlonrichert** [comment]
> Is there a config setting that fully removes the semi-colons, even prior to pressing space?

No, there is no such config. Is this important somehow? Patches welcome. 🙂

> I can't imagine when I'd need to repeat a command from history while also tacking on another command with ;.

I use it quite often, actually, to put multiple history items into one command line.

**Comment by pcjmfranken** [comment]
Semis are not being removed from completions when you move to edit them. If you then complete this edited command, you end up with two trailing semis which is a no-op.

Perhaps leftwards cursor movements such as <kbd>←</kbd>, <kbd>HOME</kbd>, etc. could be added as semi-removal triggers similar to how <kbd>Space</kbd> works since fe20fc50b8ae1909441a10f2d8466f514d7c65fe?
