### ISSUE TITLE
per-directory-history

### ISSUE THREAD

**Issue by martaver** [marlonrichert/zsh-autocomplete#366]
## What do you want?
A way to constrain history to commands executed in CWD.

## Why do you want this?
Global command history is shared across terminals and history often ends up polluted with stuff that's irrelevant.
Plugins like `per-directory-history` solve this problem, by ensuring command history only cycles through commands that have been executed in the current directory.

Currently, if I use `zsh-autocomplete` then the behaviour of `per-directory-history` is overriden.

## Who else would benefit from this?
Any user who uses `per-directory-history` or one of its variants.

## Example scenario

Given the following situation:
I'm coding with one terminal and find some kind of problem with what I'm doing that's related to something in another directory.

When I perform the following steps:
1. I open up another terminal in the other directory, and proceed to debug.
1. Many commands to terminal ensue... 
1. Finally, after a long time I solve the problem, and open a terminal back in my original location. 

Then I expect the following to happen:
* In my original location, I want to re-run the last command, so I press up. 

...but history now contains all the debugging commands instead.

**Comment by martaver** [comment]
With a little closer inspection, if I use [`per-directory-history`](https://github.com/jimhester/per-directory-history), `zsh-autocomplete` does seem to read from different sources if I toggle with CTRL-G, however the local history broken: it always shows the same history regardless of directory/terminal. 

Maybe if this could be fixed, then `zsh-autocomplete` could be used harmoniously with `per-directory-history`.

**Comment by marlonrichert** [comment]
> Currently, if I use `zsh-autocomplete` then the behaviour of `per-directory-history` is overriden.

How? In what way? Can you give me a reproducible test case?

**Comment by marlonrichert** [comment]
I tested the `per-directory-history` plugin in a clean `zsh` environment, which I set up as follows:
```zsh
cd $(mktemp -d)
git clone --depth 1 -- https://github.com/jimhester/per-directory-history.git
> .zshrc <<EOF
source per-directory-history/per-directory-history.zsh
HISTFILE=$PWD/zhist
HISTSIZE=36
SAVEHIST=30
EOF
env -i HOME=$PWD PATH=$PATH FPATH=$FPATH TERM=$TERM zsh -d
```

It's _extremely_ buggy. I cannot get it to work correctly in vanilla `zsh` at all. The per-dir histories don't appear to get saved correctly.

Ergo, this should be fixed in the `per-directory-history` plugin. Please file an issue over there, using the setup I provided above.

**Comment by martaver** [comment]
Thanks for the quick response!

Actually, the reason I submitted this as a feature request was because
ultimately I'm just trying to constrain history to a directory, I don't
really care how it's done.

Do you think there's scope in zsh-autocomplete for it, or is this really
something that should be handled outside your plugin?

**Comment by marlonrichert** [comment]
It's out of scope for this plugin, but you're welcome to submit a feature request for it [in the `zsh-hist` repo](https://github.com/marlonrichert/zsh-hist).
