### ISSUE TITLE
Add a setting for limiting completions to a maximum number of lines

### ISSUE THREAD

**Issue by Lite5h4dow** [marlonrichert/zsh-autocomplete#368]
I cant seem to get the external command, ancillary manipulator command or main porcelain command to display only a few lines 

### Environment

```zsh
a364a84 (grafted, HEAD -> main, origin/main, origin/HEAD) Reduce number of files listed for `source` or `.`

pc linux-gnu /usr/bin/zsh -zsh zsh-5.8-0-g77d203f
```

### Steps to reproduce

1. edit .zshrc ,mine looks like this 
```zsh
#-----zsh-autocomplete-----
zstyle ':autocomplete:*' list-lines 5
zstyle ':autocomplete:history-search:*' list-lines 5
zstyle ':autocomplete:history-incremental-search-*:*' list-lines 5
zstyle ':autocomplete:*' min-input 1
zstyle ':autocomplete:*' fzf-completion yes
source ~/.config/zsh/plugins/zsh-autocomplete/zsh-autocomplete.plugin.zsh
```
2. start typing any command.
3. get this mess
![image](https://user-images.githubusercontent.com/18059545/141201942-cf1ec047-5e96-4a60-a0db-049d83f417de.png)
![image](https://user-images.githubusercontent.com/18059545/141202359-b363eaa6-7396-4e4f-aca4-0a0f88915b50.png)

**Comment by marlonrichert** [comment]
`list-lines` sets maximum number of lines to which to _grow_ if not all the lines fit on screen. If more lines will fit on screen, then `zsh-autocomplete` will use them.

**Comment by Lite5h4dow** [comment]
yeah, but i dont want it to fill the whole window though if its clear, because I clear my window a lot
how do i get it to not fill the whole window?

**Comment by Lite5h4dow** [comment]
if this isn't possible I will just uninstall it and leave you alone.

**Comment by marlonrichert** [comment]
> how do i get it to not fill the whole window?

Like I said, by typing more. 

Why is this so important? It won't stay there; it's just temporary.

> if this isn't possible I will just uninstall it and leave you alone.

Of course it's possible. You just have to implement it. Patches welcome. 🙂

**Comment by Lite5h4dow** [comment]
>why is this so important?
I don't like a full terminal in any way. I don't like useless information since the vast majority of suggestions arent useful. I don't like clutter.

**Comment by marlonrichert** [comment]
Not planning to implement this any time soon.

**Comment by yesthisisjoe** [comment]
Just thought I would chime in that I agree with @Lite5h4dow on this one. I would have thought that the "all" line limit setting would actually apply to **all** autocomplete types. it feels weird that this isn't included.

It's jarring that my window gets cleared whenever I type a git command. Unfortunately it's enough of an annoyance that I'll be disabling the plugin.

**Comment by marlonrichert** [comment]
I can see your point. I'll reopen this, but I don't really have time to implement it any time soon. Pull requests welcome! 🙂
