### ISSUE TITLE
warning: no such `suffix alias'

### ISSUE THREAD

**Issue by gex** [marlonrichert/zsh-autocomplete#369]
i updated to [8a538ff](https://github.com/marlonrichert/zsh-autocomplete/tree/8a538ff9a5cb30ac060fb4b4fa9d4ce8bb08ae3b) and since then when i start a new shell i see a ``no such `suffix alias'`` warning(?) all the time. screenshot with everything commented out in `.zshrc` (except this plugin of course):

<img width="263" alt="Screen Shot 2021-11-19 at 7 48 27" src="https://user-images.githubusercontent.com/15120752/142577805-3342a7d8-bad5-4d2a-ab2c-e8cd139b27af.png">

### Environment

```
% git -C ~zsh-autocomplete log --oneline -n1
8a538ff (HEAD -> main, origin/main, origin/HEAD) Don't pass -C flag to `compinit`
```

```
% print -l $_autocomplete__funcfiletrace

```

```
% print $VENDOR $OSTYPE $SHELL $ZSH_ARGZERO $ZSH_PATCHLEVEL
apple darwin20.0 /bin/zsh /bin/zsh zsh-5.8-0-g77d203f
```

**Comment by marlonrichert** [comment]
Fixed.

PS: If you enjoy using my software, please consider [sponsoring me](https://github.com/sponsors/marlonrichert). 🙂
