### ISSUE TITLE
Let most widgets remove trailing `;` from history lines

### ISSUE THREAD

**Issue by marlonrichert** [marlonrichert/zsh-autocomplete#370]
Semis are not being removed from completions when you move to edit them. If you then complete this edited command, you end up with two trailing semis which is a no-op.

Perhaps leftwards cursor movements such as <kbd>←</kbd>, <kbd>HOME</kbd>, etc. could be added as semi-removal triggers similar to how <kbd>Space</kbd> works since fe20fc50b8ae1909441a10f2d8466f514d7c65fe?

_Originally posted by @pcjmfranken in https://github.com/marlonrichert/zsh-autocomplete/issues/361#issuecomment-974411177_

**Comment by pcjmfranken** [comment]
PS I was looking into a reliable method for generating a trigger list, but most search results were StackOverflow posts on related matters written by you :)

**Comment by marlonrichert** [comment]
What, are you saying my SO posts are not reliable? 😉

> generating a trigger list

What do you mean by that?

**Comment by marlonrichert** [comment]
@pcjmfranken @amomchilov @adinklotz Done.

PS: If you enjoy using my software, please consider [sponsoring me](https://github.com/sponsors/marlonrichert). 🙂
