### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by 1Spinne** [marlonrichert/zsh-autocomplete#371]
When I activate the plugin, zsh crashes.
No error messages are displayed.

**Comment by marlonrichert** [comment]
Please follow the steps in the bug report template.

**Comment by 1Spinne** [comment]
Really?

**Comment by 1Spinne** [comment]
Is this a bot?

**Comment by 1Spinne** [comment]
Pls read my comment

**Comment by 1Spinne** [comment]
And description
