### ISSUE TITLE
I doesnt`t work

### ISSUE THREAD

**Issue by 1Spinne** [marlonrichert/zsh-autocomplete#372]
When I start the plugin, my zsh crashes
### Environment
zsh: no such user or named directory: zsh-autocomplete

### Steps to reproduce
It doesn't work in this shell only in the default.
The default shell just crashes without any error, when I run `znap source marlonrichert/zsh-autocomplete`

**Comment by 1Spinne** [comment]
I installed it with znap

**Comment by marlonrichert** [comment]
Closing this as not reproducible. I'll reopen it if you can provide me with a minimal, reproducible test case. If I cannot reproduce your problem, then I cannot fix it.
