### ISSUE TITLE
Support for fzy

### ISSUE THREAD

**Issue by JP-Ellis** [marlonrichert/zsh-autocomplete#373]
## What do you want?
I see there's support for fzf already, and I was wondering whether it would be possible to add support for [fzy](https://github.com/jhawthorn/fzy) too?  From what I understand, it can be mostly a drop-in replacement though I am not experienced with the development of Zsh plugins.

## Why do you want this?
I think the description from fzy's readme best describes why fzy might be good:

> fzy is faster and shows better results than other fuzzy finders.
> 
> Most other fuzzy matchers sort based on the length of a match. fzy tries to find the result the user intended. It does this by favouring matches on consecutive letters and starts of words. This allows matching using acronyms or different parts of the path.

## Who else would benefit from this?
Everyone who is already using fzf might enjoy the (perhaps subjective) improvements that fzy can offer.

**Comment by marlonrichert** [comment]
“Support” is a big word: I’m merely working around [`fzf`’s shaky shell “extensions”](https://github.com/junegunn/fzf/tree/master/shell) that some people use. `fzy`, however, doesn’t appear to ship with any widgets, keybindings or other shell code. So, there’s really not anything there to support. 

What exactly would you want me to support? Your issue doesn’t say.
