### ISSUE TITLE
Option to not expand command substitution?

### ISSUE THREAD

**Issue by jerryc05** [marlonrichert/zsh-autocomplete#374]
### Environment

```zsh
print $VENDOR $OSTYPE $SHELL $ZSH_ARGZERO $ZSH_PATCHLEVEL
print -l $_autocomplete__funcfiletrace
git -C ~zsh-autocomplete log --oneline -n1
```
```
ubuntu linux-gnu /usr/bin/zsh /usr/bin/zsh ubuntu/5.8-10
/home/jerryc05/.zinit/bin/zinit.zsh:1612
/home/jerryc05/.zinit/bin/zinit.zsh:1253
/home/jerryc05/.zinit/bin/zinit.zsh:2667
```

### Steps to reproduce
```
echo `head -n1 /dev/urandom`
```

Place cursor to the end of the backtick, and then press RIGHT ARROW multiple times, the content between the backticks is evaluated every time I press RIGHT ARROW.

This is not my expected behavior. One use case is when I run ``eval `ssh-agent` `` the command `ssh-agent` gets evaluated multiple times (whenever my cursor moves around the backticks)

**Comment by marlonrichert** [comment]
That should be easy to fix. In the meantime, as a workaround, add this to your `.zshrc` file:
```zsh
zstyle ':completion:*' substitute no
```
