### ISSUE TITLE
Brew formula

### ISSUE THREAD

**Issue by f-r-o-g** [marlonrichert/zsh-autocomplete#379]
## What do you want?
Install your fantastic autocomplete script via brew.

## Why do you want this?
Maintain most of my software lifecycle via brew MacOS or Linux. Also since znap is also not available via brew.

## Who else would benefit from this?
Everyone who uses zsh and brew.

**Comment by ShivamJoker** [comment]
I was just gonna write this 🤣 
I am waiting too not sure how to create one :)

**Comment by marlonrichert** [comment]
Please submit an issue or pull request to https://github.com/Homebrew/homebrew-core 🙂

**Comment by marlonrichert** [comment]
I'll leave this open in case someone else wants to do it or, god forbid, pay me for it. 😁

**Comment by ChristopherA** [comment]
Specifically, how much?

**Comment by marlonrichert** [comment]
Actually, I take that back: I realized I have no interest in doing that at all, not even for money. Sorry. 🙂
