### ISSUE TITLE
Asynchronous feature stopped plugin from working

### ISSUE THREAD

**Issue by weilbith** [marlonrichert/zsh-autocomplete#38]
Hey :wave: 

Thanks again for your continuous work. Especially the asynchronous feature makes this plugin a must-have! Unfortunately it does not work anymore for me. Which means it does not appear automatically anymore, but I must trigger the suggestions manually with `tab` again. Note that I configured the plugin to use `tab` and also do the suggestions appear grouped, as I also configured for this plugin. So the plugin is still there and somehow working. But not automated anymore.

So my local version is on commit 0260d55e28746b29a93f5c80ee0f20906b742c20 which is the `HEAD@master` here on GitHub for the moment. I tried to do a minimized setup, but this fails already. So how do I try to achieve a minimal testing environment for reproducibility:

```sh
> zsh -d -f  # zsh without any configuration
host% source $XDG_CACHE_HOME/antibody/https-COLON--SLASH--SLASH-github.com-SLASH-marlonrichert-SLASH-zsh-autocomplete/zsh-autocomplete.plugin.zsh
host% fpath+=($XDG_CACHE_HOME/antibody/https-COLON--SLASH--SLASH-github.com-SLASH-marlonrichert-SLASH-zsh-autocomplete)
host% cd ~/  # expect auto completion here
```

Of course can the location of the plugin differ. Since I use `antibody` as my zsh plugin manager that's how it looks for me. Anyways I load the plugin manually here, doing the same as `antibody` would do. The point is, that already the `source` command fails with the error message `(eval):1: _autocomplete.add-zsh-hook: function definition file not found`. I guess that's bad. :joy:
So if we could make it to fix this minimized setup, then I could continue to checkout if something else in my custom setup affects this problem.

Thank you so much in advanced. I want to experience the asynchronous completion
myself!!!!

**Comment by marlonrichert** [comment]
Hm, I can reproduce that, but I have no idea why it's not working. I'll have to investigate.

**Comment by marlonrichert** [comment]
@weilbith Alright, this should fix it. Please update.

**Comment by weilbith** [comment]
Cool. Thanks for the fix. Now I get the completion for the minimal zsh. Let's see why this is not working for my custom setup. :+1:

**Comment by marlonrichert** [comment]
@weilbith This should now be fixed on the `dev` branch. Please try it out.

**Comment by weilbith** [comment]
Jop works. I should consider to switch my plugin manager. Wasn't able to change branch for some reason (took no effect) and also not manually. Had to to it completely manually. Buuuut that is not the topic. ^^

Thanks for fixing it.
Could you give a quick headsup here when it is in `master`?

**Comment by marlonrichert** [comment]
I use https://github.com/zdharma/zinit as my plugin manager. Have a look at [my `.zshrc` file](https://github.com/marlonrichert/.config/blob/master/zsh/.zshrc) for an example of how to use it.

Yes, I will give you a heads-up. 🙂

**Comment by weilbith** [comment]
Yeah I'm aware of `zinit`. But since I was pretty happy with `antibody` so far and because `zinit` looks like an overkill, I hesitate to switch so far. But actually I like such powerful tools like `zinit`. Maybe I should invest the time to read the details and figure out how I can profit by them. For example which of my plugins could be lazy loaded etc.

**Comment by marlonrichert** [comment]
I'm keeping this issue open until I've merged to `master`. 🙂

**Comment by marlonrichert** [comment]
Most of `zinit`'s feature you don't really need. And if you want lazy loading, just use [Powerlevel10k's instant prompt feature](https://github.com/romkatv/powerlevel10k/blob/master/README.md#instant-prompt) which will cause (almost) your entire `.zshrc` to be lazily loaded.

**Comment by weilbith** [comment]
> just use Powerlevel10k's instant prompt feature 

I do :grimacing:

Unfortunately there is no comparison with `antibody`. But since I use the approach to trigger the plugin bundling manually and then just source that, I can barely believe it can become faster. For the "on-the-fly" bundle within the `.zshrc` I guess it is a different story.

**Comment by marlonrichert** [comment]
I have no idea what you mean with "plugin bundling". 🙂

The first time you call `zinit` on a plugin, it clones the repo, then sources it. Afterwards, it will just source it. It updates your plugins when you tell it to do so. Yeah, it can tell it to do a bunch of extra stuff whenever it clones, updates or sources a plugin, but that's optional.

**Comment by marlonrichert** [comment]
@weilbith It's in `master` now.
