### ISSUE TITLE
Option to not expand variables?

### ISSUE THREAD

**Issue by jerryc05** [marlonrichert/zsh-autocomplete#380]
### Environment

```zsh
print $VENDOR $OSTYPE $SHELL $ZSH_ARGZERO $ZSH_PATCHLEVEL
print -l $_autocomplete__funcfiletrace
git -C ~zsh-autocomplete log --oneline -n1
```
```
apple darwin20.1.0 /usr/local/bin/zsh /usr/local/bin/zsh zsh-5.8-0-g77d203f
# username hidden below
~/.zinit/bin/zinit.zsh:1620
~/.zinit/bin/zinit.zsh:1261
~/.zinit/bin/zinit.zsh:2675
~/.sh-zinit:6
~/.zshrc:43
```

### Steps to reproduce
- Suppose I have a shell variable that contains a very very long string (e.g. the `__conda_setup` variable from `conda init`)
- Now, type `$__con` and hit <key>Tab</key>. It will be autocompleted to `$__conda_setup`.
- Here is what goes wrong: 
  - It keeps popping up the prompt `zsh: do you wish to see all 1 possibilities (46 lines)?` every time I hit left arrow or right arrow.
  - If I do not respond with `n` or `y` and keep pressing arrow keys, my shell will automatically insert lots of `^[D`s or `^[C`s, which is extremely annoying.

```
$__conda_setup^[D^[D^[D^[D^[D^[D^[D^[C^[C^[C^[C
zsh: do you wish to see all 1 possibilities (48 lines)? 
```

**Comment by marlonrichert** [comment]
That behavior was a regression. It's fixed now.

PS: If you enjoy using my software, please consider [sponsoring me](https://github.com/sponsors/marlonrichert). 🙂
