### ISSUE TITLE
config.cache-path

### ISSUE THREAD

**Issue by Grohiik** [marlonrichert/zsh-autocomplete#389]
I'm like 90% sure this isn't actually a bug, but just me being stupid.  
But I have spent like WAY too much time trying to fix it or google for the answer so I guess I'm asking for help here  
I get some error about parameters not being set. It only happens when i source .zshrc never when first starting a terminal  
I'm on void, and at the bottom is my entier .zshrc, the issue dissapears if I remove `znap source marlonrichert/zsh-autocomplete`  

### Environment
```zsh
❯ print $VENDOR $OSTYPE $SHELL $ZSH_ARGZERO $ZSH_PATCHLEVEL
unknown linux-gnu /bin/zsh /bin/zsh zsh-5.8-0-g77d203f

❯ print -l $_autocomplete__funcfiletrace
/home/heart/.config/zsh/plugins/zsh-snap/functions/.znap.source:26
/home/heart/.config/zsh/plugins/zsh-snap/functions/znap:42
/home/heart/.zshrc:29

❯ git -C ~zsh-autocomplete log --oneline -n1
18a9bfb (grafted, HEAD -> main, origin/main, origin/HEAD) Show dotfiles if and only if `GLOB_DOTS` is set
```

### Steps to reproduce
```
cd $(mktemp -d)
git clone --depth 1 -- https://github.com/marlonrichert/zsh-autocomplete.git
> .zshrc <<EOF
PS1='%# ' PS2= RPS2='%^'; setopt transientrprompt interactivecomments
source ~/zsh-autocomplete/zsh-autocomplete.plugin.zsh
EOF
env -i HOME=$PWD PATH=$PATH TERM=$TERM ${TERMINFO:+TERMINFO=$TERMINFO} zsh -d

❯ source ~/.zshrc
_autocomplete.config.cache-path:1: array parameter reply created globally in function _autocomplete.config.cache-path
_autocomplete.config.completer:1: CURRENT: parameter not set
```

#### .zshrc
```
# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi


# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt autocd extendedglob
bindkey -e
# End of lines configured by zsh-newuser-install

# Enable p10k if suported
if [ `tput colors` = "256" ]; then
    source ~/powerlevel10k/powerlevel10k.zsh-theme
fi

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh


# Plugins
# source znap plugin manager
source ~/.config/zsh/plugins/zsh-snap/znap.zsh
znap source marlonrichert/zsh-autocomplete
#znap source zsh-users/zsh-history-substring-search

# non znap plugins
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh


# Path
path+=('/home/heart/.cargo/bin')

export PATH


# Aliases
alias config='/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME'
```

**Comment by marlonrichert** [comment]
> `unknown`

What kind of Linux do you use?

> ```zsh
> cd $(mktemp -d)
> git clone --depth 1 -- https://github.com/marlonrichert/zsh-autocomplete.git
> > .zshrc <<EOF
> PS1='%# ' PS2= RPS2='%^'; setopt transientrprompt interactivecomments
> source ~/zsh-autocomplete/zsh-autocomplete.plugin.zsh
> EOF
> env -i HOME=$PWD PATH=$PATH TERM=$TERM ${TERMINFO:+TERMINFO=$TERMINFO} zsh -d
> 
> ❯ source ~/.zshrc
> ```

You cannot have that kind of prompt if you followed the instructions above it. Please _actually_ follow the instructions, then report back here.

**Comment by Grohiik** [comment]
> What kind of Linux do you use?

Pretty sure I said, but Void Linux

> You cannot have that kind of prompt if you followed the instructions above it. Please actually follow the instructions, then report back here with the results.

I copied all the lines in one go as I assumed that would work it didn't apparently.  
Yeah I can't reproduce when copying it correctly  
Sorry for wasting your time
