### ISSUE TITLE
Expansion from CTRL+SPACE error with fuzzy file search

### ISSUE THREAD

**Issue by thaihugo** [marlonrichert/zsh-autocomplete#39]
Hi,

Thanks for your work on this plugin. I cannot get the expansion to work using ctrl space as I get this error message:
```
_autocomplete.expand-or-complete.zle-widget:43: maximum nested function level reached; increase FUNCNEST?
_p9k_widget_zle-line-pre-redraw:43: maximum nested function level reached; increase FUNCNEST?
```

For example, ctrl-space alone works (directory selection) but vim (space) ctrl-space shows the error.
Vim ** then ctrl-T works as ctrl-space should.

Here are the FZF options:
```
FZF_COMPLETION_TRIGGER='**'
FZF_DEFAULT_COMMAND='ag --hidden --ignore-dir /RetroPie/ -g ""'
FZF_DEFAULT_OPTS='--bind=ctrl-space:abort,ctrl-k:kill-line'
```

Is there something I'm missing?

**Comment by marlonrichert** [comment]
@thaihugo This should be fixed now. Please update. 🙂

**Comment by thaihugo** [comment]
Corrected. thanks for the fix.
