### ISSUE TITLE
_autocomplete.config.completer:1: CURRENT: parameter not set

### ISSUE THREAD

**Issue by geyang** [marlonrichert/zsh-autocomplete#400]
### Environment

```zsh
print $VENDOR $OSTYPE $SHELL $ZSH_ARGZERO $ZSH_PATCHLEVEL
print -l $_autocomplete__funcfiletrace
git -C ~zsh-autocomplete log --oneline -n1
```

4fd8a6c (grafted, HEAD -> main, origin/main, origin/HEAD) Fix link to `.autocomplete.config` in Readme

### Steps to reproduce

After a clean installation of oh-my-zsh, and following the installation instruction, in each new terminal session I get the following error:
```bash
_autocomplete.config.completer:1: CURRENT: parameter not set
```

**Comment by marlonrichert** [comment]
I'm unable to reproduce this. Here's what I did:
```zsh
% cd $(mktemp -d)
% > .zshrc <<EOF
PS1='%# '
EOF
% env -i HOME=$PWD PATH=$PATH TERM=$TERM TERMINFO=$TERMINFO zsh -d 
% sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
[...]
➜  ~ git clone --depth 1 -- https://github.com/marlonrichert/zsh-autocomplete.git
[...]
➜  ~ () { > .zshrc } <<< 'source zsh-autocomplete/zsh-autocomplete.plugin.zsh' < .zshrc
➜  ~ exec zsh
➜  ~ 
```

Please use the above template to provide me with a reproducible test case.

**Comment by marlonrichert** [comment]
Well, I'm sorry, but then that means the problem is not in the Zsh Autocomplete plugin. 🤷🏽‍♂️
