### ISSUE TITLE
Binaries get lost after sourcing zsh-autocomplete

### ISSUE THREAD

**Issue by soar** [marlonrichert/zsh-autocomplete#412]
## Environment
```zsh
apple darwin20.0 /bin/zsh /bin/zsh zsh-5.8-0-g77d203f

73b947d (HEAD -> main, origin/main, origin/HEAD) Update bug-report.md
```
* Operating system: macOS 11.6
* Terminal emulator: any (iTerm2, terminal, etc)

## Description

After sourcing zsh-autocomplete plugin completion doesn't work for most binaries in the system. If I try to add a function with the prefix like a name of a binary, this binary also becomes invisible for autocompletion.

### Example 1

Recorded in my live console with all plugins disabled

[![asciicast](https://asciinema.org/a/17l9iM4SGh5P6OxNtj6X1Cplq.svg)](https://asciinema.org/a/17l9iM4SGh5P6OxNtj6X1Cplq)

### Example 2

Recorded in a clean console

[![asciicast](https://asciinema.org/a/7F4RXrzA9IcYqckiyDIxiOBk6.svg)](https://asciinema.org/a/7F4RXrzA9IcYqckiyDIxiOBk6)

**Comment by marlonrichert** [comment]
I don't understand what problem you're trying to describe. Can you please provide steps to reproduce in a form that I can copy-paste into my terminal, without needing external dependencies?

**Comment by marlonrichert** [comment]
Closing, as I haven't heard back from @soar.
