### ISSUE TITLE
Cannot search history with less than min-input chars

### ISSUE THREAD

**Issue by ThinkChaos** [marlonrichert/zsh-autocomplete#413]
## Environment

```zsh
pc linux-gnu /nix/store/2lbh492826zha3s1ma8ma64a3ynz8l63-zsh-5.8/bin/zsh /nix/store/2lbh492826zha3s1ma8ma64a3ynz8l63-zsh-5.8/bin/zsh zsh-5.8-0-g77d203f
/home/me/.dotfiles/zsh/.zshrc:3
73b947d Update bug-report.md
```
* Operating system: NixOS
* Terminal emulator: Kitty

## Steps to reproduce
```zsh
zstyle ':autocomplete:*' min-input 3
# Try Ctrl-R now, doesn't work
```

**Comment by marlonrichert** [comment]
Thanks for reporting! Fixed.

PS: If you enjoy using my software, please consider [sponsoring me](https://github.com/sponsors/marlonrichert). 🙂

**Comment by ThinkChaos** [comment]
Thanks, just tested it and it works!

**Comment by marlonrichert** [comment]
@ThinkChaos PS: I maintain all of this in my free time. If you enjoy using my software, please consider giving back by [sponsoring me](https://github.com/sponsors/marlonrichert). 🙂
