### ISSUE TITLE
Lags on zsh 5.8.1

### ISSUE THREAD

**Issue by ad-on-is** [marlonrichert/zsh-autocomplete#416]
Is it just me, or did the recent zsh-update affect the performance of this plugin?
`zsh 5.8.1 (x86_64-pc-linux-gnu)` and Arch, btw.

I started noticing an extreme lag when typing.

**Comment by yutkat** [comment]
Temporary workaround
`git checkout 21.08.27`

**Comment by theol0403** [comment]
The prompt essentially freezes when typing, and pressing keyboard interrupt gives 
![image](https://user-images.githubusercontent.com/16546293/154126245-582ff88a-f0ae-4eb3-a18c-f7755b5a2543.png)

**Comment by marlonrichert** [comment]
Fixed.

**Comment by StefanLobbenmeier** [comment]
Just wanted to add details to make sure others find it as well:

in my case I noticed packagekitd to jump to 100% cpu usage after typing any character. Executing git pull in the zsh-autocomplete directory fixed the issue. 

(Searching for oh my zsh packagekitd  and zsh packagekitd  did not yield any results on google, hopefully this comment will now be indexed)

**Comment by marlonrichert** [comment]
@ad-on-is @jbro @glotchimo @AlexanderGunnarssonMW @theol0403 @mehanoid @Vysp3r @MartinJesusDev @hhlp @StefanLobbenmeier @ztNFny @YenLegion @hhlp

PS: I maintain all of this in my free time. If you enjoy using my software, please consider giving back by [sponsoring me](https://github.com/sponsors/marlonrichert). 🙂
