### ISSUE TITLE
zsh-autocomplete blocks after one character

### ISSUE THREAD

**Issue by ddddavidee** [marlonrichert/zsh-autocomplete#42]
I've probably some misconfiguration because I get some really annoying result when typing `ls` or `cd`: it stops after the first char asking if I want to see all the gazillions of possible completions. And of course it blocks.
[_zshrc.txt](https://github.com/marlonrichert/zsh-autocomplete/files/4736142/_zshrc.txt)
[_zsh_aliases.txt](https://github.com/marlonrichert/zsh-autocomplete/files/4736151/_zsh_aliases.txt)

**Comment by marlonrichert** [comment]
You have too many plugins and other customizations for me to be able to say what's the problem or to be able to test with. Can you please disable one by one to try to figure out where the problem lies? Then I can try to fix it.

**Comment by ddddavidee** [comment]
I'll try. But cannot tell when, sorry. We can close it for now.
