### ISSUE TITLE
Single-quotes in filenames are not escaped correctly when autocompleted

### ISSUE THREAD

**Issue by J-E-Mc** [marlonrichert/zsh-autocomplete#422]
## Environment

```zsh
unknown linux-gnu /bin/zsh zsh zsh-5.8.1-0-g1a490c7
/home/mcard/.local/zsh-snap/zsh-snap/functions/.znap.source:26
/home/mcard/.local/zsh-snap/zsh-snap/functions/znap:42
/home/mcard/.zshrc:3
7ab87cb (HEAD -> main, origin/main, origin/HEAD) Remove the Zsh version checks
```
* Operating system: Void Linux x86 glibc 
* Terminal emulator: foot 

## Steps to reproduce

```zsh
touch "test'"
# type up to the first quote and try to use autocomplete to complete the file name
ls 'test\''
```

expected result: `touch 'test\''`
i get: `touch 'test'\''`

**Comment by marlonrichert** [comment]
That’s not handled by this plugin, but by Zsh’s completion system. Please post a bug report on [the Zsh workers mailing list](https://zsh.sourceforge.io/Arc/mlist.html).
