### ISSUE TITLE
Crash on pressing up arrow to load history

### ISSUE THREAD

**Issue by the-argus** [marlonrichert/zsh-autocomplete#429]
## Environment
```zsh
print $VENDOR $OSTYPE $SHELL $ZSH_ARGZERO $ZSH_PATCHLEVEL
pc linux-gnu /bin/zsh /bin/zsh zsh-5.8.1-0-g1a490c7

print -l $_autocomplete__funcfiletrace

(no output)

git -C ~zsh-autocomplete log --oneline -n1
d6a0ff5 (HEAD -> main, origin/main, origin/HEAD) Fix a bug in async list trimming
```
* Operating system: Arch Linux
* Terminal emulator: Alacritty

## Steps to reproduce
The bug does not occur in the temp environment shell. If these means it is a problem  with the program I am using, I just need pointing in that direction.
Instead, I'll provide my config:
```zsh
# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
# setopt extendedglob
unsetopt autocd beep nomatch notify
bindkey -v
# End of lines configured by zsh-newuser-install

source ~/.aliases
source ~/.config/key-bindings.zsh
source /usr/share/zsh/plugins/zsh-autocomplete/zsh-autocomplete.plugin.zsh
source /usr/share/zsh/plugins/fast-syntax-highlighting/fast-syntax-highlighting.plugin.zsh

# minimum number of characters to type before autocomplete
zstyle ':autocomplete:*' min-input 1
# only insert up to common characters
zstyle ':autocomplete:*' insert-unambiguous yes
# dont move prompt up to make room for autocomplete very much
zstyle ':autocomplete:*' list-lines 4
# tab multiple times to move through menu
zstyle ':autocomplete:*' widget-style menu-select

eval "$(starship init zsh)"
```
and the steps to reproduce:
1.) install neofetch
2.) run ``neofetch --source``
3.) press the up arrow to return to the previous command.
The shell should crash and the terminal window should exit.

So far, to fix it, I've tried installing fzf, disabling ``insert-ambiguous``, disabling extended glob matching. and adding the ``source key-bindings.zsh`` line, which refers to the fzf key bindings. for zsh, which are needed for fzf support in this plugin. I did that because someone with a similar issue was told to do the same.

It's worth pointing out that when this problem occurs, the preceding commands are not appending to your zsh histfile. Additionally, although the example is with neofetch, I've noticed it happen intermittently before with other programs, but I can't remember what because I did not keep track of the early occurrences.

**Comment by marlonrichert** [comment]
Sorry, I'm unable to reproduce this. Try putting parts of your config into the bug report template until you have a reproducible test case. Alternatively, try commenting out parts of your config until the behavior disappears; then you will have found what causes it.
