### ISSUE TITLE
Throwing "no such file or directory" on .zcompdump

### ISSUE THREAD

**Issue by AlfredJKwack** [marlonrichert/zsh-autocomplete#433]
Hi,

On occasion I see the below error in my terminal.

`.autocomplete.compinit.precmd:11: no such file or directory: /Users/thomas/.zcompdump-PortaMac-5.8`

I've tried to trace it down and it looks like the below line is the one causing it.
https://github.com/marlonrichert/zsh-autocomplete/blob/d6a0ff574679280af52258ee6d2dcd3857283270/scripts/.autocomplete.compinit#L29-L30

The very odd thing is, `~/.zcompdump-PortaMac-5.8` is definitly present prior to the shell starting up.

This was run on an M1 mac with a fresh install of omz and plugins are all up to date.

**Comment by AlfredJKwack** [comment]
This might be relevant: I have iterm.app (and terminal. app) set to launch with multiple windows. Could this be a concurrency issue?

**Comment by marlonrichert** [comment]
> Could this be a concurrency issue?

That’s very well possible. I should update the code you posted to check whether the file exists, not just whether the variable has been set. 

Thanks for reporting!

**Comment by marlonrichert** [comment]
@AlfredJKwack It's fixed now. Also, if you enjoy using my software, please consider giving back by [sponsoring me](https://github.com/sponsors/marlonrichert). 🙂
