### ISSUE TITLE
Can config to only show different history?

### ISSUE THREAD

**Issue by phanthaiduong22** [marlonrichert/zsh-autocomplete#435]
## What do you want?

I want the history feature can only show different histories. Because duplicated histories is useless. We can remove duplicated, and can move up faster
<img width="377" alt="image" src="https://user-images.githubusercontent.com/30502963/165667126-b254d7bf-4873-4d2f-983a-4d5ce48ed240.png">

## Why do you want this?
For convenience quicker move up to get history I want

## Who else would benefit from this?
Everyone

## How should it work?

Given the following situation:
* 
*

When I perform the following steps:
1. 
1. 

Then I expect the following to happen:
* 
*

**Comment by pcjmfranken** [comment]
Alternatively you could prevent ZSH from creating any duplicate history entries in the first place: https://zsh.sourceforge.io/Doc/Release/Options.html#History
