### ISSUE TITLE
Don't work `down-line-or-select` in completion menu.

### ISSUE THREAD

**Issue by near129** [marlonrichert/zsh-autocomplete#440]
## Environment

```zsh
apple darwin21.3.0 /opt/homebrew/bin/zsh -zsh zsh-5.9-0-g73d3173
/Users/near129/.zshrc:1
5b0073d (grafted, HEAD -> main, origin/main, origin/HEAD) Check that `$ZSH_COMPDUMP` file can be read
```
* Operating system: macOS 12.3.1 (M1 Mac mini)
* Terminal emulator: iTerm2 3.4.15

## Steps to reproduce

```zsh
cd $(mktemp -d)
git clone --depth 1 -- https://github.com/marlonrichert/zsh-autocomplete.git
> .zshrc <<EOF
PS1='%# ' PS2= RPS2='%^'; setopt transientrprompt interactivecomments
source ~/zsh-autocomplete/zsh-autocomplete.plugin.zsh
bindkey '^N' down-line-or-select
EOF
env -i HOME=$PWD PATH=$PATH TERM=$TERM ${TERMINFO:+TERMINFO=$TERMINFO} zsh -d
```

I want to use `ctrl-n` in the same way as `down arrow key`. However, as shown in video blow, it don't work down line in the completion menu.

https://user-images.githubusercontent.com/56579877/170820875-c3ce73e2-c8ef-4495-ac00-ff817c6d20a6.mov

**Comment by marlonrichert** [comment]
Zsh Autocomplete intentionally tries to limit the number of key bindings it replaces. Overriding too many keybindings can cause conflicts between plugins and/or the user's own custom key bindings.

If you want to use <kbd>Ctrl</kbd><kbd>N</kbd> in the same way as <kbd>Down Arrow</kbd>, just add the following to your `.zshrc` file:
```zsh
bindkey '^N' down-line-or-select
```

**Comment by marlonrichert** [comment]
For the completion menu, you’ll need to add the following, too:
```zsh
bindkey -M menuselect '^N' down-history
```

See https://zsh.sourceforge.io/Doc/Release/Zsh-Modules.html#Menu-selection
