### ISSUE TITLE
Flatpak autocompletion

### ISSUE THREAD

**Issue by yellowhat** [marlonrichert/zsh-autocomplete#443]
## Environment

```zsh
$ print $VENDOR $OSTYPE $SHELL $ZSH_ARGZERO $ZSH_PATCHLEVEL
pc linux-gnu /bin/zsh /bin/zsh zsh-5.9-0-g73d3173

$ print -l $_autocomplete__funcfiletrace
/home/user/.cache/zsh-snap/functions/.znap.source:26
/home/user/.cache/zsh-snap/functions/znap:42
/home/user/.config/zsh/.zshrc:37

$ git -C ~zsh-autocomplete log --oneline -n1
5b0073d (grafted, HEAD -> main, origin/main, origin/HEAD) Check that `$ZSH_COMPDUMP` file can be read
```
* Operating system: Gentoo
* Terminal emulator: foot

## Steps to reproduce

```zsh
$ cd $(mktemp -d)
$ git clone --depth 1 -- https://github.com/marlonrichert/zsh-autocomplete.git
$ > .zshrc <<EOF
PS1='%# ' PS2= RPS2='%^'; setopt transientrprompt interactivecomments
source ~/zsh-autocomplete/zsh-autocomplete.plugin.zsh
EOF
$ env -i HOME=$PWD PATH=$PATH TERM=$TERM ${TERMINFO:+TERMINFO=$TERMINFO} zsh -d

$ nvim De<tab>esktop
$ flatpak run io.neovim.nvim De<tab>
no matching 'option' or 'argument' completions
```

I am not sure if this is a bug or a configuration issue.
Anyway if I run the `flatpak` version of `nvim`, `zsh-autocomplete` does not autocomplete files or folders.

Thanks

**Comment by marlonrichert** [comment]
I don't know from where you installed `flatpak` completion, but that is a bug in the completion function, not Zsh Autocomplete. `no matching 'option' or 'argument' completions` means that the completion function for `flatpak` is trying to complete options and arguments only, not files. Please file a bug report over there.
