### ISSUE TITLE
Get out from history menu without selecting anything

### ISSUE THREAD

**Issue by Arrow-x** [marlonrichert/zsh-autocomplete#446]
## What do you want?

When you are in history mode you have to select something, I want to hit Ctrl C to get out of the menu.
![image](https://user-images.githubusercontent.com/3308421/173898579-9f0d1a59-d047-409e-9133-ec70483c5819.png)

## Why do you want this?

the completion menu already has that feature, and I want to change my mind

## Who else would benefit from this?

anybody who was looking for something, didn't find it or changed their mind and want to quit

## How should it work?

a keybind that make get out of the menu and back to editing your line

**Comment by baudneo** [comment]
ESC works for me for this

**Comment by marlonrichert** [comment]
Thanks for the suggestion. I will add this. 

In the meantime, just add this to your `.zshrc` file:
```zsh
bindkey -M menuselect '^_' .undo
```

**Comment by marlonrichert** [comment]
@Arrow-x It's now implemented.

PS: If you enjoy using my software, please consider [sponsoring me](https://github.com/sponsors/marlonrichert). 🙂
