### ISSUE TITLE
Loading select-word-style breaks .autocomplete.zle-flags

### ISSUE THREAD

**Issue by knu** [marlonrichert/zsh-autocomplete#450]
## Environment
apple darwin21.3.0 /usr/local/bin/zsh /usr/local/bin/zsh zsh-5.9-0-g73d3173
f52f45a (HEAD, origin/main, origin/HEAD, main) Change precmd to chpwd for zlua
* Operating system: macOS
* Terminal emulator: iTerm2

## Steps to reproduce
1. Run `autoload -Uz select-word-style; select-word-style normal`
2. Type a few words (aaa bbb ccc)
3. Go to the beginning of the line
4. Do kill-word (M-d) twice
5. Paste (C-y)
6. See only the last word (` bbb`) get pasted instead of the last two concatenated (`aaa bbb`)

Without loading either select-word-style or zsh-autocomplete, I get the expected result.

**Comment by marlonrichert** [comment]
@knu Thanks for reporting. Since you know where the problem is, would you mind submitting a pull request? 🙂

**Comment by knu** [comment]
@marlonrichert Unfortunately I'm yet to identify where the problem is.   As long as I observe, select-word-style redefines the widgets `kill-word`/`backward-kill-word` but they should still match `*kill-*~vi-*`, so the "kill" flag should be set by `.autocomplete.zle-flags`. 🤔

**Comment by marlonrichert** [comment]
It's a bug in [`kill-word-match`](https://github.com/zsh-users/zsh/blob/master/Functions/Zle/kill-word-match). It relies on `$LASTWIDGET` to check if the last keystroke executed a kill command, but that doesn't work when a `zle-line-pre-redraw` hook widget has been installed. Please report it on the official [`zsh-workers` mailing list](https://zsh.sourceforge.io/Arc/mlist.html).

**Comment by marlonrichert** [comment]
As an alternative to `select-word-style`, I would recommend my [Zsh Edit plugin](https://github.com/marlonrichert/zsh-edit). It works a lot better than `select-word-style` in general.
