### ISSUE TITLE
breaks fzf kill/ssh/.. completion

### ISSUE THREAD

**Issue by ztNFny** [marlonrichert/zsh-autocomplete#46]
fzf has some special completions defined (see completion.zsh), e.g. for "kill -9 [TAB]" it uses ps to list the processes. With zsh-autocomplete that list is broken.

**Comment by marlonrichert** [comment]
@ztNFny I cannot reproduce this. `kill -9` followed by fzf-completion looks identical to me with and without `zsh-autocomplete`. Can you please update and try again? This might have been fixed already in 3980bb725a6c5ff17c14af20cf8105bc088d49a4.

**Comment by ztNFny** [comment]
@marlonrichert I'm on the latest version already.
With zsh-autocomplete:
![image](https://user-images.githubusercontent.com/1258173/83977770-5ee0ac80-a903-11ea-9ea4-8d58774aa118.png)
Without:
![image](https://user-images.githubusercontent.com/1258173/83977785-6e5ff580-a903-11ea-9d40-e437376211d6.png)

I can repoduce that with a minimal .zshrc:

source "$HOME/.zinit/bin/zinit.zsh"
autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit
zinit ice pick"shell/key-bindings.zsh" src"shell/completion.zsh"
zinit light junegunn/fzf
zinit light marlonrichert/zsh-autocomplete

**Comment by marlonrichert** [comment]
Ah, now I see. It's not broken. It's working as intended. When you press Tab with `zsh-autocomplete`, it never uses `fzf`. 🙂  If you want to use `fzf`'s completion with `zsh-autocomplete`, you need to press <kbd>Ctrl</kbd><kbd>Space</kbd>. Please see the Readme: https://github.com/marlonrichert/zsh-autocomplete/blob/master/README.md#with-fzf

**Comment by marlonrichert** [comment]
You can disable this behavior and keep the default `fzf` tab behavior by putting the following into your `.zshrc` file:
```shell
zstyle ':autocomplete:tab:*' completion fzf
```

**Comment by ztNFny** [comment]
is "zstyle ':autocomplete:" something that's defined by this plugin? I can only find information on "zstyle ':completion:" but not autocomplete

**Comment by marlonrichert** [comment]
`zstyle` is Zsh's mechanism for storing preferences. You can read more about it here: http://zsh.sourceforge.net/Doc/Release/Zsh-Modules.html#The-zsh_002fzutil-Module

**Comment by ztNFny** [comment]
that one i found, i was wondering about :autocomplete: specifically

**Comment by ztNFny** [comment]
what I'm trying to achieve is when I'm in the middle of a word to use zsh-autocomplete (e.g. "ls tes<TAB>") but with a space prefix to use fzf (e.g. "ls <TAB>") but I fail to see where in zsh-autocomplete.zsh that zstyle ':autocomplete:tab:*' completion fzf is handled to derive from it

**Comment by marlonrichert** [comment]
> that one i found, i was wondering about :autocomplete: specifically

That's the prefix/namespace I use for `zsh-autocomplete`.

**Comment by marlonrichert** [comment]
> what I'm trying to achieve is when I'm in the middle of a word to use zsh-autocomplete (e.g. "ls tes") but with a space prefix to use fzf (e.g. "ls ") but I fail to see where in zsh-autocomplete.zsh that zstyle ':autocomplete:tab:*' completion fzf is handled to derive from it

That sounds like a feature request to me. Please open a new issue for it. 🙂

**Comment by marlonrichert** [comment]
@ztNFny There's an issue for this now: #51. Let's discuss there.
