### ISSUE TITLE
zsh: do you wish to see all 201 possibilities (101 lines)?

### ISSUE THREAD

**Issue by manuelduarte077** [marlonrichert/zsh-autocomplete#460]
## Environment

```zsh
zsh: do you wish to see all 201 possibilities (101 lines)?
```
* Operating system:  macOS
* Terminal emulator: iTerm

## Steps to reproduce
I have that error every time I write in the terminal, let's say I put the letter s and I get that error

**Comment by marlonrichert** [comment]
Please use the bug report template to create a [minimal, reproducible test case](https://stackoverflow.com/help/minimal-reproducible-example). If I can’t reproduce your problem, then I cannot fix it.
