### ISSUE TITLE
Not able get `ignored-input` working

### ISSUE THREAD

**Issue by ragu-manjegowda** [marlonrichert/zsh-autocomplete#461]
I am not sure if this is a bug or just me not able to get this working.

I have `zstyle ':autocomplete:*' ignored-input '..##' # extended glob pattern` in my zshrc but I am not able disable auto-complete when I execute `..` or `..##` in the terminal.

For example, `.. cd` will still suggest directories to cd into.

I am using zsh and adding the plugin here - https://github.com/ragu-manjegowda/config/blob/master/.config/zsh/.zshrc#L28

Setting auto complete to disable here (ignore `;;` I was just playing around to make it work) - https://github.com/ragu-manjegowda/config/blob/master/.config/zsh/zsh-custom/plugins/custom-alias/custom-alias.plugin.zsh#L153

- [X] I have carefully read all of the instructions in this issue template.
- [X] I have carried them out to the letter.

Failure to do so can and will result in your issue being closed without warning.

## Environment
```zsh
* print $VENDOR $OSTYPE $SHELL $ZSH_ARGZERO $ZSH_PATCHLEVEL  
    pc linux-gnu /bin/zsh zsh zsh-5.9-0-g73d3173  

* print -l $_autocomplete__funcfiletrace  
    /home/ragu/.config/zsh/.zshrc:51  

* git -C ~zsh-autocomplete log --oneline -n1
    f52f45a (HEAD, origin/main, origin/HEAD, main) Change precmd to chpwd for zlua
```

* Operating system: 
    Arch Linux

* Terminal emulator: 
    Alacritty

- [X] I have filled out the fields above.
- [X] I have ran the commands in the code block above.
- [X] I have pasted their output into the same block. 

## Steps to reproduce
```zsh
cd $(mktemp -d)
git clone --depth 1 -- https://github.com/marlonrichert/zsh-autocomplete.git
> .zshrc <<EOF
PS1='%# ' PS2= RPS2='%^'; setopt transientrprompt interactivecomments
source ~/zsh-autocomplete/zsh-autocomplete.plugin.zsh
EOF
env -i HOME=$PWD PATH=$PATH TERM=$TERM ${TERMINFO:+TERMINFO=$TERMINFO} zsh -d
```
- [x] I have run the code block above to create a test environment.
- [x] I have reproduced my problem in this environment in the most minimal way possible.
- [x] I have copy-pasted my entire test session into the same code block.

**Comment by marlonrichert** [comment]
You checked the last checkbox, but I don’t see any output above it. Please add it and I’ll reopen the issue.

**Comment by ragu-manjegowda** [comment]
- [x] I have copy-pasted my entire test session into the same code block.

```
░▒▓     ~ ············································································································ 51s    1.82    19:23:09   ▓▒░
❯ cd $(mktemp -d)                                                                                                                                   97%  ▓▒░

░▒▓     /var/folders/_6/91slktdj2jl8qf0gmclbv0280000gn/T/tmp.hYK0MOi2 ························································· 1.91    19:25:08   ▓▒░
❯ git clone --depth 1 -- https://github.com/marlonrichert/zsh-autocomplete.git                                                                      96%  ▓▒░
Cloning into 'zsh-autocomplete'...
remote: Enumerating objects: 59, done.
remote: Counting objects: 100% (59/59), done.
remote: Compressing objects: 100% (55/55), done.
remote: Total 59 (delta 0), reused 24 (delta 0), pack-reused 0
Receiving objects: 100% (59/59), 1.64 MiB | 3.20 MiB/s, done.

░▒▓     /var/folders/_6/91slktdj2jl8qf0gmclbv0280000gn/T/tmp.hYK0MOi2 ························································· 1.88    19:25:18   ▓▒░
❯ > .zshrc <<EOF                                                                                                                                    96%  ▓▒░
PS1='%# ' PS2= RPS2='%^'; setopt transientrprompt interactivecomments
source ~/zsh-autocomplete/zsh-autocomplete.plugin.zsh
EOF

░▒▓     /var/folders/_6/91slktdj2jl8qf0gmclbv0280000gn/T/tmp.hYK0MOi2 ························································· 1.83    19:25:27   ▓▒░
❯ env -i HOME=$PWD PATH=$PATH TERM=$TERM ${TERMINFO:+TERMINFO=$TERMINFO} zsh -d                                                                     96%  ▓▒░
%
% l
zsh: command not found: l
% ls
zsh-autocomplete
% .. ls
directory
zsh-autocomplete/
% ..## cd
directory
zsh-autocomplete/
```

**Comment by ragu-manjegowda** [comment]
@marlonrichert sorry I over looked it earlier. Copied the output now. Please let me know if you anything else. Reopening the issue. Thanks.

**Comment by marlonrichert** [comment]
What exactly are you expecting `.. cd` or `.. ls` to do? Why would you type this?

**Comment by ragu-manjegowda** [comment]
I am looking for a way to disable autocomplete. For example, if I type `ls ` I do not want suggestions to show up. 

```
zstyle ':autocomplete:*' ignored-input '' # extended glob pattern
# '':     Always show completions.
# '..##': Don't show completions when the input consists of two or more dots.
```

Isn't `..`  supposed to do it? Or am I reading it incorrect?

**Comment by marlonrichert** [comment]
“Input” in this context means the current word. So, with `..#`, if the current word consists of two or more dots, completions won’t be shown _for that word._

I’ll update that comment to be more precise.

**Comment by ragu-manjegowda** [comment]
@marlonrichert I would really appreciate it if you can please enable option to temporarily disable completion for `full command` instead of just `word`.

Let me know if you are interested in implementing this, happy to create an issue requesting `feature`.

**Comment by marlonrichert** [comment]
Feel free to open a feature request – or better yet, a pull request. 🙂
