### ISSUE TITLE
Remap Up/Down to Tab/Shift-Tab

### ISSUE THREAD

**Issue by g-h-97** [marlonrichert/zsh-autocomplete#462]
## What do you want?
Remap Up/Down to Tab/Shift-Tab

## Why do you want this?
For fast option selection, and keeping fingers at the main row

## Who else would benefit from this?
Virtually all users and fast tapers

## How should it work?
Remapping from .zshrc 

Thanks,

**Comment by marlonrichert** [comment]
> Remap Up/Down to Tab/Shift-Tab

Can you be more precise than this? I’m not sure what you want exactly.

**Comment by g-h-97** [comment]
@marlonrichert, I updated the issue with requested fields. Sorry for the misunderstanding btw,

**Comment by marlonrichert** [comment]
This is [already implemented](https://github.com/marlonrichert/zsh-autocomplete/blob/d8bfbef46efc54c1189010a3b70d501b44487504/.zshrc#L42).
