### ISSUE TITLE
Option to not show results until N characters or Space input

### ISSUE THREAD

**Issue by Dwight-D** [marlonrichert/zsh-autocomplete#47]
Typing one character results in a horrible list of suggestions that flashes briefly at the start of every command

![image](https://user-images.githubusercontent.com/25592807/83991764-22866e00-a94e-11ea-97fa-445e465374c2.png)

It's a minor grievance, but this flash looks pretty ugly and is a little annoying. I strongly suspect no one types one character and then auto-completes anyway, unless they use some kind of auto-cd feature. 

An option to disable suggestions until for instance two characters or space has been typed could stop this ugly suggestion flood. 

It doesn't need to be very sophisticated and edge cases like `type two characters` -> `erase one` could just be ignored, it's mostly the initial flash at every command that annoys me.

**Comment by marlonrichert** [comment]
How about using the new [“shorten the automatic completions list“](https://github.com/marlonrichert/zsh-autocomplete/blob/master/README.md#shorten-the-automatic-completions-list) feature? Would that solve your problem?

**Comment by Dwight-D** [comment]
I guess almost but not quite. The thing is that I can't think of any situation where suggestions would be desirable after only typing one character, so you're always gonna have a huge list that pops up for a second and then disappears, since I'm always gonna keep typing after that. 

There's no point to it being there at all, no matter the size of the list. I guess I can make it smaller but it's still gonna flash by for no reason every time I start typing a command which is just unpleasant UI/UX to me.

**Comment by marlonrichert** [comment]
OK, thanks for the explanation. I can add that.

**Comment by marlonrichert** [comment]
@Dwight-D @jcassee @PythonNut It's now available on the `master` branch. See the Readme for the syntax: https://github.com/marlonrichert/zsh-autocomplete/blob/master/README.md#wait-for-minimum-amount-of-input

**Comment by jcassee** [comment]
Thanks, @marlonrichert. I especially like how autocomplete does kick in after I type space, even when the minimum number of characters has not been reached.
