### ISSUE TITLE
Bugs on MacOS Monterey M2 Air with Oh My Zsh.

### ISSUE THREAD

**Issue by hyptocrypto** [marlonrichert/zsh-autocomplete#474]
- [x] I have carefully read all of the instructions in this issue template.
- [x] I have carried them out to the letter.

Failure to do so can and will result in your issue being closed without warning.

## Environment
```zsh
print $VENDOR $OSTYPE $SHELL $ZSH_ARGZERO $ZSH_PATCHLEVEL
print -l $_autocomplete__funcfiletrace
git -C ~zsh-autocomplete log --oneline -n1
```
apple darwin21.0 /bin/zsh zsh zsh-5.8.1-0-g1a490c7
/Users/julianbaumgartner/.zshrc:83

* Operating system: MacOs Monterey
* Terminal emulator: Iterm2

- [x] I have filled out the fields above.
- [x] I have ran the commands in the code block above.
- [x] I have pasted their output into the same block. 

## Steps to reproduce
```zsh
cd $(mktemp -d)
git clone --depth 1 -- https://github.com/marlonrichert/zsh-autocomplete.git
> .zshrc <<EOF
PS1='%# ' PS2= RPS2='%^'; setopt transientrprompt interactivecomments
source ~/zsh-autocomplete/zsh-autocomplete.plugin.zsh
EOF
env -i HOME=$PWD PATH=$PATH TERM=$TERM ${TERMINFO:+TERMINFO=$TERMINFO} zsh -d
```
- [x] I have run the code block above to create a test environment.
- [ ] I have reproduced my problem in this environment in the most minimal way possible.
- [ ] I have copy-pasted my entire test session into the same code block.

So I have I currently have 4 Macs. Overkill I know lol
All running oh_my_zsh with identical .zshrc files and MacOS Monterey 12.5.
2015 intel macbook (old personal)
2018 intel macbook (work)
2020 M1 Mac Mini (personal desktop)
2022 M2 Mac Air (new personal)

I just got the new 2022 M2 air and configured everything the exact same as the other machines. Im now running into issues with the zsh-autocomplete plugin. Im so used to it I dont think I could live without it lol. 
When running in the isolated env from the code block above, the plugin works just fine. So im guessing this has something to do with oh_my_zsh or the M2 chip. But this works no problem on the M1 chip with the exact same config. 
Issues are as follows:
1.  The completions dont show automatically. 
2. Only one completion option shows after typing a a few chars (not the same amount every time. Depends on the possible completions)
3. The search history/fuzzy finder does not work at all
4. Tab to autocomplete just flashes the completions

https://user-images.githubusercontent.com/60943792/186932107-462f0c55-b539-439a-8e47-df5b591fbe0d.mov

This may just be some weird issue stemming from the new M2 chip, but, this exact same set up works on an M1 chip.
Any pointers or insights would be very very appreciated. Please let me know if there is any other info or examples I should provide. Thanks!

**Comment by marlonrichert** [comment]
I’m unable to test this, because I don’t have an M2 chip to test with at the moment. Are there any clues in the log files, `$_autocomplete__log`, `$_autocomplete__log_pty` and `$_autocomplete__log_async`?

**Comment by hyptocrypto** [comment]
pty and async are empty. The error in the base log looks like it could point to something. 
<img width="1136" alt="Screen Shot 2022-08-27 at 8 40 18 AM" src="https://user-images.githubusercontent.com/60943792/187030711-0768f01c-5390-4b7b-a73d-4d9dd83eb2bb.png">

**Comment by hyptocrypto** [comment]
Hey @marlonrichert. So I tried the same set up on a friends macbook (intel) and ran into the same issue. So it must be some combo of the most recent version os oh-my-zsh and the autocomplete plugin. But its not related to the M2 chip. 
I just started jumping back in the commit history and rolling back to `d8bfbef` fixes things. Not sure if this will help you in identifying the issue, but just wanted to keep you posted.

**Comment by marlonrichert** [comment]
Thanks. Then the problem must be in 96bbb5bb5b3698ca23d54ee28eb595a3727bf6df.

**Comment by hyptocrypto** [comment]
> Thanks. Then the problem must be in [96bbb5b](https://github.com/marlonrichert/zsh-autocomplete/commit/96bbb5bb5b3698ca23d54ee28eb595a3727bf6df).

Yea I tried messing with some of those settings, but didnt get it working on the main branch. Ill fork and see if I can get things working.

**Comment by latipun7** [comment]
@marlonrichert this issue seems similar to mine https://github.com/marlonrichert/zsh-autocomplete/issues/468. I don't even using Mac.

**Comment by marlonrichert** [comment]
Yes, it does. I'm gonna close this as duplicate.

@hyptocrypto Please continue the conversation in #468.
