### ISSUE TITLE
Zsh crash when creating terminal splits while history menu is open

### ISSUE THREAD

**Issue by kidonng** [marlonrichert/zsh-autocomplete#478]
- [x] I have carefully read all of the instructions in this issue template.
- [x] I have carried them out to the letter.

Failure to do so can and will result in your issue being closed without warning.

## Environment
```zsh
apple darwin21.3.0 zsh zsh-5.9-0-g73d3173

4c363ff (grafted, HEAD -> main, origin/main, origin/HEAD) Let `^_` exit menu and remove last completion
```

* Operating system: macOS
* Terminal emulator: kitty

- [x] I have filled out the fields above.
- [x] I have ran the commands in the code block above.
- [x] I have pasted their output into the same block. 

## Steps to reproduce

1. Enter test environment
2. Fill history with random commands
3. Open history menu
4. Create terminal splits for multiple times
5. zsh crashes

https://user-images.githubusercontent.com/44045911/188600802-54450734-35ed-4369-954a-88e114c4d2d8.mov

- [x] I have run the code block above to create a test environment.
- [x] I have reproduced my problem in this environment in the most minimal way possible.
- [x] I have copy-pasted my entire test session into the same code block.

#451 seems to be the same issue, bug I'm creating this new one in order not to hijack the discussion there.

**Comment by marlonrichert** [comment]
This looks like a bug in Zsh to me. What happens if you run `zstyle ':autocomplete:async' enabled no` _before_ sourcing Autocomplete? Does the bug still occur?

**Comment by marlonrichert** [comment]
Closing, since I haven't heard back from @kidonng.

**Comment by MrinmoyHaloi** [comment]
any updates ? @marlonrichert

**Comment by marlonrichert** [comment]
@MrinmoyHaloi I haven't done anything with this because I have not heard back from @kidonng. However, if you can make me a reproducible test, I'll reopen it.

**Comment by MrinmoyHaloi** [comment]
@marlonrichert I have some info that might be helpful.

According fedora bug report it crashes because it moves to a **invalid address**. 
Crashing function: **complistmatches**
file_name: **"/usr/lib64/zsh/5.9/zsh/complist.so"**

**Comment by marlonrichert** [comment]
Well, then it's a bug in Zsh. If you could make me a [minimal, reproducible test case](https://stackoverflow.com/help/minimal-reproducible-example), then I can file a bug report about it upstream.
