### ISSUE TITLE
Compdump is regenerated every time on startup

### ISSUE THREAD

**Issue by tobiasBora** [marlonrichert/zsh-autocomplete#480]
- [X] I have carefully read all of the instructions in this issue template.
- [X] I have carried them out to the letter.

## Environment
```zsh
> print $VENDOR $OSTYPE $SHELL $ZSH_ARGZERO $ZSH_PATCHLEVEL
pc linux-gnu /run/current-system/sw/bin/bash zsh zsh-5.9-0-g73d3173
> print -l $_autocomplete__funcfiletrace

> git -C ~zsh-autocomplete log --oneline -n1
fatal: ni ceci ni aucun de ses répertoires parents n'est un dépôt git : .git
# Note that I install it from 4c363ff553be227db90842d7481fd6e02de8703c with home manager
```

* Operating system:  NixOs
* Terminal emulator:  Konsole

## Steps to reproduce

zsh-autocomplete is relatively slow on startup (1-2 seconds, which is not huge… but not small either especially when many scripts are loaded and when the system is overloaded, in which case it can be much more)

It's hard to point exactly to a setup that is slow as the time seems to increase in more complex setups. But when we run the most basic config zsh-autocomplete already takes maybe 1 second to start
```zsh
cd $(mktemp -d)
git clone --depth 1 -- https://github.com/marlonrichert/zsh-autocomplete.git
> .zshrc <<EOF
PS1='%# ' PS2= RPS2='%^'; setopt transientrprompt interactivecomments
source ~/zsh-autocomplete/zsh-autocomplete.plugin.zsh
EOF
env -i HOME=$PWD PATH=$PATH TERM=$TERM ${TERMINFO:+TERMINFO=$TERMINFO} zsh -d
```
Then if we run it with zsh-powerlevel10k then it is slightly slower, maybe 2 seconds: 

![Peek 07-09-2022 02-05](https://user-images.githubusercontent.com/2164118/188761868-1d8a025d-91e1-453f-a7bc-67432e685a80.gif)

Note that if we disable this script the loading time is basically not noticeable:

![Peek 07-09-2022 02-09](https://user-images.githubusercontent.com/2164118/188761922-11586ff1-d6a9-496a-93da-492d64407890.gif)

To create these more complex setups, I actually used this config by home manager (for the `./p10k-config/p10k.zsh` file you can put any style you like created with `p10k configure`, if you want I can give mine but these files are rather lengthy so I guess it's better not to paste them here)

```
{ config, lib, pkgs, ... }:
let
  # load the configuration that we was generated the first
  # time zsh were loaded with powerlevel enabled.
  # Make sure to comment this part if you want to run
  # again 'p10k configure' and to copy the generated file
  # $ mv ~/.p10k.zsh p10k-config/p10k.zsh
  configThemeNormal = ./p10k-config/p10k.zsh;
  configThemeTTY = ./p10k-config/p10k_tty.zsh;
in
{
  fonts.fontconfig.enable = true;
  home.packages = with pkgs; [
    # Meslo Nerd Font patched for Powerlevel10k
    # Restart Konsole and configure it (profile) to choose MesloLGS NF
    meslo-lgs-nf
    # For fuzzy filter in cd
    # https://github.com/junegunn/fzf
    fzf
    any-nix-shell
    zsh
  ];
  programs.direnv.enableZshIntegration = true;
  programs.zsh = {
    enable = true;
    # enableAutosuggestions = true;
    enableCompletion = true;
    enableSyntaxHighlighting = true;
    enableVteIntegration = true;
    defaultKeymap = "emacs";
    initExtra = ''
      # By default backward deleting a word would consider / as a regular
      # word. Now this problem is gone with this option, see also
      # https://stackoverflow.com/questions/444951/zsh-stop-backward-kill-word-on-directory-delimiter
      autoload -U select-word-style
      select-word-style bash

      # Ctrl-arrows fail in konsole
      # https://unix.stackexchange.com/questions/58870/ctrl-left-right-arrow-keys-issue
      # urxvt/rxvt-unicode (and maybe others):
      bindkey "^[Od" backward-word
      bindkey "^[Oc" forward-word
      # alacritty, konsole, terminator, xterm (and maybe others):
      bindkey "^[[1;5D" backward-word
      bindkey "^[[1;5C" forward-word
      # to find the proper char just type cat and type your char!
      bindkey "^[[3~" delete-char
      # By default, only alt-backspace deletes a word, now we can also use
      # ctrl instead of Alt
      bindkey "^H" backward-kill-word

      if zmodload zsh/terminfo && (( terminfo[colors] >= 256 )); then
        [[ ! -f ${configThemeNormal} ]] || source ${configThemeNormal}
      else
        [[ ! -f ${configThemeTTY} ]] || source ${configThemeTTY}
      fi

      any-nix-shell zsh --info-right | source /dev/stdin
    '';

    # https://github.com/marlonrichert/zsh-autocomplete
    # COMMENT THE NEXT 11 LINES TO SEE THE QUICK VERSION    
    completionInit = let
      autoComplete = pkgs.fetchFromGitHub {
        owner = "marlonrichert";
        repo = "zsh-autocomplete";
        rev = "4c363ff553be227db90842d7481fd6e02de8703c";
        sha256 = "sha256-3hRRrTpRtVrQdc2rTO67Sn1SJ5nPop9liTJfu3qRYHs=";
      };
    in ''
      source ${autoComplete}/zsh-autocomplete.plugin.zsh
    '';
    
    plugins = [
      {
        # A prompt will appear the first time to configure it properly
        # make sure to select MesloLGS NF as the font in Konsole
        name = "powerlevel10k";
        src = pkgs.zsh-powerlevel10k;
        file = "share/zsh-powerlevel10k/powerlevel10k.zsh-theme";
      }
    ];
  };
}

```

- [X] I have run the code block above to create a test environment.
- [X] I have reproduced my problem in this environment in the most minimal way possible.
- [X] I have copy-pasted my entire test session into the same code block.

**Comment by marlonrichert** [comment]
> I actually used this config by home manager

I have no idea what kind of config that is.

Can you please use the setup I provided in the bug report template to create a [minimal, reproducible test case](https://stackoverflow.com/help/minimal-reproducible-example). Thanks!

**Comment by marlonrichert** [comment]
Closing, as I haven't heard back from @tobiasBora.

**Comment by tobiasBora** [comment]
Thanks! And sorry for not giving any feedback, I was quite busy and it's not that easy to write a super minimal expression as the bug is more visible when we add p10k and therefore the minimal example must install p10k as well.

The above code uses [home manager](https://github.com/nix-community/home-manager) which is a way to configure your home using Nix in a reproducible and centralized way. It is maybe not ideal to use if you don't want to install home-manager on your system (even if it's not really complicated nor invasive). However, if you want I can take a few minutes to create a script to reproduce this in a VM. Once you [installed nix](https://nixos.org/download.html#download-nix) with
```
$ sh <(curl -L https://nixos.org/nix/install) --no-daemon
```
(you can uninstall it simply by removing the `/nix/` folder)

then you would be able to start the VM with:
```
$ nix build-vm --flake path-to-some-git-repo-I-will-create
$ ./result/bin/nix-run-vm
```
This would be completely independent of your system (so more reproducible and secure).

Let we know if you want me to spend a few minutes on that.

**Comment by tobiasBora** [comment]
Oh, maybe I know why I can reproduce it better with nix/home-manager and not in a new MWE. If I do `programs.zsh.enable = true;` it enables automatically https://github.com/spwhitt/nix-zsh-completions which is a completion tool for `nix` commands on zsh. Maybe in that case compdump takes a few seconds to generate the completion script. And since it's not cached by this project, it takes a few seconds to start.

(nix zsh's completion also show some other bugs of this project when a large number of items is present for the completion… but it's another issue and has maybe been corrected in the meantime)

**Comment by marlonrichert** [comment]
> If I do `programs.zsh.enable = true;` it enables automatically https://github.com/spwhitt/nix-zsh-completions which is a completion tool for `nix` commands on zsh.

How exactly does `nix` "enable" https://github.com/spwhitt/nix-zsh-completions? Just adding those completion functions to your `$fpath` should not have much impact on startup time.

**Comment by tobiasBora** [comment]
It does it in two ways:
- first it installs `nix-zsh-completion` [here](https://github.com/nix-community/home-manager/blob/bc90de24d898655542589237cc0a6ada7564cb6c/modules/programs/zsh.nix#L488) whose installation steps are described [here](https://github.com/NixOS/nixpkgs/blob/8ff7b290e6dd47d7ed24c6d156ba60fc3c83f100/pkgs/shells/zsh/nix-zsh-completions/default.nix) (basically just copy the files into the nix equivalent of `/usr/share/zsh/{site-functions,plugins/nix}`) 
- then [it runs](https://github.com/nix-community/home-manager/blob/bc90de24d898655542589237cc0a6ada7564cb6c/modules/programs/zsh.nix#L523) `cfg.completionInit` that I override above as `source ${autoComplete}/zsh-autocomplete.plugin.zsh`

**Comment by marlonrichert** [comment]
That shouldn’t really add any additional overhead. Let’s first see if fixing the compdump bug makes things better.
