### ISSUE TITLE
Bug? `sudo` completes from history on up arrow, `ls` goes to last history item?

### ISSUE THREAD

**Issue by spikespaz** [marlonrichert/zsh-autocomplete#482]
## What do you want?

> [How can I search history with text already entered at the prompt in zsh?](https://unix.stackexchange.com/questions/97843/how-can-i-search-history-with-text-already-entered-at-the-prompt-in-zsh)

<https://unix.stackexchange.com/questions/97843/how-can-i-search-history-with-text-already-entered-at-the-prompt-in-zsh>

I don't understand how this works currently.
- When I press <kbd>down</kbd>, executables are shown, good.
- When I type `sudo` and press <kbd>up</kbd>, the history items beginning with `sudo` are shown.
- When I type `ls` and press <kbd>up</kbd>, the last-added entry of history is shown. ???

Why does occurrence 3 not use history?

## Why do you want this?

I used to have a ZSH configuration (that I cannot seem to find on any drive) that would show history lines whose beginnings matched the string that I had currently typed. It was as if history filtered itself as I typed. I wish to have this feature again.

**Comment by marlonrichert** [comment]
It works for me. Can you put together a [minimal, reproducible test case](https://stackoverflow.com/help/minimal-reproducible-example) using the setup below?

```zsh
cd $(mktemp -d)
git clone --depth 1 -- https://github.com/marlonrichert/zsh-autocomplete.git
> .zshrc <<EOF
PS1='%# ' PS2= RPS2='%^'; setopt transientrprompt interactivecomments
source ~/zsh-autocomplete/zsh-autocomplete.plugin.zsh
EOF
env -i HOME=$PWD PATH=$PATH TERM=$TERM ${TERMINFO:+TERMINFO=$TERMINFO} zsh -d
```

**Comment by spikespaz** [comment]
I think that this issue was either a history misconfiguration, or a conflict of keybinds between zsh-edit and this. Both have been resolved.

Question: You make both plugins, why do the default keybinds overlap?

**Comment by marlonrichert** [comment]
They don’t for this case at least. Zsh Edit does not touch the <kbd>Up</kbd> key.

On which keybindings do they overlap?
