### ISSUE TITLE
Menu items not showing with OMZ

### ISSUE THREAD

**Issue by TheProjectsGuy** [marlonrichert/zsh-autocomplete#483]
When I try using the suggestions, they do not appear at the bottom of the prompt. I always have to use the down arrow to bring them up. They seem to flicker when I press the tab key (unless there is only one obvious choice).
This used to work in Ubuntu 20.04 with the same Agnoster theme.

- [x] I have carefully read all of the instructions in this issue template.
- [x] I have carried them out to the letter.

Failure to do so can and will result in your issue being closed without warning.

## Environment
```zsh
print -l $_autocomplete__funcfiletrace
git -C ~zsh-autocomplete log --oneline -n1
```

```zsh
$ print $VENDOR $OSTYPE $SHELL $ZSH_ARGZERO $ZSH_PATCHLEVEL
ubuntu linux-gnu /usr/bin/zsh /usr/bin/zsh ubuntu/5.8.1-1

$ print -l $_autocomplete__funcfiletrace
/home/avneesh/.zshrc:82

$ git -C ~zsh-autocomplete log --oneline -n1
aed8e17 (HEAD -> main, origin/main, origin/HEAD) Fix recent-dirs naming conflict
```

* Operating system: Linux Mint 21 (Vanessa), downstream of Ubuntu 22.04 (Jammy) and Debian bookworm
* Terminal emulator: Terminator (version 2.1.1), ZSH, Agnoster theme

- [x] I have filled out the fields above.
- [x] I have ran the commands in the code block above.
- [x] I have pasted their output into the same block. 

## Steps to reproduce
```zsh
cd $(mktemp -d)
git clone --depth 1 -- https://github.com/marlonrichert/zsh-autocomplete.git
> .zshrc <<EOF
PS1='%# ' PS2= RPS2='%^'; setopt transientrprompt interactivecomments
source ~/zsh-autocomplete/zsh-autocomplete.plugin.zsh
EOF
env -i HOME=$PWD PATH=$PATH TERM=$TERM ${TERMINFO:+TERMINFO=$TERMINFO} zsh -d
```
- [x] I have run the code block above to create a test environment.
- [ ] I have reproduced my problem in this environment in the most minimal way possible.
- [ ] I have copy-pasted my entire test session into the same code block.

Somehow, in the above steps, the issue does not occur.

The problem is not getting options here
![image](https://user-images.githubusercontent.com/29420733/189836180-f362a156-13fc-4af8-8219-e128671be5a0.png)

In the above test session, they do come up
![image](https://user-images.githubusercontent.com/29420733/189836356-02c04e76-51a1-4aa9-ad9d-0a156fe7fa8f.png)

**Comment by TheProjectsGuy** [comment]
By "flickering" options, I mean the menu flickers when I press the tab key. When it stayed earlier, it served as an important visual guide for me and I really want it to be there.

https://user-images.githubusercontent.com/29420733/189837531-d6512599-cde5-4ca6-a24a-1a2c3d880208.mp4

**Comment by Ynng** [comment]
Getting the same issue but in Ubuntu 18.04.

**Comment by marlonrichert** [comment]
I'm unable to reproduce this in a clean environment like this on Ubuntu 20.04 with Zsh 5.8:

```zsh
cd $(mktemp -d)
git clone --depth 1 -- https://github.com/marlonrichert/zsh-autocomplete.git
> .zshrc <<EOF
PS1='%# ' PS2= RPS2='%^'; setopt transientrprompt interactivecomments
source ~/zsh-autocomplete/zsh-autocomplete.plugin.zsh
EOF
env -i HOME=$PWD PATH=$PATH TERM=$TERM ${TERMINFO:+TERMINFO=$TERMINFO} zsh -d
```

Can you please use the setup above to create a [minimal, reproducible test case](https://stackoverflow.com/help/minimal-reproducible-example)? If I cannot reproduce the bug, then I cannot fix it.

**Comment by TheProjectsGuy** [comment]
> Can you please use the setup above to create a [minimal, reproducible test case](https://stackoverflow.com/help/minimal-reproducible-example)? If I cannot reproduce the bug, then I cannot fix it.

![image](https://user-images.githubusercontent.com/29420733/191172250-aa9376ac-7f07-448f-aa7b-cc6e9c5dcd86.png)

I am unable to get the same behavior in a minimal environment. Is there any other way (maybe I could send some files)?

**Comment by marlonrichert** [comment]
> I am unable to get the same behavior in a minimal environment.

@TheProjectsGuy 
This means the problem is somewhere else in your dotfiles. Please add parts of your Zsh dotfiles to the minimal env until you find what causes this.

> My other computer is on 5b0073d8ffde20498c820f94ddc62b7f3f54cfc7 and working, so I checked it out manually and the problem is no more.

@TheProjectsGuy @Ynng Can you please run `git bisect` in the `zsh-autocomplete` repo in the environment where the bug occurs to find the exact commit where the bug  appears for you?

**Comment by Ynng** [comment]
d8bfbef4 is the last working commit for me, so 96bbb5bb broke it for me.

I've done a bit of testing and found that the problem only occurs with `zsh-autocomplete` + `ohmyzsh` + `powerlevel10k`

Here's a test case:
1. Download Ubuntu 22.04 LTS (I did it in wsl)
2. Install zsh, chose option 2 to populate `.zshrc`
3. `git clone https://github.com/marlonrichert/zsh-autocomplete` to `~`
4. Install oh my zsh `sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"`
5. add `skip_global_compinit=1` to `.zshenv`
6. append the following to `.zshrc`
```
setopt autocd extendedglob nomatch notify
zstyle :compinstall filename '$HOME/.zshrc'
source ~/zsh-autocomplete/zsh-autocomplete.plugin.zsh
```
7. Install powerline 10k: `git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k`
8. Start a new `zsh` instance to go through powerline 10k's configuration wizard. **Always pick the first option**
9. ~~Set `ZSH_THEME="powerlevel10k/powerlevel10k" in .zshrc~~ (not needed)
10. `cd ~`
11. Press tab

**Comment by marlonrichert** [comment]
> d8bfbef4 is the last working commit for me, so 96bbb5bb broke it for me.

Thanks! That explains it completely. Fixing it should be trivial.

**Comment by Locorock** [comment]
By testing a few commits i found out that specifically f4e6b33 is when this behavior starts appearing

**Comment by marlonrichert** [comment]
@Locorock Did you run `git bisect`? Changing the commit that @Ynng pointed out fixes it for me. Also, did you test in the same environment as @Ynng? Or what is your test setup?

**Comment by Locorock** [comment]
@marlonrichert Not really, i just did it manually. This is the only content of my .zshrc
```
source ~/.plugins/zsh-snap/znap.zsh
znap source marlonrichert/zsh-autocomplete
znap source ohmyzsh/ohmyzsh
```

**Comment by marlonrichert** [comment]
@Locorock Modifying the change in 96bbb5bb5b3698ca23d54ee28eb595a3727bf6df fixed your test case for me. So, it's not possible that the commit you pointed out is the faulty one.

**Comment by Locorock** [comment]
@marlonrichert You are correct, somehow i ended up making a shallow clone of the repository and 96bbb got cut out, i can confirm that the commit before 96bbb5b works correctly

**Comment by TheProjectsGuy** [comment]
> @TheProjectsGuy @Ynng Can you please run git bisect in the zsh-autocomplete repo in the environment where the bug occurs to find the exact commit where the bug appears for you?

I ran the following `git bisect` session on the package. Just as with @Ynng and @Locorock, it appears that commit 96bbb5bb5b3698ca23d54ee28eb595a3727bf6df does not work correctly, but commit d8bfbef46efc54c1189010a3b70d501b44487504 (commit immediately before 96bbb5bb5b3698ca23d54ee28eb595a3727bf6df) works perfectly.

![image](https://user-images.githubusercontent.com/29420733/193520369-e252d83e-c14c-42fa-84ae-91bb04379fb4.png)

A simple `git diff` says that not much has changed.

![image](https://user-images.githubusercontent.com/29420733/193521055-8ebef2e9-fc50-46c0-be03-b4195ec6aa68.png)

**Comment by marlonrichert** [comment]
Thanks, but as I said, I already found a fix:

> Modifying the change in https://github.com/marlonrichert/zsh-autocomplete/commit/96bbb5bb5b3698ca23d54ee28eb595a3727bf6df fixed your test case for me.

**Comment by chaoqunya** [comment]
```zsh
>>> ls
same-prefix-folder-a    same-prefix-folder-b    diff-prefix-folder
>>> cd diff    // match one folder will show suggestion
directory
diff-prefix-folder
>>> cd same    // match more than on folder, will not show suggestion
```

**Comment by MrAureliusR** [comment]
Having the same issue. Someone suggested a particular commit for me to try (d8bfbef as others have pointed out) and that *does* fix the issue temporarily. However, after running perhaps 3-4 commands, it completely breaks and I get no autocompletion at all.

Am I to take it that the comment by marlonrichert 2 above this one means the issue has been spotted and/or fixed? I don't see any commit since Sep 9. I would be willing to provide any info/help I can.

**Comment by sevy2011** [comment]
@MrAureliusR if you have installed manually try to revert to the commit mentioned:
`git checkout d8bfbef46efc54c1189010a3b70d501b44487504`
if not you will have to wait for the fix
someone correct me if i'm wrong

**Comment by latipun7** [comment]
> Thanks, but [as I said](https://github.com/marlonrichert/zsh-autocomplete/issues/483#issuecomment-1254604647), I already found a fix:
> 
> > Modifying the change in [96bbb5b](https://github.com/marlonrichert/zsh-autocomplete/commit/96bbb5bb5b3698ca23d54ee28eb595a3727bf6df) fixed your test case for me.

@marlonrichert , please push the fix 🙏

**Comment by marlonrichert** [comment]
Sorry for the delay. I haven’t had much time for plugin development lately because of programming-related injuries. I’ll make a Pull Request soon for you to review.

**Comment by MrAureliusR** [comment]
> @MrAureliusR if you have installed manually try to revert to the commit mentioned: `git checkout d8bfbef46efc54c1189010a3b70d501b44487504` => this requires to clone the repo without `--depth 1` this fixed it for me if not you will have to wait for the fix someone correct me if i'm wrong

Please read my entire comment. I already tried that commit, and it only partially fixes the issue.

**Comment by marlonrichert** [comment]
Please try the branch in the pull request above and let me know if it works for you.
