### ISSUE TITLE
Refine `insert-unambiguous yes` behavior

### ISSUE THREAD

**Issue by yshui** [marlonrichert/zsh-autocomplete#484]
- [x] I have carefully read all of the instructions in this issue template.
- [x] I have carried them out to the letter.

Failure to do so can and will result in your issue being closed without warning.

## Environment
```zsh
print $VENDOR $OSTYPE $SHELL $ZSH_ARGZERO $ZSH_PATCHLEVEL
print -l $_autocomplete__funcfiletrace
git -C ~zsh-autocomplete log --oneline -n1
```

```
pc linux-gnu /bin/zsh -zsh zsh-5.9-0-g73d3173
/home/shui/.zshrc:21
887bfd6 (HEAD -> master, origin/master, origin/HEAD) Update info action output and update README.md
```

* Operating system: Archlinux
* Terminal emulator: Alacritty
- [x] I have filled out the fields above.
- [x] I have ran the commands in the code block above.
- [x] I have pasted their output into the same block. 

## Steps to reproduce

I'm using `zimfw`, my `.zshrc`:

```zsh
zstyle ':zim:zmodule' use 'degit'
zstyle ':autocomplete:tab' insert-unambiguous 'yes'
zstyle ':autocomplete:recent-dirs' backend zoxide
ZIM_HOME=$HOME/.config/zimfw
ZDOTDIR=$HOME/.config
if [[ ! ${ZIM_HOME}/init.zsh -nt ${ZDOTDIR:-${HOME}}/.zimrc ]]; then
  source ${ZIM_HOME}/zimfw.zsh init -q
fi

source ${ZIM_HOME}/init.zsh
```

my `.zimrc`:

```zsh
#zmodule zsh-users/zsh-syntax-highlighting
#zmodule zsh-users/zsh-autosuggestions
#zmodule zsh-users/zsh-history-substring-search
#zmodule zsh-users/zsh-completions --fpath src
#zmodule completion
zmodule marlonrichert/zsh-autocomplete
#zmodule romkatv/powerlevel10k --use degit
```

Pressing `TAB` always insert the first entry in the list, despite `insert-unambiguous yes`

- [ ] I have run the code block above to create a test environment.
- [x] I have reproduced my problem in this environment in the most minimal way possible.
- [ ] I have copy-pasted my entire test session into the same code block.

**Comment by marlonrichert** [comment]
Can you please use the setup below (which was in the bug report template, but you deleted it) to create a [minimal, reproducible test case](https://stackoverflow.com/help/minimal-reproducible-example)? Then I'll reopen your issue.
```zsh
cd $(mktemp -d)
git clone --depth 1 -- https://github.com/marlonrichert/zsh-autocomplete.git
> .zshrc <<EOF
PS1='%# ' PS2= RPS2='%^'; setopt transientrprompt interactivecomments
source ~/zsh-autocomplete/zsh-autocomplete.plugin.zsh
EOF
env -i HOME=$PWD PATH=$PATH TERM=$TERM ${TERMINFO:+TERMINFO=$TERMINFO} zsh -d
```

**Comment by yshui** [comment]
@marlonrichert yeah the problem is reproducible with that minimal config. I ran it and the problem is there.

**Comment by yshui** [comment]
@marlonrichert it happens with this .zshrc:

```zsh
PS1='%# ' PS2= RPS2='%^'; setopt transientrprompt interactivecomments
zstyle ':autocomplete:tab' insert-unambiguous 'yes'
source ~/zsh-autocomplete/zsh-autocomplete.plugin.zsh
```

**Comment by marlonrichert** [comment]
@yshui Please turn it into a test case that has _all the steps_ I need to reproduce the problem. Simply running the code you now pasted _does not reproduce the problem._

**Comment by yshui** [comment]
So:

1. Use the above .zshrc
2. cd into a directory with some files
3. press TAB

Expected:

The longest common prefix is inserted.

Actual:

The first result is inserted.

**Comment by marlonrichert** [comment]
> some files

Please be more specific than that. Update your test case so that I can copy-paste it into my terminal and run it.

**Comment by yshui** [comment]
> some files

literally _any_ files. like:

```zsh
mkdir files
cd files
touch aaa aab aac
```

and Tab gives me `aaa` instead of `aa`

**Comment by marlonrichert** [comment]
In that scenario, do you press Tab on an empty line? Or what is left of your cursor when you press Tab?

**Comment by yshui** [comment]
> Or what is left of your cursor when you press Tab?

A command that accepts a file, like `ls`

**Comment by marlonrichert** [comment]
Thanks, I can reproduce it now. Will fix.

**Comment by marlonrichert** [comment]
@yshui You're missing a colon. It should be 
```zsh
zstyle ':autocomplete:tab:*' insert-unambiguous yes
```
or just 
```zsh
zstyle ':autocomplete:*' insert-unambiguous yes
```

**Comment by yshui** [comment]
ah, i see. so the behavior is to insert the common prefix if there is one. if the candidates don't have a common prefix, then the first choice is inserted.

**Comment by marlonrichert** [comment]
Do you think that's what most people using `insert-unambiguous` would want? I don't use it myself, so it's hard for me to judge.

If it worked like that, wouldn't you then be unable to insert anything else than the common prefix? I mean, how would you then insert any completion that's not exactly equal to the common prefix? Would you always use the arrow keys? Or would you just type until you have only one completion left and then press Tab?

**Comment by yshui** [comment]
Other people could chime in, but IMO tab and arrow key would fit well with these two different kinds of completions - Tab to insert common prefix, and arrow key to select from the menu. I think another option would be using the "tab, tab again" behavior, i.e. tab once to insert common prefix, if the user tapped tab again immediately, enter selection. I think most of the users would be used to this behavior?

**Comment by marlonrichert** [comment]
> I think most of the users would be used to this behavior?

Probably, but the autocompletion makes it a bit trickier. I’ll look into. Pull requests welcome, too, of course. 🙂

**Comment by marlonrichert** [comment]
Tested again and I can't reproduce it.
