### ISSUE TITLE
_autocomplete.config.completer:1: CURRENT: parameter not set in WSL2

### ISSUE THREAD

**Issue by markfaine** [marlonrichert/zsh-autocomplete#491]
- [x] I have carefully read all of the instructions in this issue template.
- [x] I have carried them out to the letter.

## Environment
```zsh

print -l $_autocomplete__funcfiletrace
git -C ~zsh-autocomplete log --oneline -n1
```

```zsh
% print $VENDOR $OSTYPE $SHELL $ZSH_ARGZERO $ZSH_PATCHLEVEL
ubuntu linux-gnu zsh ubuntu/5.8.1-1

% print -l $_autocomplete__funcfiletrace
> No output

% git -C ~zsh-autocomplete log --oneline -n1
aed8e17 (grafted, HEAD -> main, origin/main, origin/HEAD) Fix recent-dirs naming conflic
```

* Operating system: 
* Terminal emulator: 

```
Ubuntu 22.04 WSL2 
Linux wsl 5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
Windows Terminal Preview
Version: 1.16.2641.0
```

- [x] I have filled out the fields above.
- [x] I have ran the commands in the code block above.
- [x] I have pasted their output into the same block. 

## Steps to reproduce
```zsh
cd $(mktemp -d)
git clone --depth 1 -- https://github.com/marlonrichert/zsh-autocomplete.git
> .zshrc <<EOF
PS1='%# ' PS2= RPS2='%^'; setopt transientrprompt interactivecomments
source ~/zsh-autocomplete/zsh-autocomplete.plugin.zsh
EOF
env -i HOME=$PWD PATH=$PATH TERM=$TERM ${TERMINFO:+TERMINFO=$TERMINFO} zsh -d
```

```
   /tmp/tmp.e3EvTP4tSD  git clone --depth 1 -- https://github.com/marlonrichert/zsh-autocomplete.git           34
Cloning into 'zsh-autocomplete'...
remote: Enumerating objects: 58, done.
remote: Counting objects: 100% (58/58), done.
remote: Compressing objects: 100% (54/54), done.
remote: Total 58 (delta 0), reused 25 (delta 0), pack-reused 0
Receiving objects: 100% (58/58), 1.64 MiB | 13.32 MiB/s, done.
   /tmp/tmp.e3EvTP4tSD  > .zshrc <<EOF                                                                         35
PS1='%# ' PS2= RPS2='%^'; setopt transientrprompt interactivecomments
source ~/zsh-autocomplete/zsh-autocomplete.plugin.zsh
EOF
   /tmp/tmp.e3EvTP4tSD  env -i HOME=$PWD PATH=$PATH TERM=$TERM ${TERMINFO:+TERMINFO=$TERMINFO} zsh -d
```

- [x] I have run the code block above to create a test environment.
- [ ] I have reproduced my problem in this environment in the most minimal way possible.
- [x] I have copy-pasted my entire test session into the same code block.

My issue is the same as #467 which was closed as invalid.

This isn't really an accurate (real-world) way to test though.  If I'm running it in a very minimal environment that doesn't take into account anything else in my zsh configuration of course it will work, likely every time, barring some major issue.  I need it to work **with my** environment.

It seems like everything is working, just getting this error message when the shell starts:

```
_autocomplete.config.cache-path:1: array parameter reply created globally in function _autocomplete.config.cache-path
_autocomplete.config.completer:1: CURRENT: parameter not set
_autocomplete.config.cache-path:1: array parameter reply created globally in function _autocomplete.config.cache-path
_autocomplete.config.cache-path:1: array parameter reply created globally in function _autocomplete.config.cache-path
_autocomplete.config.completer:1: CURRENT: parameter not set
```

**Comment by marlonrichert** [comment]
> This isn't really an accurate (real-world) way to test though. If I'm running it in a very minimal environment that doesn't take into account anything else in my zsh configuration of course it will work, likely every time, barring some major issue. I need it to work with my environment.

Please add lines from your `.zshrc` file to the test environment until you find what's actually causing this. Thanks!

**Comment by archae0pteryx** [comment]
I also have this issue on a fresh install (Monterey 12.6). I will fill out a formal report when i get some time (hopefully). Just wanted to add the +1 really.

**Comment by marlonrichert** [comment]
Closing, as I haven't gotten a proper test case from @markfaine or @archae0pteryx.

**Comment by archae0pteryx** [comment]
@marlonrichert I shoulda updated. I wasn't able to get a good reproduction cause I've got a lot going on in my userspace and didn't have the time to strip everything out to a blank state... I still get the issue but i'm not sure how to reproduce for you with everything that's going on... Is there some debug dump that might be helpful? Maybe you can see something right off the bat? I ended up uninstalling...

**Comment by marlonrichert** [comment]
The best way to debug it is still [what I asked you to do earlier](https://github.com/marlonrichert/zsh-autocomplete/issues/491#issuecomment-1265048409):

> Please add lines from your `.zshrc` file to the test environment until you find what's actually causing this.

Alternatively, you can try commenting out lines from your `.zshrc` until you find which ones conflicts with Autocomplete.

**Comment by archae0pteryx** [comment]
Ah. Sorry. Shoulda reviewed our prev convo.

**Comment by marlonrichert** [comment]
NP 🙂

**Comment by markfaine** [comment]
It's no longer an issue
