### ISSUE TITLE
Spamming tabs stopped the autocompletion from working

### ISSUE THREAD

**Issue by Sinderella** [marlonrichert/zsh-autocomplete#492]
- [x] I have carefully read all of the instructions in this issue template.
- [x] I have carried them out to the letter.

Failure to do so can and will result in your issue being closed without warning.

## Environment
```zsh
apple darwin21.3.0 /opt/homebrew/bin/zsh zsh zsh-5.9-0-g73d3173
print -l $_autocomplete__funcfiletrace // no output
aed8e17 (HEAD -> main, origin/main, origin/HEAD) Fix recent-dirs naming conflict
```

* Operating system: macOS
* Terminal emulator: alacritty

- [x] I have filled out the fields above.
- [x] I have ran the commands in the code block above.
- [x] I have pasted their output into the same block. 

## Steps to reproduce
```zsh
cd $(mktemp -d)
git clone --depth 1 -- https://github.com/marlonrichert/zsh-autocomplete.git
> .zshrc <<EOF
PS1='%# ' PS2= RPS2='%^'; setopt transientrprompt interactivecomments
source ~/zsh-autocomplete/zsh-autocomplete.plugin.zsh
EOF
env -i HOME=$PWD PATH=$PATH TERM=$TERM ${TERMINFO:+TERMINFO=$TERMINFO} zsh -d
cd zsh-autocomplete/<here>
```
From `<here>`, start spamming tabs until it reaches the end, then delete the path then start spamming again. I noticed that it doesn't happen all the time, but it's happening more than I'd like.

Screen record: https://share.cleanshot.com/zNOEjW

- [x] I have run the code block above to create a test environment.
- [x] I have reproduced my problem in this environment in the most minimal way possible.
- [x] I have copy-pasted my entire test session into the same code block.
   - I provided the screen record with some explanation instead as it cannot be shown in the code block.

**Comment by marlonrichert** [comment]
@Sinderella Do you think #445 is the same issue?

**Comment by Sinderella** [comment]
> @Sinderella Do you think #445 is the same issue?

While I see similar stacktraces on the issue in my logs as well, I don't think it's the same. I tried replicating my own issue again and it doesn't produce an error report or stacktraces.

I think it doesn't completely crash in my case, it's just quickly trying to display and clear the results?

**Comment by marlonrichert** [comment]
What about #441?

**Comment by Sinderella** [comment]
> What about #441?

I think it's the same behaviour, so yep, I think it's the same issue.

**Comment by marlonrichert** [comment]
OK, then let’s continue over there.
