### ISSUE TITLE
Typing delays and high CPU load

### ISSUE THREAD

**Issue by 2epeat** [marlonrichert/zsh-autocomplete#496]
When typing, when I hold down the key, there is a noticeable delay before the characters are displayed in the terminal. This delay is not standard for Mac OS. Also, this delay manifests itself during the continuous deletion of characters.
The above is shown in the video: https://disk.yandex.ru/i/IFnB8PudQ_9OKw
If I disable the plugin, there are no delays.
It is played both in the built-in terminal and in iTerm.

Also, my iTerm sometimes crashes — I can't reproduce it.
Also, I can load my processor 99% just randomly typing text in the terminal — I can reproduce it.

```
apple darwin21.0 /bin/zsh -zsh zsh-5.8.1-0-g1a490c7
/Users/vi/.zshrc:101
3de533e (grafted, HEAD -> main, origin/main, origin/HEAD) Delete breaking zstyle from OMZ
```

```
macOS 12.6 (21G115)
iTerm2 Build 3.4.16
Terminal 2.12.7 (445)
```

I use the `passion' theme. But all this is reproduced without it.

### How to reproduce?
Launch the terminal.
Start typing naturally.
Hold the button for 1 second (for example g)
quick unhold
Hold the button for 1 more second (for example h)
quick unhold
Hold backspace button

**Comment by marlonrichert** [comment]
I'm unable to reproduce this on macOS in iTerm. Can you please try reproducing it in a clean environment like this?
```zsh
% cd $(mktemp -d)
> .zshrc <<EOF
PS1='%# ' PS2= RPS2='%^'; setopt transientrprompt interactivecomments
source /Users/marlon/Git/zsh-autocomplete/zsh-autocomplete.plugin.zsh
EOF
env -i HOME=$PWD PATH=$PATH TERM=$TERM ${TERMINFO:+TERMINFO=$TERMINFO} zsh -d
```
If the problem does not occur in there, then the cause is somewhere in your config. Try executing lines from your config in this clean environment until you find the one that clashes.

**Comment by marlonrichert** [comment]
Closing, as I haven't heard back from @2epeat.
