### ISSUE TITLE
Include history in completion

### ISSUE THREAD

**Issue by ad-on-is** [marlonrichert/zsh-autocomplete#497]
Is there a way to include the history into the completion as well?

```
$ vi A
directory
Aaaa/ Aaxy/
file
Aaa.py Abc.py
history
vi Awesome/somefile.txt
```

**Comment by marlonrichert** [comment]
I tried that some time in the past, but it had a significantly negative impact on completion speed. So, I discarded that idea.

However, if you can figure out a way to make it work without significantly reducing performance, feel free to submit a pull request. 🙂

**Comment by ad-on-is** [comment]
oh ok... 
well, I'm not the most experienced bash-programmer, so I'd have a hard time figuring out where to begin with. could you give me a short in-a-nutshell, what files/function need to be modified to include history results in the completion?

**Comment by ad-on-is** [comment]
Or maybe something else... I have zsh-autosuggestions installed which does exactly that, but I love the menu-select of zsh-autocomplete.

is there a way for <tab> to select zsh-autosuggestions (if available) otherwise use zsh-autocomplete?

**Comment by marlonrichert** [comment]
> is there a way for to select zsh-autosuggestions (if available) otherwise use zsh-autocomplete?

You can [press Ctrl-R](https://github.com/marlonrichert/zsh-autocomplete) to switch Zsh Autocomplete from completion mode to history search mode. The history item corresponding to the autosuggestion will be at or near the top.

Alternative, you can [configure Autocomplete to always start in history mode](https://github.com/marlonrichert/zsh-autocomplete/blob/3de533e7d322cec073f09264a6bf211e0ba627de/.zshrc#L7).

In both cases, you can press Ctrl-R to toggle back to completion mode.

**Comment by marlonrichert** [comment]
> could you give me a short in-a-nutshell, what files/function need to be modified to include history results in the completion?

Off the top of my head:
* Add to [`_autocomplete._main_complete.post`](https://github.com/marlonrichert/zsh-autocomplete/blob/3de533e7d322cec073f09264a6bf211e0ba627de/scripts/.autocomplete.compinit#L125) a call to [`_autocomplete.history_lines`](https://github.com/marlonrichert/zsh-autocomplete/blob/main/functions/completion/_autocomplete.history_lines).
* Modify the latter to set [`$min_lines` and `$max_lines`](https://github.com/marlonrichert/zsh-autocomplete/blob/3de533e7d322cec073f09264a6bf211e0ba627de/functions/completion/_autocomplete.history_lines#L12) to `1` when the function is called in this way.
* Test it with a reasonably large command history to see the impact on performance.

**Comment by ad-on-is** [comment]
Thx... my current history is around 500kb... will try a 10MB one

**Comment by marlonrichert** [comment]
The amount of bytes is not the limiting factor. It’s the number of history items that matters. In my experience, having more than ~500 entries causes significant slowdown.

**Comment by ad-on-is** [comment]
Assuming this command is correct, my history file should have 10k history items
```
sort .zsh_history | uniq -c | wc -l
10463
```

**Comment by marlonrichert** [comment]
`print $#history` is easier. 😉

**Comment by ad-on-is** [comment]
LOL, print $#history shows 10126

**Comment by mgussekloo** [comment]
This would be a great feature, even if it would only search a small number of recent history items.

**Comment by marlonrichert** [comment]
It might be feasible once #459 has been implemented.
