### ISSUE TITLE
zsh: do you wish to see all 3121 possibilities (3121 lines)?

### ISSUE THREAD

**Issue by CallumHoward** [marlonrichert/zsh-autocomplete#5]
As soon as I type there is a message `zsh: do you wish to see all 3121 possibilities (3121 lines)?`. Perhaps this is set from Oh-my-zsh. It causes problems because it eats keystrokes when typing. Is there a way to disable it?

**Comment by Dwight-D** [comment]
I think this should go away if you make sure pull the latest version and then call `compinit` before you source the script.

**Comment by marlonrichert** [comment]
I'm working on making this easier. I'll push an update soon.

**Comment by marlonrichert** [comment]
@CallumHoward I updated the code. Can you test if it resolves the issue for you?

**Comment by marlonrichert** [comment]
This should be resolved now. Please read the updated installation instructions: https://github.com/marlonrichert/zsh-autocomplete/blob/master/README.md#installation

I will close this issue now. Let me know if it needs to be reopened.

**Comment by CallumHoward** [comment]
Hi, sorry for slow response, been pretty busy. I'll try this tonight.

**Comment by marlonrichert** [comment]
> Also, make sure you follow the instructions about the order in which to load plugins. This is tricky with oh-my-zsh, so I had to split them into two groups and then alter oh-my-zsh.sh to load everything in the right sequence.

This should not be necessary anymore because of the changes I made for #1.

**Comment by CallumHoward** [comment]
I pulled the latest master but it still didn't work so I commented everything in my config to find the culprit. Here it is:

```zsh
# nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
```

This gets added when you install Node Version Manager, it seems to load some completion scripts which cause the problem. My solution will be to comment out the last line here. Thanks for a cool plugin!
