### ISSUE TITLE
Allow customizing warning messages

### ISSUE THREAD

**Issue by PythonNut** [marlonrichert/zsh-autocomplete#50]
### Is your feature request related to a problem? Please describe.
I would like to be able to customize the messages that `zsh-autocomplete` outputs. In particular, I would like to make the outputs extremely terse so they produce minimal visual distraction, although this would obviously be bad UX for new users.

### Describe the solution you'd like
I think it would be nice if the messages were customizable via `zstyle`.

**Comment by marlonrichert** [comment]
I've already been thinking about doing this. So, will do. 🙂

**Comment by marlonrichert** [comment]
@PythonNut @forivall This is available in the `dev` branch now. Please try it out.

**Comment by PythonNut** [comment]
Works great! Thank you!

**Comment by marlonrichert** [comment]
You're welcome. 😊 

Merged to `master`.
