### ISSUE TITLE
fzf trigger sequence (**) does not work as expected (even using control + space)

### ISSUE THREAD

**Issue by paw-lu** [marlonrichert/zsh-autocomplete#51]
This is some really cool work. Thanks for sharing it!

### Describe the bug

The fzf search menu no longer seems to pop up when the trigger sequence is used when zsh-autocomplete is enabled, even when using the new shortcut—[<kbd>control</kbd>](# "down")[<kbd>␣</kbd>](# "space").

### To Reproduce

```sh
% zsh -df

% [ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

% cat dir/** [TAB]
>
3/3
> dir/file1.txt
> dir/file2.txt
> dir/file3.txt

% source ~/dir/dir/zsh-autocomplete.plugin.zsh

% cat dir/** [CTRL][SPACE]
file1.txt    file2.txt    file3.txt
```

Of course, this fixes itself if I run `zstyle ':autocomplete:tab:*' completion fzf`.  [<kbd>tab</kbd>](# "tab") is now controlled by fzf, and the trigger sequence `**` works as expected. But then normal autocomplete seems broken at that point.

### Expected behavior

I thought [<kbd>control</kbd>](# "down")[<kbd>␣</kbd>](# "space") (with zsh-autocomplete) would trigger the kind of behaviour fzf would trigger by hitting [<kbd>tab</kbd>](# "tab") normally (without zsh-autocomplete).

### Desktop
 - OS + distribution:  macOS 10.15.5
 - Zsh version:  5.7.1
 - Plugin version:  33d98129

**Comment by marlonrichert** [comment]
> I thought [<kbd>control</kbd>](# "down")[<kbd>␣</kbd>](# "space") (with zsh-autocomplete) would trigger the kind of behaviour fzf would trigger by hitting [<kbd>tab</kbd>](# "tab") normally (without zsh-autocomplete).

Well, there's the crux of the matter: I never promised any such thing. 😉 

This is completely intentional. Since you now have one key binding for normal completion and one key binding for `fzf` completion, you really don't need the "trigger" sequence anymore. You can now choose on the spot which kind of completion style you want.

However, I could make it so that `zstyle ':autocomplete:tab:*' completion fzf` provides a sort "smart" behavior [that was suggested here](https://github.com/marlonrichert/zsh-autocomplete/issues/46#issuecomment-641533135) by @ztNFny.

Let's discuss: How should this really behave? There's more than one way to go about this and there is no obvious "right" one. 🙂

**Comment by marlonrichert** [comment]
> So—if I'm understanding correctly—<kbd>control</kbd>+<kbd>␣</kbd> is essentially the same as <kbd>control</kbd>+<kbd>T</kbd> (the default keyboard shortcut fzf creates)?

No, it's not. It's actually <kbd>⌥</kbd><kbd>␣</kbd>`fzf-cd-widget` plus alias expansion plus insert longest common expansion prefix plus <kbd>⇥</kbd>`fzf-completion` rolled into one. 🙂 If you're interested, you can find the code over here: https://github.com/marlonrichert/zsh-autocomplete/blob/dev/zsh-autocomplete.zsh#L710

**Comment by marlonrichert** [comment]
@paw-lu @ztNFny Can you please checkout the `dev` branch and try out the latest autocomplete behavior? I've made some enhancements and I'm wondering if this in any way changes your `fzf` integration needs.

**Comment by paw-lu** [comment]
@marlonrichert 
Thanks for the explanation on `fzf-cd-widget`—it really cleared things up!

I tried out `dev`. Thanks a lot for the work!

### 👍
fzf-specific <kbd>tab</kbd> features seem to be working as expected

- `kill [TAB]` works as expected now (with fzf taking over)
- Trigger sequences work (`**`) with fzf

### 👎
Pressing <kbd>tab</kbd> under "normal" expected circumstances leads to unexpected behavior.

- Directories trigger fzf instead of "normal" autocomplete or zsh-autocomplete.

  ```sh
  $ ls
  dir    folder    container
  
  # Without zsh-autocomplete
  $ cd con[TAB]

  $ cd container

  # With zsh-autcomplete
  $ cd con[TAB]
  >
  3/3
  dir
  folder
  container
  ```

- Arguments no longer complete upon pressing <kbd>tab</kbd>

  ```sh
  # Without zsh-autocomplete
  $ brew ins[TAB]

  $ brew install

  # With zsh-autocomplete
  $ brew inst[TAB]
  install   install a formula
  install-bundler-gems

  $ brew inst
  install   install a formula
  install-bundler-gems
  ```

So it seems that fzf works fine, but at the expense of the normally expected tab behavior.

**Comment by marlonrichert** [comment]
> - Directories trigger fzf instead of "normal" autocomplete or zsh-autocomplete.
> 
>   ```sh
>   $ ls
>   dir    folder    container
>   
>   # Without zsh-autocomplete
>   $ cd con[TAB]
> 
>   $ cd container
> 
>   # With zsh-autcomplete
>   $ cd con[TAB]
>   >
>   3/3
>   dir
>   folder
>   container
>   ```

`zsh-autocomplete`'s tab completion _never_ calls `fzf-completion`. It is called from control-space completion only.

On your command line, can you please run `bindkey '^I'`? If the output is `"^I" fzf-completion`, then there's something wrong with your setup. 🙂 

> - Arguments no longer complete upon pressing <kbd>tab</kbd>
> 
>   ```sh
>   # Without zsh-autocomplete
>   $ brew ins[TAB]
> 
>   $ brew install
> 
>   # With zsh-autocomplete
>   $ brew inst[TAB]
>   install   install a formula
>   install-bundler-gems
> 
>   $ brew inst
>   install   install a formula
>   install-bundler-gems
>   ```

That has nothing to do with `zsh-autocomplete`. For whatever reason, `brew`'s completion is just ridiculously slow. You'll find that without `zsh-autocomplete`, completion for `brew` is even more unusable. Please complain at https://github.com/Homebrew/brew/issues

In general, with `zsh-autocomplete`, if there are no completions listed, then pressing <kbd>⇥</kbd> will not do anything, because the list shows what it can complete at that moment in time. You either have to wait a moment or type more, until you get a list of completions. But once that list is visible, then tab completion should always be instantaneous (at least, on the `dev` branch right now).

**Comment by marlonrichert** [comment]
@paw-lu I did some testing and actually, `brew` completion is slow only when caching isn't use and `zsh-autocomplete` turns on caching. In a clean install, `brew` completion is slow. However, add `zsh-autocomplete` and use completion on `brew` commands a couple of times, and it becomes faster. If `brew` completion is slow for you all the time, then you really have not installed `zsh-autocomplete` correctly.

How exactly have you installed `zsh-autocomplete`?

**Comment by paw-lu** [comment]
I can confirm that you are correct about

```sh
❯ bindkey '^I'
"^I" fzf-completion
```

Is there an issue with that? That seems to be one of the default shortcuts that are bound when `[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh` is run. It's what I would expect to be bound to <kbd>^</kbd>+<kbd>I</kbd>.

I want to clarify about the Homebrew example. That was just a random command I chose and was not specific to homebrew. This happens across all commands. As far as I can tell, it is not "slow"—completion just isn't happening when hitting <kbd>tab</kbd>.

[Just to clear things up I recorded my screen.](https://photos.app.goo.gl/RGyKgNnsXckA8MYm6) First I show how directory and argument autocomplete normally work, then I activate zsh-autocomplete, then I try those two again. You can also see one way I "install" zsh-autocomplete in the recording.

**Comment by marlonrichert** [comment]
> I can confirm that you are correct about
> 
> ```sh
> ❯ bindkey '^I'
> "^I" fzf-completion
> ```
> 
> Is there an issue with that?

Yes, there definitely is a _major_ issue with that. It means that `zsh-autocomplete` has not been loaded correctly. Could you please share your `.zshrc` file with me, so I can try to figure out what has gone wrong?

**Comment by paw-lu** [comment]
Yeah no problem! 😄

I'm able to replicate this with an absolute minimum `.zshrc`. This is using oh-my-zsh.

```zsh
# Minimum .zshrc via oh-my-zsh
plugins=(
    zsh-autocomplete
)
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
zstyle ':autocomplete:tab:*' completion fzf

```

Obviously, it follows that we can reproduce this issue with a completely blank `.zshrc`.

```sh
%  [ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
% zstyle ':autocomplete:tab:*' completion fzf
% source zsh-autocomplete.zsh 
% bindkey '^I'
"^I" fzf-completion
```

Just for my understanding—I thought the goal here is to keep fzf running as expected and to keep zsh-autocomplete from "interfering" with its features. So I would naively think that fzf's default shortcuts should be surviving.

**Comment by marlonrichert** [comment]
> `zstyle ':autocomplete:tab:*' completion fzf`

Ah, right, I completely forgot about that. 🤦🏽‍♂️ That explains the `bindkey` output.

Thanks! Now I know what to tweak.

**Comment by marlonrichert** [comment]
@paw-lu @ztNFny Alright, I pushed in a new update on the `dev` branch. Can you please try it out?

**Comment by paw-lu** [comment]
Gave it a quick look. As far as I can tell this seems good!

### 👍

<kbd>tab</kbd> features seem to be working as expected

- [x] `kill [TAB]` works as expected (with fzf taking over)
- [x] Trigger sequences work (`**`) with fzf
- [x] Directories autocomplete with <kbd>tab</kbd>
- [x] Arguments autocomplete with <kbd>tab</kbd>

**Comment by marlonrichert** [comment]
@ztNFny How do you feel about the current behavior on the `dev` branch?

**Comment by paw-lu** [comment]
I'm willing to close this @marlonrichert is everyone is comfortable with the changes.

**Comment by ztNFny** [comment]
I'll try to take a look tomorrow/Sunday. Busy at work right now.

**Comment by ztNFny** [comment]
@marlonrichert sorry, still hadn't had the chance, work is killing me atm

**Comment by ztNFny** [comment]
just had a quick look at dev, more hopefully on the weekend:
- kill [tab] looks good
- so does FZF_COMPLETION_TRIGGER
- the new default "magic" space behaviour is killing me, don't think that's a good default option imho. especially the alias seems uncalled for.

**Comment by paw-lu** [comment]
What's the new magic space behavior?

Paulo S. Costa

**Comment by ztNFny** [comment]
See README.MD in dev. Basically it expands pretty much anything. History, suggestions, alias (this i find the most annoying, the point of aliases is to not gave the original command), spellcheck.
There's a config option but the default is to have it all on.

**Comment by marlonrichert** [comment]
Auto-expanding aliases is related to #60. I’ve actually read it works like that in Fish. But I do agree that it’s not very nice when you have very long aliases. I’ll have to tweak that a bit still.

**Comment by marlonrichert** [comment]
But anyway, if the `fzf`-related behavior looks god to you, then I’ll merge that part soon to `master`.

**Comment by ztNFny** [comment]
@marlonrichert fish doesn't insert aliases.

**Comment by marlonrichert** [comment]
OK. I just read it somewhere. ¯\_(ツ)_/¯

**Comment by marlonrichert** [comment]
Ah, I just discovered that what I'm doing to address #60 is [completely unnecessary](https://github.com/marlonrichert/zsh-autocomplete/issues/60#issuecomment-649242706). I'll remove it soon.

**Comment by marlonrichert** [comment]
Merged to `master`.
