### ISSUE TITLE
Add a configuration setting to add `-u` to `compinit` call

### ISSUE THREAD

**Issue by CraigSiemens** [marlonrichert/zsh-autocomplete#518]
## What do you want?
I'd be nice if there was an option to pass the `-u` flag to `compinit` in  [.autocomplete.compinit#L60](https://github.com/marlonrichert/zsh-autocomplete/blob/main/scripts/.autocomplete.compinit#L60)

Something like this, though conditionally added based on a configuration setting.
```
compinit -u -d $_comp_dumpfile
```

## Why do you want this?
By default `compinit` enforces that files loaded are owned by root or the current user. ([docs](https://zsh.sourceforge.io/Doc/Release/Completion-System.html#Use-of-compinit))

This causes a conflict when using homebrew on a system with multiple users. Homebrew doesn't allow being run as root, so that's not an option for the owner of the files. Then if a command is installed by user A, user B will always get the following message.

```
zsh compinit: insecure directories and files, run compaudit for list.                                                                                 
Ignore insecure directories and files and continue [y] or abort compinit [n]? 
```

Adding `-u` as an option allows skipping that check/warning when running on a multiuser system when the users are trusted.

## Who else would benefit from this?
- a multiuser system
- with completions installed at a global location 
- where the file owner can't be `root` for any reason

## How should it work?

Given the following situation:
* when the conditions above apply

When I perform the following steps:
1. Ideally, enable a new configuration setting to skip/ignore the user security check.

Then I expect the following to happen:
* The `compinit` warning about insecure directories should no longer be shown when files are owned by a user other than root.

**Comment by huyz** [comment]
Same here.

In my startup scripts, I have: 
```zsh
    # some conditional
        _compinit_args=(-u "${_compinit_args[@]}")
…
  compinit "${_compinit_args[@]}"
```

So I can't adopt zsh-autocomplete unless I can continue to specify `-u` as needed.

**Comment by kevcube** [comment]
Yes please, same problem. I can't use `znap` either for this reason.

**Comment by marlonrichert** [comment]
There you go: f79acc771eeb7ab9e61d731ad210a06b164cf992

Also available in Znap: https://github.com/marlonrichert/zsh-snap/commit/d1f282bbabda1cdf14c52c5d80f5dd032587307f
