### ISSUE TITLE
Plugin gets stuck with 100% one core usage when trying to autocomplete specific folder name from history

### ISSUE THREAD

**Issue by AndreaHasani** [marlonrichert/zsh-autocomplete#519]
- [x] I have carefully read all of the instructions in this issue template.
- [x] I have carried them out to the letter.

Failure to do so can and will result in your issue being closed without warning.

## Environment
```
pc linux-gnu /bin/zsh /bin/zsh zsh-5.9-0-g73d3173
/home/strixx/.config/.zim/init.zsh:11
/home/strixx/.config/.zshrc:86
866c661 (HEAD -> main, origin/main, origin/HEAD) Fix bug in compdump logic
```

* Operating system: 
* Terminal emulator: 

- [x] I have filled out the fields above.
- [x] I have ran the commands in the code block above.
- [x] I have pasted their output into the same block. 

## Steps to reproduce
```zsh
cd $(mktemp -d)
git clone --depth 1 -- https://github.com/marlonrichert/zsh-autocomplete.git
> .zshrc <<EOF
PS1='%# ' PS2= RPS2='%^'; setopt transientrprompt interactivecomments
source ~/zsh-autocomplete/zsh-autocomplete.plugin.zsh
EOF
env -i HOME=$PWD PATH=$PATH TERM=$TERM ${TERMINFO:+TERMINFO=$TERMINFO} zsh -d
mkdir pickled_instances_state
cd pickled_instances_state (up arrow to show history)
```
- [x] I have run the code block above to create a test environment.
- [x] I have reproduced my problem in this environment in the most minimal way possible.
- [x] I have copy-pasted my entire test session into the same code block.

## Issue

This issue is quite simply to reproduce, just create a folder called pickled_instances_state/ and use up arrow to go into history mode. zsh will not complete and use 100% cpu usage. Also if I press ctrl-c to cancel the action, something about _autocomplete.history is shown for less than 1s (it says killing that action) so I suspect the issue is somewhere there

Sometimes it does complete but the history is laggy and zsh keeps using 100% cpu usage.

My system is a ryzen 5800H so i doubt it has to do with power.

Also, should i make another git issue for another problem I have which includes the fact that this plugin history autocompletes by matching text with substring.

What i want to do is have it match the string i have written and find continuations.

**Comment by marlonrichert** [comment]
> Also, should i make another git issue for another problem I have which includes the fact that this plugin history autocompletes by matching text with substring.
> 
> What i want to do is have it match the string i have written and find continuations.

Yes, please open a feature request for that.

**Comment by marlonrichert** [comment]
@AndreaHasani Should be fixed now.

PS: If you enjoy using my software, please consider [sponsoring me](https://github.com/sponsors/marlonrichert). 🙂
