### ISSUE TITLE
[Help] How to disable auto directory listing?

### ISSUE THREAD

**Issue by aneesdev** [marlonrichert/zsh-autocomplete#526]
Hi,

Does anyone know how to disable auto directory listing? like here:

![image](https://user-images.githubusercontent.com/92947803/208298380-fd0b61b7-fc1c-4ef7-8b24-488aae902568.png)

I want directory listing only when I type a command.

@marlonrichert

**Comment by GiladGuralnikkk** [comment]
+1
same for me, I'm using mac M1 with powerlevel10k

**Comment by gabaji** [comment]
Put `zstyle ':autocomplete:*' min-input 1 ` in your .zshrc

**Comment by aneesdev** [comment]
> Put `zstyle ':autocomplete:*' min-input 1 ` in your .zshrc

Thanks man
