### ISSUE TITLE
Completion widget for history should follow the `min-input` setting

### ISSUE THREAD

**Issue by wtfzambo** [marlonrichert/zsh-autocomplete#527]
## What do you want?
The setting `zstyle ':autocomplete:*' min-input X` makes the completion widget appear after `X` characters have been typed. However, this only works for the command suggestion widget, but not for the history widget.

## Why do you want this?
I feel like it would provide a cleaner user experience. Currently, with 0 typed characters, the last 16 history lines are shown by default, which may or may not be relevant to the user.

## Who else would benefit from this?
Anyone using the history suggestion widget.

## How should it work?
Exactly like the command suggestion widget when setting `min-input > 0`

Given the following situation:
* `zstyle ':autocomplete:*' min-input X` and
* Context set to history search

When I perform the following steps:
1. If number of typed characters is less than `X`

Then I expect the following to happen:
* The history suggestion widget is not displayed until the number of typed characters is at least equal to `X`.

**Comment by marlonrichert** [comment]
@wtfzambo Should be fixed now. Let me know if it still doesn't work for you.

**Comment by marlonrichert** [comment]
@wtfzambo Should be fixed now. Let me know if it still doesn't work for you.

**Comment by marlonrichert** [comment]
@wtfzambo Should be fixed now. Let me know if it still doesn't work for you.

**Comment by wtfzambo** [comment]
Works great!

**Comment by marlonrichert** [comment]
Nice to hear! 🥳 

PS: If you enjoy using my software, please consider [sponsoring me](https://github.com/sponsors/marlonrichert). 🙂

**Comment by wtfzambo** [comment]
> Nice to hear! 🥳
> 
> PS: If you enjoy using my software, please consider [sponsoring me](https://github.com/sponsors/marlonrichert). 🙂

Sent a little donation over :)

**Comment by marlonrichert** [comment]
Very generous of you! Thanks! 🙇🏽‍♂️
