### ISSUE TITLE
Let user choose case sensitivity behaviour

### ISSUE THREAD

**Issue by g4cm4n** [marlonrichert/zsh-autocomplete#53]
Installing plugin seem to mess with zsh options about case insensitive completions. It would be great if user could decide about this feature in personal configuration or better yet if it could be done old way with plain zsh functionality. Perhaps it is possible, but i couldn't figure it out. Not sure if it's a bug or is it simply not implemented.
Maybe it's the matter of command order in zsh dotfiles? Many plugins have specific rules about that.
I'm using this plugin along with zsh-autosuggestions, zsh-completions, zsh-syntax-highlighting and fzf and i don't have any manager.

**Comment by marlonrichert** [comment]
Case-sensitivity is set separately in Zsh for many different circumstances. Can you give me some concrete examples of what behavior you would like to see and how `zsh-autocomplete` is doing it differently?

**Comment by g4cm4n** [comment]
Let's say i'm in "/etc" and i want to quickly change current directory to "~/workdir". Effeciency is the key in this buissnes, my boss says. I realize that and trying my best to be a good slave. My intention is to type "~/w" and let autocompletion do the rest. Sadly my finger slipped, i typed "~/W" and quickly hit completion button. Unfortunately i'm prompted with red coloured message: _No matching completions found._ :( I'm furiously tapping the key 13 more times but stupid machine is not listening! Now i have to make a great effort of fixing my mistake which is a catastrophy. My day is ruined and i think about quitting my job.

Few days passed by and I forgot my traumatic experiance. Back at work. I receive important file from my colleague and hmm... it look like an compressed archive. I think i know what to do next. While i was taking a quick peek at new receptionst i slowly began to type. Ok, she's gone. Let's make sure my input is correct so far. "UNZI" . Wait, what? Caps lock was enabled!!! HOW? Do i have to start over? No. After all i use elite zsh plugins - i know magic. Just press TAB. Pressing and... nothing. I'm trying again. Nothing.......... Next 50 tries didn't change the outcame. So now i'm wondering wheather to smash LCD with keyboard or simply kill myself.

In both cases, behaviour was different - expected that is - after disabling this plugin.

BTW, i had this option set whole time:
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'

**Comment by marlonrichert** [comment]
Yeah, `zsh-autocomplete` overrides the `matcher-list`. I could choose not to, but there's an awful lot of people using, for example, Oh-My-Zsh (or some other "framework" that sets the `matcher-list`), and they'll be terribly confused when `zsh-autocomplete` does not appear to work "correctly" out of the box.

But I _can_ provide a setting to make case insensitivity bi-directional, instead of only from lower- to uppercase, as `zsh-autocomplete` does by default. Or I could even just change the default. I'll try it out and see which one is better, and then maybe provide the other one as an option, if necessary.

**Comment by marlonrichert** [comment]
@g4cm4n An improved version of the matching algorithm is now available on the `dev` branch, which should address the problems you've been experiencing. In your clone of `zsh-autocomplete`, please do `git checkout dev`, restart your terminal, try it out and let me know what you think.

**Comment by g4cm4n** [comment]
Yes, issues i had before seem to be resolved on dev branch. Much appreciated.

**Comment by marlonrichert** [comment]
Merged to `master`
