### ISSUE TITLE
Using different keymaps disables the visible options

### ISSUE THREAD

**Issue by niksingh710** [marlonrichert/zsh-autocomplete#530]
- [x] I have carefully read all of the instructions in this issue template.
- [x] I have carried them out to the letter.

Failure to do so can and will result in your issue being closed without warning.

## Environment
```zsh
print $VENDOR $OSTYPE $SHELL $ZSH_ARGZERO $ZSH_PATCHLEVEL
print -l $_autocomplete__funcfiletrace
git -C ~zsh-autocomplete log --oneline -n1



pc linux-gnu /usr/bin/zsh zsh zsh-5.9-0-g73d3173
/home/niksingh710/.setup/shell/zsh/plugins/zsh-snap/functions/.znap.source:26
/home/niksingh710/.setup/shell/zsh/plugins/zsh-snap/functions/znap:42
/home/niksingh710/.config/shell/zsh/config:21
/home/niksingh710/.config/shell/rc:21
/home/niksingh710/.zshrc:2
d00142d (grafted, HEAD -> main, origin/main, origin/HEAD) Update VSCode settings
```

* Operating system:  Arch linux
* Terminal emulator:  foot

- [x] I have filled out the fields above.
- [x] I have ran the commands in the code block above.
- [x] I have pasted their output into the same block. 

## Steps to reproduce
```zsh

zstyle ':completion:*' menu select
zmodload zsh/complist
# use the vi navigation keys in menu completion
bindkey '^j' expand-or-complete 
bindkey -M menuselect '^h' vi-backward-char
bindkey -M menuselect '^k' vi-up-line-or-history
bindkey -M menuselect '^l' vi-forward-char
bindkey -M menuselect '^j' vi-down-line-or-history


```
- [x] I have run the code block above to create a test environment.
- [x] I have reproduced my problem in this environment in the most minimal way possible.
- [x] I have copy-pasted my entire test session into the same code block.

Using these zsh options.
using the line `zstyle ':completion:*' menu select`  does not show the prompt e.g `cd` not lilsting directories

**Comment by marlonrichert** [comment]
If you switch to the [`feature` branch](https://github.com/marlonrichert/zsh-autocomplete/tree/feature), does it solve the problem for you?

**Comment by niksingh710** [comment]
> If you switch to the [`feature` branch](https://github.com/marlonrichert/zsh-autocomplete/tree/feature), does it solve the problem for you?

Nope the result is same.

again on commenting the line `zstyle '*:completion:*' menu select` It worked as expected

**Comment by marlonrichert** [comment]
@niksingh710 The steps to reproduce you’ve provided do not include any statement to `source` Autcomplete. Please update your test case to be stand-alone runnable and I’ll reopen the issue.
