### ISSUE TITLE
`insert-unambiguous` and symlinks brake recent dirs with z.lua

### ISSUE THREAD

**Issue by BonaBeavis** [marlonrichert/zsh-autocomplete#531]
- [x] I have carefully read all of the instructions in this issue template.
- [x] I have carried them out to the letter.

Failure to do so can and will result in your issue being closed without warning.

## Environment
```zsh
ubuntu linux-gnu /usr/bin/zsh zsh ubuntu/5.9-1
/home/beavis/.zshrc:179
d00142d (grafted, HEAD -> main, origin/main, origin/HEAD) Update VSCode settings
Ubuntu 22.10
gnome-terminal
```

## Steps to reproduce
```zsh
cd $(mktemp -d)
git clone --depth 1 -- https://github.com/marlonrichert/zsh-autocomplete.git
> .zshrc <<EOF
PS1='%# ' PS2= RPS2='%^'; setopt transientrprompt interactivecomments
source ~/zsh-autocomplete/zsh-autocomplete.plugin.zsh
ZPLUGINDIR=~/.local/share/zsh/plugins
if [[ ! -d $ZPLUGINDIR/zsh_unplugged ]]; then
  git clone --quiet https://github.com/mattmc3/zsh_unplugged $ZPLUGINDIR/zsh_unplugged
fi
source $ZPLUGINDIR/zsh_unplugged/zsh_unplugged.zsh
plugin-load skywind3000/z.lua
zstyle ':autocomplete:*' recent-dirs 'z.lua'
_autocomplete.recent_directories() {
      reply=( ${${(f)"$( _zlua --complete $1 2> /dev/null )"}##<->[[:space:]]##} )
}
zstyle ':autocomplete:*' insert-unambiguous yes
ln -rs ~/zsh-autocomplete ~/zsh-autocomplete-test
mkdir -p a/b c
ln -rs a/b c/b
cd a/b
cd ../../
cd c/b
cd ../../

EOF
env -i HOME=$PWD PATH=$PATH TERM=$TERM ${TERMINFO:+TERMINFO=$TERMINFO} zsh -d
```

Now input `cd b` :
<pre><font color="#8B8B8B">recent directory</font>
<font color="#FF0086"><b>~/a/b</b></font>/  <font color="#1FAAAA"><b>~/c/b</b></font>@
</pre>
and press tab. This inserts `~/b` instead of `~/a/b/`

**Comment by marlonrichert** [comment]
I've changed the way how Autocomplete integrates with dir jumping tools. Have a look at the Readme.

**Comment by BonaBeavis** [comment]
Awesome works perfectly now! And feels somehow even faster and more fluent. I have one more question, could it be that `-` inside directory names could break the retrieval of recent-dirs?

**Comment by marlonrichert** [comment]
> could it be that `-` inside directory names could break the retrieval of recent-dirs? 

I tested it and it doesn't.

**Comment by marlonrichert** [comment]
BTW: If you enjoy using my software, please consider [sponsoring me](
