### ISSUE TITLE
Show alias values

### ISSUE THREAD

**Issue by PROxZIMA** [marlonrichert/zsh-autocomplete#532]
## What do you want?
Option to expand all the aliases which are provided in the suggestions.

## Why do you want this?
Here I've set some `git aliases` in a file and I've sourced them in `.zshrc`. After hitting the tab I'm getting the `aliases` as my suggestions.

![Screenshot from 2021-11-26 23-36-03](https://user-images.githubusercontent.com/43103163/143618142-d9636db5-e3d1-45e2-ac31-76b011b64845.png)

Is there any way to expand those suggestions(aliases) then and there only? Something like this.

```zsh
 ╭─proxzima@proxzima in ~ via  v3.9.5 took 87ms [ 100%]
 ╰─☣ gb
alias
gb: aliased to git branch
gba: aliased to git branch -a
gbd: aliased to git branch -d
gbD: aliased to git branch -D
gbm: aliased to git branch -m
gbM: aliased to git branch -M
gbnm: aliased to git branch --no-merged
gbr: aliased to git branch --remote
gbl: aliased to git blame -b -w
gbsb: aliased to git bisect bad
gbsg: aliased to git bisect good
gbsr: aliased to git bisect reset
gbss: aliased to git bisect start
```
I'm familiar with the `_expand_alias` flag but it provides alias expansion ***in*** the command line but not in the suggestions. My concern is related to alias expansion in the suggestions.

## Who else would benefit from this?
All those who are using the omz's `git` plugin as it provides lots of git related aliases.

## How should it work?
A flag that can enable/disable this feature.

Given the following situation:
* If the flag is enabled then the output can be similar to the one mentioned above.
* If the flag is disabled then there will be no change in the output.

**Comment by marlonrichert** [comment]
Good idea. I will probably implement this in Zsh upstream, not here, but I'll keep this issue open until I have.

**Comment by Myzel394** [comment]
any news here? I'd love to see this feature!

**Comment by marlonrichert** [comment]
I completely forgot that I had submitted a patch to Zsh for this about a year ago. Apparently, it got merged almost right away, but no one told me about it. It was added in https://github.com/zsh-users/zsh/commit/9a5f213573fbda6a6d23e985113eaeb849d4ee6d

**Comment by slacksystem** [comment]
Sorry to comment on this closed issue, I've been following but am a little confused. This was implemented in zsh a year ago? I still don't see this in my terminal. I've installed using apt on linux mint and it's the most recent version offered to me. Is this in a different release? Is there something I have to do to enable it? I'm using 5.8.1 apparently

**Comment by sa-mendez** [comment]
I am running the latest Arch and I confirmed that my zsh is on 5.9.

Also, I found that adding the following to my .zshrc:

`zstyle ':completion:*' completer _expand_alias _complete _ignored`

Is all I needed to do to get the alias completion to work.

**Comment by vinnymeller** [comment]
doing the above only completes the alias I have typed, e.g. typing `gm` will show `alias\ngit merge`

like the original ask I'd like to be able to get a list such as his original example:

```
 ╭─proxzima@proxzima in ~ via  v3.9.5 took 87ms [ 100%]
 ╰─☣ gb
alias
gb: aliased to git branch
gba: aliased to git branch -a
gbd: aliased to git branch -d
gbD: aliased to git branch -D
gbm: aliased to git branch -m
gbM: aliased to git branch -M
gbnm: aliased to git branch --no-merged
gbr: aliased to git branch --remote
gbl: aliased to git blame -b -w
gbsb: aliased to git bisect bad
gbsg: aliased to git bisect good
gbsr: aliased to git bisect reset
gbss: aliased to git bisect start
```

is it possible with the change, or I'm doing something wrong?

zsh version:
```
zsh --version
zsh 5.9 (x86_64-pc-linux-gnu)
```
on nixos

(1) have added `zstyle ':completion:*' completer _expand_alias _complete _ignored` as above and got the result I mentioned,

(2) have also tried `zstyle ':completion:*' verbose yes` and a couple other variants that seemed to do nothing

as well as 1 & 2 together, and a few other variants I can't think of off the top of my head. i've never really messed with this sort of config so realize I'm probably doing something wrong

does anyone have a snippet that accomplishes the original goal of this issue?

**Comment by akainth015** [comment]
Can this be re-opened? Using the `zstyle` mentioned also inhibits the completion of different aliases.

without `_expand_alias`
```
❯ gca
command
gca     gca!    gcam    gcan!   gcann!  gcans!  gcas    gcasm
```

with `_expand_alias`
```
❯ gca
alias
git commit --verbose --all
```

It would be nice to see the current alias' expansion in a display similar to `common substring` to understand what I'm running better , and use the menu to switch between the different completion options

**Comment by slacksystem** [comment]
Yeah I like the option to expand the current alias in shown completion options but it's such a bummer that I have to choose between that and seeing the common substring suggestions
