### ISSUE TITLE
History search only available with async

### ISSUE THREAD

**Issue by nopunYntendeed** [marlonrichert/zsh-autocomplete#533]
- [x] I have carefully read all of the instructions in this issue template.
- [x] I have carried them out to the letter.

Failure to do so can and will result in your issue being closed without warning.

## Environment
```zsh
print $VENDOR $OSTYPE $SHELL $ZSH_ARGZERO $ZSH_PATCHLEVEL
- pc linux-gnu /usr/bin/zsh zsh zsh-5.9-63-ge4aeb3b
print -l $_autocomplete__funcfiletrace
- empty
git -C ~zsh-autocomplete log --oneline -n1
- f52f45a (HEAD) Change precmd to chpwd for zlua
```

* Operating system: 
Linux  6.0.12-arch1-1  x86_64 GNU/Linux
* Terminal emulator: 
Konsole 22.12.0

- [x] I have filled out the fields above.
- [x] I have ran the commands in the code block above.
- [x] I have pasted their output into the same block. 

## Steps to reproduce
```zsh
cd $(mktemp -d)
git clone --depth 1 -- https://github.com/marlonrichert/zsh-autocomplete.git
> .zshrc <<EOF
PS1='%# ' PS2= RPS2='%^'; setopt transientrprompt interactivecomments
zstyle ':autocomplete:*' async no
source ~/zsh-autocomplete/zsh-autocomplete.plugin.zsh
EOF
env -i  PATH=$PATH TERM=$TERM ${TERMINFO:+TERMINFO=$TERMINFO} zsh -d
```
Press Ctrl+R for history search.

Expected: 
History menu search is still functional

Actual:
Defaults back to bck-i-search

Evidences:
![historyMenuNoAsync](https://user-images.githubusercontent.com/52470165/210529320-5cd03c00-046d-4716-9d00-769b0141da7f.png)

- [x] I have run the code block above to create a test environment.
- [x] I have reproduced my problem in this environment in the most minimal way possible.
- [x] I have copy-pasted my entire test session into the same code block.

---
Out of scope:
Thanks for the hard work Marlon. I will sponsor you asap.

**Comment by marlonrichert** [comment]
It’s not possible to provide history search with auto-updating search results without using asynchronous autocompletion. Sorry.
