### ISSUE TITLE
Allow for `vi`-like navigation in the completion menu

### ISSUE THREAD

**Issue by sellithy** [marlonrichert/zsh-autocomplete#537]
## What do you want?
Similar to how you can emulate `vi`-like navigation by setting
```zsh
bindkey -M menuselect 'h' vi-backward-char
bindkey -M menuselect 'k' vi-up-line-or-history
bindkey -M menuselect 'l' vi-forward-char
bindkey -M menuselect 'j' vi-down-line-or-history
```
allow for an option to navigate the completion menu using `h`, `k`, `l`, and `k`.

## Why do you want this?
I don't like taking my hands off the home row

## Who else would benefit from this?
Anyone who is used to vim navigation or had the `bindkey`s and wants to use this plugin.

## How should it work?
Simply, exactly like the arrow keys, at least at the beginning.

**Comment by marlonrichert** [comment]
You can bind these keys yourself in the `menuselect` keymap.
