### ISSUE TITLE
Update to the latest stable version tag for Homebrew package creation

### ISSUE THREAD

**Issue by near129** [marlonrichert/zsh-autocomplete#538]
I would like to submit a pull request to Homebrew. Please update to the latest stable version tag for creating the Homebrew package. 
As per the Homebrew guidelines, creating a Homebrew package requires a stable version tag.
(Reference: https://docs.brew.sh/Acceptable-Formulae#stable-versions)

Here is the link to the current Homebrew package (Formula) file: 
https://github.com/near129/homebrew-core/commit/ca43e692f1fb9ecb96235427c7aa0f4c1a39bfdb

**Comment by marlonrichert** [comment]
According to that same page, "stable" means

> e.g. not declared “unstable” or “beta” by upstream

So, there shouldn't be any obstacle for your submit that PR.

**Comment by near129** [comment]
OK, thank you!

**Comment by near129** [comment]
Hi, @marlonrichert.
I added the zsh-autocomplete formula to Homebrew, in https://github.com/Homebrew/homebrew-core/pull/122391.
Now macOS and Linux users can install the zsh-autocomplete with the following command.
```zsh
brew install zsh-autocomplete
```
Thanks for creating great tool!

**Comment by marlonrichert** [comment]
Nice work. Thank you, too! 👏🏽
