### ISSUE TITLE
Config option to disable or rebind history menu

### ISSUE THREAD

**Issue by OrangeBurrito** [marlonrichert/zsh-autocomplete#544]
## What do you want?
Forgive me if I'm mistaken, but there seems to be no way to outright hide the history menu that appears when using the up/down arrow keys, or to use the up/down arrow keys to select previous commands without opening said menu.

## Why do you want this?
For less terminal clutter, especially when the window is small.

## Who else would benefit from this?
Anyone who is used to oh-my-zsh up/down autocomplete.

## How should it work?
Add separate keybinding for up/down arrow command auto-completion, while preserving the up/down-line-or-search options.

**Comment by marlonrichert** [comment]
Yes, there is. Documented here: https://github.com/marlonrichert/zsh-autocomplete/blob/5cc9da132e7535a540fb1235ce27fd5a233d4f0e/.zshrc#L76

**Comment by DanKaplanSES** [comment]
Forgive my ignorance (I'm a newbie), but what's the proper way to modify this? I'm using oh-my-zsh and have follow the instructions of a manual install. Am I supposed to put `bindkey '\e[A' up-line-or-search` in my `~/.zshrc` to overwrite it, or am I supposed to modify something in `~/.oh-my-zsh/lib/key-bindings.zsh`?

**Comment by marlonrichert** [comment]
> Am I supposed to add `bindkey '\e[A' up-line-or-search` to my `~/.zshrc` to overwrite the default

Yes, that's always the place to put your own customizations.

> am I supposed to modify something in `~/.oh-my-zsh/lib/key-bindings.zsh`

No, because then you will likely not be able to update OMZ anymore.
