### ISSUE TITLE
Plugin creates new Windows zsh process for each key press and lags

### ISSUE THREAD

**Issue by mpenachayan** [marlonrichert/zsh-autocomplete#548]
- [x] I have carefully read all of the instructions in this issue template.
- [x] I have carried them out to the letter.

Failure to do so can and will result in your issue being closed without warning.

## Environment
```zsh
print $VENDOR $OSTYPE $SHELL $ZSH_ARGZERO $ZSH_PATCHLEVEL
print -l $_autocomplete__funcfiletrace
git -C ~zsh-autocomplete log --oneline -n1

pc msys /usr/bin/bash zsh zsh-5.9-0-g73d3173
5cc9da1 (HEAD -> main, origin/main, origin/HEAD) Fix typo in 8ef6b73
```

* Operating system: Windows MSYS
* Terminal emulator: Windows Terminal, Git Bash

- [x] I have filled out the fields above.
- [x] I have ran the commands in the code block above.
- [x] I have pasted their output into the same block. 

## Steps to reproduce
Just type some command or use arrows to navigate through ZSH command history. 
There is a noticeable lag between keyboard strokes and the letters showing up in screen
![image](https://user-images.githubusercontent.com/52072219/221150453-89a1f282-2da8-4e8e-891e-b0d7fc858906.png)

```zsh
cd $(mktemp -d)
git clone --depth 1 -- https://github.com/marlonrichert/zsh-autocomplete.git
> .zshrc <<EOF
PS1='%# ' PS2= RPS2='%^'; setopt transientrprompt interactivecomments
source ~/zsh-autocomplete/zsh-autocomplete.plugin.zsh
EOF
env -i HOME=$PWD PATH=$PATH TERM=$TERM ${TERMINFO:+TERMINFO=$TERMINFO} zsh -d
```
- [x] I have run the code block above to create a test environment.
- [x] I have reproduced my problem in this environment in the most minimal way possible.
- [x] I have copy-pasted my entire test session into the same code block.

EDIT: After testing in WSL, a new process for each key press is created but there is no lag whatsoever so maybe it's a problem in ZSH MSYS build

**Comment by marlonrichert** [comment]
> After testing in WSL, a new process for each key press is created but there is no lag whatsoever so maybe it's a problem in ZSH MSYS build

Hard for me to confirm or deny, as I do not have any Windows machines to test with. If you could do some more investigation yourself, I would appreciate it. 🙂

**Comment by mpenachayan** [comment]
I tried different things as disabling Windows Defender because I noticed the memory consumption went wild after creating so many zsh processes.
If I have some spare time I will try using diferent zsh builds for Windows

**Comment by rapandya** [comment]
I have similar issue on mac. it is starting new process with every key press. This process is keep running even after killing the iterm or terminal. Also the CPU is spiking up almost 100% because of this
