### ISSUE TITLE
Work better with history-substring-search-up/down

### ISSUE THREAD

**Issue by jcassee** [marlonrichert/zsh-autocomplete#55]
### Is your feature request related to a problem? Please describe.

Because zsh-autocomplete sets `zstyle ':zle:up/down-line-or-beginning-search' leave-cursor no`, it is awkward to use with up/down arrow keys bound to `history-substring-search-up/down`. When typing the up arrow, the cursor does not move to the end of the line.

```sh
% zsh -df
% source path/to/zsh-autocomplete.plugin.zsh
% autoload up-line-or-beginning-search
% zle -N up-line-or-beginning-search
% autoload down-line-or-beginning-search
% zle -N down-line-or-beginning-search
% bindkey "^[OA" up-line-or-beginning-search
% bindkey "^[OB" down-line-or-beginning-search
% z↑
```

### Describe the solution you'd like

Some way of getting prefix history search to move the cursor to the end of line while still working with zsh-autocomplete.

### Describe alternatives you've considered

Setting `zstyle ':zle:up/down-line-or-beginning-search' leave-cursor yes` does not work, because after pressing up once, the search prefix (apparently) becomes the whole line.

```sh
% zstyle ':zle:up-line-or-beginning-search' leave-cursor yes
% b↑↑
```

**Comment by marlonrichert** [comment]
@jcassee This should be fixed now on the `dev` branch. Please do a checkout and let me know if it works for you.

**Comment by jcassee** [comment]
I can confirm that this is fixed on the `dev` branch. For some reason it does not yet work with my full prezto config loaded. I'll try to find out why.

**Comment by daxmc99** [comment]
It seems to be working in dev

**Comment by marlonrichert** [comment]
Alright, it's now available in `master`.

**Comment by marlonrichert** [comment]
@jcassee @daxmc99 I pushed in a new fix on the `dev` branch that should work with any widget that has the word `history` or `search` in it. It would be great if you could try it out. 🙂

**Comment by daxmc99** [comment]
Thanks! I will take a look

**Comment by jcassee** [comment]
@marlonrichert This change seems to work very well. I had disabled the plugin again because of some interference I could not get to the bottom of, but I'm enabling it again and see how I fare. Thanks a lot!
