### ISSUE TITLE
Pressing 'Y' on "see all N possibilities

### ISSUE THREAD

**Issue by Tony-Sol** [marlonrichert/zsh-autocomplete#551]
- [x] I have carefully read all of the instructions in this issue template.
- [x] I have carried them out to the letter.

Failure to do so can and will result in your issue being closed without warning.

## Environment
```zsh
# print $VENDOR $OSTYPE $SHELL $ZSH_ARGZERO $ZSH_PATCHLEVEL
apple darwin22.0 /bin/zsh /bin/zsh zsh-5.8.1-0-g1a490c7
# print -l $_autocomplete__funcfiletrace
# empty line as output
# git -C ~zsh-autocomplete log --oneline -n1
5cc9da1 (HEAD, origin/main, origin/HEAD) Fix typo in 8ef6b73
```

* Operating system:  macOS
* Terminal emulator:  WezTerm

- [x] I have filled out the fields above.
- [x] I have ran the commands in the code block above.
- [x] I have pasted their output into the same block. 

## Steps to reproduce
```zsh
cd $(mktemp -d)
git clone --depth 1 -- https://github.com/marlonrichert/zsh-autocomplete.git
> .zshrc <<EOF
PS1='%# ' PS2= RPS2='%^'; setopt transientrprompt interactivecomments
source ~/zsh-autocomplete/zsh-autocomplete.plugin.zsh
EOF
env -i HOME=$PWD PATH=$PATH TERM=$TERM ${TERMINFO:+TERMINFO=$TERMINFO} zsh -d
```
- [ ] I have run the code block above to create a test environment.
- [ ] I have reproduced my problem in this environment in the most minimal way possible.
- [ ] I have copy-pasted my entire test session into the same code block.

**Comment by marlonrichert** [comment]
No idea what you are trying to report here.

**Comment by Tony-Sol** [comment]
Sorry, it was a draft which i accidentally submitted
Actual issue is https://github.com/marlonrichert/zsh-autocomplete/issues/552
