### ISSUE TITLE
Setting `widget-style` breaks ArrDwn keybinding

### ISSUE THREAD

**Issue by Tony-Sol** [marlonrichert/zsh-autocomplete#552]
- [x] I have carefully read all of the instructions in this issue template.
- [x] I have carried them out to the letter.

Failure to do so can and will result in your issue being closed without warning.

## Environment
```zsh
# print $VENDOR $OSTYPE $SHELL $ZSH_ARGZERO $ZSH_PATCHLEVEL
apple darwin22.0 /bin/zsh /bin/zsh zsh-5.8.1-0-g1a490c7
# print -l $_autocomplete__funcfiletrace
# empty string
# git -C ~zsh-autocomplete log --oneline -n1
5cc9da1 (HEAD, origin/main, origin/HEAD) Fix typo in 8ef6b73
```

* Operating system:  macOS
* Terminal emulator:  WezTerm

- [x] I have filled out the fields above.
- [x] I have ran the commands in the code block above.
- [x] I have pasted their output into the same block. 

## Steps to reproduce
```zsh
cd $(mktemp -d)
git clone --depth 1 -- https://github.com/marlonrichert/zsh-autocomplete.git
> .zshrc <<EOF
PS1='%# ' PS2= RPS2='%^'; setopt transientrprompt interactivecomments
source ~/zsh-autocomplete/zsh-autocomplete.plugin.zsh
EOF
env -i HOME=$PWD PATH=$PATH TERM=$TERM ${TERMINFO:+TERMINFO=$TERMINFO} zsh -d

# steps to reproduce
echo "zstyle ':autocomplete:*' widget-style menu-complete" >> .zshrc
source ~/.zshrc
cd zsh-autocomplete
# type `git ` and press down arrow key - you'll see message "do you wish to see all N possibilities (M lines)?"
# press 'Y' - shows `list-lines 16` lines
# press down arrow key - same message
# press down arrow key again
%git [B
```
- [x] I have run the code block above to create a test environment.
- [x] I have reproduced my problem in this environment in the most minimal way possible.
- [x] I have copy-pasted my entire test session into the same code block.

https://user-images.githubusercontent.com/33671815/222236257-a0acb473-d4fc-4a95-a053-841484630a89.mp4

**Comment by marlonrichert** [comment]
Can you checkout the [`feature` branch](https://github.com/marlonrichert/zsh-autocomplete/tree/feature) and see if the problem is solved there?

**Comment by Tony-Sol** [comment]
Yep, looks like it's all fin in `feature` branch

**Comment by marlonrichert** [comment]
`feature` has been merge into `main` now.
