### ISSUE TITLE
Remove the duplicated entry in `^R`

### ISSUE THREAD

**Issue by zhou13** [marlonrichert/zsh-autocomplete#553]
## What do you want?

Remove the duplicated entry in `^R`.

## How should it work?
When you press `^R` and input some common strings, no duplicated command should be shown.

When I perform the following steps:
1. press `^Rls`
2. I got

<img width="482" alt="Screenshot 2023-03-02 at 5 19 58 PM" src="https://user-images.githubusercontent.com/576382/222607505-a8c0938b-22d0-4d53-939e-b6001c8729d3.png">

Then I expect the following to happen:
* Going through 10+ `ls` commands from history not very efficient
* It will be better if the history can be deduplicated.

**Comment by marlonrichert** [comment]
Use `setopt HIST_FIND_NO_DUPS`. See #129.
