### ISSUE TITLE
Implement better keybinding logic for the history menu

### ISSUE THREAD

**Issue by zhou13** [marlonrichert/zsh-autocomplete#554]
This might be a regression of https://github.com/marlonrichert/zsh-autocomplete/issues/297

- [x] I have carefully read all of the instructions in this issue template.
- [x] I have carried them out to the letter.

Failure to do so can and will result in your issue being closed without warning.

## Environment
```zsh
apple darwin22.0 /bin/zsh zsh zsh-5.9-0-g73d3173print -l $_autocomplete__funcfiletrace
/Users/yichaozhou/.zgen/zgen.zsh:368
/Users/yichaozhou/.zgen/zgen.zsh:492
/Users/yichaozhou/.zshrc:20
5cc9da1
```
* Operating system: MacOS
* Terminal emulator: Kitty

- [x] I have filled out the fields above.
- [x] I have ran the commands in the code block above.
- [x] I have pasted their output into the same block. 

## Steps to reproduce
```zsh
cd $(mktemp -d)
git clone --depth 1 -- https://github.com/marlonrichert/zsh-autocomplete.git
> .zshrc <<EOF
PS1='%# ' PS2= RPS2='%^'; setopt transientrprompt interactivecomments
source ~/zsh-autocomplete/zsh-autocomplete.plugin.zsh
EOF
env -i HOME=$PWD PATH=$PATH TERM=$TERM ${TERMINFO:+TERMINFO=$TERMINFO} zsh -d
```

* Enter `ls<cr>`
* Enter `<Up>`
* You get `ls;` instead of `ls`
- [x] I have run the code block above to create a test environment.
- [x] I have reproduced my problem in this environment in the most minimal way possible.
- [x] I have copy-pasted my entire test session into the same code block.

**Comment by marlonrichert** [comment]
Looks like I broke this in 574b16c

**Comment by marlonrichert** [comment]
@zhou13 To exit the history menu, press Enter, Tab, Backspace or Delete, or just type something.

**Comment by marlonrichert** [comment]
The reason I changed it is the problem that if you aborted the history menu, you'd be stuck with the rebound arrows in the completion menu. However, I could work around that by resetting them in a `line-init` hook.

**Comment by marlonrichert** [comment]
Or actually, no, that wouldn’t work, because you can end up on the same command line after interrupting. Perhaps a single-use `line-pre-redraw` hook would work.

**Comment by zhou13** [comment]
Another thing that might be related on exiting the history menu is that when doing
1. press `<C-r>`
2. press `<down>` several times
3. press `<BS>`

You will find that you are still in the history menu... Not sure how to exit it.  However, if you replace 2 with `<up>`, then you can successfully exit with backspace in 3.

**Comment by marlonrichert** [comment]
Should be fixed now. Let me know if it doesn't work for you.
