### ISSUE TITLE
100% CPU load while typing

### ISSUE THREAD

**Issue by LeeeeT** [marlonrichert/zsh-autocomplete#556]
My CPU goes 100% when I type anything in the terminal. This is not noticeable if you type slowly or for a short period of time.

- [x] I have carefully read all of the instructions in this issue template.
- [x] I have carried them out to the letter.

## Environment
```zsh
print $VENDOR $OSTYPE $SHELL $ZSH_ARGZERO $ZSH_PATCHLEVEL
print -l $_autocomplete__funcfiletrace
git -C ~zsh-autocomplete log --oneline -n1

pc linux-gnu /bin/zsh zsh zsh-5.9-0-g73d3173

5cc9da1 (HEAD -> main, origin/main, origin/HEAD) Fix typo in 8ef6b73
```

![Screenshot](https://user-images.githubusercontent.com/95910070/224309765-fd7c563a-6a37-4480-bf2a-f2f13e05d887.png)

* Operating system: I use arch btw
* Terminal emulator: GNOME Terminal

- [x] I have filled out the fields above.
- [x] I have ran the commands in the code block above.
- [x] I have pasted their output into the same block. 

## Steps to reproduce
```zsh
cd $(mktemp -d)
git clone --depth 1 -- https://github.com/marlonrichert/zsh-autocomplete.git
> .zshrc <<EOF
PS1='%# ' PS2= RPS2='%^'; setopt transientrprompt interactivecomments
source ~/zsh-autocomplete/zsh-autocomplete.plugin.zsh
EOF
env -i HOME=$PWD PATH=$PATH TERM=$TERM ${TERMINFO:+TERMINFO=$TERMINFO} zsh -d

Cloning into 'zsh-autocomplete'... done.
% asdasdasdasdasdasdasdasdasdasdasdasdasdasdasd
```
- [x] I have run the code block above to create a test environment.
- [x] I have reproduced my problem in this environment in the most minimal way possible.
- [x] I have copy-pasted my entire test session into the same code block.

**Comment by marlonrichert** [comment]
Can you checkout the [`feature` branch](https://github.com/marlonrichert/zsh-autocomplete/tree/feature) and see if the problem is solved there?

**Comment by LeeeeT** [comment]
The same problem on https://github.com/marlonrichert/zsh-autocomplete/commit/00c2a07c77847093ed29a4f8151dc930343b5972.

**Comment by marlonrichert** [comment]
@LeeeeT @4ooc Can you update and check if this is still a problem?

**Comment by LeeeeT** [comment]
@marlonrichert Still the same on 2c7a323.

**Comment by LeeeeT** [comment]
For me, it is reproducing even inside a docker container.

```console
docker run -it ubuntu bash
```
Then run the commands from the "Steps to reproduce" section.

**Comment by LeeeeT** [comment]
I was able to reproduce it on a machine provided by GitHub Codespaces. Maybe this will help you debug.

**Comment by marlonrichert** [comment]
@LeeeeT Can you give me some pointers on how to do? Never used Codespaces before.

**Comment by LeeeeT** [comment]
@marlonrichert You can read about how to create and use Codespaces directly from native VS Code in the [docs](https://docs.github.com/en/codespaces/developing-in-codespaces/creating-a-codespace-for-a-repository?tool=vscode). Codespaces have zsh pre-installed, so you can reproduce the bug simply by running the command from the "Steps to reproduce" section.

**Comment by marlonrichert** [comment]
Unable to reproduce this on current `main` branch.
