### ISSUE TITLE
Invalid flags `nolast` and `.auto-suffix-retain` with `insert-unambiguous yes`

### ISSUE THREAD

**Issue by aaronkollasch** [marlonrichert/zsh-autocomplete#564]
- [x] I have carefully read all of the instructions in this issue template.
- [x] I have carried them out to the letter.

Failure to do so can and will result in your issue being closed without warning.

## Environment
```console
% print $VENDOR $OSTYPE $SHELL $ZSH_ARGZERO $ZSH_PATCHLEVEL
apple darwin22.0 /bin/zsh -zsh zsh-5.9-0-g73d3173
% print -l $_autocomplete__funcfiletrace
/Users/aaron/.zshrc:21
% git -C ~zsh-autocomplete log --oneline -n1
5cc9da1 (HEAD -> main, origin/main, origin/HEAD) Fix typo in 8ef6b73
```

* Operating system: macOS 13.3 Ventura
* Terminal emulator: Terminal.app, iTerm2

- [x] I have filled out the fields above.
- [x] I have ran the commands in the code block above.
- [x] I have pasted their output into the same block. 

## Steps to reproduce
```console
% cd $(mktemp -d)
git clone --depth 1 -- https://github.com/marlonrichert/zsh-autocomplete.git
> .zshrc <<EOF
PS1='%# ' PS2= RPS2='%^'; setopt transientrprompt interactivecomments
source ~/zsh-autocomplete/zsh-autocomplete.plugin.zsh
EOF
env -i HOME=$PWD PATH=$PATH TERM=$TERM ${TERMINFO:+TERMINFO=$TERMINFO} zsh -d
Cloning into 'zsh-autocomplete'...
remote: Enumerating objects: 57, done.
remote: Counting objects: 100% (57/57), done.
remote: Compressing objects: 100% (55/55), done.
remote: Total 57 (delta 0), reused 30 (delta 0), pack-reused 0
Receiving objects: 100% (57/57), 1.64 MiB | 6.31 MiB/s, done.
% zstyle ':autocomplete:*' insert-unambiguous yes
% zsh_math_func_
.autocomplete.async.complete:zle:36: invalid flag `nolast' given to zle -f
.autocomplete.async.complete:zle:36: invalid flag `.auto-suffix-retain' given to zle -f
% zsh_math_func_
shell function
zsh_math_func_max  zsh_math_func_min  zsh_math_func_sum
```

In the last prompt, I type `zs<Tab>`, then two `zle` errors print and the prompt resets with `zsh_math_func_` filled.

- [x] I have run the code block above to create a test environment.
- [x] I have reproduced my problem in this environment in the most minimal way possible.
- [x] I have copy-pasted my entire test session into the same code block.

**Comment by JuanZoran** [comment]
i met the same issue as well

**Comment by marlonrichert** [comment]
It appears that you are actually running Zsh 5.8, even though `$ZSH_VERSION` report `5.8`. There's something wrong with your Zsh installation or the way you start your Zsh session. I can't check for the Zsh version if it's not set correctly.
