### ISSUE TITLE
Line limit setting doesn't work

### ISSUE THREAD

**Issue by thorn-jmh** [marlonrichert/zsh-autocomplete#566]
- [x] I have carefully read all of the instructions in this issue template.
- [x] I have carried them out to the letter.

Failure to do so can result in your issue being closed.

## Environment
```zsh
typeset -p1 VENDOR OSTYPE SHELL ZSH_ARGZERO ZSH_PATCHLEVEL _autocomplete__funcfiletrace
git -C ~zsh-autocomplete log --oneline -n1

pc linux-gnu /bin/zsh zsh zsh-5.9-0-g73d3173
.zshrc:92
zsh:3
2c7a323 (grafted, HEAD -> main, origin/main, origin/HEAD) Remove debug code
```

* Operating system: arch linux x86_64
* Terminal emulator: xfce4-terminal

- [x] I have filled out the fields above.
- [x] I have ran the commands in the code block above.
- [x] I have pasted their output into the same block.

## Steps to reproduce
```zsh
cd $(mktemp -d)
git clone --depth 1 -- https://github.com/marlonrichert/zsh-autocomplete.git
> .zshrc <<EOF
PS1='%# ' PS2= RPS2='%^'; setopt transientrprompt interactivecomments
source ~/zsh-autocomplete/zsh-autocomplete.plugin.zsh
EOF
env -i HOME=$PWD PATH=$PATH TERM=$TERM ${TERMINFO:+TERMINFO=$TERMINFO} zsh -d

vim .zshrc

# add `export HISTFILE="$HOME/.zsh_history"` before source autocomplete and save changes

source .zshrc

# enter more than 16 instructions 

^[[A
```
the history list will be more than 16 lines ( actually it will cover all lines if you have lots of histories )

![image.png](https://s2.loli.net/2023/04/06/EZD1OymrIT9fnAw.png)

I tried to change max line following [this](https://github.com/marlonrichert/zsh-autocomplete#limit-the-number-of-lines-shown), but it doesn't work.

And the history menu only bloats when I press `pgup`,  when I use `ctrl+r`, it's just 16 lines

- [x] I have run the code block above to create a test environment.
- [x] I have reproduced my problem in this environment in the most minimal way possible.
- [x] I have copy-pasted my entire test session into the same code block.

**Comment by marlonrichert** [comment]
> I tried to change max line following [this](https://github.com/marlonrichert/zsh-autocomplete#limit-the-number-of-lines-shown), but it doesn't work.

Can you please update your steps to reproduce to show _exactly_ how you tried to change the the number of lines.
