### ISSUE TITLE
`compcache` created in `~/~/.cache/zsh` instead of `~/.cache/zsh`

### ISSUE THREAD

**Issue by ywwry66** [marlonrichert/zsh-autocomplete#575]
## Environment

784e3a9 (HEAD -> main, origin/main, origin/HEAD) Move logs to $XGD_STATE_DIR

* Operating system:  macOS 13.3.1
* Terminal emulator:  Terminal.app

## Steps to reproduce

* Install `brew` (Don't know what other programs triggers creation of `compcache`, sorry for the inconvenience)
* put the following in `~/.zshrc`
```zsh
FPATH="$(brew --prefix)/share/zsh/site-functions:${FPATH}"
source ~/zsh-autocomplete/zsh-autocomplete.plugin.zsh
```
* open Terminal.app and run `brew ls`
* `~/~/.cache/zsh/compcache` is created.

Expected result: `~/.cache/zsh/compcache` is created, which is the behavior before 784e3a9.

**Comment by aliculPix4D** [comment]
For me `~/.cache/zsh/compcache` is created in every directory from which I execute some commands.

**Comment by ywwry66** [comment]
> For me `~/.cache/zsh/compcache` is created in every directory from which I execute some commands. This is super annoying of course.

Yes, can confirm this is the behavior on my machine as well.

**Comment by mebaran** [comment]
This is a major issue for me too and can confirm similar behavior.
