### ISSUE TITLE
The result of zsh-autosuggestions is remaining in menu-select

### ISSUE THREAD

**Issue by yutkat** [marlonrichert/zsh-autocomplete#576]
- [x] I have carefully read all of the instructions in this issue template.
- [x] I have carried them out to the letter.

Failure to do so can result in your issue being closed.

## Environment
```zsh
typeset -p1 VENDOR OSTYPE SHELL ZSH_ARGZERO ZSH_PATCHLEVEL _autocomplete__funcfiletrace

typeset VENDOR=pc
typeset OSTYPE=linux-gnu
export SHELL=/usr/bin/zsh
typeset ZSH_ARGZERO=zsh
typeset ZSH_PATCHLEVEL=zsh-5.9-0-g73d3173
typeset -a _autocomplete__funcfiletrace

git -C ~zsh-autocomplete log --oneline -n1

784e3a9 (HEAD -> main, origin/main, origin/HEAD) Move logs to `$XGD_STATE_DIR`
```

* Operating system: Arch Linux
* Terminal emulator: wezterm

- [x] I have filled out the fields above.
- [x] I have ran the commands in the code block above.
- [x] I have pasted their output into the same block.

## Steps to reproduce
```zsh
cd $(mktemp -d)
env -i HOME=$PWD PATH=$PATH TERM=$TERM ${TERMINFO:+TERMINFO=$TERMINFO} zsh -d
git clone --depth 1 -- https://github.com/marlonrichert/zsh-autocomplete.git marlonrichert---zsh-autocomplete
git clone --depth 1 -- https://github.com/zsh-users/zsh-autosuggestions zsh-users---zsh-autosuggestions

source ~/marlonrichert---zsh-autocomplete/zsh-autocomplete.plugin.zsh
source ~/zsh-users---zsh-autosuggestions/zsh-autosuggestions.zsh

bindkey '\t' menu-select "$terminfo[kcbt]" menu-select
bindkey -M menuselect '\t' menu-complete "$terminfo[kcbt]" reverse-menu-complete
```

```zsh
source 
```

![swappy-20230414-170148](https://user-images.githubusercontent.com/8683947/231984614-37474d37-aafb-4800-a615-4cbf03bf339a.png)

Suggestion are displayed by zsh-autosuggestions.

And type `<Tab>`.

The result of zsh-autosuggestions is remaining.

![swappy-20230414-170202](https://user-images.githubusercontent.com/8683947/231984611-0422b2a6-b96a-496d-9fa8-2f0aeab6e810.png)

My memory is that it used to disappear just fine before the recent refactoring.

- [x] I have run the code block above to create a test environment.
- [x] I have reproduced my problem in this environment in the most minimal way possible.
- [x] I have copy-pasted my entire test session into the same code block.

**Comment by marlonrichert** [comment]
Unable to reproduce this on current `main`.

**Comment by yutkat** [comment]
In my environment it was still reproducing but I increased the delay for autosuggestions to load and it seems to have improved.

If it reoccurs again, I will clarify the reproduction procedure and report back.

**Comment by raxod502** [comment]
I updated to the latest `main` branch and the behavior has not changed for me. Here's a Dockerfile that reproduces the behavior:

```
FROM ubuntu:22.04
RUN apt-get update
RUN apt-get install -y zsh
RUN apt-get install -y curl
RUN apt-get install -y git
RUN chsh -s /usr/bin/zsh
CMD ["zsh"]
RUN bash -c "$(curl --fail --show-error --silent --location https://raw.githubusercontent.com/zdharma-continuum/zinit/HEAD/scripts/install.sh)"
RUN echo 'zinit light zsh-users/zsh-autosuggestions' >> ~/.zshrc
RUN echo 'zinit light marlonrichert/zsh-autocomplete' >> ~/.zshrc
RUN echo "bindkey '\t' menu-select \"\$terminfo[kcbt]\" menu-select" >> ~/.zshrc
RUN echo "bindkey -M menuselect '\t' menu-complete \"\$terminfo[kcbt]\" reverse-menu-complete" >> ~/.zshrc
```

Simply build and run the Dockerfile, run the command `false`, then type `f` and use `TAB` to cycle through autocompletions. Observed behavior:

![image](https://user-images.githubusercontent.com/6559064/236648652-7d2da53d-e1aa-4fb1-ba9b-d7fb37ae008d.png)

Expected behavior: the string `alse` should not be displayed after the selected completion `float`.

**Comment by yutkat** [comment]
Maybe it would work if loaded in reverse order. I think I need to load zsh-autocomplete first.

```bash
RUN echo 'zinit light marlonrichert/zsh-autocomplete' >> ~/.zshrc
RUN echo 'zinit light zsh-users/zsh-autosuggestions' >> ~/.zshrc
```

**Comment by raxod502** [comment]
I see the same behavior whichever order the plugins are loaded in (easy to verify by modifying the Dockerfile above).

**Comment by raxod502** [comment]
The fix works beautifully, thank you so much!
