### ISSUE TITLE
Eats quotes

### ISSUE THREAD

**Issue by daxmc99** [marlonrichert/zsh-autocomplete#58]
### Describe the bug

zsh removes double quotes from commands

### To Reproduce

Try to do `git commit -m "Test commit"` 
The autocompletion / autocorrect will remove the quotes from the command. 

### Expected behavior

Maybe disabling of auto-complete when a `"` character is detected? At that point I am going to be typing a string so there should be nothing to complete

### Additional context

On `dev` branch

**Comment by marlonrichert** [comment]
I cannot reproduce this in any way, shape or form. Here's what I tried:
```shell
$ cd "$(mktemp -d)"
$ ZDOTDIR=$PWD HOME=$PWD zsh -df
% source path/to/marlonrichert/zsh-autocomplete/zsh-autocomplete.plugin.zsh
% git init
% git commit -m "Test commit"
```
and I then pressed <kbd>Tab</kbd>, <kbd>Space</kbd>, <kbd>Enter</kbd>, <kbd>Ctrl</kbd><kbd>Space</kbd>, <kbd>Shift</kbd><kbd>Tab</kbd>, you name it. Nothing happens, least of all to the quotes.

Can you please `git pull` to update your copy of the `dev` branch, restart your shell and try the above? If the problem does not occur with you either under these circumstances, then the problem must be somewhere in your config.

Next step would be to figure out what exactly in your config clashes with `zsh-autocomplete`. You could try executing lines from your `.zshrc` one by one in the sub shell  created above until you find what causes the problem.

**Comment by yutakatay** [comment]
I was experiencing the same problem until yesterday.
But, when I updated the master(4ad65c910768acc8d7c373fa01041292ac720ae6) today, it stopped happening for me.

**Comment by daxmc99** [comment]
@yutakatay Thanks for commenting, after upgrading to master (e03aeb2cdd5b8463df5f54a782e4261898d94987) I'm not longer seeing the issue. 
Feel free to close
