### ISSUE TITLE
<Tab> cycle  in the menu behavior:

### ISSUE THREAD

**Issue by wookayin** [marlonrichert/zsh-autocomplete#580]
- [x] I have carefully read all of the instructions in this issue template.
- [x] I have carried them out to the letter.

Failure to do so can result in your issue being closed.

## Description

![GIF](https://user-images.githubusercontent.com/1009873/233464200-66fd3c82-dd86-4c48-8898-04cb8059f0c6.gif)

As you can see in the GIF, when I use `Tab` to cycle through the completion menu there is a ghost text appearing in the prompt. Not sure where they come from. I used the bindkey commands in the README to make `Tab` cycle through the menu.

## Environment
```zsh
typeset -p1 VENDOR OSTYPE SHELL ZSH_ARGZERO ZSH_PATCHLEVEL _autocomplete__funcfiletrace
git -C ~zsh-autocomplete log --oneline -n1
```
```
typeset VENDOR=apple
typeset OSTYPE=darwin21.3.0
export SHELL=/opt/homebrew/bin/zsh
typeset ZSH_ARGZERO=zsh
typeset ZSH_PATCHLEVEL=zsh-5.9-0-g73d3173
typeset -a _autocomplete__funcfiletrace=(
  /Users/wookayin/.zsh_plugins.zsh:13
  /Users/wookayin/.zshrc:153
  zsh:0
)
784e3a9 (grafted, HEAD -> main, origin/main, origin/HEAD) Move logs to `$XGD_STATE_DIR`
```

* Operating system: macOS
* Terminal emulator: agnostic (kitty, iTerm2)

- [x] I have filled out the fields above.
- [x] I have ran the commands in the code block above.
- [x] I have pasted their output into the same block.

## Steps to reproduce
```zsh
# Minimal setup
cd $(mktemp -d)
git clone --depth 1 -- https://github.com/marlonrichert/zsh-autocomplete.git
> .zshrc <<EOF
PS1='%# ' PS2= RPS2='%^'; setopt transientrprompt interactivecomments
source ~/zsh-autocomplete/zsh-autocomplete.plugin.zsh
EOF
env -i HOME=$PWD PATH=$PATH TERM=$TERM ${TERMINFO:+TERMINFO=$TERMINFO} zsh -d

# Make Tab go straight to the menu and cycle there
bindkey '\t' menu-select "$terminfo[kcbt]" menu-select
bindkey -M menuselect '\t' menu-complete "$terminfo[kcbt]" reverse-menu-complete
```
- [x] I have run the code block above to create a test environment.
- [ ] I have reproduced my problem in this environment in the most minimal way possible.
- [x] I have copy-pasted my entire test session into the same code block.

Note:

- With the minimal reproduction template the bug does not happen. So I guess this is some sort of conflicts with other plugins, like powerlevel10k or [F-Sy-H](https://github.com/z-shell/F-Sy-H). However disabling both also makes the problem happening.

**Comment by marlonrichert** [comment]
Unable to reproduce this on current `main` branch.

**Comment by marlonrichert** [comment]
> With the minimal reproduction template the bug does not happen.

@wookayin Instead of giving a 👎🏽, you could update your test case to actually reproduce the problem. If I cannot reproduce it, I cannot fix it.

**Comment by marlonrichert** [comment]
Do try out the current `main` branch, by the way. If it works there for me, it might work there for you, too. 🙂
