### ISSUE TITLE
Use <left> and <Right> to move the cursor in the history menu

### ISSUE THREAD

**Issue by zhou13** [marlonrichert/zsh-autocomplete#582]
## What do you want?
Use `<left>` and `<right>` arrow keys to move the cursor in the history menu.

## Why do you want this?
Right now, `<left>` and `<Right>` move the selection in the history menu (triggered by `<Up>` or `<C-s>`). If I want to edit the current selection, I have to exit the menu with an extra `<BS>` and then use `<left>` and `<right>`.

Since the function of `<left>` and `<right>` is the same as `<up> and `<down>` as far as I can tell, they are not very useful in the history menu.

## Who else would benefit from this?
People who wants to use `<left>` and `<right>` arrow keys to move the cursor in the history menu.

## How should it work?
Use `<left>` and `<right>` arrow keys to move the cursor in the history menu.

Given the following situation:
* open a shell

When I perform the following steps:
1.  `<Up>`
2. `<Left>`

Then I expect the following to happen:
* Cursor will move to left instead of changing the selection in the history menu.

**Comment by marlonrichert** [comment]
You can now press <kbd>Enter</kbd> to exit the history menu (and the completion menu, too). Hopefully that helps.

I've tried implementing this feature previously, but it's really hard to keep it from breaking during runtime. Not interested in spending resources on maintaining this anymore. It's more trouble than it's worth.
