### ISSUE TITLE
_autocomplete.history_lines:shift:(102/125): argument to shift must be non-negative

### ISSUE THREAD

**Issue by travelskid** [marlonrichert/zsh-autocomplete#587]
- [x] I have carefully read all of the instructions in this issue template.

- [x] I have carried them out to the letter.

Failure to do so can result in your issue being closed.

## Environment
```zsh
VENDOR= pc
OSTYPE= linux-gnu
SHELL=zsh
ZSH_ARGZERO ZSH_PATCHLEVEL=zsh-5.9-0-g73d3173
_autocomplete__funcfiletrace=(
$ZSH/oh-my-zsh.sh:170
$ZSH/oh-my-zsh.sh:199
$ZDOTDIR/.zshrc:70
zsh:0
)
f79acc7 (HEAD -> main, origin/main, origin/HAED) Add setting for 'compinit' arguments
```

* Operating system: archlinux 6.3.1
* Terminal emulator: linux console (tty vconsole)

- [x] I have filled out the fields above.
- [x] I have ran the commands in the code block above.
- [x] I have pasted their output into the same block.

## Steps to reproduce
```zsh
cd $(mktemp -d)
git clone --depth 1 -- https://github.com/marlonrichert/zsh-autocomplete.git
> .zshrc <<EOF
PS1='%# ' PS2= RPS2='%^'; setopt transientrprompt interactivecomments
source ~/zsh-autocomplete/zsh-autocomplete.plugin.zsh
EOF
env -i HOME=$PWD PATH=$PATH TERM=$TERM ${TERMINFO:+TERMINFO=$TERMINFO} zsh -d
```
- [x] I have run the code block above to create a test environment.
- [x] I have reproduced my problem in this environment in the most minimal way possible.
- [x] I have copy-pasted my entire test session into the same code block.

1. Send some 'echo foo' command to make history commands
2. Press <kbd>↑</kbd>  to call the history
3. It's showed the errors:
`_autocomplete.history_lines:shift:102: argument to shift must be non-negative`
`_autocomplete.history_lines:shift:125: argument to shift must be non-negative`

**Comment by rikusen0335** [comment]
I've got the same issue.
The reproduce way can reproduce.
 
Here's environment:
```
> typeset -p1 VENDOR OSTYPE SHELL ZSH_ARGZERO ZSH_PATCHLEVEL _autocomplete__funcfiletrace
typeset VENDOR=redhat
typeset OSTYPE=linux-gnu
export SHELL=/bin/zsh
typeset ZSH_ARGZERO=/bin/zsh
typeset ZSH_PATCHLEVEL=zsh-5.8.1-0-g1a490c7
typeset -a _autocomplete__funcfiletrace=(
  /home/rikusen/.local/share/zinit/zinit.git/zinit.zsh:1824
  /home/rikusen/.local/share/zinit/zinit.git/zinit.zsh:1691
  /home/rikusen/.local/share/zinit/zinit.git/zinit.zsh:1329
  /home/rikusen/.local/share/zinit/zinit.git/zinit.zsh:2819
  /home/rikusen/.zshrc:61
  zsh:8
)

> git -C ~zsh-autocomplete log --oneline -n1
584bcba (HEAD -> main, origin/main, origin/HEAD) Change how to check for history search completion
```

**Comment by supersri811** [comment]
I too have the same issue. Perhaps it could be the result of a recent software update?
`➜  ~ typeset -p1 VENDOR OSTYPE SHELL ZSH_ARGZERO ZSH_PATCHLEVEL _autocomplete__funcfiletrace 
typeset VENDOR=pc
typeset OSTYPE=linux-gnu
export SHELL=/usr/bin/zsh
typeset ZSH_ARGZERO=zsh
typeset ZSH_PATCHLEVEL=zsh-5.9-0-g73d3173
typeset -a _autocomplete__funcfiletrace=(
  /home/supersri/.oh-my-zsh/oh-my-zsh.sh:170
  /home/supersri/.oh-my-zsh/oh-my-zsh.sh:199
  /home/supersri/.zshrc:75
  zsh:0
)

git -C ~zsh-autocomplete log --oneline -n1
584bcba (grafted, HEAD -> main, origin/main, origin/HEAD) Change how to check for history search completion
(END)
`

**Comment by Scia0** [comment]
I also have the problem 
  ~ ❯ typeset -p1 VENDOR OSTYPE SHELL ZSH_ARGZERO ZSH_PATCHLEVEL _autocomplete__funcfiletrac          at 00:48:14
typeset: no such variable: _autocomplete__funcfiletrac
typeset VENDOR=pc
typeset OSTYPE=linux-gnu
export SHELL=/bin/zsh
typeset ZSH_ARGZERO=-zsh
typeset ZSH_PATCHLEVEL=zsh-5.9-0-g73d3173

**Comment by Scia0** [comment]
I installed with znap so I ran znap pull and it fixed ???

**Comment by romainquellec** [comment]
Exact same issue.

**Comment by xkoldxx** [comment]
i cloned the repo and getting this error too 

Setup:
- m1 mac 
- zsh 5.9 
- iterm2

**Comment by baudneo** [comment]
Same issue, fresh install of ubuntu 22.04. Manual install, installed alongside syntax-highlighting and auto-suggestions. This is a headless system as well.

**Comment by noonriser** [comment]
Also getting the same issue. M2 mac, zsh 5.9 (arm-apple-darwin22.1.0), iterm2.

Occurs when using up arrow for history whilst already having text present to use back-searching feature.

**Comment by supersri811** [comment]
Yup, Can confirm that it works.
Thanks for the support!
