### ISSUE TITLE
Don't override ↑ and ↓ bindings when fzf is installed

### ISSUE THREAD

**Issue by paw-lu** [marlonrichert/zsh-autocomplete#59]
### Is your feature request related to a problem? Please describe.

Currently, if fzf is installed, zsh-autocomplete will rebind <kbd>↑</kbd> so that it no longer toggles through history, but fuzzy searches through it.

For my usage this seems unnecessary, since <kbd>^</kbd>+<kbd>R</kbd> already activates fuzzy search, and <kbd>↑</kbd> is a convenient well-known shortcut to repeat the last few commands.

### Describe the solution you'd like

Either disable the automatic remapping of <kbd>↑</kbd> when fzf is detected or offer an option to bring it back to its original functionality.

---

Again, thanks for the great work!

**Comment by yutakatay** [comment]
I agree with you.

this is the workaround.

```bash
function precmd_remove_up_down_bindkey() {
  bindkey '^[OA' up-line-or-history
  bindkey '^[OB' down-line-or-history
}

add-zsh-hook precmd precmd_remove_up_down_bindkey
```

**Comment by marlonrichert** [comment]
@paw-lu @yutakatay Do you have any suggestions what the `zstyle` statement for this should be? What would you expect it to be?

**Comment by dylanjm** [comment]
Another comment would be to suppress completions when using `up-line-or-history`. When I move back in history and am modifying commands, it would be good to hold off on showing completions until I start typing or something.

**Comment by marlonrichert** [comment]
@dylanjm I actually have implemented that already in my local copy of the `dev` branch. You can expect to see it soon.

**Comment by marlonrichert** [comment]
Merged to `master`.
