### ISSUE TITLE
Colored completions with nerd font icons

### ISSUE THREAD

**Issue by ryan-griffin** [marlonrichert/zsh-autocomplete#591]
## What do you want?
A config option for colored completions with nerd font icons similar to how the `ls` replacement [`exa`](https://github.com/ogham/exa) does it.

## Why do you want this?
It looks nice and makes it easier to distinguish between completions.

## Who else would benefit from this?
People who like colors and use a nerd font.

## How should it work?
ex. when given directory completions they should be blue with a folder icon.

**Comment by marlonrichert** [comment]
Sorry, that's not easily possible for files in Zsh's completion system. Feel free to ask for this feature on the [official Zsh mailing lists](https://zsh.sourceforge.io/Arc/mlist.html). I do not plan implement that as part of this plugin. It would be too costly to maintain for me.
