### ISSUE TITLE
cd<space> always lists 'ancestor directory' list first

### ISSUE THREAD

**Issue by sanderbongers** [marlonrichert/zsh-autocomplete#592]
Sorry for not providing the bug report template, I only have a question.

cd<space> always lists ancestor directories:
```shell
~ $ cd 
ancestor directory
Users/

/usr/local/var/www $ cd 
ancestor directory
usr/    local/  var/
``` 
But when using `cd`, I most of the time want to cd to a directory in the current directory. The only way to have them shown now, is:
```shell
~ $ cd ./
directory
Desktop/     Documents/        Downloads/    ...
```

Can this be prioritized in any way?

**Comment by sanderbongers** [comment]
I am using zoxide by the way, and have just now added:
```
+autocomplete:recent-directories() {
  reply=(${(f)"$(zoxide query --list)"})
}
```
that works, it shows zoxide history as 'recent directories'.

But the problem above persists, `cd<space>` shows ancestor directories.

**Comment by marlonrichert** [comment]
I'm unable to reproduce that. It only happens for me in an empty directory.

Also, please do not delete the bug report template when filing a new bug report. It's there for a reason. Use it to provide a reproducible test case. If I cannot reproduce it, I cannot fix it.
