### ISSUE TITLE
output on terminal start up

### ISSUE THREAD

**Issue by MiaFate** [marlonrichert/zsh-autocomplete#593]
- [x] I have carefully read all of the instructions in this issue template.
- [x] I have carried them out to the letter.

Failure to do so can result in your issue being closed.

## Environment
```zsh
miafate•~» typeset -p1 VENDOR OSTYPE SHELL ZSH_ARGZERO ZSH_PATCHLEVEL _autocomplete__funcfiletrace                                  [4:16:20]
git -C ~autocomplete log --oneline -n1
typeset VENDOR=apple
typeset OSTYPE=darwin22.0
export SHELL=/bin/zsh
typeset ZSH_ARGZERO=/bin/zsh
typeset ZSH_PATCHLEVEL=zsh-5.9-0-g73d3173
typeset -a _autocomplete__funcfiletrace=(
  /Users/miafate/.oh-my-zsh/custom/plugins/zsh-autocomplete/zsh-autocomplete.plugin.zsh:2
  /Users/miafate/.oh-my-zsh/oh-my-zsh.sh:170
  /Users/miafate/.oh-my-zsh/oh-my-zsh.sh:199
  /Users/miafate/.zshrc:76
  zsh:0
)
18e9cf3 (grafted, HEAD -> main, origin/main, origin/HEAD) Minimize the number of asynchronous processes
```
* Operating system: macOS ventura 13.4
* Terminal emulator: kitty / hyper

- [x] I have filled out the fields above.
- [x] I have ran the commands in the code block above.
- [x] I have pasted their output into the same block.

## Steps to reproduce
```zsh
(anon):16: no matches found: /Users/miafate/.oh-my-zsh/custom/plugins/zsh-autocomplete/Functions/**/.autocomplete:*~*.zwc(D-:)
miafate•~» cd $(mktemp -d)                                                                                                          [4:23:56]
git clone --depth 1 -- https://github.com/marlonrichert/zsh-autocomplete.git
> .zshrc <<EOF
PS1='%# ' PS2= RPS2='%^'; setopt transientrprompt interactivecomments
source ~/zsh-autocomplete/zsh-autocomplete.plugin.zsh
EOF
env -i HOME=$PWD PATH=$PATH TERM=$TERM ${TERMINFO:+TERMINFO=$TERMINFO} zsh -d
Cloning into 'zsh-autocomplete'...
remote: Enumerating objects: 55, done.
remote: Counting objects: 100% (55/55), done.
remote: Compressing objects: 100% (53/53), done.
remote: Total 55 (delta 0), reused 43 (delta 0), pack-reused 0
Receiving objects: 100% (55/55), 1.64 MiB | 6.40 MiB/s, done.
(anon):16: no matches found: /private/var/folders/17/brztglb55xv5_q9np9095tsm0000gn/T/tmp.M1j540ae/zsh-autocomplete/Functions/**/.autocomplete:*~*.zwc(D-:)
```
- [x] I have run the code block above to create a test environment.
- [x] I have reproduced my problem in this environment in the most minimal way possible.
- [x] I have copy-pasted my entire test session into the same code block.
- [ ] I have copy-pasted the content of the log files found in the `~autocomplete-log` dir of the above session into
  their respective sections below.

<details>
<summary><code>YYYY-MM-DD.log</code> (click to expand)</summary>
<pre>

</pre>
</details>

<details>
<summary><code>YYYY-MM-DD_async.log</code> (click to expand)</summary>
<pre>

</pre>
</details>

<details>
<summary><code>YYYY-MM-DD_pty.log</code> (click to expand)</summary>
<pre>

</pre>
</details>

<img width="1350" alt="image" src="https://github.com/marlonrichert/zsh-autocomplete/assets/52300099/074c8166-a313-4314-a277-8d8fc4381c74">

this is my .zshrc file
```sh
export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="fletcherm"

zstyle ':omz:update' mode reminder  # just remind me to update when it's time

plugins=(zsh-autocomplete)

source $ZSH/oh-my-zsh.sh

if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
   export EDITOR=/opt/homebrew/bin/nvim
fi
```

**Comment by iabdelkareem** [comment]
+1

**Comment by antiq25** [comment]
Was having this issue as well, what worked for me was rm -rf ~/zsh-snap in .config and .local

then moving the marlonrichert/zsh-autocomplete directly inside of the plugins folder instead and leaving zsh-edit in there. 
then sudo rm -rf .cache

**Comment by MiaFate** [comment]
I wasnt using snap and I did manual install. I don't know why `but rm -rf zsh-autocomplete` and clone again in the same directory worked, TYVM
