### ISSUE TITLE
`.autocomplete:__main__:precmd:unfunction:9: bad option: -z`

### ISSUE THREAD

**Issue by pep-sanwer** [marlonrichert/zsh-autocomplete#594]
## Bug

Not sure If I've appropriately filled out the below issue, but please let me know how I can provide needed details.

Issue is as follows:
I'm seeing 
```.autocomplete:__main__:precmd:unfunction:9: bad option: -z```
output after most terminal operations, and a
```.autocomplete:__main__:precmd:unfunction:9: no such hash table element: zsh```
in the session created by the reproducible session

I'm not seeing any other issues as a consequence.
Thank you for this lovely plugin!

## Environment
```zsh
λ typeset -p1 VENDOR OSTYPE SHELL ZSH_ARGZERO ZSH_PATCHLEVEL _autocomplete__funcfiletrace
typeset VENDOR=ubuntu
typeset OSTYPE=linux-gnu
export SHELL=/usr/bin/zsh
typeset ZSH_ARGZERO=-zsh
typeset ZSH_PATCHLEVEL=ubuntu/5.8.1-1
typeset -a _autocomplete__funcfiletrace=(
  /home/devblade/.oh-my-zsh/custom/plugins/zsh-autocomplete/zsh-autocomplete.plugin.zsh:2
  /home/devblade/.oh-my-zsh/oh-my-zsh.sh:170
  /home/devblade/.oh-my-zsh/oh-my-zsh.sh:199
  /home/devblade/.zshrc:91
  zsh:0
)
.autocomplete:__main__:precmd:unfunction:9: bad option: -z
```

```zsh
λ git -C ~autocomplete log --oneline -n1
36f10ba (grafted, HEAD -> main, origin/main, origin/HEAD) Tweak history search order
.autocomplete:__main__:precmd:unfunction:9: bad option: -z
```

* Operating system: `WSL2/Ubuntu`
* Terminal emulator: `Windows Terminal`

## Steps to reproduce
```zsh
cd $(mktemp -d)
git clone --depth 1 -- https://github.com/marlonrichert/zsh-autocomplete.git
> .zshrc <<EOF
PS1='%# ' PS2= RPS2='%^'; setopt transientrprompt interactivecomments
source ~/zsh-autocomplete/zsh-autocomplete.plugin.zsh
EOF
env -i HOME=$PWD PATH=$PATH TERM=$TERM ${TERMINFO:+TERMINFO=$TERMINFO} zsh -d
```

Output:
```zsh
λ cd $(mktemp -d)
git clone --depth 1 -- https://github.com/marlonrichert/zsh-autocomplete.git
> .zshrc <<EOF
PS1='%# ' PS2= RPS2='%^'; setopt transientrprompt interactivecomments
source ~/zsh-autocomplete/zsh-autocomplete.plugin.zsh
EOF
env -i HOME=$PWD PATH=$PATH TERM=$TERM ${TERMINFO:+TERMINFO=$TERMINFO} zsh -d
Cloning into 'zsh-autocomplete'...
remote: Enumerating objects: 55, done.
remote: Counting objects: 100% (55/55), done.
remote: Compressing objects: 100% (53/53), done.
remote: Total 55 (delta 0), reused 39 (delta 0), pack-reused 0
Receiving objects: 100% (55/55), 1.64 MiB | 809.00 KiB/s, done.
.autocomplete:__main__:precmd:unfunction:9: no such hash table element: zsh
compinit:503: no such file or directory: /usr/share/zsh/vendor-completions/_docker
% pwd
/tmp/tmp.D4daP1WbAb
.autocomplete:__main__:precmd:unfunction:9: no such hash table element: zsh
% ls
zsh-autocomplete
.autocomplete:__main__:precmd:unfunction:9: no such hash table element: zsh
%
```

<details>
<summary><code>2023-05-31.log</code> (click to expand)</summary>
<pre>
*no contents*
</pre>
</details>

<details>
<summary><code>2023-05-31_async.log</code> (click to expand)</summary>
<pre>
*doesn't exist*
</pre>
</details>

<details>
<summary><code>2023-05-31_pty.log</code> (click to expand)</summary>
<pre>
*no contents*
</pre>
</details>

**Comment by shouvSarker** [comment]
Reverting to commit 52e2e03 solved my issue too. Hoping the maintainers fix this soon.

**Comment by YesnielX** [comment]
Thankss, now work!

**Comment by RafaZeero** [comment]
OMG Thank you guys soo much!

**Comment by Garvit-32** [comment]
Is this bug solved? I am facing the same issue.

**Comment by marlonrichert** [comment]
No problem! 🤗 

PS: If you enjoy using my software, then please consider [sponsoring me](https://github.com/sponsors/marlonrichert). 💝

@pep-sanwer @AlexErrant @mlalic @sawaca96 @jaron-l @sthasubin429 @PhilipAD @metr0jw @rmlekus @iluuu1994 @shouvSarker @YesnielX @Garvit-32 @RafaZeero
