### ISSUE TITLE
Odd History Behavior

### ISSUE THREAD

**Issue by landoncrabtree** [marlonrichert/zsh-autocomplete#601]
## Environment

```
typeset VENDOR=apple
typeset OSTYPE=darwin23.0
typeset ZSH_PATCHLEVEL=zsh-5.9-0-g73d3173
typeset -a _autocomplete__funcfiletrace=(
  /Users/landon/.oh-my-zsh/custom/plugins/zsh-autocomplete/zsh-autocomplete.plugin.zsh:4
  /Users/landon/.oh-my-zsh/oh-my-zsh.sh:170
  /Users/landon/.oh-my-zsh/oh-my-zsh.sh:199
  /Users/landon/.zshrc:82
  zsh:0
)

e327674 (grafted, HEAD -> main, origin/main, origin/HEAD) Don't overwrite Autosuggest's default ignore list
```

* Operating system: macOS Sonoma (14.0 Beta (23A5257q))
* Terminal emulator: Terminal.app

## Steps to reproduce
Note, this is not limited to the command "sysopen flag.txt" This is a command I have found reliable to reproduce the error. I've had the error happen on multiple different commands, but it seems to be random on when it occurs. For example, I did a fresh macOS install yesterday and sometimes `brew` commands would also cause the weird fluttering. 

![image](https://i.gyazo.com/1870b2d25726058c2fb65957427eef51.gif)
![image](https://i.gyazo.com/148fd1deac9b71456024205066376490.gif)

```
# install ohmyzsh
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

# install zsh-autocomplete
git clone --depth 1 -- https://github.com/marlonrichert/zsh-autocomplete.git $ZSH_CUSTOM/plugins/zsh-autocomplete

# enable plugin
sed -i '' 's/plugins=(git)/plugins=(git zsh-autocomplete)/' ~/.zshrc

# enable changes
exec zsh

# get some history
whoami
hostname
ls -al
ifconfig
exec zsh

sysopen flag.txt

# try to  check history via arrow key
```

<details>
<summary>Contents of <code>~autocomplete-log/YYYY-MM-DD.log</code> (click to expand)</summary>
<pre>
.autocomplete:async:pty:zle-widget:19: completion cannot be used recursively (yet)
.autocomplete:async:complete:fd-widget:37: completion cannot be used recursively (yet)
.autocomplete:async:pty:zle-widget:19: completion cannot be used recursively (yet)
.autocomplete:async:complete:fd-widget:37: completion cannot be used recursively (yet)
.autocomplete:async:pty:zle-widget:19: completion cannot be used recursively (yet)
.autocomplete:async:complete:fd-widget:37: completion cannot be used recursively (yet)
.autocomplete:async:pty:zle-widget:19: completion cannot be used recursively (yet)
.autocomplete:async:complete:fd-widget:37: completion cannot be used recursively (yet)
.autocomplete:async:pty:zle-widget:19: completion cannot be used recursively (yet)
.autocomplete:async:complete:fd-widget:37: completion cannot be used recursively (yet)
.autocomplete:async:pty:zle-widget:19: completion cannot be used recursively (yet)
.autocomplete:async:complete:fd-widget:37: completion cannot be used recursively (yet)
</pre>
</details>

**Comment by marlonrichert** [comment]
Does this happen only with OMZ?

**Comment by wu-qing-157** [comment]
I've having the same problem. I'm also using macOS and OMZ. It can happen on various commands.

**Comment by marlonrichert** [comment]
I'm not about to debug OMZ myself to figure out what causes this. Try selectively disabling parts of OMZ until you find which part it is that causes this behavior. Once you can provide me with that info, I'll reopen the issue.

**Comment by Jh142857** [comment]
您好，我是陈俊豪，我已收到您的邮件，会尽快给您回复，谢谢！
