### ISSUE TITLE
"Read-only file system" error

### ISSUE THREAD

**Issue by marcio1002** [marlonrichert/zsh-autocomplete#603]
Hello!

I'm having problems with my OS, it's getting corrupted after zsh-autocomplete throws an error and it's in an endless loop showing the error message. The OS information is just below.

![image](https://github.com/marlonrichert/zsh-autocomplete/assets/50804131/10daa73f-1ecb-41f8-be98-6ceb2b23fb27)

**Comment by jaiakash** [comment]
Can you send the screenshot of the error.

**Comment by marcio1002** [comment]
I can't because when this error happens, it ends up corrupting my operating system, and then I have to correct it to continue reusing it, but when it happens again (I hope not) I'll try to take a print or a photo.

**Comment by marlonrichert** [comment]
Could it be the same as this? https://github.com/marlonrichert/zsh-snap/issues/255#event-9495249568

That one is caused by a bug in Zsh itself.

**Comment by marcio1002** [comment]
Happened recently 6/22

![image](https://github.com/marlonrichert/zsh-autocomplete/assets/50804131/2706032d-f737-4225-aeb2-7238996ba68f)

**Comment by marlonrichert** [comment]
@marcio1002 The error says that the file that Autocomplete is trying to write to is read-only. What happens if you delete `/home/marcio/.local/state/zsh-autocomplete`?

**Comment by marcio1002** [comment]
At that moment I can't execute any command because the terminal is stuck and when I restart the notebook zorion only shows the terminal to fix the zorion interface once and for all. In this case, I run a bootable to fix it.

Now that I've recovered I can show you the logo that appeared in the print

![image](https://github.com/marlonrichert/zsh-autocomplete/assets/50804131/3b93e0bf-97c0-4374-8892-abcbb8588f08)

**Comment by marlonrichert** [comment]
`push_past` is not a function in Autocomplete nor one supplied with Zsh itself. I also have no idea what `Xdebug` is. Looks like you have some additional software installed that's causing problems. I can't help you with that, unless you can provide a [minimal, reproducible test case](https://stackoverflow.com/help/minimal-reproducible-example).
