### ISSUE TITLE
Does not reset ↑ and ↓ properly

### ISSUE THREAD

**Issue by jclusso** [marlonrichert/zsh-autocomplete#609]
The docs have this snippet for reseting the original functionaliy for the ↑ and ↓ arrows. This is not correct though. Typing the start of a previously typed command would result in you going back through commands that start with what you typed.

## Example
```shell
ssh root@domain.com
htop
time
reset
```

**Before**
If you started typing `ssh` and then hit ↑ you would jump to `ssh@root@domain.com`

**After**
If you start typing `ssh` and then hit ↑ you will get `reset`.

https://github.com/marlonrichert/zsh-autocomplete/blob/203513d7047c330766833028d393d2a96a9b2c38/README.md?plain=1#L273-L286

**Comment by jclusso** [comment]
It appears I've found the solution which is switching to `up-line-or-beginning-search` and `down-line-or-beginning-search`. I don't have anything in my `.zshrc` that would change this. Should I make a PR to update the documentation?

**Comment by marlonrichert** [comment]
> Typing the start of a previously typed command would result in you going back through commands that start with what you typed.

That's not the default behavior in Zsh. Just start your shell with `zsh -f` and try how it works.

> Should I make a PR to update the documentation?

Sure, but then try to make the instructions generic. Maybe point to the [official docs](https://zsh.sourceforge.io/Doc/Release/Zsh-Line-Editor.html#History-Control).

**Comment by jclusso** [comment]
@marlonrichert I guess you're right. I'm not sure how to best document this because the documentation you linked doesn't have `up-line-or-beginning-search` or `down-line-or-beginning-search`. I've confirmed the default behaviour is what you said so I'm going to close this issue since that is my mistake. I'm assuming since I use ohmyzsh, it must be overriding the history commands somewhere.

**Comment by marlonrichert** [comment]
Those two are optional widgets that ship Zsh, which indeed OMZ binds to those keys. They are documented here: https://zsh.sourceforge.io/Doc/Release/User-Contributions.html#Widgets
