### ISSUE TITLE
Getting  /Users/xxxx/.local/state/zsh-autocomplete/log/2023-07-09.log % git -C ~autocomplete log --oneline -n1

### ISSUE THREAD

**Issue by Ganiredi** [marlonrichert/zsh-autocomplete#614]
## Environment

I installed the zsh-autosuggest plugin, but I am not able to get the correct information because it is showing an error. I removed the steps that I took to reproduce the error, so I need to provide them again so that you can help me troubleshoot the issue.

VENDOR OSTYPE ZSH_PATCHLEVEL _autocomplete__funcfiletrace
➜  Repos typeset -p1 VENDOR OSTYPE ZSH_PATCHLEVEL _autocomplete__funcfiletrace
.autocomplete:async:complete:6: no such file or directory: /Users/xxxx/.local/state/zsh-autocomplete/log/2023-07-09.log
% git -C ~autocomplete log --oneline -n1
<output>
```

After Removal :

```
typeset -p1 VENDOR OSTYPE ZSH_PATCHLEVEL _autocomplete__funcfiletrace
typeset: no such variable: _autocomplete__funcfiletrace
typeset VENDOR=apple
typeset OSTYPE=darwin22.0
typeset ZSH_PATCHLEVEL=zsh-5.9-0-g73d3173
```

```
git -C ~autocomplete log --oneline -n1                <region:us-west-2>
zsh: no such user or named directory: autocomplete
```

</details>

**Comment by marlonrichert** [comment]
No idea what you're trying to explain. In any case, this is not the repo for `zsh-autosuggestions`. You can find that one [over here](https://github.com/zsh-users/zsh-autosuggestions).
