### ISSUE TITLE
CTRL + Z behaviour / reset default

### ISSUE THREAD

**Issue by StefanoChiodino** [marlonrichert/zsh-autocomplete#616]
## Environment

```zsh
% typeset -p1 VENDOR OSTYPE ZSH_PATCHLEVEL _autocomplete__funcfiletrace
<output>
typeset VENDOR=ubuntu
typeset OSTYPE=linux-gnurace
typeset ZSH_PATCHLEVEL=ubuntu/5.8.1-1
typeset -a _autocomplete__funcfiletrace=(
  /nail/home/stefanochiodino/repos/zsh-autocomplete/zsh-autocomplete.plugin.zsh:4
  /nail/home/stefanochiodino/.zshrc:22
  zsh:0
)
<output>
```

* Operating system: Ubuntu Jammy
* Terminal emulator: Pycharm

## Steps to reproduce

`CTRL+R`

I can't get the original history search behaviour. The readme has some instructions about it (https://github.com/marlonrichert/zsh-autocomplete#reset-ctrlr-and-ctrls) but the code seems broken.

I want to be able to select an entry, and it's not possible with how this plugin works.

Thanks!

**Comment by marlonrichert** [comment]
Please provide a reproducible test case.
