### ISSUE TITLE
stuck in the middle of completion

### ISSUE THREAD

**Issue by YanivHaliwa** [marlonrichert/zsh-autocomplete#617]
description of problem:
sometime and i cant tell exactly when . but i know for sure its happen on specific commands only cuz i tried to repeat the issue and its happen again and again on this specific command.

i use the autocomplete with list so when i type command  i do arrow up and i see the exact lasts command i want to use.
yes i know its possible to get it without shown the list but i like to see the list and choose its more comfo for me. 

problem is that sometime after i put the begining and do arrow up - the autocomplete STUCK on the last line without optin to move and nither CTRL+c help. anything cannot break that unless i open new terminal or new tab in terminal. 
 
example 1 i got error  [those i bold] - its happen when the list is stuck
wine ~/.wine/dosdevices/c:/users/yaniv/AppData/Local/Programs/Python/Python38/Scripts/pip.exe --upgrade pyinstaller; 
**double free or corruption (out)**
                                                             
sometimes i got other errors when its stuck. i really sad about it cuz i really love autocomplete please fix it.                           
  

## Environment

```zsh
% typeset -p1 VENDOR OSTYPE ZSH_PATCHLEVEL _autocomplete__funcfiletrace

that my output:
typeset VENDOR=debian
typeset OSTYPE=linux-gnu
typeset ZSH_PATCHLEVEL=debian/5.9-4+b2
typeset -a _autocomplete__funcfiletrace=(
  /home/yaniv/.oh-my-zsh/custom/plugins/zsh-autocomplete/zsh-autocomplete.plugin.zsh:4
  /home/yaniv/.zshrc:23
  zsh:0
  



% git -C ~autocomplete log --oneline -n1

that the output:
6d059a3 (HEAD -> main, origin/main, origin/HEAD) Fix bugs in insertion logic
 

```

Operating system+ Terminal emulator:  

here full info :
OS: Kali GNU/Linux Rolling x86_64 
Host: Inspiron 5491 2n1 
Kernel: 6.3.0-kali1-amd64 
Shell: zsh 5.9 
Terminal: qterminal 
CPU: Intel i7-10510U (8) @ 4.900GHz 
GPU: Intel CometLake-U GT2 [UHD Graphics] 
Memory: 3809MiB / 7600MiB 

## Steps to reproduce

```zsh
% cd $(mktemp -d)
% git clone --depth 1 -- https://github.com/marlonrichert/zsh-autocomplete.git
<output>
% > .zshrc <<EOF
setopt interactivecomments transientrprompt

input - wine ~/.wine/dosdevices/c:/users/yaniv/AppData/Local/Programs/Python/Python38/Scripts/pip.exe;
output of list from autocomplete [stuck holding on 13]
    1  ls                                                                                       
    2  cd                                                                                       
    3  ls                                                                                       
    4  cd ..                                                                                    
    5  ls                                                                                       
    6  cd #HOME                                                                                 
    7  LS                                                                                       
    8  ls                                                                                       
    9  cd /home                                                                                 
   10  ls                                                                                       
   11  cd yaniv                                                                                 
   12  ls                                                                                       
   13 wine ~/.wine/dosdevices/c:/users/yaniv/AppData/Local/Programs/Python/Python38/Scripts/pip.exe;
    
 
 Contents of <code>~autocomplete-log/YYYY-MM-DD.log</code> (click to expand)</summary>
answer:
no log found in ststem not in ur folder of autocomplete and not in /var/log

**Comment by garthk** [comment]
@YanivHaliwa check your CPU consumption when it's stuck (_eg._ by running `top` in another terminal) to see whether this might be a relative of #611.
