### ISSUE TITLE
Negative numbers in history search menu

### ISSUE THREAD

**Issue by SushiTee** [marlonrichert/zsh-autocomplete#626]
## Environment
```shell
typeset VENDOR=pc
typeset OSTYPE=linux-gnu
typeset ZSH_PATCHLEVEL=zsh-5.9-0-g73d3173
typeset -a _autocomplete__funcfiletrace=(
  /home/sushi/.oh-my-zsh/custom/plugins/zsh-autocomplete/zsh-autocomplete.plugin.zsh:4
  /home/sushi/.oh-my-zsh/oh-my-zsh.sh:170
  /home/sushi/.oh-my-zsh/oh-my-zsh.sh:199
  /home/sushi/.zshrc:88
  zsh:0
)
```

```shell
6d059a3 (grafted, HEAD -> main, tag: 23.07.13, origin/main, origin/HEAD) Fix bugs in insertion logic
```

* Operating system: Arch Linux
* Terminal emulator: /dev/pts/0

## Steps to reproduce
* Use <kbd>Ctrl</kbd><kbd>R</kbd> to enter history search
* I searched for *nano* but it basically happens with more or less everything
* --> I get negative numbers in the search results
![grafik](https://github.com/marlonrichert/zsh-autocomplete/assets/293612/730ffda7-e56a-48d9-b534-00ec420698f6)

When I comment out the _Fuzzy sort_ part here:
https://github.com/marlonrichert/zsh-autocomplete/blob/6d059a3634c4880e8c9bb30ae565465601fb5bd2/Completions/_autocomplete__history_lines#L109
this does not happen.

**Comment by marlonrichert** [comment]
Yeah, I've noticed this, too. I will investigate.
