### ISSUE TITLE
Make directory-jumping completion source optional

### ISSUE THREAD

**Issue by PythonNut** [marlonrichert/zsh-autocomplete#63]
This follows-up on #54.

### Is your feature request related to a problem? Please describe.
`zsh-autocomplete` seems to have become slower since `fasd` (and similar) completions were enabled. I am not sure if this is the actual cause. (Note that `fasd` itself is quite slow so this seems reasonable.) However, because I cannot disable the integration, I cannot test it.

### Describe the solution you'd like
I would like to be able to disable the directory jumping completion using `zstyle`.

### Describe alternatives you've considered
Having quickly glanced at the implementation (which patches `_path_files`), it seems like completion based on fasd doesn't depend on `zsh-autocomplete` behavior and may also be of interest to `zsh` users who do not `zsh-autocomplete`. (Essentially, I am wondering if the features are orthogonal.) If this were the case then it may make sense for the `_path_files` patch to be in its own package.

**Comment by marlonrichert** [comment]
Many of the features in `zsh-autocomplete` could be spun off into mini plugins. However, I don’t think there’s too much value in that. On the other hand, I do think there’s added value in bundling then together in a coherent way.

Having said that: I have been thinking about ways to make the features of `zsh-autocomplete` more modular. Nobody’s been asking to get any of the features separately, though, so it’s been kinda low priority for me. 

Anyway, I will implement a way to turn off “frecent dirs” completion, but I would recommend you perhaps have a look at faster alternatives to `fasd` (which, as you know, hasn’t been maintained in ~5 years), such as https://github.com/ajeetdsouza/zoxide

**Comment by marlonrichert** [comment]
@PythonNut It's available now on the `dev` branch. Please try it out.

**Comment by PythonNut** [comment]
> Many of the features in `zsh-autocomplete` could be spun off into mini plugins. However, I don’t think there’s too much value in that. On the other hand, I do think there’s added value in bundling then together in a coherent way.
> 
> Having said that: I have been thinking about ways to make the features of `zsh-autocomplete` more modular. Nobody’s been asking to get any of the features separately, though, so it’s been kinda low priority for me.

That's totally understandable, I was just throwing some stuff out since the issue template asked for it.

> Anyway, I will implement a way to turn off “frecent dirs” completion, but I do recommend you perhaps have a look at faster alternatives to fasd (which, as you know, hasn’t been maintained in ~5 years), such as https://github.com/ajeetdsouza/zoxide

Hmm the issue is that I've built a _lot_ of infrastructure around `fasd` (lots of integrations with other software). This is partly why I am not benefiting as much from the integration here as other people might. I'm aware that `fasd` is a hot mess and maybe one day I'll move all of my systems over to something faster, but I don't have time for that right now.

Anyway, thanks a lot for implementing my request. It's working great!

**Comment by marlonrichert** [comment]
Cool, it's available on `master` now.

**Comment by marlonrichert** [comment]
@PythonNut Heads up: I'm renaming the `frecent-dirs` setting to `recent-dirs`.

**Comment by PythonNut** [comment]
Now, it seems like the `zstyle` options are ignored on the latest master.

**Comment by marlonrichert** [comment]
Should be fixed in 0ee9470d3f80981b520b29aa919f8d6be956350d.

**Comment by marlonrichert** [comment]
@PythonNut It is now possible to individually disable any and all extra completions that `zsh-autocomplete` adds: https://github.com/marlonrichert/zsh-autocomplete/blob/master/README.md#disable-particular-completions
