### ISSUE TITLE
zsh occupies more than 99% of the CPU on M1 Mac Monterey 12.6.7

### ISSUE THREAD

**Issue by Arcovegle** [marlonrichert/zsh-autocomplete#631]
## Environment
* zsh-autocomplete commit: 4188b22 (HEAD -> master, origin/master) feat(agnoster): add git tag to prompt (#8417)
* Operating system: macOS Ventura 12.6.7 (M1 chip Macbook Air)
* Terminal emulator: Terminal.app

## Details
In the past two days, when I used the Terminal.app as usual, I found that my Macbook was overheating. However, I did not do any heavy jobs. Then I checked in the Activity Monitor and found that the cpu usage rate of zsh was as high as 99%. After canceling the zsh-autocomplete plugin in oh-my-zsh and restart the system, the problem just disappeared.

I wonder what caused such a high CPU usage.

**Comment by Arcovegle** [comment]
I think it is quite like this issue #611
Alse, here is the [crash report](https://pastebin.com/TEf2Ax7h) that may help.

**Comment by pesterhazy** [comment]
FWIW I'm also on an M1 (I reported #611)

**Comment by marlonrichert** [comment]
I'm not able to reproduce this on my M2 Mac. Can you add a reproducible test case, please?

**Comment by ImBIOS** [comment]
I sometimes encounter this issue, and now... I'm used to this behaviour.
But it'd be nice if it can be fixed.

**Comment by marlonrichert** [comment]
I can't fix it if I don't have a reproducible test case.
