### ISSUE TITLE
Incompatibility with bunjs completions

### ISSUE THREAD

**Issue by pesterhazy** [marlonrichert/zsh-autocomplete#632]
It appears there's a conflict with [zsh-autocomplete](https://github.com/marlonrichert/zsh-autocomplete)

With bun completions enabled, when I type  `l<TAB>`, I get:

```
~$ % arch(eval):1: command not found: _autocomplete.command
(eval):1: command not found: _autocomplete.command
(eval):1: command not found: _autocomplete.command
(eval):1: command not found: _autocomplete.command
(eval):1: command not found: _autocomplete.command
(eval):1: command not found: _autocomplete.command
(eval):1: command not found: _autocomplete.command
(eval):1: command not found: _autocomplete.command
```

The probably disappears when I remove this line from my zshrc

```
[ -s "/Users/user/.bun/_bun" ] && source "/Users/user/.bun/_bun"
```

I suspect the problem is with [bunjs](https://github.com/oven-sh/bun/blob/main/completions/bun.zsh) so I'm filing the issue here for completeness only, so that people may find this bug report if they search for the error string. Feel free to close if there's nothing actionable on your side.

**Comment by pesterhazy** [comment]
See also https://github.com/oven-sh/bun/issues/1272#issuecomment-1676343857

**Comment by pesterhazy** [comment]
Please see @marlonrichert's comment here https://github.com/oven-sh/bun/issues/1272#issuecomment-1681018321

**Comment by marlonrichert** [comment]
@pesterhazy Let me know when Bun's completion has been updated, if it's still a problem then.
