### ISSUE TITLE
Disable "Show all X possibilities?" prompt. 

### ISSUE THREAD

**Issue by Thy-GoD** [marlonrichert/zsh-autocomplete#634]
Originally posted as a question but was told to make a bug report instead.

This screenshot sums up the problem:

![image](https://github.com/marlonrichert/zsh-autocomplete/assets/123708601/2375f12a-abf2-4b61-aa9d-17b941155cc4)

This prompt will sometimes occur mid-typing and basically force me to backspace and re-type the whole thing. 

It will sometimes occur for longer commands as well, though I can't remember a case off memory.

Main way to reproduce is to type in `curl -` and it should show up.

**Comment by ImBIOS** [comment]
I need to disable this too,

```sh
zsh: do you wish to see all 57 possibilities (12 lines)?
```

**Comment by marlonrichert** [comment]
Please don't delete the bug report template when filing a bug.
