### ISSUE TITLE
Toggle autocomplete visibility on and off

### ISSUE THREAD

**Issue by adamerose** [marlonrichert/zsh-autocomplete#638]
## What do you want?
I would like to only see autocomplete suggestions when I hit a hotkey like Ctrl+Space

## Why do you want this?
I find the automatic text popup distracting. My suggestion to only show autocomplete when you press a hotkey is the default behavior you'll find in IDEs like VS Code.

I'm pretty new to Zsh... I tried the code below in my zshrc but it doesn't seem to prevent autocomplete from popping up
```
source ~/.zsh/zsh-autocomplete/zsh-autocomplete.plugin.zsh
zstyle ':autocomplete:*' auto-suggest false
bindkey '^ ' _autocomplete
```

**Comment by marlonrichert** [comment]
> I would like to only see autocomplete suggestions when I hit a hotkey like Ctrl+Space

It’s not autocompletion if it doesn’t show completions _automatically._ If you want regular shell completion, then don’t use this plugin.

> only show autocomplete when you press a hotkey is the default behavior you'll find in IDEs like VS Code.

It doesn’t work like that for me in VS Code. It shows completions automatically. 🤔
