### ISSUE TITLE
recent-directories stopped working

### ISSUE THREAD

**Issue by ad-on-is** [marlonrichert/zsh-autocomplete#643]
```
+autocomplete:recent-directories() {
  reply=(${(f)"$(zoxide query -l)"})
}
```

I had this code in my .zshrc file for recent directories. This stopped working. Were there any breaking changes introduced recently?

**Comment by ad-on-is** [comment]
Sorry to bother, but this was an issue with zoxide.
https://github.com/aymanbagabas/dotfiles/commit/30e8323147281b07a9f77879b6d14881acbf0ff4

**Comment by stefan2904** [comment]
maybe-stupid question, why `reply=(${(f)"$(zoxide query -l)"})` and not `typeset -ga reply=(zoxide query -l)` like in the README?

**Comment by ad-on-is** [comment]
@stefan2904 I just followed a guide that I found online a few years ago.

**Comment by marlonrichert** [comment]
`typeset -ga reply=(zoxide query -l)` does not work correctly. Just try it on the command line:
```sh
% typeset -ga reply=(zoxide query -l)
% print $reply
zoxide query -l
%
```

**Comment by ad-on-is** [comment]
> `typeset -ga reply=(zoxide query -l)` does not work correctly. Just try it on the command line:
> 
> ```shell
> % typeset -ga reply=(zoxide query -l); typeset -p1 reply
> typeset -a reply=(
>   zoxide
>   query
>   -l
> )
> %
> ```
> 
> `reply=( ${(f)"$( zoxide query -l )"} )` is the correct way to do it:
> 
>     * `"$( <command> )"` preserves all whitespace in `<command>`'s output.
> 
>     * `${(f)"$( <command> )"}` splits the output on newlines.

That's how I have it, but strangely it doesn't work in the users home-directory.

If, in the home-directory I type `cd foo`, I'd expect it to show all recent directories containing foo, but it does not. 
Doing a `zoxide query -l foo`however brings up a few results.

If I `cd` into ~/Downloads and do the same, the results come up.

**Comment by marlonrichert** [comment]
@ad-on-is And is that a problem in Autocomplete or in Zoxide?
