### ISSUE TITLE
How to ignore ssh from auto-completing

### ISSUE THREAD

**Issue by jamnaughty** [marlonrichert/zsh-autocomplete#648]
I am having trouble accessing the right IP address through SSH. Every time I try to type the SSH command and paste the IP address, it displays a list of 400 other IP addresses in the known host file. Additionally, when I paste the IP address, the first two digits get eaten up. Can you please guide me on how to disable the auto-complete feature for SSH?

**Comment by marlonrichert** [comment]
Definitely sounds like a bug, but I'm unable to reproduce this. Please don't delete the bug report template. Use it to provide a reproducible test case. If I cannot reproduce it, I cannot fix it. I will reopen this once you've restored the bug report template and added the test.
