### ISSUE TITLE
Don't override existing completion matcher list

### ISSUE THREAD

**Issue by slavistan** [marlonrichert/zsh-autocomplete#65]
### Problematic behavior

Existing completion matcher lists are ignored and overridden by the plugin's internal completion settings. 
### Expected behavior

The plugin should respect the user's existing completion matcher lists.

---
### Additional context
Hi there ;)

I just stumbled upon this plugin and love it so far. My only gripe is the above issue: I am unable to use my own matcher list. From an architectural standpoint it feels like overriding the matcher-lists is way outside the scope of the plugin. The asynchronous preview of completion results is what I would naively expect the plugin to do - which it does very well.

Is there a technical reason for this behavior? Your [comment](https://github.com/marlonrichert/zsh-autocomplete/issues/53#issuecomment-642594238) in a related issue suggests that this is done solely to mimick the default behavior of oh-my-zsh.

Thank you for your efforts.
Best regards

**Comment by marlonrichert** [comment]
It's not just Oh My Zsh. Other frameworks such as Prezto and Ziomfw also set `matcher-list` values that would prevent `zsh-autocomplete` from working correctly out of the box.

`zsh-autocomplete` relies heavily on setting `zstyle ':completion:'` styles to modify completion behavior. Without it, I would not be able to get the completion behavior that I want. `matcher-list` is just one of them.

Care to share your `matcher-list`, so I can appreciate why you want to use it over the one I'm providing? If you can help me understand what end result you're trying to achieve, then I could change `zsh-autocomplete`'s behavior to match or provide a setting for it.

If you really want to set your own `matcher-list`, here's a workaround for you:
```sh
add-zsh-hook precmd use-my-matcher-list
use-my-matcher-list() {
  # insert code here
}
```
However, **be warned:** `zsh-autocomplete`'s completion handling is fairly complex and relies on more than just `matcher-list`. You might not get results you expect this way.

That's I would really like you to explain what it is exactly that you want as the end result. `matcher-list` might not even be the thing you need to set. 🙂

**Comment by slavistan** [comment]
> That's why I would really like you to explain what it is exactly that you want as the end result. matcher-list might not even be the thing you need to set.

I'm playing around with the internals of zsh to gain an understanding of what can be done with it. To this end, I've done away with oh-my-zsh which hid all the complexity from me to which I want to be exposed now. So, what I want depends chiefly on what zsh has to offer about which I am largely ignorant at this point and, hence, I have no idea what I want :-) I'm basically just a curious zsh novice.

> Can you share your matcher-list with and tell what it does for you that zsh-autocomplete doesn't?

Having said the above, there's nothing clever about my matcher list, but here you go.
```zsh
zstyle ':completion:*' matcher-list \
  'M:{a-zA-Z}={a-zA-Z}' \
  'm:{a-zA-Z}={A-Za-z}' \
  'm:{a-zA-Z}={A-Za-z} l:|=*'
```
This generates completions by (1) literal match, (2) case-insensitive match and (3) case-insensitive infix match. Only if one rule does not generate any completions is the next one consulted. `zsh-autocomplete`'s matching rules are far more fuzzy. To give an example, the first suggestion after having typed `cd` is not the eponymous shell built-in, but rather `calendar`, which I personally dislike.

> If you really want to set your own matcher-list, here's a workaround for you

I have attempted the following, unsuccessfully.
```zsh
# .zshrc
# ...
source "~/.config/zsh/plugins/zsh-autocomplete/zsh-autocomplete.plugin.zsh"
zstyle ':autocomplete:*' fuzzy-search off
zstyle ':autocomplete:*' frecent-dirs off
zstyle ':autocomplete:*' groups off
add-zsh-hook precmd use-my-matcher-list
use-my-matcher-list() {
  zstyle ':completion:*' matcher-list \
    'M:{a-zA-Z}={a-zA-Z}' \
    'm:{a-zA-Z}={A-Za-z}' \
    'm:{a-zA-Z}={A-Za-z} l:|=*'
}
```
The first suggestion after having typed `cd` is still `calendar`, so my completion settings are not being used. Did I make a mistake?

> It's not just Oh My Zsh. Other frameworks such as Prezto and Zimfw also set matcher-list to values that would prevent zsh-autocomplete from working correctly out of the box, if I wouldn't override them.

By *working correctly* do you mean working in general without runtime errors, or rather working in a manner customized to *your* subjective wants (e.g. using *your* completion settings, etc.)? It still eludes me whether `zsh-autocomplete` overrides completion settings because of an inevitable technical requirement, or because of a personal taste of yours. I guess I could restate this issue's topic as a yes/no question: **Is it possible to use `zsh-autocomplete` without it changing any of the user's completion settings (such as matcher lists)?**

**Comment by marlonrichert** [comment]
> I have attempted the following, unsuccessfully.
> ```zsh
> # .zshrc
> # ...
> source "~/.config/zsh/plugins/zsh-autocomplete/zsh-autocomplete.plugin.zsh"
> zstyle ':autocomplete:*' fuzzy-search off
> zstyle ':autocomplete:*' frecent-dirs off
> zstyle ':autocomplete:*' groups off
> add-zsh-hook precmd use-my-matcher-list
> use-my-matcher-list() {
>   zstyle ':completion:*' matcher-list \
>     'M:{a-zA-Z}={a-zA-Z}' \
>     'm:{a-zA-Z}={A-Za-z}' \
>     'm:{a-zA-Z}={A-Za-z} l:|=*'
> }
> ```
> The first suggestion after having typed `cd` is still `calendar`, so my completion settings are not being used. Did I make a mistake?

Yeah, at present, you need to do all `zstyle ':autocomplete:*'` statements _before_ your source `zsh-autocomplete`. However, that’s definitely something I can improve on. I’ll look into it.

> **Is it possible to use `zsh-autocomplete` without it changing any of the user's completion settings (such as matcher lists)?**

Not yet, but I can make it possible. 🙂 It’s been on my list of things to do to make `zsh-autocomplete` more modular ([as I mentioned to @PythonNut here](https://github.com/marlonrichert/zsh-autocomplete/issues/63#issuecomment-649791189)), so you can source only the things you want, but it will take me some time to figure out how to do it right.

**Comment by marlonrichert** [comment]
@slavistan I tried your example `.zshrc` file above. I then ran the following command, which gave the following output:
```sh
% zstyle -L ':completion:*' matcher-list
zstyle ':completion:list-expand:complete:*' matcher-list $'\n    r:|?=** m:{[:lower:][:upper:]-_}={[:upper:][:lower:]_-}'
zstyle ':completion:*:complete:*' matcher-list $'\n    r:|?=**' '+m:{[:lower:][:upper:]-_}={[:upper:][:lower:]_-}'
zstyle ':completion:*' matcher-list 'M:{a-zA-Z}={a-zA-Z}' 'm:{a-zA-Z}={A-Za-z}' 'm:{a-zA-Z}={A-Za-z} l:|=*'
```

As you can see, your style is in effect. However, the line above it _is more specific,_ thus overriding your line when the `complete` completer is being used.

To make it work as you want, you need to change your line to this:
```sh
zstyle ':completion:*:complete:*' matcher-list 'M:{a-zA-Z}={a-zA-Z}' 'm:{a-zA-Z}={A-Za-z}' 'm:{a-zA-Z}={A-Za-z} l:|=*'
```

**Comment by marlonrichert** [comment]
@slavistan By the way, I pushed in some changes to the `dev` branch that enhance the matching behavior. I would be happy if you could try them out and let me know what you think. 🙂

**Comment by marlonrichert** [comment]
I will probably provide a solution for this similar to #72.

**Comment by slavistan** [comment]
Yepp, looks like that does it! I'll give it a thorough testing :+1:

**Comment by marlonrichert** [comment]
@slavistan I pushed in a major rewrite with comprehensive documentation on the `dev` branch. Please try it out and let me know what you think.

**Comment by marlonrichert** [comment]
@slavistan Can you please try out the `dev` and let me know what you think? Documentation over here: https://github.com/marlonrichert/zsh-autocomplete/blob/dev/README.md#advanced-use-your-own-completion-config

**Comment by marlonrichert** [comment]
Merged to `master`.
