### ISSUE TITLE
Symbols like @ breaks auto complete

### ISSUE THREAD

**Issue by MaoMaoCake** [marlonrichert/zsh-autocomplete#650]
## Environment

```zsh
% typeset -p1 VENDOR OSTYPE ZSH_PATCHLEVEL _autocomplete__funcfiletrace
typeset VENDOR=ubuntu
typeset OSTYPE=linux-gnu
typeset ZSH_PATCHLEVEL=ubuntu/5.8.1-1
typeset -a _autocomplete__funcfiletrace=(
  /home/maomao/zsh-addons/zsh-autocomplete/zsh-autocomplete.plugin.zsh:4
  /home/maomao/.zshrc:1
  zsh:0
)


% git -C ~autocomplete log --oneline -n1
afc5afd (grafted, HEAD -> main, origin/main, origin/HEAD) Add configuration note for NixOS users

```

* Operating system:  'Ubuntu 22.04.2 LTS'
* Terminal emulator: Gnome Terminal

## Steps to reproduce

```zsh
echo @
echo @
press up arrow
```

affected symbols 
exclamation point !
at @ 
percent %
plus + 
closing curly }
closing square ]
colon :
comma , 

<details>
<summary>Contents of <code>~autocomplete-log/YYYY-MM-DD.log</code> (click to expand)</summary>
<pre>
.autocomplete.async.complete.fd-widget.inner:25: completion cannot be used recursively (yet)
double free or corruption (out)
double free or corruption (out)
.autocomplete.async.complete.fd-widget.inner:25: completion cannot be used recursively (yet)
</pre>
</details>

**Comment by contentfree** [comment]
I believe that parenthesis in names breaks it too. (Thanks Adobe After Effects for defaulting to `(Footage)` for your footage folder…)
