### ISSUE TITLE
Up arrow in history menu always cycling - not allowing older entries to be viewed

### ISSUE THREAD

**Issue by poopsicles** [marlonrichert/zsh-autocomplete#652]
## Environment

```zsh
% typeset -p1 VENDOR OSTYPE ZSH_PATCHLEVEL _autocomplete__funcfiletrace

typeset VENDOR=apple
typeset OSTYPE=darwin21.0
typeset ZSH_PATCHLEVEL=zsh-5.8.1-0-g1a490c7
typeset -a _autocomplete__funcfiletrace=(
  /Users/fumnanya/zsh-repos/marlonrichert/zsh-autocomplete/zsh-autocomplete.plugin.zsh:4
  /Users/fumnanya/zsh-repos/znap/functions/.znap.source:34
  /Users/fumnanya/zsh-repos/znap/functions/.znap.source:37
  /Users/fumnanya/zsh-repos/znap/functions/znap:27
  /Users/fumnanya/.zshrc:21
  zsh:0
)

% git -C ~autocomplete log --oneline -n1

afc5afd (grafted, HEAD -> main, origin/main, origin/HEAD) Add configuration note for NixOS users
```

* Operating system: macOS Monterey 12.7 (21G816)
* Terminal emulator: iTerm2 Build 3.4.20

## Steps to reproduce

```zsh
% cd $(mktemp -d)
% git clone --depth 1 -- https://github.com/marlonrichert/zsh-autocomplete.git

Cloning into 'zsh-autocomplete'...
remote: Enumerating objects: 55, done.
remote: Counting objects: 100% (55/55), done.
remote: Compressing objects: 100% (53/53), done.
remote: Total 55 (delta 0), reused 35 (delta 0), pack-reused 0
Receiving objects: 100% (55/55), 1.64 MiB | 1.66 MiB/s, done.

% > .zshrc <<EOF
setopt interactivecomments transientrprompt
PS1='%# '
PS2=
RPS2='%^'
source $PWD/zsh-autocomplete/zsh-autocomplete.plugin.zsh
EOF
% env -i HOME=$PWD PATH=$PATH TERM=$TERM ${TERMINFO:+TERMINFO=$TERMINFO} zsh -d
% ls
zsh-autocomplete

# do that ten or so times - enough for the history to be more than half the screen
# press up-arrow
% ls;
    9  ls
   10  ls
   11  ls
   12  ls
   13  ls
   14  ls
   15  ls
   16  ls # <- this is selected

# keep pressing up until entry 9 is selected
# press up again, it cycles back to 16 instead of going to 8
```

<details>
<summary>Contents of <code>~autocomplete-log/YYYY-MM-DD.log</code> (click to expand)</summary>
<pre>
empty
</pre>
</details>

The history menu that shows the last 16 items, along with the history search (invoked with `Ctrl+R`) loop between the bottom and top lines shown on the screen instead of showing older entries. I originally thought this might be intended behaviour, but #550 appears to be meant to implement this behaviour, so I'm not sure.

https://github.com/marlonrichert/zsh-autocomplete/assets/87488715/b1290d97-f6ee-4a0f-b113-2658223b4eda

**Comment by jackiesogi** [comment]
I have the same problem, I think it will be perfect if it is fixed.

**Comment by 0xluc** [comment]
Yep, same here

**Comment by Cyberozoc** [comment]
Just remove the `source ~/Repos/zsh-autocomplete/zsh-autocomplete.plugin.zsh` from .zshrc and add `zsh-autocomplete` to the `plugins`

**Comment by poopsicles** [comment]
@Cyberozoc I use Znap for plugin management, not oh-my-zsh, so I don't think there's a "plugins" section of my .zshrc...

this is how it looks:

```sh
$ cat .zshrc
# get znap
source ~/zsh-repos/znap/znap.zsh

fpath+=~/.zfunc # completions dir
rustup completions zsh > ~/.zfunc/_rustup
rustup completions zsh cargo > ~/.zfunc/_cargo
poetry completions zsh > ~/.zfunc/_poetry

export PYENV_ROOT="$HOME/.pyenv"
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"

setopt autocd
zstyle ':completion:*' matcher-list '' 'm:{a-zA-Z}={A-Za-z}' 'r:|=*' 'l:|=* r:|=*'

# Download Znap, if it's not there yet.
[[ -r ~/zsh-repos/znap/znap.zsh ]] ||
    git clone --depth 1 -- \
        https://github.com/marlonrichert/zsh-snap.git ~/zsh-repos/znap

znap source marlonrichert/zsh-autocomplete
znap source zsh-users/zsh-autosuggestions

# tab and shift tab cycle through dir suggestions
zstyle ':autocomplete:*complete*:*' insert-unambiguous yes
zstyle ':autocomplete:*history*:*' insert-unambiguous yes
zstyle ':autocomplete:menu-search:*' insert-unambiguous yes
bindkey '\t' menu-complete "$terminfo[kcbt]" reverse-menu-complete
#bindkey -M menuselect '\r' .accept-line

znap eval starship 'starship init zsh --print-full-init'
znap prompt
```

**Comment by poopsicles** [comment]
@ajmalab cloning just the repo alone (without oh-my-zsh, znap, or any other managers) still loops for me

**Comment by aninder** [comment]
have you tried changing the number of list-lines setting , 
zstyle ':autocomplete:history-search-backward:*' list-lines 256

**Comment by aninder** [comment]
it;s not perfect as it also clears the terminal and takes up all screen..

**Comment by yeoleobun** [comment]
It seems zsh autocomplete conflict with zsh auto suggestion, after remove zsh auto suggestion, it never happened.

**Comment by poopsicles** [comment]
@yeoleobun weird because removing the `zstyle` ':autocomplete:history-search-backward:*' list-lines 256` setting and commenting out `zsh-autosuggestions` still has the issue

**Comment by JerryZhongJ** [comment]
I have the same problem, I thought it was a feature🤣

**Comment by edte** [comment]
I also encountered the same problem when using zinit management plug-in

**Comment by Islam394** [comment]
# The Solution

##  To Solve The Problem Make This Steps : 

1. Open .zshrc File .
2. Add This Code To .zshrc 
```zsh
bindkey '\t' menu-select "$terminfo[kcbt]" menu-select
bindkey -M menuselect '\t' menu-complete "$terminfo[kcbt]" reverse-menu-complete

# Autocompletion
zstyle -e ':autocomplete:list-choices:*' list-lines 'reply=( $(( LINES / 3 )) )'

# Override history search.
zstyle ':autocomplete:history-incremental-search-backward:*' list-lines 8

# History menu.
zstyle ':autocomplete:history-search-backward:*' list-lines 256
```
3. Save And Close The File .
4. Type In The Terminal 
```sh
source [Path_To_.zshrc]
```

[Uploading Screencast from 03-11-2024 11:18:36 AM.webm…]()

**Comment by marlonrichert** [comment]
If you want to be able to scroll more lines, then you need to configure this. See discussion #699.
