### ISSUE TITLE
search for branches in git checkout command

### ISSUE THREAD

**Issue by oberow** [marlonrichert/zsh-autocomplete#66]
I have spent a few hours trying to figure this out, I apologize if this is already available in zsh-autocomplete.

### Is your feature request related to a problem? Please describe.

Autocompletion does not support searching of the options in the completion menu when trying to complete the git checkout command

### Describe the solution you'd like

Currently, when I type git checkout <Tab>, zsh-autocomplete lists all the possible suggestions in the completion menu. I would like to be able to search for the "sprint-12/bugfix/ARG-1622" branch by simply typing 1622. However, once I type "1622", I am shown "No matching completions are found". Instead I must type "sprint-12/bugfix/..." in order to match the branch with "1622" in it.

### Additional context

![2020-07-04_20-25-02](https://user-images.githubusercontent.com/7954426/86512457-0e426d80-be35-11ea-9ef0-8a3ab5f849b0.gif)

**Comment by marlonrichert** [comment]
Interesting. I don’t have any branches with that kind of names. I’ll investigate, but it might be a limitation of the `git` completion you’re using. Are you using Zsh’s own `git` completion or the one installed by Git? I would recommend using the former, not the latter. The one Git install is a bad Bash port and is full of bugs.

**Comment by oberow** [comment]
Thanks marlon, that fixed it.

To anyone who might have the same problem, I looked in my $fpath (print -l $fpath to list its contents) and found a symlink in /usr/local/share/zsh/site-functions pointing to the git completion function in my git cellar: Cellar/git/2.27.0/share/zsh/site-functions/_git.

Removing the symlink to _git in my /usr/local/share/zsh/site-functions fixed it. Zsh then uses its _git function instead of the one supplied by git.
