### ISSUE TITLE
Conflict with zsh-vi-mode

### ISSUE THREAD

**Issue by koko-ng** [marlonrichert/zsh-autocomplete#667]
## Environment

```zsh
% typeset -p1 VENDOR OSTYPE ZSH_PATCHLEVEL _autocomplete__funcfiletrace
typeset VENDOR=redhat
typeset OSTYPE=linux-gnu
typeset ZSH_PATCHLEVEL=zsh-5.9-0-g73d3173
typeset -a _autocomplete__funcfiletrace=(
  /zsh-autocomplete/zsh-autocomplete.plugin.zsh:4
  /root/.zshrc:2
  zsh:0
)
% git -C ~autocomplete log --oneline -n1
c7b6550 (HEAD -> main, origin/main, origin/HEAD) Add instructions on how to insert longest common prefix
% git -C zsh-vi-mode log --oneline -n1 
ea1f58a (HEAD -> master, tag: v0.11.0, origin/master, origin/HEAD) release: v0.11.0
```

* Operating system: Fedora 39 (Also tested on the container)
* Terminal emulator: Gnome Terminal

## Steps to reproduce

```zsh
% cd $(mktemp -d)
% git clone --depth 1 -- https://github.com/marlonrichert/zsh-autocomplete.git
% git clone --depth 1 -- https://github.com/jeffreytse/zsh-vi-mode.git
% > .zshrc <<EOF
setopt interactivecomments transientrprompt
PS1='%# '
PS2=
RPS2='%^'
source $PWD/zsh-vi-mode/zsh-vi-mode.plugin.zsh
source $PWD/zsh-autocomplete/zsh-autocomplete.plugin.zsh
EOF
% env -i HOME=$PWD PATH=$PATH TERM=$TERM ${TERMINFO:+TERMINFO=$TERMINFO} zsh -d
% ls # Enter, then <k> to open history, then enter two time to select and execute command
% l; 
zsh: command not found: l
% 

```

First, thanks a lot for the plugin!
I have a slight compatibility problem, with [jeffreytse/zsh-vi-mode](https://github.com/jeffreytse/zsh-vi-mode), when selecting a command from the history, while trying to delete the suffix it deletes the last character of the command instead of the semicolon. My hypothesis is that zsh-vi-mode moves the cursor by one character, which causes `LBUFFER` to end one character before the end.
See the [associated PR](https://github.com/marlonrichert/zsh-autocomplete/pull/668) for a potential fix.

Best

**Comment by adoolaard** [comment]
Hi, unfortunately, I am still experiencing this issue, which makes the history menu unusable for me. Is there anything I can do to fix this? I noticed that @koko-ng made a commit addressing this issue.

**Comment by marlonrichert** [comment]
Your steps to reproduce don't work for me:
```sh
% cd $(mktemp -d)
% git clone --depth 1 -- https://github.com/marlonrichert/zsh-autocomplete.git
% git clone --depth 1 -- https://github.com/jeffreytse/zsh-vi-mode.git
% > .zshrc <<EOF
setopt interactivecomments transientrprompt
PS1='%# '
PS2=
RPS2='%^'
source $PWD/zsh-vi-mode/zsh-vi-mode.plugin.zsh
source $PWD/zsh-autocomplete/zsh-autocomplete.plugin.zsh
EOF
% env -i HOME=$PWD PATH=$PATH TERM=$TERM ${TERMINFO:+TERMINFO=$TERMINFO} zsh -d
% ls
zsh-autocomplete	zsh-vi-mode
% k
zsh: command not found: k
% 
% 
```
Please update your test case.

**Comment by marlonrichert** [comment]
On startup, `zsh-vi-mode` inserts line editor hooks by creating wrappers around all existing [special widgets](https://zsh.sourceforge.io/Doc/Release/Zsh-Line-Editor.html#Special-Widgets). It shouldn't do this. It should inserts its hooks through [`add-zle-hook-widget `](https://zsh.sourceforge.io/Doc/Release/User-Contributions.html#index-add_002dzle_002dhook_002dwidget) instead. Please file a bug report over there.
