### ISSUE TITLE
zsh-autocomplete does not list all branches in the git repository

### ISSUE THREAD

**Issue by oberow** [marlonrichert/zsh-autocomplete#67]
### Describe the bug
zsh-autocomplete does not list all branches in the git repository

### To Reproduce

```shell
# *Always* test with the following three steps:
$ cd "$(mktemp -d)"  # Create a temp dir and enter it
$ ZDOTDIR=$PWD HOME=$PWD zsh -df  # Start a subshell without config files
% source path/to/zsh-autocomplete.plugin.zsh

1. git checkout <tab>
* view the branches suggested without zsh-autocomplete
* many branches can be seen, eg sprint-11/... sprint-12/... sprint-13/... 
2. Next, turn on zsh-autocomplete and repeat git checkout <tab>
* the number of branches suggested is less, e.g., sprint-11/... and sprint-13/... can no longer be found
```

### Expected behavior
whether or not zsh-autocomplete is used, the number of suggestions shown by git checkout <tab> should be the same

### Actual behavior
![2020-07-12_20-43-06](https://user-images.githubusercontent.com/7954426/87247171-b800aa80-c484-11ea-8ec5-8910a18d1c67.gif)

### Desktop
 - OS + distribution: macOS Catalina 10.15.5
 - Zsh version: 5.8
 - Plugin version: d2cd472e92c8e7cfb12407ff4c475121a6c2d062

**Comment by marlonrichert** [comment]
Thanks for reporting! I’ll investigate.

**Comment by marlonrichert** [comment]
@oberow This should be fixed on the `dev` branch now. Please check it out and let me know if it works for you.

**Comment by oberow** [comment]
@marlonrichert I tested on the dev branch and it works! thanks!
