### ISSUE TITLE
The possibility of integrating argc-completions?

### ISSUE THREAD

**Issue by baudneo** [marlonrichert/zsh-autocomplete#670]
## What do you want?
Hi, Ive been using your software for awhile now, its great! Recently, I stumbled upon [argc-completions](https://github.com/sigoden/argc-completions) . It allows a user to have some pretty deep control of compiling completions but, it does not have a way to show menus and such that your software does so a user can select which completion with arrow keys, etc.

It would be fantastic to combine the two, use argc-completions to parse the help output and compile completions, and autocomplete to use the menus to select which completion of args/flags.

Maybe this is a pipe dream, but I thought I would mention it.

Thanks for your work!

## Why do you want this?
argc-completions allows a user to write code that can really dial in the completions based on context and combining other flags/args. argc-completions is specifically only for parsing the --help output and compiling completions, not displaying the completions and having menus a user can select which completion from. 

## Who else would benefit from this?
I think power users would benefit from this idea

**Comment by marlonrichert** [comment]
I don't use `argc-completions` and have no interest in finding out how to use it. Feel free to submit a pull request, though.

**Comment by baudneo** [comment]
No worries, I ended up moving to argc completions completely.
