### ISSUE TITLE
The plugin doesn't suggest shell functions

### ISSUE THREAD

**Issue by ahmadiehsan** [marlonrichert/zsh-autocomplete#672]
## Environment

```zsh
typeset VENDOR=debian
typeset OSTYPE=linux-gnu
typeset ZSH_PATCHLEVEL=debian/5.8-6+deb11u1
typeset -a _autocomplete__funcfiletrace=(
  /tmp/zsh_repos/zsh-autocomplete/zsh-autocomplete.plugin.zsh:4
  /home/ea/.zshrc:1
  zsh:0
)
```

```zsh
c7b6550 (grafted, HEAD -> main, origin/main, origin/HEAD) Add instructions on how to insert longest common prefix
```

* Operating system: "Debian GNU/Linux 11 (bullseye)"
* Terminal emulator: "gnome terminal"

## Steps to reproduce

The `.zshrc` file content:

```
source /tmp/zsh_repos/zsh-autocomplete/zsh-autocomplete.plugin.zsh

alias my_custom_command1=""
function my_custom_command2() {}
my_custom_command3() {}
```

When I type `my_custom_` the plugin only suggests `my_custom_command1`:

![screenshot_20231217_182452](https://github.com/marlonrichert/zsh-autocomplete/assets/32063407/e822c91e-989e-49c0-8825-fcf456f2a044)

But it is expected to suggest `my_custom_command1`, `my_custom_command2`, and `my_custom_command3`

**Comment by marlonrichert** [comment]
That's a problem I hadn't considered. Thanks for reporting. This should be fixed.
