### ISSUE TITLE
history-beginning-search doesn't work

### ISSUE THREAD

**Issue by yutakatay** [marlonrichert/zsh-autocomplete#68]
### Describe the bug

I really like this plugin! 
I'm not very trouble, but I found that history-beginning-search is not working.

### To Reproduce

```shell
# *Always* test with the following three steps:
$ cd "$(mktemp -d)"  # Create a temp dir and enter it
$ ZDOTDIR=$PWD HOME=$PWD zsh -df  # Start a subshell without config files
% source path/to/zsh-autocomplete.plugin.zsh
% zle -N history-beginning-search-backward-end history-search-end
% zle -N history-beginning-search-forward-end history-search-end
% bindkey '^P' history-beginning-search-backward-end
% bindkey '^N' history-beginning-search-forward-end

% ls /
% ls /home
% ls /tmp
% ls #type <C-p>
```

### Expected behavior

history-beginning-search can work.

### Actual behavior

No history search.

### Desktop
 - OS + distribution: Arch Linux 2020.07.15
 - Zsh version: zsh 5.8 (x86_64-pc-linux-gnu)
 - Plugin version: d2cd472e92c8e7cfb12407ff4c475121a6c2d062

**Comment by marlonrichert** [comment]
Thanks for reporting! I’ll investigate.

**Comment by marlonrichert** [comment]
@yutakatay I pushed in a fix on the `dev` branch. Can you try it out, please?

**Comment by yutakatay** [comment]
Great! It worked. Thank you :+1:
