### ISSUE TITLE
Is there any way to cancel certain shortcut keys?

### ISSUE THREAD

**Issue by ghost** [marlonrichert/zsh-autocomplete#680]
## What do you want?

Can be customized to cancel certain shortcut keys

## Why do you want this?

Conflicts with other tools, e.g [atuin](https://github.com/atuinsh/atuin) `^r`

## Who else would benefit from this?

Anyone who wants to disable some of the built-in shortcuts

## How should it work?

I'm using [atuin](https://github.com/atuinsh/atuin) as a history tool.
This uses the same `^r` shortcut as zsh-autocomplete.
I had to place the `bindkey '^r' _atuin_search_widget` at the bottom of `.zshrc`
but when I reboot the system, press `ctrl + r`, the zsh-autocomplete history widget still appears.
I'm currently only able to get `ctrl + r`, using the atuin widget, to work via `source ~/.zshrc`.
Is there a more convenient way to disable some keys?  Like adding environment variables, etc.

**Comment by Numenorean** [comment]
it took me almost two days to find out that there is apparently no way to rebind builtin shortcuts because of that shitty precmd trick to bind the keys just before the prompt appears. Works only if I manually execute bindkey in prompt.

What I tried:

```zsh
source $XDG_DATA_HOME/zinit/plugins/marlonrichert---zsh-autocomplete/zsh-autocomplete.plugin.zsh

testfunc() {
    echo "test"
    zle       reset-prompt
}
zle -N testfunc
bindkey '\E[1;3A' testfunc # Alt-Up
```

Zsh log:

```
+/home/emon/.config/zsh/.zshrc:169> bindkey '\E[1;3A' testfunc
+.autocomplete__key-bindings:precmd:16> .autocomplete__key-bindings:bind main history-search-backward '\e\e[A' '\e\eOA' '\e[1;3A'
+.autocomplete__key-bindings:bind:3> bindkey -M main '\e\e[A' history-search-backward '\e\eOA' history-search-backward '\e[1;3A' history-search-backward
```

IMHO that should be added to README to not misguide the other people
