### ISSUE TITLE
Color of Suggestions

### ISSUE THREAD

**Issue by mayurankv** [marlonrichert/zsh-autocomplete#687]
## What do you want?
Is it possible to change the color of suggestions?

## Why do you want this?
All suggestions are currently white directories and it would be clearer that they are not part of the currently typed code if they were grey instead.

## Who else would benefit from this?
Anyone who gets distracted by the white suggestions.

## How should it work?
Be able to specify terminal color for the suggestions.

Given the following situation:
Whenever the list of directories to autocomplete from is rendered.

When I perform the following steps:
1. Currently, try and ignore the fact that the suggestions are white

Then I expect the following to happen:
I would like them to be grey so they aren't distracting.

**Comment by mayurankv** [comment]
Sorry, I believe this is actually available via `zstyle ':completion:*:descriptions' format '%F{blue}%d%f'` etc. Apologies.

**Comment by mayurankv** [comment]
I would appreciate a heads up of what setting I can use to change the colours of the suggestions though! I can't seem to figure it out.

**Comment by marlonrichert** [comment]
@mayurankv I'm not sure what you mean. Can you post some screenshots?
