### ISSUE TITLE
`*.tar.zst` is not considered for `tar -xvf`

### ISSUE THREAD

**Issue by Rizhiy** [marlonrichert/zsh-autocomplete#688]
## Environment

```zsh
% typeset -p1 VENDOR OSTYPE ZSH_PATCHLEVEL _autocomplete__funcfiletrace
typeset VENDOR=ubuntu
typeset OSTYPE=linux-gnu
typeset ZSH_PATCHLEVEL=ubuntu/5.8.1-1
typeset -a _autocomplete__funcfiletrace=(
  /home/rizhiy/.antigen/bundles/marlonrichert/zsh-autocomplete-main/zsh-autocomplete.plugin.zsh:4
  /home/rizhiy/.antigen/init.zsh:59
  /home/rizhiy/.local/share/antigen/bin/antigen.zsh:39
  /home/rizhiy/.zshrc:20
  zsh:0
)
% git -C ~autocomplete log --oneline -n1
c7b6550 (grafted, HEAD -> main, origin/main, origin/HEAD) Add instructions on how to insert longest common prefix
```

* Operating system: Ubuntu 22.04 LTS
* Terminal emulator: Alacrity

## Steps to reproduce

```zsh
% cd $(mktemp -d)
% git clone --depth 1 -- https://github.com/marlonrichert/zsh-autocomplete.git
Cloning into 'zsh-autocomplete'...
remote: Enumerating objects: 55, done.
remote: Counting objects: 100% (55/55), done.
remote: Compressing objects: 100% (53/53), done.
remote: Total 55 (delta 0), reused 37 (delta 0), pack-reused 0
Receiving objects: 100% (55/55), 1.64 MiB | 6.35 MiB/s, done.
% > .zshrc <<EOF
setopt interactivecomments transientrprompt
PS1='%# '
PS2=
RPS2='%^'
source $PWD/zsh-autocomplete/zsh-autocomplete.plugin.zsh
EOF
% env -i HOME=$PWD PATH=$PATH TERM=$TERM ${TERMINFO:+TERMINFO=$TERMINFO} zsh -d
% wget https://github.com/ankitects/anki/releases/download/23.12.1/anki-23.12.1-linux-qt6.tar.zst
% tar -xvf
directory
zsh-autocomplete/
```

<details>
<summary>Contents of <code>~autocomplete-log/YYYY-MM-DD.log</code> (click to expand)</summary>
<pre>
.autocomplete:async:complete:fd-widget:31: completion cannot be used recursively (yet)
.autocomplete:async:pty:zle-widget:15: completion cannot be used recursively (yet)
.autocomplete:async:complete:fd-widget:31: completion cannot be used recursively (yet)
.autocomplete:async:pty:zle-widget:15: completion cannot be used recursively (yet)
.autocomplete:async:complete:fd-widget:31: completion cannot be used recursively (yet)
.autocomplete:async:pty:zle-widget:15: completion cannot be used recursively (yet)
.autocomplete:async:complete:fd-widget:31: completion cannot be used recursively (yet)
.autocomplete:async:pty:zle-widget:15: completion cannot be used recursively (yet)
.autocomplete:async:complete:fd-widget:31: completion cannot be used recursively (yet)
.autocomplete:async:pty:zle-widget:15: completion cannot be used recursively (yet)
.autocomplete:async:complete:fd-widget:31: completion cannot be used recursively (yet)
.autocomplete:async:pty:zle-widget:15: completion cannot be used recursively (yet)
.autocomplete:async:complete:fd-widget:31: completion cannot be used recursively (yet)
compadd:shift:31: shift count must be <= $#
compadd:shift:31: shift count must be <= $#
compadd:shift:31: shift count must be <= $#
compadd:shift:31: shift count must be <= $#
compadd:shift:31: shift count must be <= $#
compadd:shift:31: shift count must be <= $#
compadd:shift:31: shift count must be <= $#
.autocomplete:async:pty:zle-widget:15: completion cannot be used recursively (yet)
.autocomplete:async:complete:fd-widget:31: completion cannot be used recursively (yet)
.autocomplete:async:pty:zle-widget:15: completion cannot be used recursively (yet)
.autocomplete:async:complete:fd-widget:31: completion cannot be used recursively (yet)
.autocomplete:async:pty:zle-widget:15: completion cannot be used recursively (yet)
.autocomplete:async:complete:fd-widget:31: completion cannot be used recursively (yet)
compadd:shift:31: shift count must be <= $#
compadd:shift:31: shift count must be <= $#
.autocomplete:async:pty:zle-widget:15: completion cannot be used recursively (yet)
.autocomplete:async:complete:fd-widget:31: completion cannot be used recursively (yet)
.autocomplete:async:pty:zle-widget:15: completion cannot be used recursively (yet)
.autocomplete:async:complete:fd-widget:31: completion cannot be used recursively (yet)
</pre>
</details>

`*.tar.zst` files can be opened by `tar -xvf`, but are not suggested.
I have a feeling any `*.tar.*` file can be opened with tar given correct compression algorithm is installed, so they all should be suggested.

**Comment by marlonrichert** [comment]
Works for me with Zsh 5.9:
```sh
% cd $(mktemp -d)
% git clone --depth 1 -- https://github.com/marlonrichert/zsh-autocomplete.git
Cloning into 'zsh-autocomplete'...
remote: Enumerating objects: 53, done.
remote: Counting objects: 100% (53/53), done.
remote: Compressing objects: 100% (51/51), done.
remote: Total 53 (delta 0), reused 28 (delta 0), pack-reused 0
Receiving objects: 100% (53/53), 1.64 MiB | 4.42 MiB/s, done.
% > .zshrc <<EOF
setopt interactivecomments transientrprompt
PS1='%# '
PS2=
RPS2='%^'
source $PWD/zsh-autocomplete/zsh-autocomplete.plugin.zsh
EOF
% env -i HOME=$PWD PATH=$PATH TERM=$TERM ${TERMINFO:+TERMINFO=$TERMINFO} zsh -d
% touch anki-23.12.1-linux-qt6.tar.zst
% tar -xvf
directory
zsh-autocomplete/
archive file
anki-23.12.1-linux-qt6.tar.zst
common substring: zs
```

Additionally, if this is indeed a bug, then it is a bug in Zsh, not in Autocomplete.
