### ISSUE TITLE
Multiple suggestions for zoxide

### ISSUE THREAD

**Issue by ajeetdsouza** [marlonrichert/zsh-autocomplete#69]
### Is your feature request related to a problem? Please describe.

Hey, thanks for making this! I'm the author of zoxide, and I noticed you've added autocomplete support for it. I'd really appreciate it if you could support multiple suggestions too!

### Describe the solution you'd like

The latest version of zoxide allows you to query for a list of results:

```sh
zoxide query --list <keywords>
```

The results are in order of their frequency (best match first).

### Additional context

Since this feature is only supported in zoxide v0.4.2+, this might cause errors for users on lower versions.

**Comment by marlonrichert** [comment]
Thanks! When I added the feature, `zoxide` did not yet support listing multiple suggestions. Glad to hear you've now implemented it. I will add support for it. 🙂

**Comment by marlonrichert** [comment]
@ajeetdsouza It's there now on the `dev` branch. Please try it out.

**Comment by marlonrichert** [comment]
@ajeetdsouza Now available on `master`.

**Comment by ajeetdsouza** [comment]
Hey @marlonrichert,

I just tested this, and I'm not seeing any frecent results from zoxide. Am I doing something wrong? I haven't added anything to my configuration except `zgen load marlonrichert/zsh-autocomplete`.

**Comment by marlonrichert** [comment]
You need to also add `eval "$(zoxide init zsh)"` to your config. If `zoxide` is installed, but `zsh-autocomplete` does not find the function `_zoxide_hook`, then it assumes you are not actively using it.

Other than that, certain directories might be hidden from time to time because of how the completion system works.

**Comment by ajeetdsouza** [comment]
Ah, I was initializing zoxide after loading the plugin. Thanks a lot!
