### ISSUE TITLE
Hidden text

### ISSUE THREAD

**Issue by Ktyf37** [marlonrichert/zsh-autocomplete#690]
![Screenshot_20240217_173519](https://github.com/marlonrichert/zsh-autocomplete/assets/135925971/827d4509-bb66-42ef-aaad-4a60d7d59406)

As the picture describes, this prompt text is too long, how can I hide it?

text message:
**no matching `executable file', `suffix alias', `recent directory', or `ancestor directory' completions**

**Comment by curbengh** [comment]
https://github.com/marlonrichert/zsh-autocomplete/discussions/513#discussioncomment-4137144

> Yes, you can add to your `.zshrc` (_after_ sourcing Autocomplete) the following to hide the message or change it to something else:
> 
> ```shell
> zstyle ':completion:*:warnings' format <string>
> ```
