### ISSUE TITLE
Keybindings in Konsole (KDE Plasma)

### ISSUE THREAD

**Issue by joeatodd** [marlonrichert/zsh-autocomplete#7]
Hey,

First off - amazing plugin. Seeing this on reddit yesterday made me decided to refresh my zsh setup & install this plugin.

I have an issue (which I have fixed locally, so no rush) which is that the keybindings, eg:

key[Down]='^[[B'

don't correspond to what my terminal feeds in. For each of down, up, left, right, I had to swap the second '[' for a capital O. Not sure why this is the case.

**Comment by Dwight-D** [comment]
This has been discussed here:

https://github.com/marlonrichert/zsh-autocomplete/pull/3

**Comment by marlonrichert** [comment]
Duplicate of #3.

**Comment by marlonrichert** [comment]
Sorry, I closed this by accident. I thought #3 was an issue, but it was a pull request.

**Comment by marlonrichert** [comment]
@joeatodd I updated the code. Can you test if it resolves the issue for you?

**Comment by marlonrichert** [comment]
This should be resolved now. Closing the issue. Please let me know if it needs to be reopened.
