### ISSUE TITLE
Unexpected full completion on TAB

### ISSUE THREAD

**Issue by nunojsa** [marlonrichert/zsh-autocomplete#705]
I'm not really sure this is an issue or intended behavior but (at least to me) is really not what I would expect on a completion. Just with the following (no other plugins):

```
source .zsh/plugins/zsh-autocomplete/zsh-autocomplete.plugin.zsh
zstyle ':autocomplete:*complete*:*' insert-unambiguous yes
zstyle ':completion:*:*' matcher-list 'm:{[:lower:]-}={[:upper:]_}' '+r:|[.]=**'
```

And having the next output:

```
ls zynq-zc706
file
zynq-zc706-adv7511-ad6676-fmc.dts                       zynq-zc706-adv7511-ad9081.dts
zynq-zc706-adv7511-ad9081-np12.dts                      zynq-zc706-adv7511-ad9082.dts
zynq-zc706-adv7511-ad9136-fmc-ebz.dts                   zynq-zc706-adv7511-ad9172-fmc-ebz.dts
zynq-zc706-adv7511-ad9265-fmc-125ebz.dts                zynq-zc706-adv7511-ad9361-4-fmcomms2-3-4-userspace.dts
zynq-zc706-adv7511-ad9361-fmcomms2-3.dts                zynq-zc706-adv7511-ad9361-fmcomms5.dts
zynq-zc706-adv7511-ad9361-fmcomms5-ext-lo-adf5355.dts   zynq-zc706-adv7511-ad9361-fmcomms5-userspace.dts
zynq-zc706-adv7511-ad9364-fmcomms4.dts                  zynq-zc706-adv7511-ad9434-fmc-500ebz.dts
(MORE)
```

Where zynq-zc706-adv7511- is the common prefix, pressing tab will fully complete to the first result which is a bit annoying and not the default behavior of zsh AFAICT. It looks like this depends on the display size somehow. If I increase my window, making $LINES bigger then I could see the expected behavior (not in the above particular case because even fullscreen does not work - due to the amount of files with the same common prefix I guess). So, is this expected? And if so, any way to configure it otherwise?

**Comment by marlonrichert** [comment]
This works correctly for me in the latest version. Please update and try again.
