### ISSUE TITLE
Master branch is currently failing

### ISSUE THREAD

**Issue by daxmc99** [marlonrichert/zsh-autocomplete#73]
### Describe the bug

Seeing 
```
/Users/dax/.oh-my-zsh/custom/plugins/zsh-autocomplete/zsh-autocomplete.zsh:22: defining function based on alias `_expand'
/Users/dax/.oh-my-zsh/custom/plugins/zsh-autocomplete/zsh-autocomplete.zsh:100: parse error near `()'
``` 
on startup
### To Reproduce

Use the Oh My Zsh custom plugin option with the latest master branch. This is started occurring after I upgraded to the latest version.  
The last working commit (for me) was 8fadcb8b7ed6ac1d586a1470880296ef1107e86f  

### Expected behavior

Autocomplete works on master

### Actual behavior

Autocomplete does not work and I see `zsh: _autocomplete.main.hook: function definition file not found` on every attempt to autocomplete

### Desktop
 - OS + distribution: OSX
 - Zsh version: 5.7.1
 - Plugin version: 75ca496d8fe989544aac9576b0b2b21e213eda93

**Comment by marlonrichert** [comment]
Sorry, but I cannot reproduce this with a clean install of OhMyZsh plus `zsh-autocomplete`.

Here's what I did:
```sh
$ cd $(mktemp -d)
$ HOME=$PWD ZDOTDIR=$PWD zsh -d
% sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
% cd $ZSH_CUSTOM
% git clone git@github.com:marlonrichert/zsh-autocomplete.git
```
Then, in the temp dir's `.zshrc`, add `zsh-autocomplete` to the list of plugins and restart the sub-shell.

Can you please try the steps above and see if it works for you? If it does, then there's something else in your config that's messing things up. In that case, please try narrowing it down until you find what combination of things is causing, by commenting out plugins in your own `.zshrc` until the problem disappears.

**Comment by marlonrichert** [comment]
Closing, since I cannot reproduce this and I haven't heard back from @daxmc99.

**Comment by daxmc99** [comment]
Solved by removing the kubectl plugin from my plugin list... 
```
plugins=(
	git
	golang
	docker
	#kubectl
	zsh-autosuggestions
	zsh-autocomplete
	zsh-syntax-highlighting
	)
```
All the other plugins were set to lastest. I'm not sure why this could happen but this resolved it

**Comment by marlonrichert** [comment]
@daxmc99 I thought I'd let you know that similar problem have come up in other issues. In case you need it, you can find more info here:
* https://github.com/kubernetes/kubectl/issues/125
* https://github.com/kubernetes/website/issues/19844
* https://stackoverflow.com/a/60383091/13832769
