### ISSUE TITLE
Cannot disable frecent dirs feature

### ISSUE THREAD

**Issue by jcassee** [marlonrichert/zsh-autocomplete#75]
### Describe the bug

The readme says `zstyle ':autocomplete:*' frecent-dirs off` can be used to turn the frecent dirs feature off. However, that does not seem to work. Also, `grep -r frecent .` at commit 3c7e78daf32f19d3091c088d041942c545d208f1 does not find anything.

### To Reproduce

```shell
# *Always* test with the following three steps:
$ cd "$(mktemp -d)"  # Create a temp dir and enter it
$ ZDOTDIR=$PWD HOME=$PWD zsh -df  # Start a subshell without config files
% zstyle ':autocomplete:*' frecent-dirs off
% source path/to/zsh-autocomplete.plugin.zsh
% echo |
```

The completion for `echo` will list frecent dirs.

### Expected behavior

The `zstyle ':autocomplete:*' frecent-dirs off` setting will disable the frecent dirs feature.

### Actual behavior

The feature is enabled.

### Desktop
 - OS + distribution: Ubuntu 20.04
 - Zsh version: 5.8
 - Plugin version: 3c7e78daf32f19d3091c088d041942c545d208f1

**Comment by marlonrichert** [comment]
Thanks for reporting. I know what causes this. It will be easy to fix.

**Comment by marlonrichert** [comment]
@jcassee This should be fixed now on the `dev` branch. Please test.

**Comment by jcassee** [comment]
@marlonrichert Indeed, now works as advertised. Thanks!

**Comment by marlonrichert** [comment]
Merged to `master`.

**Comment by marlonrichert** [comment]
@jcassee It is now possible to individually disable any and all extra completions that `zsh-autocomplete` adds: https://github.com/marlonrichert/zsh-autocomplete/blob/master/README.md#disable-particular-completions

**Comment by jcassee** [comment]
Nice! You are really putting in a lot of thought and effort. Thanks you.
