### ISSUE TITLE
Stops working when KSH_GLOB is set 

### ISSUE THREAD

**Issue by PythonNut** [marlonrichert/zsh-autocomplete#76]
### Describe the bug

When KSH_GLOB is set, the pattern `*(history|search)*` is equivalent to `*` on [this line](https://github.com/marlonrichert/zsh-autocomplete/blob/3c7e78daf32f19d3091c088d041942c545d208f1/zsh-autocomplete.zsh#L591). This could be fixed by using an `emulate` call for that function.  

### To Reproduce

```shell
# *Always* test with the following three steps:
$ cd "$(mktemp -d)"  # Create a temp dir and enter it
$ ZDOTDIR=$PWD HOME=$PWD zsh -df  # Start a subshell without config files
% source path/to/zsh-autocomplete.plugin.zsh
% setopt KSH_GLOB
```

### Expected behavior
`zsh-autocomplete` will work as normal.

### Actual behavior
`zsh-autocomplete` will be completely disabled.

### Desktop
 - OS + distribution: Arch Linux 2020.08.02
 - Zsh version: 5.8
 - Plugin version: 3c7e78d

**Comment by marlonrichert** [comment]
@PythonNut I pushed in a fix on the `dev` branch. Please test.

**Comment by PythonNut** [comment]
It appears to be working again. Thanks!

**Comment by PythonNut** [comment]
It worked when I checked 3c7e78daf3, sorry for the delay. I'll reopen if it ever becomes an issue.

**Comment by marlonrichert** [comment]
Don’t worry about it. 🙂 I’ve kept it open, because it’s not merged yet to `master`. I’ve been doing a complete refactoring of the codebase on the `dev` and it’s taking me some time to iron out all the kinks.
