### ISSUE TITLE
overwrite my path

### ISSUE THREAD

**Issue by neuroloops** [marlonrichert/zsh-autocomplete#77]
### Describe the bug
I was creating a new angular componente
```ng g c recipes/recipes-list```, then when I type `/` it change my path by another one ``` ng c node_modules/browserlist/```

### To Reproduce

![Screenshot_20200807_162907](https://user-images.githubusercontent.com/56033812/89657377-45d98500-d8cd-11ea-9286-996480a9d4cb.png)

### Expected behavior
Don't autocomplete my path

### Desktop
 - OS + distribution: ManjaroLinux 20.0.3

 - Zsh version: 5.8
 - Plugin version: 3c7e78daf32f19d3091c088d041942c545d208f1

### Additional context
Doesn't have the behavior when I dissable the plugin

**Comment by marlonrichert** [comment]
@neuroloops Can you please try the `dev` branch? It should already be fixed there.

**Comment by neuroloops** [comment]
it seems to work, i didn't have the issue. 
I have another problem now, to confirm that problem was solve, I switched back to the `master` branch to reproduce the problem.

Then I moved again to the `dev` branch  but now I have this message when I `source ~/.zshrc`
`_autocomplete.add-zsh-hook:1: job table full or recursion limit exceeded`
How can I clear the table?

**Comment by marlonrichert** [comment]
Don’t `source ~/.zshrc`. Just restart your terminal or shell. See https://github.com/marlonrichert/zsh-autocomplete/issues/41#issuecomment-639485938 and https://github.com/romkatv/powerlevel10k/blob/master/README.md#weird-things-happen-after-typing-source-zshrc

**Comment by neuroloops** [comment]
thank you, everything is working :+1:
