### ISSUE TITLE
Error messages: Assignment to invalid subscript range

### ISSUE THREAD

**Issue by weilbith** [marlonrichert/zsh-autocomplete#78]
### Describe the bug
Sometimes while interacting with the command I type, auto-completion causes to print error messages. They then get printing quite often until I finish the command. My prompt gets redrawn again and again with the "old" command is automatically inserted again and the cursor on the new location.

### To Reproduce
I recognize this issue especially when editing a delete command. Be aware that I use zsh in vi-mode. So I type the command `rm -r any/directory` At the end of the command I realize that I want to put the force flag as well. So I usually type `0eeeaf` (go to start of line, 3x end of word (`-` is a word on it's own...), append character `f`). While doing this I get on every key the messages:

```
_rm:72: line: assignment to invalid subscript range
_rm:72: line: assignment to invalid subscript range
_rm:72: line: assignment to invalid subscript range
_rm:72: line: assignment to invalid subscript range
_rm:72: line: assignment to invalid subscript range
```

And then my command again in a new prompt.

### Expected behavior
No error messages...

### Actual behavior
Error messages...

### Desktop
 - OS + distribution: `5.7.11-arch1-1`
 - Zsh version: `zsh 5.8 (x86_64-pc-linux-gnu)`
 - Plugin version: `3c7e78daf32f19d3091c088d041942c545d208f1`

**Comment by marlonrichert** [comment]
@weilbith Thanks! I'm able to reproduce this on `master`. Have you checked if this is also an issue on `dev`?

**Comment by weilbith** [comment]
No I haven't. Why would you expect it to be different there? Did you already worked on improvements that could affect this issue?

**Comment by marlonrichert** [comment]
I've completely reorganized the code on the `dev` branch. Many things work differently now.

However, I just tried out the `dev` branch and it seems what I last pushed in is actually broken. So, no point in checking that out now.  I'll let you know when I've fixed it.

**Comment by marlonrichert** [comment]
For me, it appears to be a problem with `zinit`. Are you using that? I have a workaround, but I still need to test it a bit more.

**Comment by weilbith** [comment]
Nope. On this machine here I use `antibody`...

**Comment by marlonrichert** [comment]
@weilbith Did you try this on the `dev` branch yet?

**Comment by weilbith** [comment]
Haven't you stated in a comment above that you tried it yourself and it doesn't help? 😮

**Comment by marlonrichert** [comment]
@weilbith No, I meant that the whole `dev` branch was broken. It's fixed now, though. So, please `git checkout dev; git pull` and try again. Your problem is currently not occurring for me on the `dev` branch.

**Comment by weilbith** [comment]
Sorry for the delay.
It appears like I can't simply source the `zsh-autocomplete.plugin.zsh` anymore. I get a lot of errors for unknown/defined things. How can I source this manually now? I need to switch my plugin-manager anyways, but for know switching the branch appears to be not so easy (or more correct I'm never sure if it worked or not). Is there a chance I can still do this somehow else?

**Comment by marlonrichert** [comment]
@weilbith Hm, you are right. It seems I have broken the `dev` branch for the case where simply `source` the plugin. I'll have to investigate what's the problem.

**Comment by marlonrichert** [comment]
@weilbith OK, should be fixed now.

**Comment by weilbith** [comment]
Hey. Sorry that I haven't respond. I was on vacations and still am. And I have no PC with me around. So just leaving here a comment via phone.

So you fixed the source problem or/and the original bug? If both I would just trust you, since you were able to reproduce it on your PC. Else this issue would remain open for so long.

**Comment by marlonrichert** [comment]
OK, I’ll close it. You can reopen if necessary.
