### ISSUE TITLE
Use zsh/terminfo

### ISSUE THREAD

**Issue by z0rc** [marlonrichert/zsh-autocomplete#8]
The approach of defining bindkeys using escape sequences is inherently flawed, it's not possible to match all terminal emulator behaviors. 

Instead please use `zsh/terminfo` module. http://zsh.sourceforge.net/Doc/Release/Zsh-Modules.html#The-zsh_002fterminfo-Module and https://wiki.archlinux.org/index.php/zsh#Key_bindings

Also while we're at it. Please provide option to skip key binds in plugin and let user to define them by their own preference.

**Comment by marlonrichert** [comment]
I'm already working on both of those points. Expect to see an update soon. Thanks! 🙂

**Comment by marlonrichert** [comment]
@z0rc I updated the code. Can you test if it resolves the issue for you?

**Comment by z0rc** [comment]
The code is okay, but not quite there.

1. You have to explicitly `zmodload zsh/terminfo`.
1. You can skip all `terminfo[]` checks if loading of the module failed.
1. I don't think sourcing `zkbd` config belongs to this plugin. The zkbd configuration is solely part of user's own configuration. Still checking for `key` array created by zkbd might be okay.

**Comment by marlonrichert** [comment]
Thanks, I will look into it.

**Comment by marlonrichert** [comment]
> You can skip all terminfo[] checks if loading of the module failed.

Perhaps, but I still need those checks when the module does load, because terminfo is not guaranteed to define the keys that I need.

**Comment by marlonrichert** [comment]
I just checked and my `/etc/zshrc` successfully uses `terminfo` without ever doing `zmodload zsh/terminfo`. Are you sure this is necessary?

**Comment by marlonrichert** [comment]
> I don't think sourcing zkbd config belongs to this plugin. The zkbd configuration is solely part of user's own configuration. 

Some people have asked for it. So, I'm not going to remove it just yet.

**Comment by z0rc** [comment]
> I just checked and my /etc/zshrc successfully uses terminfo without ever doing zmodload zsh/terminfo. Are you sure this is necessary?

You're right, it might not be required anymore. Some old zsh version might still need it, as I cannot find when exactly this happened.

**Comment by z0rc** [comment]
> > I don't think sourcing zkbd config belongs to this plugin. The zkbd configuration is solely part of user's own configuration.

> Some people have asked for it. So, I'm not going to remove it just yet.

I don't think it's a plugin job to do what zkbd explicitly asks on initial configuration. https://github.com/zsh-users/zsh/blob/master/Functions/Misc/zkbd#L262

**Comment by marlonrichert** [comment]
> I don't think it's a plugin job to do what zkbd explicitly asks to do at the end of initial configuration. https://github.com/zsh-users/zsh/blob/master/Functions/Misc/zkbd#L262

I don't think it hurts either, though. Does it?

**Comment by marlonrichert** [comment]
@z0rc I pushed in a new update. Please check it out and let me know if it resolves the issue for you. 🙂

**Comment by marlonrichert** [comment]
I think this is resolved now. Closing the issue. Let me know if you think otherwise.
