### ISSUE TITLE
command not found: _autocomplete.extras

### ISSUE THREAD

**Issue by paroque28** [marlonrichert/zsh-autocomplete#81]
### To Reproduce

```
$ zsh
```

### Expected behavior

Normal shell

### Actual behavior
```
❯ _autocomplete.main_complete:322: command not found: _autocomplete.extras
_autocomplete.main_complete:322: command not found: _autocomplete.handle_long_list

```

### Desktop
 - OS + distribution: Ubuntu 16.04
 - Zsh version: 5.8
 - Plugin version: dev branch

**Comment by paroque28** [comment]
After updating ZSH version I encountered this problem

**Comment by marlonrichert** [comment]
@paroque28 Please don't file bugs against the `dev` branch. 🙂 Everything there is experimental and very likely to change.
