### ISSUE TITLE
Autocomplete prints "bad pattern" errors when directory in path history contains "#"

### ISSUE THREAD

**Issue by thefriedman** [marlonrichert/zsh-autocomplete#83]
### Describe the bug
When user has a directory with a "#" symbol in it in their recent paths, autocomplete spits out a bunch of "bad pattern" errors once you type or ask for completion.

### To Reproduce

```shell
$ mkdir "#bad_name"
$ cd "#bad_name"
$ ls <Tab>
```
At this point the `bad pattern` errors are seen in the shell:
```shell
_autocomplete.recent-paths:10: bad pattern: ~/#bad_name
_autocomplete.recent-paths:10: bad pattern: ~/#bad_name
_autocomplete.recent-paths:10: bad pattern: ~/#bad_name
_autocomplete.recent-paths:10: bad pattern: ~/#bad_name
```

### Desktop
 - OS + distribution: MacOS  10.15.6
 - Zsh version: 5.7.1
 - Plugin version: @3c7e78

### Additional context
I've already renamed the problem directory, but I'd like to know how to clear the bad directories from my path history as the error output causes the shell to get a bit hectic, making completions much less useful.  A way to silence these errors would be even better.
Thank you.

**Comment by marlonrichert** [comment]
Thanks for reporting. I know how to fix it. You won't need to clear the bad dirs from your path history. 🙂

**Comment by marlonrichert** [comment]
Merged to `master`.
