### ISSUE TITLE
autocomplete breaks prompt theme

### ISSUE THREAD

**Issue by windowswithoutborders** [marlonrichert/zsh-autocomplete#86]
### Describe the bug

When running a prompt theme, autocomplete breaks the prompt styling, exposing the formatting instead of properly drawing it.

### To Reproduce
1)use prompt theme
2)type any character and press down. no spaces required.

```shell
# *Always* test with the following three steps:
$ cd $(mktemp -d)  # Create a temp dir and enter it
$ ZDOTDIR=$PWD HOME=$PWD zsh -df  # Start a subshell without config files
% source path/to/zsh-autocomplete.plugin.zsh
% # Insert your steps here
```

### Expected behavior

prompt properly draws

### Actual behavior

prompt formatting is exposed

### Desktop
 - OS + distribution: Arch Linux 5.4.61-1-lts 
 - Zsh version: 5.8 
 - Plugin version: cb01fad1c99b56183fedb6fc43b096f6a9e92e05 

### Additional context

autocomplete will break prompt styling in a number of ways but I believe the way I listed is the easiest to reproduce.

**Comment by marlonrichert** [comment]
@windowswithoutborders I cannot reproduce this. Can you give me a more specific test case?

**Comment by marlonrichert** [comment]
@windowswithoutborders Usually this happens when an error message is printed at the same time that the prompt is being drawn. Do you see any visible message at the top of the prompt formatting?

**Comment by windowswithoutborders** [comment]
Just noticed the error message at the top of the prompt is `.autocomplete.async.complete.fd-widget:21: completion cannot be used recursively (yet)` which I see someone has recently created an issue for. I'll try and provide relevant info in regards to this as i come upon it in that thread.
