### ISSUE TITLE
history menu opens slow with large history file

### ISSUE THREAD

**Issue by windowswithoutborders** [marlonrichert/zsh-autocomplete#87]
### Describe the bug

There is a considerable delay when opening the history menu with thousands of entries

### To Reproduce
Have large zsh_history file (mine is 250k with 9000+ lines) and open history menu

```shell
# *Always* test with the following three steps:
$ cd $(mktemp -d)  # Create a temp dir and enter it
$ ZDOTDIR=$PWD HOME=$PWD zsh -df  # Start a subshell without config files
% source path/to/zsh-autocomplete.plugin.zsh
% # Insert your steps here
```

### Expected behavior

History menu opens without considerable delay
### Actual behavior

History menu opens after a considerable delay

### Desktop
 - OS + distribution: Arch Linux 5.4.61-1-lts 
 - Zsh version: 5.8 
 - Plugin version: cb01fad1c99b56183fedb6fc43b096f6a9e92e05

**Comment by marlonrichert** [comment]
@windowswithoutborders I pushed in a fix (plus a bunch of other history-related features) on the `dev` branch. Want to give it a try?

**Comment by daxmc99** [comment]
Is there a quick way to unbind the up arrow from being taken by `zsh-autocomplete`

**Comment by daxmc99** [comment]
On the dev branch I get `.autocomplete.patch:37: maximum nested function level reached; increase FUNCNEST?`

**Comment by marlonrichert** [comment]
> Is there a quick way to unbind the up arrow from being taken by `zsh-autocomplete`?

Instructions for disabling automatic keybinds can be found in the Readme: https://github.com/marlonrichert/zsh-autocomplete/blob/master/README.md#advanced-choose-your-own-key-bindings

> On the dev branch I get `.autocomplete.patch:37: maximum nested function level reached; increase FUNCNEST?`

I'm not seeing that. Can you open a separate issue for it, please?

@daxmc99

**Comment by windowswithoutborders** [comment]
just tried out the dev branch. can confirm it is perfectly snappy on my end. thanks! This is shaping up to be a must have zsh extension as far as I'm concerned.

**Comment by marlonrichert** [comment]
Available now on `master`.
