### ISSUE TITLE
Feature modularity

### ISSUE THREAD

**Issue by windowswithoutborders** [marlonrichert/zsh-autocomplete#88]
If possible, please consider implementing a way of disabling certain features of the plugin. Having control over which features are enabled would really help with better fitting the plugin into any given workflow.

**Comment by marlonrichert** [comment]
You’re in luck: I _just_ implemented this in 07667b073059bcb82d98a5106e5d75fba0230156! 😃
 
See [this part of the Readme](https://github.com/marlonrichert/zsh-autocomplete/blob/master/README.md#advanced-use-your-own-completion-config) for examples.
