### ISSUE TITLE
no such hash table element: add-zsh-hook

### ISSUE THREAD

**Issue by crian** [marlonrichert/zsh-autocomplete#89]
### Describe the bug
Getting this message when i start the terminal:
`(anon):unfunction:30: no such hash table element: add-zsh-hook`

### To Reproduce

```shell
# *Always* test with the following three steps:
$ cd $(mktemp -d)  # Create a temp dir and enter it
$ ZDOTDIR=$PWD HOME=$PWD zsh -df  # Start a subshell without config files
% source path/to/zsh-autocomplete.plugin.zsh
% # Insert your steps here
```

### Desktop
 - OS + distribution: Arch Linux
 - Zsh version: 5.8
 - Plugin version: cb01fad1c99b56183fedb6fc43b096f6a9e92e05

**Comment by marlonrichert** [comment]
@crian Can you please fill out the steps to reproduce?

**Comment by marlonrichert** [comment]
Fixed and pushed to `master`.
