### ISSUE TITLE
.autocomplete.async.complete.fd-widget:21: completion cannot be used recursively (yet)

### ISSUE THREAD

**Issue by yutakatay** [marlonrichert/zsh-autocomplete#90]
### Describe the bug

When I set `zstyle ':completion:*:default' menu select=1`, the following error occurs.

`.autocomplete.async.complete.fd-widget:21: completion cannot be used recursively (yet)`

The version at the end of July had no problems.

### To Reproduce

```shell
# *Always* test with the following three steps:
$ cd $(mktemp -d)  # Create a temp dir and enter it
$ ZDOTDIR=$PWD HOME=$PWD zsh -df  # Start a subshell without config files
% source path/to/zsh-autocomplete.plugin.zsh
% zstyle ':completion:*:default' menu select=1
% ls -l<DownArrow>
```

### Expected behavior
I can select the completion candidates.

### Actual behavior
I cannot select the completion. And this error is displayed.
`.autocomplete.async.complete.fd-widget:21: completion cannot be used recursively (yet)`

### Desktop
 - OS + distribution: ArchLinux
 - Zsh version: sh 5.8.0.2
 - Plugin version: 0de4c97eb77da4a5605a616ccb4053bfce559b06

**Comment by marlonrichert** [comment]
@yutakatay I cannot reproduce this with the steps you provided. Are you sure you didn't leave something out?

**Comment by yutakatay** [comment]
Oh, really? I've checked that and the procedure is correct. I'll try to reproduce it on docker.

**Comment by yutakatay** [comment]
OK. I could reproduce on docker.

```shell
docker run -it archlinux /bin/bash
pacman -Sy
pacman -S git zsh
zsh
git clone https://github.com/marlonrichert/zsh-autocomplete.git
source zsh-autocomplete/zsh-autocomplete.plugin.zsh
zstyle ':completion:*:default' menu select=1
ls -l<DownArrow>
```

You should be able to see the error message.

```
7e801abb8f71# ls -lA
.autocomplete.async.complete.fd-widget:21: completion cannot be used recursively (yet)
7e801abb8f71# ls -lA
-A   list all except . and ..
```

**Comment by marlonrichert** [comment]
Sorry, I don't use Docker. :(

**Comment by marlonrichert** [comment]
Does the problem occur when you use the `dev` branch?

**Comment by yutakatay** [comment]
This error occurs even if I use the dev branch.

**Comment by marlonrichert** [comment]
OK. Let me know if you can figure out why this happens, because I still cannot reproduce it. @yutakatay @srappan

**Comment by yutakatay** [comment]
I investigated it by changing a few parameters and settings, but I couldn't find the problem.

It definitely reproduces in my environment. I will use this commit (3c7e78daf32f19d3091c088d041942c545d208f1) for a while.

**Comment by windowswithoutborders** [comment]
just wanted to add that this is the specific message I see when my themed prompt breaks.  I'll let you know if i can narrow it down to what might be causing this.

**Comment by marlonrichert** [comment]
> I will use this commit (3c7e78d) for a while.

Is that the very last commit that works for you? Or can you still find a later one that works? It would help me a lot if you could find the exact point at which this broke.

**Comment by marlonrichert** [comment]
@windowswithoutborders Are you also using `zstyle ':completion:*:default' menu select=1`? Or do you have the problem without it? What is the minimal amount of setting with which you can reproduce this?

**Comment by marlonrichert** [comment]
@yutakatay What is it exactly you’re trying to accomplish with `zstyle ':completion:*:default' menu select=1`?

**Comment by marlonrichert** [comment]
@yutakatay @windowswithoutborders @srappan I was finally able to reproduce it and pushed in a fix on the `dev` branch. Please `git checkout dev` and let me know whether it works for you, too.

**Comment by yutakatay** [comment]
Great work! I used the dev branch and it seems to have fixed this problem.

Thank you :smile:
