### ISSUE TITLE
Affects ctrl+r and ctrl+s behavior without explanation (with specific plugins)

### ISSUE THREAD

**Issue by bashenk** [marlonrichert/zsh-autocomplete#92]
### Describe the bug
By default (i.e., without this plugin), `ctrl+r` displays `bck-i-search: ` followed by stdin and `ctrl+s` displays `fwd-i-search: ` followed by stdin.
With this plugin loaded, those messages are removed. There is no documentation mentioning this nor a clear way of reversing the change.
Without any config files loaded (i.e., by running `zsh -df` and sourcing the plugin manually), backward history search appears to function correctly; however, forward history search does not.

##### Upon further experimentation
This plugin, when loaded with any of the following plugins (non-exhaustive), causes this unusual behavior:
- history-substring-search
- zsh-autosuggestions
- zsh-syntax-highlighting

However, the previous issue with the backward history search message not appearing returns when loading a subshell without config files loaded.

### To Reproduce
Install and load the plugin.
**Addition:** Install and load at least one of the three above-listed plugins.
Press `ctrl+s` to enter forward history search mode.

### Expected behavior
`ctrl+r` and `ctrl+s` should display their respective message lines

### Actual behavior
Message lines are gone. 

### Desktop
PC 1 (WSL)
 - OS + distribution: Linux 4.19.104-microsoft-standard \#1 SMP Wed Feb 19 06:37:35 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
 - Zsh version: 5.8
 - Plugin version 1: 0de4c97eb77da4a5605a616ccb4053bfce559b06

PC 2 (Debian)
 - OS + distribution: Linux 5.4.55-1-pve \#1 SMP PVE 5.4.55-1 (Mon, 10 Aug 2020 10:26:27 +0200) x86_64 GNU/Linux
 - Zsh version: 5.7.1
 - Plugin version: 0de4c97eb77da4a5605a616ccb4053bfce559b06

### Additional context
Default theme used for normal config is [powerlevel10k](https://github.com/romkatv/powerlevel10k)

**Comment by marlonrichert** [comment]
I noticed the same thing yesterday. I have a fix ready and will push it in soon.

**Comment by marlonrichert** [comment]
@bashenk It should be fixed now on the `dev` branch. Can you please try it out?

**Comment by marlonrichert** [comment]
Fix now available on `master`.

**Comment by bashenk** [comment]
Thank you for the fix! Sorry, I missed the notification earlier.
