### ISSUE TITLE
Bug in the history when there are duplicates

### ISSUE THREAD

**Issue by maarekj** [marlonrichert/zsh-autocomplete#94]
### Describe the bug
When I have duplicates in my history, only the oldest one is displayed when I press `<up>`.

### To Reproduce
Example to reproduce the bugged behaviour

```shell
$ zsh -df
$ source ~/.zsh-autocomplete/zsh-autocomplete.plugin.zsh
$ ls -alh
$ ping google.com
$ ls -alh
$ ping google.fr
$ history

press <up>
```

The history command print:
```shell
1  source ~/.zsh-autocomplete/zsh-autocomplete.plugin.zsh
2  ls -alh
3  ping google.com
4  ls -alh
5  ping google.fr
```

And the press `<up>` print:
```shell
1  source ~/.zsh-autocomplete/zsh-autocomplete.plugin.zsh
2  ls -alh
3  ping google.com
5  ping google.fr
6  history
```

### Expected behavior
The `ls -alh` command is in line 2 and 4 of the history.
In `<up>` it should be the same.

### Desktop
 - macOS
 - Zsh version: 5.7.1
 - Plugin version: af72f8a8fae3e4311967e36a5a03f22be79b93db

### Additional context
<img width="488" alt="Capture d’écran 2020-09-09 à 18 07 01" src="https://user-images.githubusercontent.com/1654977/92624242-9165c100-f2c7-11ea-99c3-e1b484f436b6.png">

**Comment by marlonrichert** [comment]
@maarekj I pushed in a fix on the `dev` branch. Want to try it out?

**Comment by maarekj** [comment]
It's fixed.
Thank you very much.

**Comment by marlonrichert** [comment]
Fixed now on `master`.
