### ISSUE TITLE
Interferes with fast-syntax-highlighting

### ISSUE THREAD

**Issue by jakecoble** [marlonrichert/zsh-autocomplete#95]
### Describe the bug
When loaded before fast-syntax-highlighting, syntax highlighting is applied only if the user presses enter (i.e. syntax coloring is only applied to commands in the scrollback buffer).

When loaded after fast-syntax-highlighting, syntax highlighting is applied, but recursive `eval` and subshell syntax highlighting is not (i.e. `ls` in `eval "ls"` will not be highlighted as expected).

### To Reproduce

```shell
$ cd $(mktemp -d)
$ ZDOTDIR=$PWD HOME=$PWD zsh -df
% source path/to/zsh-autocomplete.plugin.zsh
% source path/to/fast-syntax-highlighting.plugin.zsh
```

```shell
$ cd $(mktemp -d)
$ ZDOTDIR=$PWD HOME=$PWD zsh -df
% source path/to/fast-syntax-highlighting.plugin.zsh
% source path/to/zsh-autocomplete.plugin.zsh
```

### Expected behavior
Syntax highlighting should be applied to commands as they're typed, as well as to commands within `eval` strings and `$()`.

### Actual behavior
Depending on the order loaded, either the syntax highlighting is not applied to commands as they're typed, or commands within `eval` strings and `$()` are not highlighted.

### Desktop
 - OS + distribution: Arch Linux 5.8.1-arch1-1
 - Zsh version: 5.8
 - Plugin version: c1f1560d257a6cf9195b60745a34e7f062c037f1

**Comment by jakecoble** [comment]
The two plugins appear to be having a disagreement over `region_highlight`. Unclear whether this is a zsh-autocomplete bug or a fast-syntax-highlighting bug.

**Comment by marlonrichert** [comment]
Thanks for reporting. Can you give me a couple of concrete test cases with which I can observe this behavior?

**Comment by jakecoble** [comment]
Ran a bisection and it looks like this bug was introduced in 005da66cd152681b1953f02dbb2d4c3c17e47970

**Comment by marlonrichert** [comment]
@jakecoble This should be fixed now on the `dev` branch. Can you please check that it is?

**Comment by jakecoble** [comment]
> @jakecoble This should be fixed now on the `dev` branch. Can you please check that it is?

I can confirm that this bug is now fixed. Thank you for working on this!

**Comment by marlonrichert** [comment]
Fixed now on `master`.
