### ISSUE TITLE
Commit 005da66 interferes with zsh-autosuggestions coloring

### ISSUE THREAD

**Issue by paw-lu** [marlonrichert/zsh-autocomplete#97]
### Describe the bug
 Commit 005da66 changes the muted coloring on zsh-autosuggestions to that of the default text. Commit before that works fine.

### To Reproduce

On 1e1be3a
 
<img width="431" alt="Screen Shot 2020-09-18 at 9 37 56 AM" src="https://user-images.githubusercontent.com/30049606/93623454-a14e6680-f993-11ea-9f34-63372eaa8e74.png">

On 005da66

<img width="431" alt="Screen Shot 2020-09-18 at 9 39 17 AM" src="https://user-images.githubusercontent.com/30049606/93623512-b62afa00-f993-11ea-9dec-d71ade1a6b2d.png">

### Expected behavior
zsh-autosuggestions suggestions keep their muted coloring.

### Actual behavior
zsh-autosuggestions suggestions have the same color as the primary text.

### Desktop
 - OS + distribution: macOS 10.15.6
 - Zsh version: 5.8
 - Plugin version: 005da66

**Comment by marlonrichert** [comment]
Fixed now on `master`.

**Comment by paw-lu** [comment]
Works great for me.
Thank you so much @marlonrichert !
