### ISSUE TITLE
Provide settings to disable key bindings individually

### ISSUE THREAD

**Issue by PythonNut** [marlonrichert/zsh-autocomplete#98]
### Describe the solution you'd like
While the new history menu you created is very nice, it doesn't match my workflow so I would like to disable it.

### Describe alternatives you've considered

I could work around this if the `key-binding` zstyle option still worked.

**Comment by marlonrichert** [comment]
@PythonNut I renamed the setting to `bindkey`. But I guess this should serve as a reminder for me to keep the old setting names, too. :)

**Comment by marlonrichert** [comment]
Or perhaps I should just change it back for the time being. I should also think of some way to enable key bindings more selectively. You are not the only one who has asked for it.

**Comment by marlonrichert** [comment]
No, I cannot think of any reasonable way to provide detailed key binding settings, without reimplementing `bindkey`. I think I’ll stick with just `yes/no`. However, I could provide a `yes/no` toggle for each key (or group of keys) that would be bound. 🤔

So, one `bind-key yes/no` setting for each of the following key groups (or “contexts”, in `zstyle` jargon:
* Tab + backtab
* Up arrow + down arrow
* Ctrl-space

**Comment by marlonrichert** [comment]
@PythonNut It's there now on the `dev` branch. Please try it out and let me know what you think.

**Comment by x51mon** [comment]
How can i get back the old behaviour of the arrop-up key but keep the new history menu at the page-up key?
Sorry I've read through the readme, also the one in the dev branch but I could not figure it out.

**Comment by marlonrichert** [comment]
@x51mon That's not possible yet, I'm afraid. I will add it, but it's going to take a little while; there's some bugs on both `master` and `dev` that I need to fix first.

**Comment by x51mon** [comment]
Ok great, thank you. So I wasn't to stupid to figure it out. And no pressure.

**Comment by marlonrichert** [comment]
It is now possible to override the Arrow Up/Down key binding. Please see the [relevant section in the Readme](https://github.com/marlonrichert/zsh-autocomplete/blob/master/README.md#change-other-key-bindings).
